### ISSUE TITLE
[3DS] pcsx_rearmed missing from 1.4.0/1.4.1 builds

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/pcsx_rearmed#100]
pcsx_rearmed missing from 1.4.0/1.4.1 3DS build

compared to 1.3.6 this is the only core that is missing

**Comment by fr500** [comment]
Failing to build:
http://p.0bl.net/1981

**Comment by gingerbeardman** [comment]
This is now back in the nightlies. 

Yet to test it myself. Will comment here again when I do.

**Comment by Saphiresurf** [comment]
Have the PCSX builds been working in the latest nightlies? They've been crashing for me on launching a game, but I think it may be because of the way I'm setting it up. Curious if this is the case for others as well.

**Comment by gingerbeardman** [comment]
It's not working for me, either.
