### ISSUE TITLE
pcsx_rearmed_show_bios_bootlogo is not respected after Restart

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/pcsx_rearmed#105]
Restart the core, you'll see the boot logo for no reason.

@meepingsnesroms

**Comment by meepingsnesroms** [comment]
This happened before my changes, my change just forced a reset on load so it would show up.

**Comment by Darknior** [comment]
I have the same problem, when you reset the PSX emu, it not read and use the config file.
It show the BIOS logo, and not use my new parameters. I must quit the emulator and come back again.

**Comment by retro-wertz** [comment]
should be fixed in latest commit...

**Comment by negativeExponent** [comment]
this should be working in latest commits

@twinaphex @hunterk @hizzlesomething
