### ISSUE TITLE
Psychic Detective - Intro Videos Bypassed/Skipped

### ISSUE THREAD

**Issue by alysincroft** [libretro/pcsx_rearmed#107]
On booting Psychic Detective, intro videos (EA logo, intro story video) are bypassed and not played. May occur at other times with additional video segments, but haven't tested further.

**Comment by gameblabla** [comment]
Does this still happen ? I've merged quite an MDEC fix and a few CDROM improvements.

**Comment by notaz** [comment]
Timing issue, should be working now.
