### ISSUE TITLE
[RPI3] Legend of Mana issues

### ISSUE THREAD

**Issue by agentmith** [libretro/pcsx_rearmed#110]
The game launches fine initially, but after a few seconds a second music track starts playing over the first, so effectively there are 2 title songs playing over each other.

Also, no matter what configuration I set in the Control settings I can't get controller input to work. No issues with any other games I've tested.

**Comment by hizzlekizzle** [comment]
Bad dump, perhaps? Are you using a BIOS or the built-in HLE BIOS?

**Comment by agentmith** [comment]
Just tested with a PBP file I made from my own disc a while back. I know that works as I played it on my PSP years ago. Same problem, controller won't work regardless of config, and the music plays over itself in the beginning. It's on PCSX-ReARMed 1.5.0 r22

Using the SCPH1001 bios (or whatever is the default, I have all the bioses in the appropriate folder, and the MD5 is correct)

**Comment by agentmith** [comment]
Just double checked the bin cue file on my computer, they play fine there also.

Let me know if there is anything else I can do to help. This is literally my favorite game of all time, and I would love to see it working.

**Comment by retro-wertz** [comment]
i am unsure as to which part of the game you are actually describing. in anycase, please feel free to retest using latest retroarch + pcsx_rearmed version...

**Comment by retro-wertz** [comment]
there is a workaround that can be done with the standalone pcsx_rearmed core. but the necessary functions does not exist in the libretro fork sadly...

**Comment by gameblabla** [comment]
I believe i have fixed that with the Diablo 1 SPU PR so this probably needs to be tested again.

**Comment by notaz** [comment]
AFAIK this is fixed.
