### ISSUE TITLE
Another nasty polygon issue

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/pcsx_rearmed#114]
Giant polygons clipping through the hallway in threads of fate.
[movie.zip](https://github.com/libretro/pcsx_rearmed/files/906349/movie.zip)
![threads of fate-170407-101452](https://cloud.githubusercontent.com/assets/1220805/24812361/99a356e4-1b7e-11e7-88ea-c07fe0713bf2.png)

This happens with neon or unai gpu, dynarec or interpreter, with and without bios, and with and without both timing hacks.
Tested on mac and android.

**Comment by meepingsnesroms** [comment]
Changing the fallback return value in gte_divider.c changes the effect some so the bug is likely here.

**Comment by gameblabla** [comment]
Since 2020, the GTE divider has been replaced with MAME's one. Unfortunately OP is dead and didn't provide a save.
I'll assume this is fixed.
