### ISSUE TITLE
Can't load on Android 6

### ISSUE THREAD

**Issue by fr500** [libretro/pcsx_rearmed#116]
The core doesn't even load anymore on android, I get a failed to open libretro core. Not sure when this started but it's important since it's the only fullspeed core on most devices.

**Comment by fr500** [comment]
http://stackoverflow.com/questions/37360464/libiconv-so-has-text-relocations

> The library is not even loaded because of its text relocations.
> 
> This is due to an old bug in the Android NDK, back in 2012. Google believed it to be solved with Lollipop, then ignored user warnings that it wasn't. The bug resurfaced in later NDKs, all API versions >=22 are considered broken. Instead of fixing the issue, apps with text relocations are now simply forbidden to deploy.
> 
> First report: https://code.google.com/p/android/issues/detail?id=23203
> 
> To avoid the problem, try compiling your app with API 21. Refer to your IDE documentation on how to target various OS versions.
> 
>

**Comment by fr500** [comment]
https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime

**Comment by twinaphex** [comment]
Things are run so professionally over at Google...

I guess we could try forcing API level 9 or something.

**Comment by fr500** [comment]
Yeah I'm aware.
No need to force API 9 though, 21 should be enough

**Comment by meepingsnesroms** [comment]
Will this be switched back to sdk 21 before RetroArch v1.5.1 is released for android?

**Comment by fr500** [comment]
I don't know, the bump in RA was for runtime permissions needed to read from the SD card.
In my personal builds (staging) I have reverted this change and it's working fine. I'm rooted so I don't care for such a thing.

The real fix is to fix the text reallocation issues.

**Comment by meepingsnesroms** [comment]
That would require rewriting or removing all assembly sections, the dynarec would be ok since it is after the library loads.

To fix all constant references would have to be removed.
So "mov 0x23, D1" would have to become "clr D1" "add 0x23, D1" because the static values are being loaded from ram using a pointer to an address that holds that value.

**Comment by fr500** [comment]
I don't know assembler (or programming) so I don't know what this implicates, you should talk to @twinaphex or @notaz or maybe @aliaspider

**Comment by mudlord** [comment]
Blame Google for doing all this shit in the name of "Security"

https://trac.ffmpeg.org/ticket/4928

Take that what you will.

**Comment by notaz** [comment]
Pushed something to my tree that might help.

**Comment by fr500** [comment]
@notaz thanks a lot, it built, and it seems to load just fine in android 6 thanks a lot.

**Comment by meepingsnesroms** [comment]
I tested too, it is confirmed working using buildbot core.

**Comment by fr500** [comment]
@notaz, do you think you can apply the same to picodrive?

**Comment by notaz** [comment]
I had no idea it also has that issue.
I'll see what I can do, just don't know when.

**Comment by fr500** [comment]
Thanks a lot!
