### ISSUE TITLE
Does not flush memory card file to disk after in game save

### ISSUE THREAD

**Issue by hooby3dfx** [libretro/pcsx_rearmed#121]
I have been playing through a PSX game on Lakka for a few days, and one day noticed that my progress from the night before was lost.

After looking into what happened I realized that when you save to the memory card in the game, the .srm file timestamp is not necessarily updated. However, when you quit the emulator/retroarch, the file is then actually written to.

This can be a problem when playing games on an embedded system that can be easily power off - you would expect that "saved" data should still be there.

**Comment by dankcushions** [comment]
that's just how retroarch handles .srm saving. it couldn't be changed in this particular core. related: https://github.com/libretro/RetroArch/issues/4901

**Comment by fr500** [comment]
You can always enable sram autosave though

**Comment by retro-wertz** [comment]
enabled sram autosave for memcard1
memcard2 saves should directly write to storage after saving.

**Comment by AnotherLife** [comment]
This is why I also do savestates now and then to prevent losing progress. Savestates are written instantly and contain the memcard contents.

This issue is non-valid and should be closed.

**Comment by negativeExponent** [comment]
unrelated to core issue.

this should be working in latest commits

@twinaphex @hunterk @hizzlesomething
