### ISSUE TITLE
[Suggestion] New BIOS Naming System

### ISSUE THREAD

**Issue by LodanZark** [libretro/pcsx_rearmed#123]
Problem:
========
Usually the bios naming its based in the psx model and not the version of the bios, which can result in the follow situations:
The model SCPH-102 has the European bios 4.4 or 4.5
The american bios 4.1 was installed in the models: SCPH-7001/SCPH-7501/SCPH-7503/SCPH-9001

Solution:
=========
Using the following BIOS naming based in the region and version of it.
If it's trouble some to enforce it, maybe could be done through the hash checksum instead the filename.

--------------------------------------------------

MISC
====

filename: DTLH2000.bin
models: DTLH2000(PlayStation 1 Dev)
crc: 18d0f7d8
md5: 2118230527a9f51bd9216e32fa912842
sha1: 1a8d6f9453111b1d317bb7dae300495fbf54600c
sha256: 7f38da2e456540d267060175a7a1e3b4c39292d964051abd8b322c05367af04f

filename: ps2-50j.bin
models: PSX BIOS found on PS2 (NTSC-J)
crc: 0dcce9d7
md5: d8f485717a5237285e4d7c5f881b7f32
sha1: d7d6be084f51354bc951d8fa2d8d912aa70abc5e
sha256: 51019af1a7928c90470bb9cbc724a5679873af85dc897c07ec27d4e8c0478b03

filename: ps1_rom.bin
models: PSX BIOS found on PS3
crc: 2f53b852
md5: 81bbe60ba7a3d1cea1d48c14cbcc647b
sha1: c40146361eb8cf670b19fdc9759190257803cab7
sha256: ab05d7bed4980fe1ddde6828b10b4968ab63d3f75dee3ef1deda16391ec29fb5

--------------------------------------------------

NTSC-UC
=======

filename: ps-20a.bin
models: DTL-H1001 (Version 2.0 05/07/95 A)
crc: 55847d8c
md5: dc2b9bf8da62ec93e868cfd29f0d067d
sha1: 649895efd79d14790eabb362e94eb0622093dfb9
sha256: 42e4124be7623e2e28b1db0d8d426539646faee49d74b71166d8ba5bd7c472ed

filename: ps-21a.bin
models: DTL-H1101 (Version 2.1 07/17/95 A)
crc: aff00f2f
md5: da27e8b6dab242d8f91a9b25d80c63b8
sha1: ca7af30b50d9756cbd764640126c454cff658479
sha256: 6ad5521d105a6b86741f1af8da2e6ea1c732d34459940618c70305a105e8ec10

filename: ps-22a.bin
models: SCPH-1001/DTL-H1201/DTL-H3001 (Version 2.2 12/04/95 A)
crc: 37157331
md5: 924e392ed05558ffdb115408c263dccf
sha1: 10155d8d6e6e832d6ea66db9bc098321fb5e8ebf
sha256: 71af94d1e47a68c11e8fdb9f8368040601514a42a5a399cda48c7d3bff1e99d3

filename: ps-30a.bin
models: SCPH-5501/SCPH-7003 (Version 3.0 11/18/96 A)
crc: 8d8cb7e4
md5: 490f666e1afb15b7362b406ed1cea246
sha1: 0555c6fae8906f3f09baf5988f00e55f88e9f30b
sha256: 11052b6499e466bbf0a709b1f9cb6834a9418e66680387912451e971cf8a1fef

filename: ps-41a.bin
models: SCPH-7001/SCPH-7501/SCPH-7503/SCPH-9001 (Version 4.1 12/16/97 A)
crc: 502224b6
md5: 1e68c231d0896b7eadcad1d7d8e76129
sha1: 14df4f6c1e367ce097c11deae21566b4fe5647a9
sha256: 39dcc1a0717036c9b6ac52fefd1ee7a57d3808e8cfbc755879fa685a0a738278

filename: psone-45a.bin
models: SCPH-101 (Version 4.5 05/25/00 A)
crc: 171bdcec
md5: 6e3735ff4c7dc899ee98981385f6f3d0
sha1: dcffe16bd90a723499ad46c641424981338d8378
sha256: aca9cbfa974b933646baad6556a867eca9b81ce65d8af343a7843f7775b9ffc8

--------------------------------------------------

NTSC-J
======

filename: ps-10j.bin
models: SCPH-1000/DTL-H1000 (Version 1.0 J)
crc: 3b601fc8
md5: 239665b1a3dade1b5a52c06338011044
sha1: 343883a7b555646da8cee54aadd2795b6e7dd070
sha256: cfc1fc38eb442f6f80781452119e931bcae28100c1c97e7e6c5f2725bbb0f8bb

filename: ps-11j.bin
models: SCPH-3000/DTL-H1000H (Version 1.1 01/22/95)
crc: 3539def6
md5: 849515939161e62f6b866f6853006780
sha1: b06f4a861f74270be819aa2a07db8d0563a7cc4e
sha256: 5eb3aee495937558312b83b54323d76a4a015190decd4051214f1b6df06ac34b

filename: ps-21j.bin
models: SCPH-3500 (Version 2.1 07/17/95 J)
crc: bc190209
md5: cba733ceeff5aef5c32254f1d617fa62
sha1: e38466a4ba8005fba7e9e3c7b9efeba7205bee3f
sha256: 6f71ca1e716da761dc53187bd39e00c213f566e55090708fd3e2b4b425c8c989

filename: ps-22d.bin
models: DTL-H1100 (Version 2.2 03/06/96 D)
crc: decb22f5
md5: ca5cfc321f916756e3f0effbfaeba13b
sha1: 73107d468fc7cb1d2c5b18b269715dd889ecef06
sha256: 4018749b3698b8694387beebcbabfb48470513066840f9441459ee4c9f0f39bc

filename: ps-22j.bin
models: SCPH-5000/DTL-H1200 (Version 2.2 12/04/95 J)
crc: 24fc7e17
md5: 57a06303dfa9cf9351222dfcbb4a29d9
sha1: ffa7f9a7fb19d773a0c3985a541c8e5623d2c30d
sha256: 0c8359870cbac0ea091f1c87f188cd332dcc709753b91cafd9fd44a4a6188197

filename: ps-22j(v).bin
models: SCPH-5903 (VideoCD support)
crc: 446ec5b2
md5: 81328b966e6dcf7ea1e32e55e1c104bb
sha1: 15c94da3cc5a38a582429575af4198c487fe893c
sha256: 6ac8348c8dcd1e34882d5df2f4ba453e4de69847a88bb845ddda3915fa042df0

filename: ps-30j.bin
models: SCPH-5500 (Version 3.0 09/09/96 J)
crc: ff3eeb8c
md5: 8dd7d5296a650fac7319bce665a6a53c
sha1: b05def971d8ec59f346f2d9ac21fb742e3eb6917
sha256: 9c0421858e217805f4abe18698afea8d5aa36ff0727eb8484944e00eb5e7eadb

filename: ps-40j.bin
models: SCPH-7000/SCPH-9000 (Version 4.0 08/18/97 J)
crc: ec541cd0
md5: 8e4c14f567745eff2f0408c8129f72a6
sha1: 77b10118d21ac7ffa9b35f9c4fd814da240eb3e9
sha256: e900504d1755f021f861b82c8258c5e6658c7b592f800cccd91f5d32ea380d28

filename: ps-41a(w).bin
models: SCPH-7000W (Playstation 10 Million Model, BIOS based on NTSC-UC, **REGION FREE**)
crc: b7c43dad
md5: b84be139db3ee6cbd075630aa20a6553
sha1: 1b0dbdb23da9dc0776aac58d0755dc80fea20975
sha256: b3aa63cf30c81e0a40641740f4a43e25fda0b21b792fa9aaef60ce1675761479

filename: psone-43j.bin
models: SCPH-100 (Version 4.3 03/11/00 J)
crc: f2af798b
md5: 8abc1b549a4a80954addc48ef02c4521
sha1: 339a48f4fcf63e10b5b867b8c93cfd40945faf6c
sha256: b29b4b5fcddef369bd6640acacda0865e0366fcf7ea54e40b2f1a8178004f89a

--------------------------------------------------

PAL-E
=====

filename: ps-20e.bin
models: DTL-H1002/SCPH-1002 (Version 2.0 05/10/95 E)
crc: 9bb87c4b
md5: 54847e693405ffeb0359c6287434cbef
sha1: 20b98f3d80f11cbf5a7bfd0779b0e63760ecc62c
sha256: 0af2be3468d30b6018b3c3b0d98b8b64347e255e16d874d55f0363648973dbf0

filename: ps-21e.bin
models: SCPH-1002/DTL-H1102 (Version 2.1 07/17/95 E)
crc: 86c30531
md5: 417b34706319da7cf001e76e40136c23
sha1: 76cf6b1b2a7c571a6ad07f2bac0db6cd8f71e2cc
sha256: 1efb0cfc5db8a8751a884c5312e9c6265ca1bc580dc0c2663eb2dea3bde9fcf7

filename: ps-22e.bin
models: SCPH-1002/DTL-H1202/DTL-H3002 (Version 2.2 12/04/95 E)
crc: 1e26792f
md5: e2110b8a2b97a8e0b857a45d32f7e187
sha1: b6a11579caef3875504fcf3831b8e3922746df2c
sha256: 3d06d2c469313c2a2128d24fe2e0c71ff99bc2032be89a829a62337187f500b7

filename: ps-30e.bin
models: SCPH-5502/SCPH-5552 (Version 3.0 01/06/97 E)
crc: d786f0b9
md5: 32736f17079d0b2b7024407c39bd3050
sha1: f6bc2d1f5eb6593de7d089c425ac681d6fffd3f0
sha256: 1faaa18fa820a0225e488d9f086296b8e6c46df739666093987ff7d8fd352c09

filename: ps-41e.bin
models: SCPH-7002/SCPH-7502/SCPH-9002 (Version 4.1 12/16/97 E)
crc: 318178bf
md5: b9d9a0286c33dc6b7237bb13cd46fdee
sha1: 8d5de56a79954f29e9006929ba3fed9b6a418c1d
sha256: 5e84a94818cf5282f4217591fefd88be36b9b174b3cc7cb0bcd75199beb450f1

filename: psone-44e.bin
models: SCPH-102 (Version 4.4 03/24/00 E)
crc: 0bad7ea9
md5: b10f5e0e3d9eb60e5159690680b1e774
sha1: beb0ac693c0dc26daf5665b3314db81480fa5c7c
sha256: 5c0166da24e27deaa82246de8ff0108267fe4bb59f6df0fdec50e05e62448ca4

filename: psone-45e.bin
models: SCPH-102 (Version 4.5 05/25/00 E)
crc: 76b880e5
md5: de93caec13d1a141a40a79f5c86168d6
sha1: dbc7339e5d85827c095764fc077b41f78fd2ecae
sha256: 42244b0c650821519751b7e77ad1d3222a0125e75586df2b4e84ba693b9809dc

--------------------------------------------------

**Comment by LodanZark** [comment]
Added new bios to the list and split them per regions

**Comment by notaz** [comment]
AFAIK currently the core can find the bios named as suggested here.
