### ISSUE TITLE
Reset won't work with .m3u playlist

### ISSUE THREAD

**Issue by ghost** [libretro/pcsx_rearmed#124]
Reset the system via hotkey or menu option won't work if the game has launched with an .m3u playlist file
It only show bios boot logo then bios menu (memory card / cd player) and won't load the game.
If the game is launched with .cue file, restart works fine!

Specs:
Retropie 4.2 on Raspberry Pi 3

**Comment by retro-wertz** [comment]
can you check with latest release if problem still exists? if it still is. please post game title.

**Comment by negativeExponent** [comment]
this should be working in latest commits

@twinaphex @hunterk @hizzlesomething
