### ISSUE TITLE
[3DS] pcsx_rearmed crashes on latest homebrew setup

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/pcsx_rearmed#125]
Luma3DS 8.0
boot9strap 1.2

1. Start pcsx_rearmed core = OK
2. Choose content = OK
3. Launch content = Crash

[crash_dump_00000003.dmp.zip](https://github.com/libretro/pcsx_rearmed/files/1052379/crash_dump_00000003.dmp.zip)

tested:
* nightly 2017-06-05
* stable 1.6.0

also:
* stable 1.5.0 (different crash)

workaround:
* use psx_rearmed from 1.3.6 (2016-12-04) https://filetrip.net/dl?cdP1xfQ0vx

**Comment by gingerbeardman** [comment]
given your previous fixes @yshui do you have any ideas?

**Comment by Saphiresurf** [comment]
Can confirm this is still happening on the latest nightlies and the  latest stable build (testing out 7/20/2017 and 1.6.0).

**Comment by zwq939681378** [comment]
Thank you for your help.

**Comment by FateForWindows** [comment]
Still happens on 1.6.7, just so everyone knows. Too bad this probably won't be fixed.

**Comment by yshui** [comment]
OK, I did some investigation. Looks like the problem is in retroarch frontend (or at least in the interfacing with the frontend). 

I compiled latest pcsx with retroarch 1.5.0 and it runs fine.

**Comment by yshui** [comment]
I will do a bisect on retroarch and see if I can get anything.

**Comment by gingerbeardman** [comment]
Great! Thanks

**Comment by yshui** [comment]
Offending commit is libretro/RetroArch@5f9f43929a62f1d15eeaea74ebadc6917e3b9711

I have no idea why....

**Comment by yshui** [comment]
OK, I figured it out. This bug is really dumb....

**Comment by gingerbeardman** [comment]
Well done! Many thanks

**Comment by gingerbeardman** [comment]
Only just got around to trying this. 

1.6.7 still crashing for me?

**Comment by Saphiresurf** [comment]
Use one of the latest nightlies @gingerbeardman. This fix was made after 1.6.7 was released.

**Comment by gingerbeardman** [comment]
Ah! Thank you!

**Comment by Saphiresurf** [comment]
Of course!
