### ISSUE TITLE
Music stops playing in Diablo

### ISSUE THREAD

**Issue by MarcinSkoczylasSH** [libretro/pcsx_rearmed#129]
Quite often music stops playing in Diablo, especially during dialogue. It seems the music is faded out, and then almost immediately after fade in it stops playing, very easy to reproduce on Raspberry Pi3 and "stock" Diablo (U) image. I've seen this also in ePSXe some time ago, but other emulators were able to play music correctly.

**Comment by retro-wertz** [comment]
there is a proposed fix for Diablo in a few other pcsx forks, its its not intensively tested if it causes problems to other games if left enabled.

**Comment by AnotherLife** [comment]
Now that a separate Diablo fix option is added shouldn't this issue be closed?

@hizzlekizzle

**Comment by negativeExponent** [comment]
this should be working in latest commits

@twinaphex @hunterk @hizzlekizzle

**Comment by gameblabla** [comment]
My PR https://github.com/libretro/pcsx_rearmed/pull/541 fixes it properly without the use of a hack. I'm closing this.
