### ISSUE TITLE
Brave Fencer Musashi FMV issue

### ISSUE THREAD

**Issue by kelppo** [libretro/pcsx_rearmed#130]
When you start a new game on Brave Fencer Musashi (I used the US version), an intro FMV plays and it freezes after a while at the exact same time every time.
This doesn't happen on PCSX Reloaded, I couldn't find the specifics but I did find [this](http://www.planetemu.net/index.php?section=news&machine=56&openid=6535):

> - cdrom: merge code from PCSX ReARMed
*lots of hacks cleaned up
*removes port3 reschedule (fixes FMVs with Brave Fencer Musashi, etc still working)
*based on new information from Mednafen, nocash, and a few tests of my own

Edit: I have to mention that this issue is present on Android, I went ahead and tried it on my PC and somehow it doesn't happen there.

**Comment by esgwpl** [comment]
There it is.
https://github.com/mirror/pcsxr/commit/27c28fcc73ea885981eb2258fc4f0f986bf8cae5

**Comment by SapphireTactician** [comment]
I have this issue too, I was able to workaround it by skipping the opening cutscene, so the game is playable at least.

**Comment by jayare5** [comment]
Has this been solved? I would really like this game to not have this problem. I too can skip the opening cutscene, but you never know if this problem could happen somewhere in the middle of the game too. As it is, I cannot feel safe to play it.

**Comment by AnotherLife** [comment]
It is an issue with the FMVs so skip them!

**Comment by jayare5** [comment]
There has to be a way to not skip...
Did you know the cut-scene does show if you use no BIOS?
I don't know what side effects that might have on the game, but it shows that. So I'm assuming it has to be an easier fix than it seems.

**Comment by jurassicplayer** [comment]
The FMV issue is game-breaking. Even if you skip the opening cutscene, after you struggle with fixing Steamwood the first time, there is an unskippable cutscene directly after. More likely than not, there are more cutscenes in the game that are also unskippable.

**Comment by jayare5** [comment]
Wow... I hope it gets fixed then :/

**Comment by AnotherLife** [comment]
Is it fixed if you enable HLE bios?

**Comment by jurassicplayer** [comment]
I can't confirm if HLE bios actually fixes the Steamwood section, but it does allow the initial cutscene at the beginning of the game to play. 

Test setup: Raspberry Pi 3B+, Retropie 4.4.9, Retroarch 1.7.6, lr-pcsx-rearmed r22

When using HLE bios, saving/loading doesn't work so progress had to be made in one sitting (which I attempted), but while heading through Twinpeak, something failed as I exited the second cave past the suspension bridge (the cave with the water hazards) and I was kicked out to emulationstation.

I also attempted to load a savestate from my original game (the one not using HLE that got to Steamwood). Using HLE, the game does load the savestate, but fails to play the Steamwood cutscene. I have not tested if the starting point of the savestate effects anything (ex. saving outside of Steamwood vs saving immediately after losing control of the character upon completion of saving Steamwood) or if that could have any effect at all.

**Comment by gameblabla** [comment]
Does it still happen ? On PCSX Reloaded, there is a hack that allows this game to be playable. I could merge that to it if needed.

**Comment by jayare5** [comment]
> Does it still happen ? On PCSX Reloaded, there is a hack that allows this game to be playable. I could merge that to it if needed. However, i believe this is ARM specific if it still happens.

Did you ever merge it?
I happen to be testing the game again on the latest version of Lakka, RPi3b+, and it made it through the opening cutscene just fine with bios! Never seen this before.

**Comment by notaz** [comment]
This should be finally be fixed.
