### ISSUE TITLE
CDRom Support RPI3?

### ISSUE THREAD

**Issue by soulgriever** [libretro/pcsx_rearmed#131]
Is it currently possible to initiate a game from disc? I figure it should be, looking at "pcsx_rearmed/libpcsxcore/cdrom.c". Have disc mounted but since emulationstation is looking for an extension the game never shows.

**Comment by Jimmy-Z** [comment]
libpcsxcore/cdrom.c is PSX side.

**Comment by notaz** [comment]
Physical cdrom support has been implemented some months ago.
