### ISSUE TITLE
Polygons missing with dynarec(Gran Turismo 2)

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/pcsx_rearmed#135]
Working:
![gran turismo 2 usa simulation mode v1 2 -170831-185306](https://user-images.githubusercontent.com/1220805/29952505-ac1b6834-8e7e-11e7-9cc5-600dd2cb97b5.png)

Broken:
![gran turismo 2 usa simulation mode v1 2 -170831-185327](https://user-images.githubusercontent.com/1220805/29952509-b585f236-8e7e-11e7-8d2c-62522d6c9f54.png)

This also happens in crash team racing.

This only happens with the dynarec, you can disable the dynarec mid game with the switch and it fixes it but its too slow.

This will likely happen in all 3d games.

There is something the dynarec is not handling the same and the best way to test it would be to route all gte functions through the interpreter.

A lookup table may have an invalid entry or there could be a signed unsigned cast.

I can not fix this as I have looked into it before and found nothing, I will also be on vacation in a week.

Using official bios.
RetroArch 1.6.7
PcsxRearmed r22 358a876

**Comment by notaz** [comment]
I'm not seeing this, probably some dynarec bug fixed long ago.
