### ISSUE TITLE
add CHD support

### ISSUE THREAD

**Issue by bigboo3000** [libretro/pcsx_rearmed#137]
Hi
Beetle psx now has CHD support, it would be great if pcsx_rearmed had CHD support as well.
It's the only PSX core usable on RPI or old PCs.

**Comment by KMFDManic** [comment]
First of all, thanks so much @notaz for the great PicoDrive, and coming out of pseudo retirement to add some nice changes to the code, and @twinaphex for all the work you have been doing in your personal time, libretro wise!  Being that chd support has been added successfully for Genesis Plus GX, Mednafen PCE-Fast & Mednafen PC-FX, I would absolutely love to push for it to be added for pcsx_rearmed/neon.  I would love both of your opinions, as far as reasonable expectations, of this being achieved...if I post a bounty for it.  I am hoping to get chd support, additionally, for 4DO and Yabause.  I will have no problem getting a few people involved in bounties for these.  PicoDrive would be nice to have chd support, too, if it isn't too much of a hassle!  But, thanks to both of you, and I look forward to seriously getting this done, if you guys and anyone else involved do not mind doing it for a bounty!  Thank you in advance for your feedback.  I am hoping to get the bounty posted, today, once I get a proper response from you:)

**Comment by Darknior** [comment]
Yes CHD is the best ISO format :)
I dram to see it on all the systems like 4DO, Yabause, etc... like you write.
But on PSX it is not the same, we already have the perfect PBP format. I convert all my ISO in it and it works very fine ;)

**Comment by Darknior** [comment]
Ok ... wish some one add it to all RA core :)
And some one other create an easy program to convert ISO of all these systems to CHD !
For the moment i don't use CHD, only on Dreamcast.

**Comment by KMFDManic** [comment]
I already made an easy setup to convert to CHD:)

**Comment by Darknior** [comment]
Excellent, where can we DL it ? have you an url please ?

**Comment by KMFDManic** [comment]
I will post it for you shortly.

**Comment by Eckaji** [comment]
@Darknior 
I made the CHD step-by-step below a little while back, but it only converts the ones with a ".cue" or ".gdi".

https://redd.it/72kh6q

**Comment by Darknior** [comment]
Thanks a lot @Eckaji , i will try it :)
So cool if i can save place for Sega and Nec games.
PSX like you write i like PBP for multiple CD games ...
I wish it will come also for 3DO and other CD systems ...

**Comment by kidburglar** [comment]
Helllo,
It would be realy a good way to gain space.
I just looked how to convert existant bin/cue files to pbp and it's a complete hell...
Thanks for your work and I hope see chd support added soon

**Comment by bebess** [comment]
it would be so great...

**Comment by nosh01** [comment]
Bump!!!!!!

**Comment by fr500** [comment]
This is not 4ch. Bumping doesn't achieve anything other than annoying people.

**Comment by nosh01** [comment]
Wellll maybe I'll contribute to a bounty, I would assume that wouldn't trigger anyone.

**Comment by bebess** [comment]
@KMFDManic , do you have any news from @notaz and/or @twinaphex  ?
I'm totally ready to start a great bounty , i have created a new https://github.com/libretro/pcsx_rearmed/issues/170 for better visibility

But i'm waiting ... an answer...if someone "can" do the request

**Comment by gt46l** [comment]
Something no one has mentioned yet, but PBP is a lossy format.  You can't revert from a PBP to a burnable iso playable on hardware because it destroys the original format and converts audio/video to lossy versions.  CHD on the other hand is a non-lossy archive quality format that you can revert to burn and play on hardware.  PBP is nice if you just want to play your roms on a PSP emulator, but beyond that its not a format I want to keep 1200 roms in.  We need CHD support for all emulators to help with rom and hard drive space management, all other file formats are just for special use cases in my opinion.

**Comment by retro-wertz** [comment]
i wish.....

**Comment by AnotherLife** [comment]
PBP is not a lossy format, you can extract the game files and they will be byte for byte identical. Saying it converts audio and video to lossy formats is false, I'm pretty sure it just gzips.

CHD does LZMA and FLAC compression, that will increase the performance/memory impact a lot and introduce new audio bugs, as if there aren't enough already.

**Comment by gingerbeardman** [comment]
> PBP is not a lossy format, you can extract the game files and they will be byte for byte identical. Saying it converts audio and video to lossy formats is false, I'm pretty sure it just gzips.

I understood that you could get lossless files back out of an EBOOT.PBP but you could not get the original CD BIN/CUE back out of it (as yo van with CHD) so it's lossy depending on your source format? https://www.psdevwiki.com/ps3/PlayStation_archive_(PSARC)

> CHD does LZMA and FLAC compression, that will increase the performance/memory impact a lot and introduce new audio bugs

What are you basing this on?

**Comment by negativeExponent** [comment]
as far as i know, CHD should already be properly supported. so this can be closed.
