### ISSUE TITLE
[Bug] Ace Combat 3 EU - can't pass langage select screen

### ISSUE THREAD

**Issue by nemo93** [libretro/pcsx_rearmed#139]
Only in the EU version of the game you got this select screen after the initial loading screen and whatever control you've chosen nothing will move there. I've tried with analog, non analog etc with same result. The US/NTSC version of game is playing perfectly fine (although there's no langage selection screen).

I'm using a RPI3 with Retropie 4.2.20 + libretro-pcsx_rearmed (latest). All other games do play fine so it's not a conf or setup issue.

I've also reported this issue back to upstream [#93](https://github.com/notaz/pcsx_rearmed/issues/93)

**Comment by Darknior** [comment]
Just for help i have try on PC and it works perfectly.
But you are real, we have a bug on PI3 ... we can't move in the menu ...
If some one can't search why, maybe it can help on other games too ...

**Comment by nemo93** [comment]
Responding to myself as the best here is to go after the Japanese version which is far more superior to the US/EU ones ([reference](https://tcrf.net/Ace_Combat_3:_Electrosphere)). And it works! Apparently with some hiccups (#223) but it's fine for me for now.

**Comment by notaz** [comment]
Seems to be working now.
