### ISSUE TITLE
[Bug] Crash Bash (Europe) Can't see the in game battle menu

### ISSUE THREAD

**Issue by Darknior** [libretro/pcsx_rearmed#140]
When you play on PI 3 with Retropie 4.2 and the **last PCSX Rearmed from source** code, all the games are working perfectly. But some time we have some little bugs like this one that make  the game harder to use.

With **Carsh Bash** all is fine but in battle mode, when you press **START** to see the in game menu to leave the match or change arena, you **can't see any text**, only listen the sound when moving in the menu.
Is it possible to correct this issue ?

![20170911_000109_hdr](https://user-images.githubusercontent.com/3703317/30253531-8dea53f0-9687-11e7-9b44-77a9974c066a.jpg)

https://github.com/notaz/pcsx_rearmed/issues/95

**Comment by gameblabla** [comment]
I know that PAL Crash Bash has a few issues regarding RAM ticks (and i believe it needs SBI as well but could be wrong).
I would use the NTSC version in the meantime.

**Comment by CometHunter92** [comment]
Crash Bash (NTSC-U) is affected too

**Comment by notaz** [comment]
IIRC I fixed it a while ago, closing.
