### ISSUE TITLE
Implement pcsx rearmed on switch (request)

### ISSUE THREAD

**Issue by iOS4all** [libretro/pcsx_rearmed#149]
@notaz hi there.
As you can see the switch is officially hacked. And retroarch is already running on it.
So please can you implement this amazing core to switch?
Thanks a lot.

**Comment by hizzlekizzle** [comment]
It's still too early for those sorts of requests. Give it some time.

**Comment by notaz** [comment]
I have very little time, don't have the device, so very unlikely I can do any work on it anyway.
