### ISSUE TITLE
[Bug] RPI3 Transformers Beast Wars Transmetals freezes after intro

### ISSUE THREAD

**Issue by ghost** [libretro/pcsx_rearmed#150]
After the intro plays through or is skipped the game sits on a black screen and loads nothing. I am using a PDP converted from a redump verified bin file.

**Comment by jeffkrull** [comment]
There has been a slight improvement with this game in recent versions. The game makes it past the intro, but now seems to freeze on the VS loading screen in Story Mode after choosing a character.

**Comment by notaz** [comment]
Should be fixed now.
