### ISSUE TITLE
[Bios related bugs] "Show bios" option not working on restart.

### ISSUE THREAD

**Issue by bslenul** [libretro/pcsx_rearmed#153]
Update on the issues (June 10):

* **Wrong path for BIOS on Windows is fixed** (no need to have files in `/system` and `/system/sytem` anymore). #175 
* **Wrong BIOS loading on Linux seems to be fixed too** (I tried with a USA game and it loaded scph5501.bin). #166 I guess?
* `Show bios` option still not working properly while OFF when using `Quick Menu > Restart`. The option works fine when loading a game, just not on restarts.

&nbsp;

**ORIGINAL POST:**

Hey!

Weird bug with PCSX Rearmed, I put the 3 bios files (correct MD5) in `\RetroArch\system`, when I load the core they are detected: ![1](https://user-images.githubusercontent.com/33353403/36051859-d4d270fa-0deb-11e8-991c-3bfb63a03add.png)

But with `retroarch.exe --verbose` I saw this when launching a game: `Could not open BIOS:"D:\programmes\RetroArch\system/system/SCPH5501.bin". Enabling HLE Bios!`.

So, I said to myself "lets create a \system folder in the \system folder and move the bios inside!" but got this: `[INFO] Environ SYSTEM_DIRECTORY: "D:\programmes\RetroArch\system".
no BIOS files found.`.

So this time I copied the bios in \system **AND** \system\system :o And this time it worked: `[INFO] Environ SYSTEM_DIRECTORY: "D:\programmes\RetroArch\system".
found BIOS file: system/SCPH5501.bin`.

Games are still showing BIOS on restart, even with the `Show bios` option turned OFF.

P.S: Using RA 1.7.3 (May 4 2018) on Windows 10 (boot screen on restart also happend on Linux).

**EDIT**  
On my Linux Mint VM bios doesnt properly load too (RA 1.7.0, Feb 9 2018 Nightly), but in a different way, when loading a US game I got this:

> found BIOS file: scph5500.bin

Which is the JPN bios, the game starts so but when I restart I get this:
![sans titre](https://user-images.githubusercontent.com/33353403/36067294-76536c58-0eba-11e8-9b9a-0bf50074cf04.png)

If I remove JPN bios it loads the EU bios (scph5502.bin, even with Region set to NTSC!) but it restarts correctly. And yes, scph5501.bin is present!

**EDIT2**  
~~Another problem with bios, when playing Legend of Mana controls doesnt work for some reason, no problem with HLE bios...~~ (see my reply below).

**Comment by bslenul** [comment]
For Legend of Mana there's a workaround: Quick Menu > Options then set Pad 1 Type to 'analog' and restart :)

Only problem is that it's a core options so you can't make a Game Override and some games (Crash Bandicoot or Castlevania SotN for example) will not work with 'analog' :(

**Comment by bslenul** [comment]
Update on the issues (June 10):

* Wrong path for BIOS on Windows is fixed (no need to have files in `/system` and `/system/sytem` anymore). #175 
* Wrong BIOS loading on Linux seems to be fixed too (I tried with a USA game and it loaded scph5501.bin). #166 (I guess?)
* BIOS still showing on restart tho, even with `Show bios` set to OFF.

**Comment by retro-wertz** [comment]
**BIOS still showing on restart tho, even with Show bios set to OFF.**
This core option is misunderstood. This only works during loading loading the core, and wont take effect during when the core is already loaded.

**Comment by Kupo91** [comment]
"If I remove JPN bios it loads the EU bios (scph5502.bin, even with Region set to NTSC!) but it restarts correctly. And yes, scph5501.bin is present!"

Unfortunatelly that doesn't work for me. Yes it loads the EU bios but it still doesn't restart the game itself. So it is still not possible to play disk 2,3,4 or whatever

**Comment by Kupo91** [comment]
Booting the jpn bios was obviously caused by my old retroarch version. In newer ones it loads the correct bios. However it shouldn't boot any bios at all so the bug is still present and playing multidisk games stays impossible, too. Tested with Lakka 2.1.1. and Retroarch 1.7.5

**Comment by bslenul** [comment]
"Show bios" option is fixed! #235

Closing the issue and thanks for the fix 👍
