### ISSUE TITLE
(Bug) Soul Blade freeze on vs screen when using hidden characters

### ISSUE THREAD

**Issue by ghost** [libretro/pcsx_rearmed#154]
When selecting Siegfried!, Sophitia!, Sophitia!!, and Han Myong as characters the game freezes on the vs screen. This issue also happens with EPSXE where it crashes but Beetle does not have this issue.

**Comment by bad361** [comment]
It freezes regardless of what char you pick. I also tried diff modes, practice, arcade, time trial... It hangs/crashes on vs screen every time. Works fine in beetle tho, yeah. The game is a classic, weird to see it not working in rearmed.

**Comment by AnotherLife** [comment]
What about Duckstation?

**Comment by bad361** [comment]
> What about Duckstation?

It works in Duckstation without any issues too.

**Comment by notaz** [comment]
I think it works now. You can reopen if not.
