### ISSUE TITLE
PBP files no longer supported on latest version of the core!

### ISSUE THREAD

**Issue by blackman91** [libretro/pcsx_rearmed#158]
On Android just updated the core and it can't load pbp files anymore, pbp files are great format to save space on mobile devices, bin works fine, please fix it.

**Comment by litaniast** [comment]
CHD support is also needed

**Comment by hizzlekizzle** [comment]
It's probably related to the recent Android makefile changes.

CHD support isn't likely, I don't think.

**Comment by blackman91** [comment]
This build in my other Android device can still load pbp files:
![screenshot_2018-04-09-10-04-33](https://user-images.githubusercontent.com/6578180/38506012-48782bba-3bde-11e8-87eb-209e43c27e62.png)

**Comment by orbea** [comment]
pbp files work in linux for me with a freshly built core.

**Comment by hizzlekizzle** [comment]
Ok, weird. That leaves the makefile change as the only commit between working and nonworking, so I guess that must be the culprit. Odd, though, since it barely does anything...

**Comment by fr500** [comment]
The other change is that the buildbot now builds with clang

**Comment by orbea** [comment]
If this is broken on only some android devices, maybe there was a change in some part of android that caused side effects?

**Comment by Darknior** [comment]
I don't try the last version on my PI3 recently, but i really wish it's a little bug that will be corrected. We are so many to only use PBP, all my collection is in PBP, so fantastic format to save some HDD place and transform the multi-cd games in an only single file :)
I'm not really fan of CHD for PSX.

**Comment by blackman91** [comment]
Yep pbp is great for mobile devices to save a lot of space, for instance Vagrant Story pbp is only 200mb and the bin is almost 1gb.

**Comment by Yabuato** [comment]
CHD is far better than PBP in any way.Guess we need a bountry for it.

**Comment by fr500** [comment]
@blackman91 try updating the device you have still working to see if it breaks there too?

**Comment by blackman91** [comment]
Still fails to load pbp files on non root motog5 Android 7 on latest core, here is a log:
![screenshot_20180415-000359-01](https://user-images.githubusercontent.com/6578180/38775275-ca62dae4-4043-11e8-8c47-3c7a55cb9c4e.jpeg)

Tested on my other Android device too with Android 4.2.2 and root and the same happens:
![screenshot_2018-04-15-00-16-59](https://user-images.githubusercontent.com/6578180/38775276-d6b32510-4043-11e8-80f5-a04e431fd68f.png)

**Comment by blackman91** [comment]
This is fixed now:
https://github.com/libretro/pcsx_rearmed/commit/661e95f6360e9bcace4531c0ca529238629e49f6

Thanks a bunch guys.

**Comment by orbea** [comment]
On a side note, why is it using `-funroll-loops`? Do we really need silly optimizations like that?
