### ISSUE TITLE
Screen position bug

### ISSUE THREAD

**Issue by Yabuato** [libretro/pcsx_rearmed#160]
Screenshot: https://i.imgur.com/lPeZbNV.jpg

The graphic of some games like Sexy Parodius and Gradius Gaiden auto-move to left side when they should be in middle of the screen,screenshot above is ePSXe,bottom one is RA PCSX-ReARMed core,is there a way to fix this?Thanks in advance.

**Comment by orbea** [comment]
Are you using a real bios?

If you aren't running on android or another arm device you could try using beetle-psx instead.

**Comment by orbea** [comment]
If you load the core and then in the retroarch menu go to `Information` -> `Core Information` does it show the bios as found? The bios file names might be case sensitive?

**Comment by Yabuato** [comment]
Yes,bios has been found.Excatly i've put all the psx bios to the system dir despite it only need a SCPH1001.BIN.

I can tell it's not bios or games issue because i'm using the same bios and games but ePSXe has no screen bug.

**Comment by Yabuato** [comment]
This man has the exactly same screen issue: http://www.theisozone.com/forum/viewtopic.php?f=74&t=57558

**Comment by orbea** [comment]
Do you have any cpu filters enabled? You can find them under `Settings` -> `Video` -> `Video filters`.

How about gpu shaders?

**Comment by Yabuato** [comment]
Yep,that is the only way to centered the in-game screen but the whole ui would be moved to right and leave the left side with black border.
It seems So it's a android particular issue.

**Comment by AnotherMuggle** [comment]
I think Gran Turismo intro is another example of this. On real hardware there are narrow black bars at the top and bottom of the screen.  I this core the screen is pushed all the way to the bottom,  leaving only a large black border at the top, and no border at the bottom. 
![screenshot_20181107-095110](https://user-images.githubusercontent.com/42422130/48124390-18812280-e274-11e8-9403-aedfc632a1ec.png)

**Comment by notaz** [comment]
Should be centered properly now.
