### ISSUE TITLE
Possible performance regression on Lakka RPi3

### ISSUE THREAD

**Issue by metchebe** [libretro/pcsx_rearmed#163]
Hello

On Lakka 2.1 stable on my RPi3, the latest armhf core from the [buildbot](http://buildbot.libretro.com/nightly/linux/armhf/latest/) from April 10th 2018 has a noticeable performance regression which I discovered in a brief test of around 4 games.

Also, I see that now the neon enhancements do not show up in the core options menu. I have them enabled from before and continue to work well in the lakka-shipped core (and the previous buildbot core):

```
pcsx_rearmed_neon_enhancement_enable = "enabled"
pcsx_rearmed_neon_enhancement_no_main = "enabled"
```

I have not tested if disabling the neon enhancements fixes the performance issue.

PS: I am aware that using buildbot cores in Lakka is not recommended, but I have had no issues until now.

**Comment by notaz** [comment]
Tons of things changed since 5 years ago so I'll assume this is fixed. Also the enhancement options should be available in menus.
