### ISSUE TITLE
Abe's Exoddus swap discs bug when using NEON. Maybe more games concerned?

### ISSUE THREAD

**Issue by bslenul** [libretro/pcsx_rearmed#168]
Hi, when playing Abe's Exoddus on SNES Classic Mini when the ingame prompt asks you to change disc it will say `Incorrect Disc Inserted` for some reason while using PCSX ReARMed r22 (tried with multiple commits): https://youtu.be/QoPyaPaJU0E (I voluntarily switched disc 1 and 2 in the playlist).

Weird thing is that it's only happening with the NEON "optimization" (?), if I use the normal core [from here](https://buildbot.libretro.com/nightly/linux/armhf/latest/) the disc swap works fine BUT the game runs at 5fps: https://youtu.be/tb5hfWVqPrY

I also tried with my Android phone to see if it was just on SNESC (Samsung A5 2016, RetroArch 1.7.2 [8002569](https://github.com/libretro/RetroArch/commit/80025692c18553f528b8abfb2c0e472d82ff443c) / PCSX ReARMed c6e7ce9) but the same behavior happened, `Incorrect Disc Inserted` when swapping.

Maybe more games are concerned with this issue, it's the only one giving me trouble from the ones I tested (Xenogears, MGS and FFVIII).

I'm not sure they can help but here's the log files:
[abe_not-working.log](https://github.com/libretro/pcsx_rearmed/files/1957561/abe_not-working.log)
[abe_working.log](https://github.com/libretro/pcsx_rearmed/files/1957562/abe_working.log)

**EDIT**  
Oops, forgot to say: tested on USA version of the game, it works fine with the PAL version.  
Also, tested with scph5500/1/2.bin and with HLE BIOS, same problem.

**Comment by bslenul** [comment]
Found a workaround, if that may help resolve the problem: when the game asks you to swap disc, just go to `Quick Menu > Options` and turn OFF `Dynamic Recompiler`, swap disc and it works! Once the second disc is loaded, turn the option back ON :)

**Comment by notaz** [comment]
I'll assume it's one of the old dynarec bugs that have been fixed, if not feel free to reopen.
