### ISSUE TITLE
Controls questions

### ISSUE THREAD

**Issue by esoptron2** [libretro/pcsx_rearmed#169]
1. What does the default setting for the Pad Type do? Is it any different from the standard setting?

2. Does Pad Type need to be set to analog for vibration to work?

3. How is the negcon mapped to the RetroPad?

**Comment by louisrousseau** [comment]
Running RetroArch 1.7.2 with PCSX-ReARMed r22 c6e7ce9 on an Nvidia Shield TV.
I'd also like to use the analog sticks and triggers from the Shield's controller as a neGcon, not getting anywhere in Wipeout.
I've tried setting the pad type to neGcon, I only get something from the d-pad, start and "Y / triangle / II" buttons.
Interestingly, it's possible to change the controller type at runtime and the options menu reacts accordingly.

**Comment by retro-wertz** [comment]
ive updated the docs and i think i missed this one that rumble only works when pad type is set to dualshock or analog
(more docs update then...)

**Comment by AnotherLife** [comment]
The user can disable Vibration in the options if it is unwanted so I think it's OK from a user standpoint. Although it's weird from an emulation standpoint.

**Comment by notaz** [comment]
Vibration should now activate for dualshock only. Anyway it seems the questions have been answered.
