### ISSUE TITLE
ARM64 build failure

### ISSUE THREAD

**Issue by IntelMiner** [libretro/pcsx_rearmed#172]
Hi,

I'm attempting to port RetroArch and all its available cores to ARM64/ARMv8. pcsx-rearmed appears to fail to build

Using the current latest git commit `c6e7ce9ef2e39e798dfc0b0fe071064b11b4ca9e`

compilation seems to fail with several errors

I've uploaded the [build log here](https://paste.pound-python.org/raw//rt5DKg1AJy9IisMdtZfu/)

I've also been working with the person maintaining [the build scripts here](https://github.com/stefan-gr/abendbrot/issues/113) and linking in other relevant bugs for each core as I can

**Comment by bparker06** [comment]
I think you need to disable the dynarec, which uses ARMv7-only assembly. @webgeek1234 has also done a lot of work porting cores to ARMv8 on Android, he may be able to help you as well.

**Comment by notaz** [comment]
This should be long resolved.
