### ISSUE TITLE
Bios issue on windows

### ISSUE THREAD

**Issue by leranger** [libretro/pcsx_rearmed#173]
Hi,

The core doesn't use bios on windows.
In the log file, I can see that the core founds the bios:
`[INFO] Environ SYSTEM_DIRECTORY: "C:\Games\libretro\RetroArch-1.7.3\system".
found BIOS file: system/scph5502.bin`
But then it says that it can't open it:
`Could not open BIOS:"C:\Games\libretro\RetroArch-1.7.3\system/system/scph5502.bin". Enabling HLE Bios!`

It seems that core concat RetroArch system directory with the bios found.
Thus getting "system" directory twice in the full path.

Thanks

[retroarch.log](https://github.com/libretro/pcsx_rearmed/files/2004237/retroarch.log)

**Comment by bslenul** [comment]
#153 

You have to put your bios files also in `\system\system` on Windows, which is a bit weird :p

**Comment by leranger** [comment]
Thanks, it worked.

**Comment by fr500** [comment]
Please reopen it so someone remembers to fix it someday

**Comment by leranger** [comment]
OK, I closed this issue because this problem seems to be referenced in #153

**Comment by leranger** [comment]
Hi,
Commit #175 seems to fix the issue.
Thanks
