### ISSUE TITLE
Crash when running CTR: Crash Team Racing

### ISSUE THREAD

**Issue by ctr-user** [libretro/pcsx_rearmed#174]
I'm trying to run the European version of CTR: Crash Team Racing. [This is the release I'm using]( http://redump.org/disc/897/).

I've got the cue/bin files, as well as the sbi file. I've verified the checksums.

I'm using BIOS `SCPH5552.BIN`, md5 checksum `32736f17079d0b2b7024407c39bd3050`. I've tried other BIOS files (SCPH1001, SCPH1002) and they all crash.

I can launch the game fine. I can even start and drive around in Adventure mode. However when I try to enter a race, the emulator crashes at the loading screen, after a few seconds.

I'm running the emulator using `/opt/retropie/emulators/retroarch/bin/retroarch --verbose --libretro /opt/retropie/libretrocores/lr-pcsx-rearmed/libretro.so <FILE>`. This is the output when it crashes—

```
NI 9f75237a @800ac40c (800ac408)
branch in delay slot @800ac418 (800ac408)
Compile at bogus memory address: 830a8db4
```

Let me know if you need any more details.

This is the build I'm running—

```
[INFO] RetroArch 1.7.3 (Git b2ceb50)
[INFO] === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: May 14 2018
[INFO] Version: 1.7.3
[INFO] Git: b2ceb50
[INFO] =================================================
```

My machine is a Raspberry Pi 2 Model B v1.1.

FWIW, running the same game, same BIOS, with the regular PCSX-ReARMed with its default settings (which I compiled at the same time as the libretro port) ran the game fine.

**Comment by leranger** [comment]
Hi,
I tried the game (same md5 than yours) with PCSX-ReARMed core on : 
- RPI2 with latest lakke nightly build => ok
- android => ok
- windows => ok

I have used bios scph5502.bin which has the same md5 checksum than your 5552 one.

Could you try latest lakka nightly build (http://nightly.builds.lakka.tv/2018-05-28/RPi2.arm/) on your PI ?

If it works, the problem probably comes from retropie provided core.

**Comment by bslenul** [comment]
I know the name of the bios is really important for some cores, if you check the docs for PCSX you'll see that your bios is incorrectly named: https://docs.libretro.com/library/pcsx_rearmed/#bios

So try renaming you bios from `SCPH5552.BIN` to `scph5502.bin`.

**Comment by ctr-user** [comment]
Thank you @leranger and @bslenul.

I want to add something.

> Running the same game, same BIOS, with the regular PCSX-ReARMed with its default settings (which I compiled at the same time as the libretro port) ran the game fine.

Regular PCSX-ReARMed (which I configured to use the same BIOS) works fine.

It is the libretro PCSX-ReARMed, this repo, that does not work.

**Comment by leranger** [comment]
Hi,
I used libretro core from this repo to run my tests with retroarch.
But the one provided with retropie maybe older or build with different compilation options or ...

You should rename your bios (lowercase at least). Linux systems are case senstive.
Check retroarch log to see if your bios is found.

**Comment by AndreaA14** [comment]
Hi, I am experiencing exactly the same problem with CTR on Raspberry PI 4 and Lakka / retroarch latest version.
The game crashes when entering a level.
Using bioses scph5502.bin  and scph1002.bin all correctly named.

Any Idea how to solve the issue? I read people that say it just works fine.

**Comment by bslenul** [comment]
> Using bioses scph5502.bin and scph1002.bin all correctly named.

So PAL version of the game? You need a .sbi file for it: http://redump.org/sbi/psx/

Extract one of the 2 .sbi available in that zip for CTR (they're identical, only filename differs) in the game folder, and make sure to rename it using the same filename as the file you're loading (e.g. if you're loading `CTR.cue`, rename the .sbi into `CTR.sbi`).

If you're still having issue, please ask in help chan on Libretro's Discord: https://discordapp.com/invite/27Xxm2h this is probably a better place than this thread ;)

**Comment by AndreaA14** [comment]
It worked! 
Thank you so much!
