### ISSUE TITLE
No way to access all the advanced options

### ISSUE THREAD

**Issue by rsn8887** [libretro/pcsx_rearmed#176]
The emulator has a native menu system rendered via libpicofe with many advanced options, as shown here:
https://retroresolution.com/2016/01/01/playstation-emulation-on-the-pi-enhancing-the-experience-with-the-options-menu-part-one-basic-features-and-save-states/

In the code, this is here for example, with many more menus above and below:
https://github.com/libretro/pcsx_rearmed/blob/5095009a1a893a04af9bb62d8cf4fe54dd97acf0/frontend/menu.c#L1557

For example, there should be a [speed hacks] menu where the user can adjust the cpu speed, a memory card management menu etc. 

Most of these options are not accessible in Retroarch. Because the flag NO_FRONTEND is set and libpicofe is not linked, the native menu system can not be summoned with ESC to set these options. Some of the options are present in the Quickmenu in XMB/Rgui, which is where all options should be, but most of them are missing.

**Comment by Darknior** [comment]
Yes great idea, it can be cool if these options can be added to CORE menu.

**Comment by retro-wertz** [comment]
psx cpu overclock is at least added in latest commit (only for dynarec builds)

**Comment by AnotherLife** [comment]
The Disable XA audio and disable CD audio could be useful to test things, save some CPU cycles or get rid of annoying distorted audio. Or get rid of distorted music when the framerate drops like what happens to me in Gran Turismo 2 on the PS Classic (I use enhanced resolution)

I mean sure, I can lower the music volume to 0 in the game options but I'm pretty sure the emulator is still burning valuable CPU cycled decoding music I don't hear.

@retro-wertz can you take a look at it? Maybe it's a simple boolean change in each case.

Maybe it will also be a workaround for game crashes etc.

**Comment by retro-wertz** [comment]
as the way the options are handled in libretro, i dont want to just add so many options unless it does confirm to help compatibility etc and/or a have great request for such option, most of those options are not even relevant to the libretro port..

**Comment by hizzlekizzle** [comment]
Can we get a list of the options that are applicable to libretro and then we can decide how/if we want to expose them?

**Comment by retro-wertz** [comment]
pcsx menu items can be checked here (search for **menu_entry** for quicker browsing:
https://github.com/libretro/pcsx_rearmed/blob/master/frontend/main.c

there are a bunch of fixes in the peops gpu plugin which might be useful.

there are 3 more hack options for dynarec too aside from PSX cpu clock.

i am more interested in the iTempo for the SPU section since this can at least remedy left-right audio desync in Legend of Mana's fmv's but the necessary function is not available for libretro's port.

a lot of these aside from having long descriptions, they are always noted "breaks compatibility".

**Comment by AnotherLife** [comment]
@retro-wertz 

Will you consider adding a "Disable XA audio" option? It would be good for debugging and for optimising performance. Some games run at close to fullspeed but the audio gets distorted, like I mentioned earlier.

**Comment by notaz** [comment]
The options have been added long ago.
