### ISSUE TITLE
[Regression] - Is it needs setting controller type?

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/pcsx_rearmed#177]
Hi,
In previous versions of the core, I didn't need set the controller type (default, analog or standard), independently of the game: I could play Rage Racer or RR Type 4 without never have to change the type of controller. Now is impossible: If I want to play Ace Combat 2 using the analogs I should set this in core's options, but keeping it makes the controller useless in Rage Racer.
What's happened?

**Comment by retro-wertz** [comment]
there is a **save game-options file** which remedies this issue...
