### ISSUE TITLE
reported resolution is not the game native resolution

### ISSUE THREAD

**Issue by Sakitoshi** [libretro/pcsx_rearmed#180]
while most ps1 games use the current reported resolution of 320x240 there are many games that use a non-standard resolution but the core still reports 320x240 even when is rendering resolution is different.
I noticed this while using my raspberry pi on a crt tv, the scanlines weren't even.

here are some screens of Crash Team Racing illustrating the issue:
![ctr_3](https://user-images.githubusercontent.com/39132563/42854918-355e48e4-8a0c-11e8-96c8-227d6f7e1c4c.png)
![ctr_1](https://user-images.githubusercontent.com/39132563/42854934-39cd6cd4-8a0c-11e8-9080-814fb3c901f8.png)
![ctr_4](https://user-images.githubusercontent.com/39132563/42854945-4205cbf8-8a0c-11e8-8711-42d3c20acbaf.png)
![ctr_2](https://user-images.githubusercontent.com/39132563/42854950-45d04aec-8a0c-11e8-97c1-cec549f7ffd4.png)
![ctr_5](https://user-images.githubusercontent.com/39132563/42854961-4b3d4534-8a0c-11e8-8893-06cd7c548867.png)
![ctr_6](https://user-images.githubusercontent.com/39132563/42854963-4f1cdaac-8a0c-11e8-9f46-6fd4b706011b.png)

I understand that this is done because there are games that change resolution while running but this affect the integer scale setting, I suggest adding a core option to toggle this behavior.
Another way of fixing this that will be very helpful for crt screens is leave the vertical resolution as 240 and not crop the overscan (leave black bars at the top and bottom).

**Comment by kamicane** [comment]
Just encountered this issue myself when using this core on a pi + crt.
This also makes it impossible to correctly switch 240p to 480p on multiscan monitors for games that natively run on 480i.

**Comment by hizzlekizzle** [comment]
This should be closed by #307, I think, so I'm going to close it. If it's still a problem, feel free to reopen.
