### ISSUE TITLE
Issue with swapping disks

### ISSUE THREAD

**Issue by Kupo91** [libretro/pcsx_rearmed#181]
Hi,

I use LibreElec 8.2.3.1 with Retroarch 7.0.2-J08 and PCSX Rearmed (r21) on a TV Box with Amlogic S905X chip. 
If I swap disks of a multidiskgame and restart the game I always end up in bios (the japanese one) no matter if my games have *.PBP or *.m3u files.

So playing multidisk games is nearly impossible at the moment.

**Edit:**

Can be closed.

Same issue like [Bios related bugs] "Show bios" option not working on restart. #153

**Comment by retro-wertz** [comment]
you can actually close this since you are the thread starter...
@hizzlekizzle favor?
