### ISSUE TITLE
[3DS] core incompatibility with updated versions of devkitARM

### ISSUE THREAD

**Issue by abelbriggs1** [libretro/pcsx_rearmed#189]
Not sure where else I can get help on this. I tried the RA discord but there doesn't seem to be anyone there who compiles their own RA 3DS builds, and the one person I can think of who does often seems to be MIA.

Trying to compile PCSX rearmed for 3DS. I have the devkitpro/devkitARM toolchains installed with the 3ds-dev package. whenever I try to compile via libretro-buildbot-recipe.sh from libretro-super, I get some compilation errors: https://pastebin.com/8VQ4ENxi

Specifically, these two segments:
```
In file included from libpcsxcore/cdriso.c:38:
frontend/3ds/pthread.h:17:2: error: conflicting types for 'pthread_t'
 }pthread_t;
  ^~~~~~~~~
In file included from /opt/devkitpro/devkitARM/arm-none-eabi/include/sys/types.h:239,
                 from /opt/devkitpro/devkitARM/arm-none-eabi/include/stdio.h:61,
                 from libpcsxcore/psxcommon.h:35,
                 from libpcsxcore/cdriso.c:22:
/opt/devkitpro/devkitARM/arm-none-eabi/include/sys/_pthreadtypes.h:32:20: note: previous declaration of 'pthread_t' was here
 typedef __uint32_t pthread_t;            /* identify a thread */
                    ^~~~~~~~~
In file included from libpcsxcore/cdriso.c:38:
frontend/3ds/pthread.h:18:13: error: conflicting types for 'pthread_attr_t'
 typedef int pthread_attr_t;
             ^~~~~~~~~~~~~~
In file included from /opt/devkitpro/devkitARM/arm-none-eabi/include/sys/types.h:239,
                 from /opt/devkitpro/devkitARM/arm-none-eabi/include/stdio.h:61,
                 from libpcsxcore/psxcommon.h:35,
                 from libpcsxcore/cdriso.c:22:
/opt/devkitpro/devkitARM/arm-none-eabi/include/sys/_pthreadtypes.h:75:3: note: previous declaration of 'pthread_attr_t' was here
 } pthread_attr_t;
   ^~~~~~~~~~~~~~
```

I'm on Linux Mint 19, x86_64. I tried doing this on Windows 7 but arrived at exactly the same error.

I'm not really sure what I can do to fix this. it looks like something in devkitARM is conflicting with the code in PCSXR and its 3ds frontend.

I know that the 3DS nightly buildbot builds get compiled with this core, so I'm kind of perplexed.

I would think it's something with my configuration, but I tried and failed using MSYS2 on Windows, completely wiped Windows(for unrelated reasons) and installed Linux Mint, and I still receive the same error.

The two things I can think of that are constant are the version of devkitPro I have installed(the most recent version) and the hard drive I pulled libretro-super to.

Any help is appreciated.

**Comment by meepingsnesroms** [comment]
I am working on getting 3ds updated to the newest devkitARM, that is what is causing this issues, I made my own pthread implementation and devkitARM ironically defines those types to prevent compilation errors but has no actual pthread implementation for 3ds.

**Comment by abelbriggs1** [comment]
Is the libretro buildbot also using an old version of DKARM then?

I did some Googling and apparently the DKPro devs erase the existence of older versions off the face of the earth when they update, so reverting version doesn't seem to be an option, unfortunately...

Thanks for all your contributions to libretro, by the way.

**Comment by meepingsnesroms** [comment]
Yes we use an old version with some even older functions hacked in, I am trying to fix this now though.

**Comment by FateForWindows** [comment]
Also be sure to change the core to unai.

**Comment by abelbriggs1** [comment]
Coincidentally, the reason I ended up trying to build for 3DS was specifically to test the Unai GPU plugin turned off in the makefile, as reported in your issue.

On the subject of Unai, I don't think it needs to be 'ported', per se(P.E.Ops was never built specifically for ARM either, to my knowledge). It just needs to be tested to see if it works at all, and if it does, whether it gives an acceptable performance increase for the accuracy tradeoff, if it gives any performance increase at all.

**Comment by fr500** [comment]
It doesn't it's a single line change.
It's not faster at all for me but on the 3DS it may I guess.

**Comment by gameblabla** [comment]
The code has been removed ever since i merged https://github.com/libretro/pcsx_rearmed/pull/552 as it was known to cause problems with Kyuukentai and an extra CDDA delay as well as a crash that could occur when combined with CHD...
This was a bad idea anyway, had little performance benefits and was prone to crashes
