### ISSUE TITLE
Sudden slowdown/lag unplayable games...

### ISSUE THREAD

**Issue by LimeyGeeza** [libretro/pcsx_rearmed#192]
Hey there, I recently did an 'Update' of all my cores and packages and now PSX games using lr-pcsx-rearmed are running very slow, laggy and unplayable. 

Games used to run fine until recently. Tried removing lr-pcsx-rearmed, deleting config files and re-installing and still have the same issue. Tried updating with source/binary - same issue. Even tried a different power supply to the pi - as I heard that could be an issue, still the same.

Running on a Raspberry pi3B+ with Retropie version 4.4.2, lr-pcsx-rearmed.

Very frustrating that just days ago it was running fine and now all games are unplayable, any help would be greatly appreciated!

Thanks

**Comment by hizzlekizzle** [comment]
There have been no changes to PCSX-ReARMed that could affect speed in months, so there's something amiss with your configuration. Do you have hard GPU sync or runahead enabled?

**Comment by LimeyGeeza** [comment]
I just went through the settings and disabled everything and enabled everything one-by-one, seems it might have something to do with:

Sound: Reverb 
Sound: Interpolation

Reverb is disabled and Interpolation is now set to off and everything now seems to be running fine again. No idea if they are on by default or if I turned them on by accident at one point (I have no idea how if I did). Anyway games are running great again.

What do both of these settings do anyway? And should they be on?

Hopefully this might help someone else if they come across it.

**Comment by hizzlekizzle** [comment]
There's an explanation of the core options here:
https://docs.libretro.com/library/pcsx_rearmed/#core-options

In short, reverb adds reverb (:P) while interpolation determines which algorithm is used in the sound interpolation process when it converts the audio from the PS1-native format to PC-native.
