### ISSUE TITLE
[Suggestion] Removing unused builds (caanoo, pandora, maemo), libpicofe dependency, and unused plugins (gpu-gles, spunull)

### ISSUE THREAD

**Issue by dannbuckley** [libretro/pcsx_rearmed#196]
Hello all,

About a year or two ago, I took a stab at making this project more dependant on the libretro framework. My approach included the following three steps:
 * Removing builds other than libretro in the Makefile(s)
 * Eliminating the dependency on the libpicofe library, because there was no instance I could find in the libretro build where including libpicofe was necessary
 * Removing the plugins that had no use (e.g. the function of spunull can be accomplished through RetroArch's mute setting)

This approach requires a lot of functions to be either altered or deleted entirely but would result in a less convoluted build process.
You can check my work [here](https://github.com/LEGOAnimal22/libretro-playstation) if you are curious.

Thanks,

LEGOAnimal22

**Comment by fr500** [comment]
As far as I know retaining the build system was a condition from upstream,
so it  stays.
Removing some files in a directory doesn't really accomplish anything
anyway.

What I would do instead is to make a libretro folder with the full libretro
solution and keep the files outside untouched as much as possible.
AFAICT there is nothing convoluted on building this core... I have built it
for PC, android, 3ds, linux without any issues.

That all being said, I think @twinaphex always meant to have a deeper fork
to backport stuff from other PCSX forks, may be worth revisiting.

**Comment by fr500** [comment]
You didn't retain any of the git history.... that's the worst thing you could ever do, it makes everything unmergeable.

**Comment by LEGOAnimal22** [comment]
Even if this was a fork, it would still be unmergable. I was thinking of creating an entirely new fork of pcsx and starting the process over again.
