### ISSUE TITLE
Analog Joystick (SCPH-1110) support in emulator

### ISSUE THREAD

**Issue by mEsUsah** [libretro/pcsx_rearmed#198]
Hi,

I'm having a blast using the emulator on my retropie. You guys are amazing 👍 

I have tested Descent 1 and 2, and Mechwarrior 2. These games run MUCH better on the emulator compared to the original hardware, but unfortunatly, i can't use my Analog Joystick (SCPH-1110) to fully enjoy the games in HD glory.

The games support analog controls, but only with the Analog Joystick (SCPH-1110).

Can you add support in the emulator for this controller?

It would be amazing if you made it mapped to reflect a dual shock or analog controller. It is in my opinion strange that the games don't support a regular analog controller, just the Analog Joystick (SCPH-1110)...

PS: The PS1 versions of descent 1 and 2 are the only ones (to my knowlege) that supports 4 axis analog control!

**Comment by retro-wertz** [comment]
this is already available in latest commit.
