### ISSUE TITLE
LibNX - Disc Track Problems

### ISSUE THREAD

**Issue by SeongGino** [libretro/pcsx_rearmed#199]
## Issue:

PCSX-ReARMed, in its current state, cannot load disc images whose original track layout has six or more distinct tracks (usually represented as multiple bins in the image used). This causes a variety of problems regarding games whose data is distributed across multiple tracks, leading to either music loss, or outright game crashes.

### Steps to reproduce:

1) Load a disc image in any format whose original track data calls for six or more distinct tracks (I.E. 6 or more unique files). This can be in either .cue/.bin format, or compressed as a .PBP of any compression level. OR, load the first unique .bin of any compatible disc image.

This will lead to a variety of problems, ranging from loss of music data, to outright crashes (observed most prominently/immediately in "PepsiMan - The Running Hero (Japan)"). Games that do not have this distinct trait in their rips need not apply (example: "Mega Man X6" (any region) plays as intended).

### Tested on:

RetroArch: 1.7.5 (LibNX version)

### Notes:

This only applies to the LibNX version of RetroArch for Nintendo Switch, and is not a core issue acknowledged on other platforms (I.E. x86_64, ARM, etc.). This has been tested using Homebrew Launcher as a system application, meaning RetroArch has a total ~400MB available RAM to use. This issue has been noted since before the official RetroArch for Nintendo Switch release (formerly known as "RetroNX").

**Comment by m4xw** [comment]
@SeongGino This is the wrong repository, for further Issues lets use
https://github.com/libretro/pcsx_rearmed_switch

**Comment by notaz** [comment]
Closing this because libretro/pcsx_rearmed_switch#1 was closed.
