### ISSUE TITLE
Dino Crisis (SLES-02208) with French language patch doesn't load game

### ISSUE THREAD

**Issue by fraf** [libretro/pcsx_rearmed#200]
Hi,
SLES-02208 rom (dino crisis) with applied french patch doesn't pass the "hack" screen (when press start to play).
Same problem with epsxe 2.0.5.
But a reliable psx compliant emulator is "pSX_1_13" and with this one, the iso patched load and continue to game introduction.
So the problem does not come from bad patch iso.

Cheers

**Comment by fraf** [comment]
Forgot : tested with retroarch 1.7.5

**Comment by AnotherLife** [comment]
The real question is: if you burn the patched iso to a CD will it play properly on a modded console?

**Comment by fraf** [comment]
I close thé issue . Works with 176 retroarch.
