### ISSUE TITLE
Disable second memory card for playing games like Tenka

### ISSUE THREAD

**Issue by Loquo** [libretro/pcsx_rearmed#207]
Hi there!

There is a problem that I can't find out how to approach it...

When I start the video game Lifeforce Tenka (Codename: Tenka in USA) in PCSX:ReARMed (in Raspberry Pi 3 with Retropie), the game perceive that there are both Memory Cards, and this situation doesn't allow to get to the game's main menu. Tenka requires that only one of the Memory Cards (or none) be inserted. Then, in order to get access to the main menu and can play the game, we need the option to disable second memory card.

I know that there is a Core option for "enable or disable second memory card", but this do nothing... Somehow, the game keep thinking that there are 2 Memory Card inserted.

Is there any solution? Thank you a lot!

**Comment by hizzlekizzle** [comment]
I have verified that this is indeed an issue and occurs on other platforms, as well, including x86/64 (i.e., good for debugging).

**Comment by retro-wertz** [comment]
fixed on latest commit, both with using real bios and hle
