### ISSUE TITLE
Soul Blade hangs/resets in Edge Master mode

### ISSUE THREAD

**Issue by zcal** [libretro/pcsx_rearmed#208]
Soul Blade (SLUS00240) hangs at the VS screen in Edge Master Mode when using the HLE BIOS, leaving RetroArch completely unresponsive.  When using the scph5501.bin BIOS, the game will hang momentarily and then reset to the Playstation boot screen.

Tested in both Android and Arch Linux using core version r22 28ea3e2.  Running RetroArch from the command line (Arch Linux) does not result in any errors reported there when this issue occurs.

Steps to reproduce:
1. Start the game.
2. Select "Edge Master Mode" from the main menu.
3. Select a character (it does not matter which).
4. Select "Book" on the map screen.
5. Flip through the pages until reaching the "Press Start >> Battle" page.
6. Press Start.
7. Notice that the VS screen will load and then emulation will hang.

**Comment by gameblabla** [comment]
Still happens, although now it actually crashes the whole emulator. : P

**Comment by CometHunter92** [comment]
Any update?

**Comment by CometHunter92** [comment]
Funnily this occurs on the PSP too (POPSloader).

**Comment by CometHunter92** [comment]
@gameblabla with the latest commit 648d944 doesn't crash the whole retroarch anymore, just hangs indefinitely at the VS. screen. Maybe it's something worth noting

**Comment by gameblabla** [comment]
Yeah that happened on interpreter as well. Good to see the ARM JIT is on par with the interpreter on that front.
Sadly it seems to me that now the issue is probably not related to CPU emulation. (or maybe it is, i honestly have no idea)

**Comment by CometHunter92** [comment]
Something related to the cdrom access emulation?

**Comment by gameblabla** [comment]
Could be related to CDC yes or it could be DMA. Either of these is broken on PCSX Rearmed. I've tried to fix the CDC as much as i could but sadly, no dice. I still need to try this on PCSX Redux to see if they fixed it.
If they did, then it's a pretty good indication this is a CPU issue, not DMA or CD.

**Comment by CometHunter92** [comment]
It crashes in PCSX redux too.

**Comment by gameblabla** [comment]
Well i think we can safely assume this is not a CPU issue then. (PCSX redux passes most of the CPU tests)

**Comment by notaz** [comment]
I've looked at it and it's certainly a problem with CDC. The game crashes after overwriting BIOS RAM memory with trash, if we look when it does that we see it's parsing data at **80102cbc**, which apparently is some structure that describes how to copy data. Enabling CDC logs reveals
```
...
CDROM setloc command (46, 09, 66)
ReadTrack *** 46:09:66
 -> 01,01 46:07:66 46:09:66
CDROM setloc command (13, 27, 03)
CDROM setloc command (13, 27, 03)
ReadTrack *** 13:27:03
 -> 01,01 13:25:03 13:27:03
cdrWrite1() Log: Setmode a0
cdrReadInterrupt() Log: cdr.Transfer 13:27:3
ReadTrack *** 13:27:04
 -> 01,01 13:25:04 13:27:04
psxDma3() Log: *** DMA 3 *** 11000000 addr = 80024848 size = 10003
psxDma3() Log: *** DMA 3 *** 11000000 addr = /80102cbc/ size = 10200
```
(address marked with //)

So it seeks to (46, 09, 66) and does nothing, then to (13, 27, 03) and only then starts copying. Clearly it didn't seek to (46, 09, 66) just to do nothing? Looking at (46, 09, 66) it seems to have the data the copy code would work correctly with. So either CDC is not doing something the game is expecting or does it at a wrong time.

**Comment by CometHunter92** [comment]
Interesting! Thanks!

**Comment by notaz** [comment]
Try a build with my latest commits.

**Comment by CometHunter92** [comment]
Great! Now it works! Thanks!
