### ISSUE TITLE
Playstation link plugin

### ISSUE THREAD

**Issue by matcr** [libretro/pcsx_rearmed#209]
Variable enabling link plugin is currently (r22) commented out:
https://github.com/libretro/pcsx_rearmed/blob/28ea3e2d87c4e239d8853b10c4496f82feb9d982/libpcsxcore/plugins.h#L29

And even after enabling it, there is a question of where is Playstation Link plugin and how it is configured? Library compiled with it enabled shows no difference in emulator.
Current implementation (or lack thereof) is messing with at least one game: (Armored Core - versus mode in splitscreen is unavailable).
_Curiously, in japanese PS Classic, which uses pcsxr and has Armored Core preinstalled, there is no such issue._

Desired behaviour is either enabling configuration and usage of link functionality, or its removal, so it doesnt interfere with split screen.

Tested on both windows pc (psx bioses ranging from 1001 to 102c) and retropie 4.4  (Pi 3B+) via Retroarch, using PAL and NTSC (USA and Japan) versions.

**Supplementary:**
https://retropie.org.uk/forum/topic/20288/armored-core-no-split-screen-option/2

**Comment by matcr** [comment]
Update:
Split screen works on Windows10 with pcsxr - 1.9.93, bladesio1 plugin is present, then disabled. Without it at all, game behaves like libretro build.
Here is source for pcsxr with bladesio1 plugin included:
https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/pcsxr/1.9.94-4/pcsxr_1.9.94.orig.tar.xz

**Comment by gameblabla** [comment]
You mean the splitscreen option only ever appears if link support is enabled ? If so then yeah, we should get around fixing that.

**Comment by gameblabla** [comment]
Fixed as of https://github.com/libretro/pcsx_rearmed/commit/559fd298151dd8704e2a02c3c356bcb437f4df15
