### ISSUE TITLE
Multitap not working

### ISSUE THREAD

**Issue by robmcc1983** [libretro/pcsx_rearmed#210]
Hi, the multitap for this core seems to have broke.
I've always played 4 players fine with retropie and lakka in the past.
But after updating both neither work now.
When I load a supported multitap game normally I just got to options and enable multi tap 1 for some 4 player fun.
Now what happens is the game will detect a multitap and let me select 4 players, but for example on micro machines v3 when it gets to character selection screen, player 3 and 4 controllers do not work.
Thanks 
Rob

**Comment by genius8086** [comment]
For the time being the workaround is to switch 3rd and 4th "controller type" back and forth in the options. Then they start working.

**Comment by retro-wertz** [comment]
multitap should work. its just that 'default" pad types are misleading. default for pad 1/2 is standard, but default on pad3-8 is none so this causes multitap to be disabled if its left on auto.

core has been updated to remove this "default" label and pcsx docs updated as well..

**Comment by hizzlekizzle** [comment]
ok, i'm going to close this, since it wasn't really broken, just hard to understand, and that's been corrected. Feel free to reopen if needed.
