### ISSUE TITLE
How do I get cheats to work?

### ISSUE THREAD

**Issue by KazuhiraMewtwo** [libretro/pcsx_rearmed#211]
Even after selecting and applying cheats on the core, the cheats don't appear to work
The game I'm trying to get to work is Final Fantasy VII on PCSX-R, and the codes are the ones for Cloud's HP and MP, and the gil codes

**Comment by retro-wertz** [comment]
just use the cheats provided from online updater

**Comment by negativeExponent** [comment]
cheats should be working using retroarch's cheat engine method

**Comment by notaz** [comment]
Closing as it's answered.
