### ISSUE TITLE
(UWP) loading savestates on retroarch for the pcsx ReARMed Core Crashes

### ISSUE THREAD

**Issue by dominater01** [libretro/pcsx_rearmed#213]
when you try to load a savestate on the uwp build it loads but then freezes before gameplay can happen

this seems to be an issue with this core on uwp only

**Comment by retro-wertz** [comment]
can you test with recently updated core and use other games. provide log too if possible. what parameters run with uwp anyways? is it using unai? peops? gles?

**Comment by dominater01** [comment]
still crashes with updated core

uwp for xbox one only has support for direct x 11 and 12

**Comment by Doctor1577** [comment]
Am having same issue but I'm thinking for different reasons was working but now says vfs not supported?

**Comment by Doctor1577** [comment]
Will try changing video driver and report bk

**Comment by dominater01** [comment]
doc its because it has to transfer the game to the ra directory and its running low on space so you need to delete it everytime

**Comment by Doctor1577** [comment]
Thanks for the info so if I'm on laptop browsing the xb1 filsytem where do
I find it to delete it also I've got roms on the xb1 drive not usb jtbc
thanks

**Comment by dominater01** [comment]
you cant find it from pc only hdd

https://www.youtube.com/watch?v=4WKdUHhIXps

**Comment by notaz** [comment]
The core doesn't access the save files, they are passed in by RetroArch (or another frontend), so the core can't do anything about issues like this.
