### ISSUE TITLE
F1 Championship Season 2000 - Won't boot past Loading screen

### ISSUE THREAD

**Issue by MLH199** [libretro/pcsx_rearmed#214]
Hi, 

Can someone please help fix F1 Championship Season 2000 so that it can be played on the PS Classic or PC via RetroArch? The game will hang on the Licensed by Formula One Administration Limited screen - which would suggest is is an incompatibility with the emulator.

![](https://user-images.githubusercontent.com/46301187/51031616-0cc41c00-1595-11e9-9cc2-3e4f439c8e4b.jpg)

**Comment by retro-wertz** [comment]
psx cpu clock option has been added to core. it should show up if your device is dynarec-build and should be able to fix some of these games by tweaking the value

**Comment by AnotherLife** [comment]
This isn't a dynarec problem because I just tested it on Windows and it stopped after the intro EA Sports logo, too. Both with real bios and HLE.

Works fine on Beetle PSX.

**Comment by decadent** [comment]
This issue is inherited from PCSX-Reloaded, btw.

**Comment by gameblabla** [comment]
This game is quite tricky to run
- Requires instruction cache emulation otherwise it will crash.
- Requires GPU cache emulation otherwise some graphical effects will look wrong.
- Seems to have some other quirks that prevent it from booting

The good news is that PCSX Redux, a similar codebase, is able to boot the game.
The bad news is that i have no idea how they did it : /

**Comment by gameblabla** [comment]
Alright, so i was in fact able to get this game to boot on notaz's PCSX Rearmed and what a pain in the ass.
This game needs:
- Proper emulation of BREAK, SLLV, SRAV, SRLV, JR and JALR.
- Very tight cdrom timings.
- GPU cache emulation for the heat wave effect when first starting up a game.

And despite that, you may still get some audio glitches in the menu screen.
My PR for icache emulation is here : https://github.com/libretro/pcsx_rearmed/pull/545

**Comment by gameblabla** [comment]
As of https://github.com/libretro/pcsx_rearmed/commit/7a8117168d6b9ad083757e013049c0e45734f3fb and https://github.com/libretro/pcsx_rearmed/commit/cd15dd450b7c261023e97ebf195a11e2a790f44a, this game can be booted in interpreter mode... randomly.
Sometimes it refuses to boot properly at all, requiring a restart.

This game won't work on Lightrec/ARM and the switch and back tactic won't work for this game either.
GPU cache emulation is still required for the heat effect but if you can get past the logo screens, the game is playable.

**Comment by pcercuei** [comment]
F1 2000 (EA version) is working fine in the master branch now.
