### ISSUE TITLE
Enhanced Resolution option not working on Nintendo Switch

### ISSUE THREAD

**Issue by tabnk** [libretro/pcsx_rearmed#219]
No change in resolution when **Enhanced Resolution**  is set to true.

**Comment by dankcushions** [comment]
depends on the game.  some don’t support it - eg games like tekken 3

**Comment by tabnk** [comment]
What games are supported?

**Comment by fr500** [comment]
Afaik enhanced resolution only works with the neon Renderer, and switch
(unless this is lakka) runs on peops instead.

**Comment by tabnk** [comment]
In that case, shouldn’t Enhanced Resolution option be remove from Switch Libnx build?

**Comment by AnotherLife** [comment]
How can you tell which renderer your core is using?

**Comment by hizzlekizzle** [comment]
For anyone following this issue, it was closed because the NEON options are now hidden on aarch64 platforms, where they don't work anyway. This doesn't make Enhanced Resolution work on Switch et al, obviously, but it should avoid confusion as to why the options don't work.
