### ISSUE TITLE
Two games that do not run on PCSX but do run on Beetle

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/pcsx_rearmed#222]
These get black screen on launch and no debug messages?

- [The Hanafuda - Simple 1500 Series Vol. 6 (v1.0) [SLPS-01684]](https://psxdatacenter.com/games/J/S/SLPS-01684.html)
- [The Hanafuda - Simple 1500 Series Vol. 6 (v1.1) [SLPS-02442]](https://psxdatacenter.com/games/J/S/SLPS-02442.html)

I tried both bin/cue and EBOOT.PBP formats.

These games run just fine in Beetle using either format.

**Comment by orbea** [comment]
Are you using a bios?

**Comment by gingerbeardman** [comment]
Yes, can you not reproduce this?

I have the BIOS that match these hashes.

| Recognized Name | Redump Name | CRC32 | MD5 |
| :---: | :---: | :---: | :---: |
| scph101.bin | psone-45a.bin | 171BDCEC | 6E3735FF4C7DC899EE98981385F6F3D0
| scph7001.bin | ps-41a.bin | 502224B6 | 1E68C231D0896B7EADCAD1D7D8E76129
| scph5501.bin | ps-30a.bin | 8D8CB7E4 | 490F666E1AFB15B7362B406ED1CEA246
| scph1001.bin | ps-22a.bin | 37157331 | 924E392ED05558FFDB115408C263DCCF

My setup, testing with latest stable and latest nightly:
- macOS 10.13.6 with RetroArch-Metal 
- N3DS 11.9.0-42 with B9S & Luma

**Comment by orbea** [comment]
Not sure, I was taking a shot in the dark and haven't heard of this game before. :)

**Comment by gingerbeardman** [comment]
OK, sorry for removing my previous comment.

./RetroArch --verbose > ~/Desktop/RetroArch.log
and
./RetroArch --verbose | tee ~/Desktop/RetroArch.log

both give a log file as below:

```
Memcard 2: disabled
Starting PCSX-ReARMed 0
Running PCSX Version 1.9 (Oct 12 2018).
psxMap: warning: wanted to map @80000000, got 0x11309d000
psxMap: warning: wanted to map @77000000, got 0x11309d000
psxMap: warning: wanted to map @14000000, got 0x119473000
psxMap: warning: wanted to map @1f800000, got 0x11309d000
psxMap: warning: wanted to map @14000000, got 0x115a22000
psxMap: warning: wanted to map @1fc00000, got 0x11309d000
psxMap: warning: wanted to map @14000000, got 0x119690000
Mapped (RAM/scrp/ROM/LUTs/TC):
19480000/15a30000/19690000/00000000/00000000
found BIOS file: SCPH5501.bin
RGB565 supported, using it
plugin: plugins/builtin_gpu
plugin: plugins/builtin_spu
plugin: plugins/builtin_pad
plugin: plugins/builtin_pad
Plugins loaded.
Loaded CD Image: /Users/matt/Downloads/2019-01-31/The Hanafuda 10.PBP[pbp].
Track 01 (DATA) - Start 00:02:00, Length 00:32:05
Track 02 (AUDIO) - Start 00:34:05, Length 02:04:68
Track 03 (AUDIO) - Start 02:38:73, Length 02:23:56
Track 04 (AUDIO) - Start 05:02:54, Length 02:54:17
Track 05 (AUDIO) - Start 07:56:71, Length 02:44:14
Track 06 (AUDIO) - Start 10:41:10, Length 02:36:20
selected sound output driver: libretro
CD-ROM Label: SLPS_01684                      
CD-ROM ID: SLPS01684
CD-ROM EXE Name: SLPS_016.84;1
ari64_reset
```

Using only 3 PSX BIOS for this test:
- SCPH5500.bin
- SCPH5501.bin
- SCPH5502.bin

Beetle does not produce any logging at all.

**Comment by Yabuato** [comment]
Same issue here,I can reproduce this.

**Comment by gameblabla** [comment]
Those games are going to be a huge pain in the ass to fix.

**Comment by gingerbeardman** [comment]
@gameblabla what's the story?

**Comment by gameblabla** [comment]
These games are very time sensitive i believe. I may have a few ideas after i looked at the PS Classic source code but i wouldn't get my hopes up for it.

**Comment by notaz** [comment]
I could get ingame of both games so this is likely fixed.
