### ISSUE TITLE
Ace Combat 3 - Electrosphere (Japan) - audio crackles, controller problem

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/pcsx_rearmed#223]
when starting the game, I could not start the game unless the intro is played. There are random crackles to be heard in varying tones across the game.

**Comment by AnotherLife** [comment]
I can confirm (playing on my PlayStation Classic) that the user needs to wait a few seconds for an intro/attract video to play even after being prompted to press Start. Then the buttons work, the video stops and the user is returned to the Press Start screen where they can press start and continue normally.

It is obviously related to all those other games having controller issues right after booting them.

https://github.com/libretro/pcsx_rearmed/issues/161

**Comment by AnotherLife** [comment]
Oh, I see you created a specific issue for that

https://github.com/libretro/pcsx_rearmed/issues/271

What about the crackles, though? I just played through the first mission of the japanese version of the game (with an unofficial translation patch) and didn't hear anything.

**Comment by arnoldsecret** [comment]
I forgot to close this one
