### ISSUE TITLE
Music tracks (CD audio) do not play

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/pcsx_rearmed#224]
# Problem
I am not hearing any CD audio with either PBP or BIN/CUE format on test games. I do hear sound effects and audio in FMV.

Tested 1.7.5 stable, 1.7.5 nightlies, and  latest 1.7.6 stable.

## Example Game
- http://redump.org/disc/41776/
- http://redump.org/disc/7612/

## Testing

- macOS 10.13.6
   - PBP = CD audio OK
   - BIN/CUE in folder = CD audio OK
   - BIN/CUE in compressed 7z = CD audio does not play
- Nintendo 3DS 11.9.0-42E (B9S, Luma 9.1)
   - PBP = CD audio does not play
   - BIN/CUE in folder = CD audio does not play

**Comment by gingerbeardman** [comment]
This is now happening with the latest build on all devices I have:

- Mac
- N3DS
- Switch

**Comment by retro-wertz** [comment]
retroarch does not extract entirely compressed files, only relevant content-in this case the .cue file. 

feel free to chip in https://github.com/libretro/RetroArch/issues/7679

**Comment by AnotherLife** [comment]
But he says he tried bin/cue as well, not only PBP

**Comment by retro-wertz** [comment]
> But he says he tried bin/cue as well, not only PBP

???

- loading multitracks  .bin/iso alone cant play audio tracks, need the .cue for the offsets of each track (there is no way to know where each track starts or ends without the cue sheet).
- compressing a cd-image, in this case will be cue and bin files when this is loaded in retroarch, only the .cue or .bin/iso will be extracted depending on which file he choose to load.

**Comment by gingerbeardman** [comment]
I'm not 100% sure what you are trying to get across @retro-wertz . I think you're saying thay the 3rd point in my macOS bullet list is "as expected". Can you clarify?

So just to reiterate, using a folder of loose (not inside a zip) cue and bins does not play CD Audio tracks, on at least N3DS platform.

**Comment by retro-wertz** [comment]
i was actually referring to compressing multi-tracked cd-images/multiple files and expecting that when a file, for example is opened from a compressed one, all files will be extracted-which is not the case.

anyways tracked the cd audio not playing issue (im on linux) and should be fixed on next update or so..

**Comment by gingerbeardman** [comment]
>i was actually referring to compressing multi-tracked cd-images/multiple files and expecting that when a file, for example is opened from a compressed one, all files will be extracted-which is not the case. ...

@retro-wertz now is see. Thanks for tracking down the issue and fixing! I'll check your fork to see what the problem was.

**Comment by retro-wertz** [comment]
is it working now?

**Comment by gingerbeardman** [comment]
I'll check soon (just had a baby)

**Comment by gingerbeardman** [comment]
@retro-werz sorry for the delay! you did indeed fix it. Tested 1.7.7 nightly

**Comment by gingerbeardman** [comment]
And thank you!
