### ISSUE TITLE
Wrong input when setting the 5 ports to device 1

### ISSUE THREAD

**Issue by kivutar** [libretro/pcsx_rearmed#226]
When setting the 5 controller ports to device 1 (joypad)

`port 0  device 1port 1  device 1port 2  device 1port 3  device 1port 4  device 1`

The core reacts like if the DOWN button of the controller 1 was constantly pressed.

And no other inputs are working.

Tested on Ludo with:

```
for p := uint(0); p < input.MaxPlayers; p++ {
    state.Global.Core.SetControllerPortDevice(p, libretro.DeviceJoypad)
}
```

And doesn't happen if I use:

```
state.Global.Core.SetControllerPortDevice(0, libretro.DeviceJoypad)
state.Global.Core.SetControllerPortDevice(1, libretro.DeviceJoypad)
```

**Comment by notaz** [comment]
The multitap code has been rewritten so I assume this is fixed. You can reopen if there is still an issue.
