### ISSUE TITLE
Refuses to load games when mednafen BIOS are present

### ISSUE THREAD

**Issue by kivutar** [libretro/pcsx_rearmed#227]
When my 3 mednafen_psx BIOS are in the system directory, pcsx_rearmed will hang at:

```
Memcard 2: disabled
Starting PCSX-ReARMed 0
Running PCSX Version 1.9 (Oct 12 2018).
Mapped (RAM/scrp/ROM/LUTs/TC):
80000000/1f800000/1fc00000/00000000/00000000
found BIOS file: SCPH5501.bin
RGB565 supported, using it
plugin: plugins/builtin_gpu
plugin: plugins/builtin_spu
plugin: plugins/builtin_pad
plugin: plugins/builtin_pad
Plugins loaded.
Loaded CD Image: /Users/kivutar/roms/Sony - PlayStation/Final Fantasy Tactics (USA).cue[+cue].
Track 01 (DATA) - Start 00:02:00, Length 51:08:51
selected sound output driver: libretro
CD-ROM Label: FINALFANTASYTACTICS
CD-ROM ID: SCUS94221
CD-ROM EXE Name: SCUS_942.21;1
ari64_reset
```

With no BIOS, the game launches:

```
Memcard 2: disabled
Starting PCSX-ReARMed 0
Running PCSX Version 1.9 (Oct 12 2018).
Mapped (RAM/scrp/ROM/LUTs/TC):
80000000/1f800000/1fc00000/00000000/00000000
no BIOS files found.
RGB565 supported, using it
plugin: plugins/builtin_gpu
plugin: plugins/builtin_spu
plugin: plugins/builtin_pad
plugin: plugins/builtin_pad
Plugins loaded.
Loaded CD Image: /Users/kivutar/roms/Sony - PlayStation/Final Fantasy Tactics (USA).cue[+cue].
Track 01 (DATA) - Start 00:02:00, Length 51:08:51
selected sound output driver: libretro
CD-ROM Label: FINALFANTASYTACTICS
CD-ROM ID: SCUS94221
CD-ROM EXE Name: SCUS_942.21;1
ari64_reset
note: running with HLE BIOS, expect compatibility problems
----------------------------------------------------------
2019/02/10 15:09:08 [OpenAL]: Using 4 buffers of 4096 bytes.
port 0  device 1port 1  device 12019/02/10 15:09:08 [Core]: Game loaded: /Users/kivutar/roms/Sony - PlayStation/Final Fantasy Tactics (USA).cue
```

Tested on OSX x86_64

**Comment by retro-wertz** [comment]
core does not care what bios you have or what region the content is as long as it matches the filename it tries to look for, so if you do have all of mednafen's bios, then its loading SCPH5501 1st and its probably incompatible (or bad dump)

https://github.com/libretro/pcsx_rearmed/blob/8569f7c3abe705930306d7537cc0f7e53e63bc19/frontend/libretro.c#L1886-L1889

**Comment by retro-wertz** [comment]
Ok, got this to work
![screenshot_2019-03-06_10-39-23](https://user-images.githubusercontent.com/23315382/53852256-5dd41780-3ffc-11e9-9f33-d62d75584c22.png)

Suikoden games are some of the titles that will have problems reading save files if not using a bios file...

**Comment by retro-wertz** [comment]
a workaround based on a previous workaround of the same behaviour is already added and i have been launching/relaunching stuff in lakka without this problem so far (aside from graphics glitching on windows 10 when using pal games)

just to add some more troubleshooting info.... if you run lakka with another non pcsx core/game and then load a game using pcsx, it does not crash anymore. The workaround was to move SysReset() from retro_load_game and run it from retro_run() (this would simulate similar to a menu-driven pcsx when you launch the UI, then use Load CDROM to run the game).
Im not experience enough to understand the underlyings in libretro or what is going on but something probably use by  pcsx (memory locations probably?) is not initialized before the first call to retro_run().

is there an ARM-based platform ludo can run? maybe this is just an interpreter-related issue and not on dynarec...

**Comment by retro-wertz** [comment]
@kivutar You might be interested to know that Kodi had a similar issue and they fixed it by moving stuff around (it had something to do with audio being initialized too early..or something)

https://github.com/kodi-game/game.libretro.pcsx-rearmed/issues/13
https://github.com/xbmc/xbmc/pull/14924/files

**Comment by gameblabla** [comment]
Most likely a user error or an external issue unrelated to the libretro core. Closing
