### ISSUE TITLE
[regression] Slow fps on ARM

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/pcsx_rearmed#23]
I'm getting ~45 fps on my odroid u3 (using xorg), c4052f4 broke it someway.

@aliaspider

**Comment by aliaspider** [comment]
not possible

**Comment by aliaspider** [comment]
what kind of make would do that Oo

**Comment by Alcaro** [comment]
I'm pretty sure that whitespace change doesn't fix anything. Reopening.

**Comment by aliaspider** [comment]
maybe he has a really buggy make xD

**Comment by sergiobenrocha2** [comment]
I'm pretty sure I'm not going crazy... let's see the launchpad build

**Comment by aliaspider** [comment]
"Since trailing space characters are not stripped from variable values" (from : https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_6.html)
ok.., I had no idea about that Oo
good catch !

**Comment by sergiobenrocha2** [comment]
The core from launchpad is working now
