### ISSUE TITLE
Analog controls skips cinematics automaticly

### ISSUE THREAD

**Issue by Galewin** [libretro/pcsx_rearmed#230]
It's a very strange issue that happen to a lot of games (rugrats search for reptar and donald goin' quacker for exemple). After investigating, intro cinematics and cinematics that are skippable in general are atutomaticly skipped if analog controls is used as an option. I play with retropie on the latest core version on a raspberry pi 3B+ and I have bios installed.

I can give more informations if necessary,

**Comment by notaz** [comment]
At least Donald Duck doesn't seem to skip, so I assume it's fixed.
