### ISSUE TITLE
Wrong content streamed from CD in certain situations (save states included)

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/pcsx_rearmed#233]
Expanded Dupe of: https://github.com/notaz/pcsx_rearmed/issues/122

This has been bugging me and I'm happy to have finally found the cause. Sorry to say that it appears to be limited to PCSX ReARMed lineage. Beetle PSX does not have this problem.

## Problem
CD access is out of whack, resulting in incorrect audio/video playing in certain circumstances.

## Game
Jun Classic C.C. & Rope Club
http://redump.org/disc/29981/

I'm using redump verified CUE & BINs as I'm a dumper of this game. Merging to a single BIN, ISO, CHD, PBP does not help. 

## Background
This is a golf game with lots of audio tracks (music, description of each hole, digitised sound effects of wind, water, rain, birds). There are also short thumbnail FMV clips that play when you hit a good shot.

## Save States
- State 0, Beetle PSX [JUNROPE.state.zip](https://github.com/notaz/pcsx_rearmed/files/2922563/JUNROPE.state.zip)
- State 1, PCSX ReARMed [JUNROPE.state1.zip](https://github.com/notaz/pcsx_rearmed/files/2922560/JUNROPE.state1.zip)

These were made using RetroArch 1.7.6 PCSX-ReARMed r22 v0370856.
I get the same problem on Nintendo Switch, which is where I noticed it.

## How to Reproduce
1. Load chosen core (Beetle/PCSX)
2. Load game content
3. Load save state (0/1)

## Expected Results
- ball comes to rest, yardage displays 
- short FMV clip in lower right corner "nice shot!"
(Beetle PSX does this)

## Actual Results
- ball comes to rest, yardage displays
- two CD Audio tracks, both short phrases, followed by the thumbnail FMV clip that is cut short
(PCSX does this)

## Screenshot
This is the final facial expression of the person in the FMV; this is never seen using PCSX.

![screen shot 2019-03-02 at 22 30 45](https://user-images.githubusercontent.com/49612/53688443-f4be7c80-3d3b-11e9-956a-ae66f3fceade.png)

## Analysis
It seems to me that PCSX seeks CD tracks at incorrect locations, somehow?

So the drive seeks to a point before the FMV and ends up in a CD Audio track, playback begins and goes through two Audio tracks not stopping at either of their end points, and then finally playback gets to the start of the FMV and it proceeds to play, but by now the "playback duration" is almost exhausted and so the FMV is cut short.

The amount of error seems to increase with the number of CD tracks.

There are many other situations with this game where the wrong audio/video plays.

## PCSX Reloaded
It seems to be a longstanding bug. 

It happens with PCSX-Reloaded 1.9.95 (SVNREVISION) on macOS.
After the ball lands, I get two voice clips and the beginning of the thumbnail FMV.

Here is a freeze/save state: [SLPM86080-000.pcsxrstate.zip](https://github.com/notaz/pcsx_rearmed/files/2923073/SLPM86080-000.pcsxrstate.zip)

Let me know if I can be of further assistance with this one.

**Comment by gameblabla** [comment]
I believe this should be fixed as of my latest changes. This will need some testing.

**Comment by notaz** [comment]
Closing in accordance with notaz#122
