### ISSUE TITLE
Expose cycle_multiplier as an option in the menu

### ISSUE THREAD

**Issue by AnotherLife** [libretro/pcsx_rearmed#237]
Some games run better with differrent values than the default 175. Some non-working games can even be playable like Parasite Eve 2. In the Playstation Classic's internal fork of pcsx-rearmed there is an option like this and people are using it to play Parasite Eve 2 and get games running better

https://www.reddit.com/r/PlaystationClassic/comments/a9sec9/parasite_eve_ii_works_on_the_playstation_classic/
https://gbatemp.net/threads/playstation-classic.522781/page-32

**Comment by retro-wertz** [comment]
ive thought there was already an option for the Parasite eve fix?

does this do the same thing or affects different variable?

**Comment by AnotherLife** [comment]
That fix used to work at some point but people have tested it and it doesn't work anymore. Please look at this older issue
https://github.com/libretro/pcsx_rearmed/issues/41

I searched the code for "Parasite" and found this snippet:
```

u32 psxRcntRcount( u32 index )
{
    u32 count;

    count = _psxRcntRcount( index );

    // Parasite Eve 2 fix.
    if( Config.RCntFix )
    {
        if( index == 2 )
        {
            if( rcnts[index].counterState == CountToTarget )
            {
                count /= BIAS;
            }
        }
    }

    verboseLog( 2, "[RCNT %i] rcount: %x\n", index, count );

    return count;
}
```

**Comment by retro-wertz** [comment]
did quick look, **cycle_multiplier** seems to be only used on dynamic recompiler builds, if so i hae no such device to test this with. is this similar to other pcsx that has overclock?

**Comment by AnotherLife** [comment]
You mean this?
https://github.com/SonofUgly/PCSX-Reloaded/commit/3f11d29f31ca02575aeedf073e87ffee933effb0

I don't think so, the option I am talking about is to set the underclock multiplier. You can see that they set the underclock multiplier higher (200 instead of 175) for older devices so it's not a "magic number".

You don't have an Android device and can only test an interpreter-only build on x86? I can test it for you on my PlayStation Classic, it has a Cortex A35 which is armv8, it can also run standard linux builds from here though:
https://buildbot.libretro.com/nightly/linux/armv7-neon-hf/

SONY forked pcsx-rearmed for use in their retro console and it has this option called "PSC Cpu clock" which is 57 by default, check this video
https://www.youtube.com/watch?v=FJNnfYDU6l0

The SONY source code is here, can you take a look and see what that option does? Does it change the cycle_multiplier like I suspect?
https://doc.dl.playstation.net/doc/psclassic-oss/
If you click pcsx-rearmed you can download the zip

**Comment by retro-wertz** [comment]
actually, cycle_multiplier is computer in pcsx as **(10000 / VALUE)**. **VALUE** is the one thats used in the options, and its default is 57, making that 10000 / 57 = 175.438596491. Libretro is just hardcoding this value to cycle_multiplier so at 175 its just the same as psx cpu overclock at 57. This option affects only dynarec builds or arm. 

I'll see what i can do since selection of 1 - 500 this option is capable of, there is no real way to make it easy selecting these much  value in retroarch...

**Comment by AnotherLife** [comment]
The users have gotten the game working by changing the 57 to 70, so the cycle_multiplier is changed from 175 to 143. And I saw that code that set the default to 200 for older CPUs, right?

So maybe the options should be 
50 (slower)
57 (recommended)
64
70

Thank you for taking the time to look into this, I think this will make Parasite Eve 2 and maybe other games playable and allow users to tweak games that don't run fullspeed.

**Comment by retro-wertz** [comment]
this PSX Cpu clock should already be available for dynarec builds. at least one person has confirmed it fixed some NBA-related issues.

**Comment by AnotherLife** [comment]
Thank you, I am waiting for an updated core to come out for the PS Classic so I can test 2 games and post my findings! Looking good though!

**Comment by AnotherLife** [comment]
Tested with NBA Live 2001 and it works, thanks! Doesn't get applied on restart apparently, I had to quit and run the game again to see the effect of the option change. Unless it was some caching thing.
