### ISSUE TITLE
Can't get Multitap to work on Crash Bash

### ISSUE THREAD

**Issue by s1h4d0w** [libretro/pcsx_rearmed#241]
I've asked for help on Reddit, I've asked for help on Discord, and in both places I was eventually told it might be better to create an issue here on Github.

**Preface**
So my 4 controllers work fine with other cores. I've been playing a lot of GameCube games with my friends on the Dolphin core. I wanted to do the same with some PSX games as a friend of mine was super nostalgic for Crash Bash.

**Issue**
However I can't seem to get player 3 and 4 working. I've tried forcing the multitap options to "enabled" in retroarch-core-options.cfg", I tried changing it in Quick Menu > Options. Some people told me to set Player 2 to "analog", other people told me to set User 3 & 4 to either analog or standard. But nothing works.

**Results**
When launching Crash Bash and going into "Settings" > "Controller" (in-game) all controllers will show up as "Off" and I can't change anything in that menu. When I go to "Battle mode" I will be able to select a 4 player game, but players 3 & 4 won't respond to button presses of their respective controllers. Both controllers work perfectly fine otherwise, if I have "All users control menu" on those 2 controllers can navigate the menu of RetroArch just fine.

Using RetroArch 1.7.6 with all cores, etc. fully updated.

**Comment by retro-wertz** [comment]
you probably missed my reply on discord


retrowertzToday at 9:13 AM
@lepel 4 players works here... you just need to set both multitaps to ON/enabled. and set the input 1-4 at least as standard. restart core
but i am using a bios file, so that probably helps too... lemme test...
ok it does not matter if you use real bios or not, you just have to set the controllers and multitap manually (these default, auto setting is useless...) and then restart core (meaning close content, and then launch content again.)

**Comment by s1h4d0w** [comment]
That fixed it, thank you! I have no idea why that specific combination worked, as on Reddit I was told not to touch the multitap options and other combinations of setting things to analog or standard.

Any idea why it's so complicated to set this up? I'd think most games would require this setup to work right?

**Comment by retro-wertz** [comment]
multitap1 on auto means that if input 3-8 is set to other than default or none, multitap 1 is auto-enabled
multitap2 on auto means that if input 5-8 is set to other than default or none, multitap 2 is auto-enabled

i sent PR to remove this "default" label as this appears to be confusing...
