### ISSUE TITLE
Boot screens

### ISSUE THREAD

**Issue by BenWlson** [libretro/pcsx_rearmed#25]
I love this core as it provides excellent speed on the raspberry pi 2, but it seems to be missing one key feature: the Sony Playstation boot screens and associated sound effects. I believe this is an important part of the nostalgia of playing PSX games and always got me excited for the game I was starting. I know the Mednafen core offers this feature, but it lacks performance on the raspberry pi.

**Comment by phaseIV** [comment]
Reset the emulator in the retroarch menu. It will (re)start and show the boot logo and sound.
Personally I'm glad it is skipped on first run.

**Comment by BenWlson** [comment]
Is there a way to add the option to enable that on first run?

**Comment by objectchris** [comment]
@BenWlson not currently. i couldn't get it to work in the upstream version either, but if it works here when you restart then I'll try and look into a hacky way of forcing a restart as soon as content is loaded, IF a new 'slow boot' option is set.

**Comment by objectchris** [comment]
interestingly retro_reset() is called when you reset content via retroarch menu, and is also called within retro_load_game (when you load a game), so i'm not sure what the difference is, unless it's a different option entirely. will debug it later and see what's going on.

**Comment by objectchris** [comment]
I had a go at adding this. Findings:
1) the logo that is displayed when you restart content is not the proper bios logo. it's actually a pcsx hack (says PCSX under the PS logo, and doesn't appear to last long enough so the sound is cut off early), even if you use a correct bios file.
2) it sometimes doesn't work right. eg in tekken 3 if I restart i get a reverse engineered version of the PSX CD player/memory card manager.

both of these make me not want to bother getting this to work. I think we need someone familiar with the upstream version to properly make this display the correct bios sequence, if that's even possible. there's an issue logged there: https://github.com/notaz/pcsx_rearmed/issues/64

**Comment by Hek121** [comment]
Hi,
Any news for this?
For nostalgia purposes it would be very cool! 
@notaz

**Comment by meepingsnesroms** [comment]
Done

**Comment by dankcushions** [comment]
this should have been a PR. the issues i mentioned before cause problems and you have it on by default??????

**Comment by dankcushions** [comment]
core is basically broken by default now according to user reports: https://retropie.org.uk/forum/topic/7977/retropie-4-1-14-broke-psx-solved

**Comment by meepingsnesroms** [comment]
I will change it to off by default and add a warning.

**Comment by meepingsnesroms** [comment]
I added a warning and changed it to off by default.

**Comment by dankcushions** [comment]
Much better, thanks :)
