### ISSUE TITLE
Formula One 2000

### ISSUE THREAD

**Issue by VGkav** [libretro/pcsx_rearmed#250]
This game plays the Midway logo then shows a Loading screen and then stops at a black screen, there is no crash, it just doesn't continue. Tested on a Playstation Classic and on Windows. So it shouldn't be a dynarec problem. I am using real bios in both platforms, tested with HLE bios forced on, on Windows, too.

Works on Beetle PSX.

**Comment by retro-wertz** [comment]
duplicate

**Comment by AnotherLife** [comment]
This is a different game from F1 Championship 2000 from EA Sports.

I am talking about this game:

https://en.wikipedia.org/wiki/Formula_One_2000_(video_game)

**Comment by retro-wertz** [comment]
ok seems like similar issue to be though. cant get this to run on any other pcsx versions i can compile or have though

**Comment by decadent** [comment]
This issue is inherited from PCSX-Reloaded—only, depending on the PAL/NTSC game version and the OS the game may hang, reboot, or the emulator crashes outright.

**Comment by gameblabla** [comment]
As of https://github.com/libretro/pcsx_rearmed/commit/7a8117168d6b9ad083757e013049c0e45734f3fb and https://github.com/libretro/pcsx_rearmed/commit/cd15dd450b7c261023e97ebf195a11e2a790f44a, this game can be booted in interpreter mode... randomly.
Sometimes it refuses to boot properly at all, requiring a restart.

This game won't work on Lightrec/ARM and the switch and back tactic won't work for this game either.
GPU cache emulation is still required for the heat effect but if you can get past the logo screens, the game is playable.

**Comment by notaz** [comment]
There is now a hack for the ARM dynarec, and other platforms can switch to the interpreter to play this game.

**Comment by pcercuei** [comment]
Formula One 2000 (Midway version) is working in the master branch, this can be closed.
