### ISSUE TITLE
Raspberry Pi 3B Building Error

### ISSUE THREAD

**Issue by MajorDangerNine** [libretro/pcsx_rearmed#251]
### Problem
This core is not building on the Raspberry Pi 3B.
***
### Primary Info
Hardware: Raspberry Pi 3B
Software: Raspbian Stretch Lite (RetroPie)
Build Log: https://pastebin.com/EbuqfBMW
***
### Additional Info
It builds fine on a RPi0. Not sure if that is relevant to this, but thought it was worth mentioning.
***
### Comments
Sorry if I didn't include everything needed. Never really done one of these. I'm just a fairly run-of-the-mill end-user that doesn't understand programming.

If there is a formatting I should follow with things like this then please make me aware of it and I'll try my best to meet it.

**Comment by retro-wertz** [comment]
this should be on rpi page. but anyways they have updated their installer script to use Makefile.libretro just recently instead the old one. that should compile the target fine...

**Comment by MajorDangerNine** [comment]
Oh, sorry.
