### ISSUE TITLE
embedded zlib missing

### ISSUE THREAD

**Issue by evilwraith** [libretro/pcsx_rearmed#252]
The embedded zlib library seems to not be in the include path for the following files. This seems to be a recent change.

```
plugins/cdrcimg/cdrcimg.c:14:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [plugins/cdrcimg/cdrcimg.o] Error 1
make: *** Waiting for unfinished jobs....
libpcsxcore/psxbios.c:30:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
libpcsxcore/cdriso.c:29:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
libpcsxcore/misc.c:29:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~

```

**Comment by hhromic** [comment]
How are you compiling?  You should be using `make -f Makefile.libretro platform=<platform>`. There is no need to invoke `configure` and doing so could lead to wrong choices for build configuration.

**Comment by evilwraith** [comment]
I'm compiling in the environment the BleemSync folks use for their builds. I've compiled this previously without issue but recent source changes seem to have broken it. I've included the files in my original post. 

In my personal build environment which has zlib.h in its includes already it builds.

**Comment by retro-wertz** [comment]
for the longest time, in include folder for the embedded zlib is missing. so its probably has been compiling using preinstalled zlib headers. just add the dep/zlib to includes or if you have existing zlib, compile with WANT_ZLIB=0
