### ISSUE TITLE
Gundam Battle Assault 2 Audio Pop/Tearing RetroArch stable 1.7.6

### ISSUE THREAD

**Issue by ProtoCas** [libretro/pcsx_rearmed#254]
Audio for this particular game works until a character is waiting for the next opponent in story mode. Also the popping/tearing occurs when doing a super move in story mode. Tested with both audio core and RetroArch settings on the PSVita/TV as well as both pbp and bin/cue versions even though there are two bin files with this game. Not a major issue but it is quite noticeable.

**Comment by retro-wertz** [comment]
are you able to test with standalone or psc if you have if any of the tweaks there fixes or at least remedies this behavior?

**Comment by ProtoCas** [comment]
This has been consistently the same ever since RetroArch has had the PCSX_Rearmed core. I haven’t try the standalone though. I’ll try to find it and try that. For the tweaks, I’ve messed with BIOS files along with the HLE, frame rates, audio sync, hrz adjustments and other suggestions on google. It’s all been a no-go and the pops are consistently present at those sections. I can’t really complain since Adrenaline doesn’t have a proper popsloader to load the game correctly and I am grateful to have played this portable again :)

**Comment by AnotherLife** [comment]
I can confirm this on the PSC (using the Retroarch core), loud static is heard a few times before the match starts, I fiddled with some options but didn't make a difference.

**Comment by retro-wertz** [comment]
@AnotherLife are you able to compile pcsx  for whatever device you use it on? i could modify my pcsx on own repo to add the advance options and see any of these options help.

**Comment by AnotherLife** [comment]
Yes, sudden loud static for me on the PlayStation Classic (dynarec+neon, build from 2-3 weeks ago). Does it happen on Windows? I will test tomorrow.

I can't build for the PSC, I need to install a version of gcc for ARM targets, I think?

**Comment by gameblabla** [comment]
Still an issue, even on PCSX Redux i believe. I believe this is either a CDROM or SPU bug.

**Comment by notaz** [comment]
> loud static is heard a few times before the match starts

Couldn't reproduce so assuming fixed. If there is still an issue please explain how to easily reproduce.
