### ISSUE TITLE
Expendable not working in Bleemsync..?  NO matter which ROM I try..?

### ISSUE THREAD

**Issue by abelogan** [libretro/pcsx_rearmed#256]
I'm trying to get the game "Expendable" to play on Bleemsync, but no matter which ROM I use (I've downloaded all the ones I could find), the game seems to start normally, but as soon as I start moving my character, the game goes all glitchy and quickly becomes an incomprehensible mess, like someone threw up all over the TV screen lol. Anyone else having problems with this game, or does anybody know how to fix this?

BTW I have Retroarch with multiple cores running on my SNES classic, so I'm somewhat familiar with it, though I've only ever "used it" with hakchi2.  I don't know how to use Retroarch on the PS classic.  I just use Bleemsync.  Sorry for being a n00b.  :(

Thanks!

**Comment by arnoldsecret** [comment]
There's an issue on Bleemsync that the game would not run if there's a letter "P" in the 3rd letter of any word. Try renaming files to "1Expendable" to make it work on Bleemsync.

Next time please report BS issues on its respective GitHub, not here.

**Comment by AnotherLife** [comment]
This isn't the usual issue of the internal emulator detecting the wrong region when the 3rd letter is P. The game is actually broken badly on the PSC even though it works on the PC. It's probably a dynrec specific problem then?

It's an old problem it seems, look here:

https://pyra-handheld.com/boards/threads/pcsx-rearmed-millenium-soldier-expendable-artifacts-in-the-game.75164/
