### ISSUE TITLE
Show boot logo option stopped working on boot (but works after reset)

### ISSUE THREAD

**Issue by hhromic** [libretro/pcsx_rearmed#257]
Hi, the "show boot logo" option stopped working on Raspberry Pi devices (at least) when booting a game, however it does show the boot logo when resetting the core.

I bisected the core and the last working commit is this one: 949ed5ba
The first bad commit is this revert commit: 6492c6e8

I'm investigating what happened, but if you have a better idea, just comment here. Thanks!

**Comment by retro-wertz** [comment]
showing boot logo is a hack and causes game compatibility ( even the reset is somewhat of a hack ). this revert is the original intended sequence and it was intended that the bios logo is suppose to be skipped over when using a bios file.

**Comment by hhromic** [comment]
Thanks for the answer. I personally do not use this function so I didn't notice it wasn't working before. It was reported by a RetroPie user on the forums that he does use it for "nostalgia effect".
Then, your reply means the current behaviour is how the core is expected to work and no alteration for this is planned?  This just to report back in the forum (and I stop looking how to "fix" it).

**Comment by retro-wertz** [comment]
someone originally did the show boot logo in this core. ill see and restore the extra forced reset call on first retro_run loop that was part of the original bootlogo hack.

**Comment by retro-wertz** [comment]
PR sent, which fixes original one that still shows bootlogo on reset if option was disabled.

just reminding that some games will not load when using the bootlogo option(must be timing thing). i have at least 2 games here that i know wont boot with it enabled, or causes to game to freeze when issuing reset (i cant remember which ones though)

**Comment by hhromic** [comment]
Thanks, very kind of you to fix it promptly.
I think users using this option are very aware that enabling this option introduces compatibility issues, so I guess on that front it should be safe as they know the risks. Other users can simply keep the option disabled for maximum compatibility (like me).
