### ISSUE TITLE
feature request: CD image caching

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/pcsx_rearmed#261]
I always notice some stutters here and there (not that much but still) with this core, and that's on a desktop PC.
I wonder if it's possible to have CD image caching to get rid of those.

**Comment by AnotherLife** [comment]
Are the stutters caused because of CD reading? I don't think so. What if you setup a RAM drive and run a game file from it, do the stutters go away?

**Comment by retro-wertz** [comment]
i believe this would defeat the purpose of having a "fast" psx core in an already limited memory ARM devices..

**Comment by Tatsuya79** [comment]
That's an option in beetle-psx, not sure if that's possible here.

**Comment by retro-wertz** [comment]
?

**Comment by Tatsuya79** [comment]
I mean it would be disabled by default to not be a problem for low spec devices.

**Comment by AnotherLife** [comment]
Install a Ram drive program, create a 1gb ramdrive, copy your game files in there and load them. I think it will still stutter.

**Comment by rtissera** [comment]
If stutter still happen after that, then it's time to add CHD read-ahead feature into libchdr.
I already have a good idea on how to handle this by having threaded / async read-ahead.

**Comment by MarioKartFan** [comment]
> If stutter still happen after that, then it's time to add CHD read-ahead feature into libchdr.
> I already have a good idea on how to handle this by having threaded / async read-ahead.

@rtissera Would this be a better solution than precache for lower spec devices?  For example precache seems to be a non starter for a device like the 3DS with low on Board memory.

**Comment by notaz** [comment]
This was likely dynarec slowdowns which have since been improved. CD precaching was also implemented but is now disabled due to stability issues.
