### ISSUE TITLE
Spot goes to Hollywood missing text on title screen

### ISSUE THREAD

**Issue by Pat86** [libretro/pcsx_rearmed#264]
What it's supposed to look like:

![2019-03-28 00_51_24-412 - Spot goes to hollywood  Playstation  - YouTube](https://user-images.githubusercontent.com/20128108/55119812-a6f72300-50f3-11e9-8917-a0a60dd24747.png)

What it looks like:

![Zwischenablage-1](https://user-images.githubusercontent.com/20128108/55119900-f1789f80-50f3-11e9-8834-471c3695d7a4.jpg)

**Comment by retro-wertz** [comment]
there are actually a few of these missing text on games, its not exclusive to the libretro port.

**Comment by gameblabla** [comment]
All PCSX forks, including libretro's, suffer from this issue no matter the graphical backend being used.
This is likely either a GTE or DMA bug. (It could be the same issue as Vampire Hunter D with DMA writes too or a CDROM bug, who knows...)

**Comment by notaz** [comment]
Closing as fixed.
