### ISSUE TITLE
PSX - Jedi Power Battle freezes always

### ISSUE THREAD

**Issue by killercuts** [libretro/pcsx_rearmed#266]
Hello
I am using for a few days Recalbox and Retropie both last releases, but I don’t know why always the game freezes in the same place in the game in the two systems. I can play only 1 minute then freezes completely. I tried using different images but no good results.
Can you test pax emulators  please?

**Comment by AnotherLife** [comment]
https://docs.google.com/spreadsheets/d/1MF9W42jU-FYvGqmi2pnDjNIO6sgc1P-hEs2qlv2Lk00/edit#gid=1412890855

Seems to be a known problem? Have you tried setting the PSX cycles from 57 to 70? That's the only thing I would test.

**Comment by killercuts** [comment]
How can I change psx cycles?
I am a completely newbie I think, I only want to play

**Comment by retro-wertz** [comment]
if you dont have psx cycles, then you probably have an older core. lr-pcsx_rearmed should already have this since a few weeks ago, you can also try the pcsx_rearmed version for retropie if it makes difference. dunno what recalbox uses...

**Comment by killercuts** [comment]
I downloaded img yesterday :/
I think is possible to change the sx cycle but I dont HOW 
I am using Recalbox now because Retropie for me is not friendly :)

**Comment by killercuts** [comment]
I downloaded img yesterday :/ the last release of recalbox 
I think is possible to change the sx cycle but I don't know HOW
I am using Recalbox now because Retropie for me is not friendly :)

**Comment by AnotherLife** [comment]
What options do you have? In the pcsx-rearmed core options? Is there a PSX cycle option?

**Comment by killercuts** [comment]
Okay, well, sincerely I am boring, fighting with the system RetroPie and Recalbox.
I bought a Raspberry Pi 3B+, special Case to get a look like mini console, 8 bit do SN30 pro and  32gb samsung micro sd, but finally I get a trash system. The Jedi Power Battle freeze in first minute playing or simply close the emulator, the mame killer instinct ultra slow, the dos game never worked properly using keyboard or mapping joystick key using ctrl+F1, the smash n64 ultra slow, Digimon Rumble Arena japanese doesnt work.

Sincerely I think it is a trash system, thanks for idea but Actually I lost all my money and time trying to configurar retropie and recalbox.

shit

**Comment by AnotherLife** [comment]
Jedi Power Battles is probably unplayable on pcsx-rearmed for years. And from what I'm reading the Killer Instinct games are unplayable on Mame 2003 for ARM devices, you can play the N64 version though.

Not sure about the japanese version of Digimon Battle Arena, what's the problem there?

**Comment by killercuts** [comment]
![hellooooooooooooooo](https://user-images.githubusercontent.com/44202176/55522975-808a3800-565d-11e9-853d-7f0e24e0f4fb.jpeg)
 
Digimon rumble arena Japanese version after lunch emulator the screen maybe freezes on the language selection and NO buttons responding. Also freezes when check memory cards data.

Killer N64 is a shit, sorry I prefer arcade version. Again Im sorry but Rasperry PI 3B+ is a trash console :D

**Comment by AnotherLife** [comment]
I can confirm that on my Windows desktop I cannot proceed to the menu in Digimon Tamers Battle Evolution (Japan)

In Beetle PSX the input works fine and I managed to get to the menu.

**Comment by killercuts** [comment]
sorry for that, but How can i enable the Beetle PSX on Recalbox :P 

have a great weekend :P

**Comment by AnotherLife** [comment]
You can't use the Beetle PSX core on your raspberry pi, it is very demanding. I tested it on my Windows PC.

**Comment by killercuts** [comment]
:(

**Comment by AnotherLife** [comment]
Does this work by using one of the new options added a couple of days ago? I think it does.

**Comment by retro-wertz** [comment]
See this: https://github.com/libretro/pcsx_rearmed/issues/294

**Comment by AnotherLife** [comment]
I tested this on the Playstation Classic, with that hack I played about 15 minutes just fine.

**Comment by gameblabla** [comment]
I'm considering disabling SMC checks by default because of games like this one.

**Comment by notaz** [comment]
Too many different things mashed into this issue. Please open new ones (one for each game) if something still doesn't work.
