### ISSUE TITLE
[Feature request] Switch automatically to correct disc when loading a save state in multi-disc games.

### ISSUE THREAD

**Issue by bslenul** [libretro/pcsx_rearmed#274]
Hey! So I made a simple test with Resident Evil 2:

* Load the game from .m3u.
* Switch to Claire disc (disc 2) and restart.
* Start a new game and make a save state.
* Close content.
* Start the game again from .m3u but without switching to disc 2.
* Load save state.
* It loads but as soon as you change screen the game freezes.

I checked and `Disk Index` stays to "1" in the `Disk Control` menu so it makes sense that the game freezes.
By curiosity I made the exact same test with Beetle PSX core and when you load the save state it automatically switches `Disk Index` to "2" so the game runs properly!

Would it be possible to implement this feature in PCSX ReARMed? That would be super helpful!

**Comment by notaz** [comment]
Is this still an issue? I see there is `.set_initial_image` that the frontend could use for this purpose but I don't know if it does.

**Comment by bslenul** [comment]
Just tested and yes it's still happening, loading a state from a different disc doesn't switch to the correct one automatically.

I tried with RE2: loading a Claire disc state while the Leon disc is inserted results in a black screen after interacting with a door (so loading a new area). And in Chrono Cross loading a disc 1 state while disc 2 is inserted results in a black screen when entering a fight (tested at the very beginning of the game).

**Comment by notaz** [comment]
Implemented something, can you do the testing?

**Comment by bslenul** [comment]
Tested briefly with 3 or 4 games and it seems to work like a charm! Thank you! ❤️ 

I will test a bit more tomorrow and I'll reopen if I have any issue.
