### ISSUE TITLE
Merging with latest version of pcsxr-reloaded

### ISSUE THREAD

**Issue by rcaridade145** [libretro/pcsx_rearmed#275]
@retro-wertz
I have noticed you were trying to backport fixed made to pcsxr and in that sense was comparing the latest source of pcsx-reloaded namely gpu.c vs psxdma.c on this branch and there are several differences especially mem2vram 

> 			bs=(bcr & 0xffff);
> 			size = (bcr >> 16) * bs; // BA blocks * BS words (word = 32-bits)
> #ifdef PSXDMA_LOG
> 			PSXDMA_LOG("*** DMA 2 - GPU mem2vram *** %lx addr = %lxh, BCR %lxh => size %d = BA(%d) * BS(%xh)\n",
> 						chcr, madr, bcr, size, size / bs, size / (bcr >> 16));
> #endif
> 			ptr = (u32 *)PSXM(madr);
> 			if (ptr == NULL) {
> #ifdef PSXDMA_LOG
> 				PSXDMA_LOG("*** DMA2 GPU - mem2vram *** NULL Pointer!!!\n");
> #endif
> 				break;
> 			}
> 			GPU_writeDataMem(ptr, size);
> 
> #if 0
> 			// already 32-bit word size ((size * 4) / 4)
> 			GPUDMA_INT(size);
> #else
> 			// X-Files video interlace. Experimental delay depending of BS.
> 			GPUDMA_INT( (7 * size) / bs );
> #endif
> 			return;
> 
> 		case 0x00000401: // Vampire Hunter D: title screen linked list update (see psxhw.c)
> 		case 0x01000401: // dma chain
> #ifdef PSXDMA_LOG
> 			PSXDMA_LOG("*** DMA 2 - GPU dma chain *** %8.8lx addr = %lx size = %lx\n", chcr, madr, bcr);
> #endif
> 
> 			size = gpuDmaChainSize(madr);
> 			GPU_dmaChain((u32 *)psxM, madr & 0x1fffff);
> 
> 			// Tekken 3 = use 1.0 only (not 1.5x)
> 
> 			// Einhander = parse linked list in pieces (todo)
> 			// Final Fantasy 4 = internal vram time (todo)
> 			// Rebel Assault 2 = parse linked list in pieces (todo)
> 			// Vampire Hunter D = allow edits to linked list (todo)
> 			GPUDMA_INT(size);
> 			return;

Are you focusing on some part right now?

**Comment by notaz** [comment]
This stuff changed a lot and is no longer relevant.
