### ISSUE TITLE
Kamen Rider V3 duplicate opening image

### ISSUE THREAD

**Issue by spielvan** [libretro/pcsx_rearmed#277]
Kamen Rider V3 when passing the game opening, the left part of the image gets duplicated as if you had the same image twice.

**Comment by gameblabla** [comment]
Duplicate of https://github.com/libretro/pcsx_rearmed/issues/356, this bug got fixed as of https://github.com/libretro/pcsx_rearmed/commit/6d9f0559579ea3a0c69976ad032c85441c200011 along with quite a few other games.
