### ISSUE TITLE
Formula One Arcade (Europe) "Crashes after first loading screen"

### ISSUE THREAD

**Issue by ghost** [libretro/pcsx_rearmed#282]
Game 			 	: Formula One Arcade (Europe) (En,Fr,De,Es,It)
Serial				: SCES-03886
Region				: PAL
Format			 	: BIN/CUE
Problem/Issue		        : Crashes after first loading screen.
Platform/s Tested	        : x86 (Windows 10) / ARM (PlayStation Classic)
RetroArch Ver.	 	        : 1.7.6 / 1.7.7
PCSX ReARMed Ver.	: r22 ecfbcc1 / r22 c631f41
GPU Plugins	Tested	: [PEOPS x86/ARM] [NEON ARM] 
Emu. Options Tested	:
- Use BIOS			: Auto/HLE
- Region				: PAL/NTSC
- Pad 1 Type			: Standard/Analog/DualShock
- Dynamic Recompiler	: ON/OFF
- PSX CPU Clock		: 30/57/100
- Show BIOS Bootlogo	: ON/OFF
					
Note				: Beetle PSX mentions "Slow CD Image read detected --
					consider using async or precache CD Access Method"
					Possibly related to the problem on PCSX ReARMed?
The crash also happens in the standalone version of PCSX ReARMed.

Video of problem: http://sendvid.com/5pzu17nh

Gameplay video : https://youtu.be/kJJM56vIF2g?t=2

**Comment by AnotherLife** [comment]
Does it happen on the PC on Retroarch with pcsx-rearmed when using real bios?

**Comment by Whtysnky** [comment]
> Does it happen on the PC on Retroarch with pcsx-rearmed when using real bios?

Same crash on PCSX ReARMed/RetroArch (X86/PC) with or without the BIOS. The options I've tested are in the initial post on both platforms.

**Comment by crazyrexz** [comment]
confirmed this issue is exist , tested on android at bios hle and auto, bin cue extension. this games and fisherman bait 3 is got issue btw. fisherman bait 3 not responding on input with or without controller.

**Comment by bslenul** [comment]
Huh, this one is really weird (Fisherman Bait 3, not Formula One), if you change controller type in Options menu you can get one input (sometimes 2) just after closing the RA menu :thinking: 

https://youtu.be/4YAfN1b6jC8

After a while playing with the Options menu I even had full working inputs, I have absolutely no idea why! I disabled the inputs overlay but I was doing the exact same thing: spamming up or down just after closing the RA menu:

https://youtu.be/JPKerrWF6GI

**Comment by Whtysnky** [comment]
Without widening the issue too far as I think this is possibly related @AnotherLife I believe has mentioned a similar loading issue for other F1 games developed by Studio 33 "Sony's Formula One series". Formula One Arcade is most likely based on similar code to Formula One 2000 and 2001 I'd guess.

**Comment by crazyrexz** [comment]
@bslenul yep i find that , spam the button and to menu. it respond.  strange isnt it

hmm so other formula is problem too. hope they will get attentions and fixed.

**Comment by gameblabla** [comment]
My PR https://github.com/libretro/pcsx_rearmed/pull/545 fixes the black screen issue after the loading screen for the interpreter and lightrec. This is one of the few PS1 games sensitive to instruction cache emulation.

**Comment by gameblabla** [comment]
Just tested my newer PR changes against it and it still works even on lightrec unlike F1 2001 which will require pure interpreter mode : /.
Not sure if it should be merged given the limited usefulness of it as both lightrec and arm need to be improved to add instruction cache emulation to them. (as it was done for MIPS in PCSX4ALL)

**Comment by gameblabla** [comment]
As of https://github.com/libretro/pcsx_rearmed/commit/7a8117168d6b9ad083757e013049c0e45734f3fb, this is fixed over Lightrec and Interpreter.
Still broken on ARM however... For this one, you may get lucky and just switch back and forth though.

**Comment by notaz** [comment]
There is now a hack for the ARM dynarec, and other platforms can switch to the interpreter to play this game.
