### ISSUE TITLE
Unsupported/Invalid CD image on converted Redump bin/cue

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/pcsx_rearmed#285]
![Untitled](https://user-images.githubusercontent.com/41223243/57847208-7fc1f580-7808-11e9-85e9-4d8b08d973c6.png)

**Comment by retro-wertz** [comment]
windows chd for windows broken atm. await next buildbot update.

https://github.com/libretro/pcsx_rearmed/pull/286
