### ISSUE TITLE
[Bug] Crusader No Remorse FR // RPI // Crash during intro

### ISSUE THREAD

**Issue by nemo93** [libretro/pcsx_rearmed#287]
Game does launch yet after the second company logo (shortly after the launch), core crashes. As I can't pass that logo the game is unplayable. 

I've compiled this core and rely on chd. I'm on PI3B+ (Retropie). I'm certain this game did work at least a year ago using that core and same device/OS.

**Comment by AnotherLife** [comment]
Then start compiling and testing versions to see which commit broke it.

**Comment by nemo93** [comment]
English is not my native language but by the tone of your comment I may have done something wrong. In that case I apologize. My other problem is that I don't know how to achieve what you suggest. I'll gladly follow any guide in order to assist. Thank you.

**Comment by AnotherLife** [comment]
Nope :D

Can you compile the core yourself? If yes, then try to find which commit broke it. Since you say it was working for you at some point.

**Comment by nemo93** [comment]
Hello @AnotherLife. I'm afraid not. I'm using Retropie and can only compile the latest source from the menu. I also have very limited knowledge on GIT, commit etc. :( I also have little time to learn about this unfortunately. Yet as I recall raising github tickets after a long-running test session in September 2017 I can definitely say that Crusader was working by that date. 

Thanks for your help.

**Comment by notaz** [comment]
I can get ingame so assuming this was fixed.
