### ISSUE TITLE
[Bug] Tai'Fu // Colony Wars Red Sun /// RPI // long loading times

### ISSUE THREAD

**Issue by nemo93** [libretro/pcsx_rearmed#288]
Using chd for both games on RPI3B+. 

* Tai'Fu. At the intro/home screen just hit Start to go to the loading screen. It will sit there almost forever. In fact, you'll have to wait for 2-3mn before the progress bar starts to fill. As a side note, there's some glltch around the Tai'Fu logo when you hit the Start option on home screen.

* Red Sun. Same as above. Just go straight to the first mission and you'll see the loading screen which doesn't move for couple of minutes.

**Comment by crazyrexz** [comment]
for colony wars red sun i play it on chd format, and complete the first mission escort , it runs flawless, plus i using fast forward. the loading is beaten in few seconds :)

for taifu not yet to play it, so cant tell you sorry.

**Comment by crazyrexz** [comment]
and im on android entry phone for information. maybe you can try update core pcsx and see if that can fix

**Comment by notaz** [comment]
Should work now on both bios and HLE.
