### ISSUE TITLE
[Bug] graphical glitches when enhanced resolution on // RPI

### ISSUE THREAD

**Issue by nemo93** [libretro/pcsx_rearmed#289]
i've noticed glitches for instance in front of character in Megaman x4 or Castlevania Chronicles. It's a vertical line in front of the sprite. It appears only when core option "enhanced resolution" is set to enabed. I have some glitches also during Breath of Fire IV intro but I need to test further.

I'm on RPI3B+ and using chd.

**Comment by dankcushions** [comment]
Many glitches with this feature. Probably every game has some kind of visual issue with it. Some games are unplayable (Doom). Prompt not worth reporting IMO.

**Comment by AnotherLife** [comment]
There are some games that work well with enhanced resolution, like all 3 Resident Evil games, Legend of Dragoon, Spyro the dragon, Crash Bandicoot, Gran Turismo 2 and many others.

Others exhibit gfx glitches, that's to be expected, it's a hack.

**Comment by nemo93** [comment]
Sorry I wasn't aware. I do confirm indeed that by disabling it games run overall much better with fewer glitches etc. Thank you.
