### ISSUE TITLE
GT2 completely broken

### ISSUE THREAD

**Issue by andres-asm** [libretro/pcsx_rearmed#291]
GT2 is completely broken on this emulator.
On Android with the dynarec on it's a glitchy mess.

With the dynarec off it's a bit better but the timedemos (and presumably the AI) just crash all over the place.

Tested on Android 7 on my Shield

**Comment by fr500** [comment]
Dynarec ON:
![image](https://user-images.githubusercontent.com/1721040/58108702-ec931200-7bb1-11e9-88c6-ecc2e732e2f1.png)

Video of both issues:

https://streamable.com/tgqv5

**Comment by retro-wertz** [comment]
another one that affects dynarec. this works fine on non-dynarec build (linux)

**Comment by fr500** [comment]
The video artifacts are dynarec.
But the timedemos going haywire is not dynarec related.

**Comment by retro-wertz** [comment]
demos works fine on my crappy android 5.1 with dynarec off that is (but slow)

**Comment by AnotherLife** [comment]
Hmm? Pcsx rearmed NEON 4b7520c is the build I now have on my PlayStation Classic and it works fine, just tested the US version and did a couple of license tests. With and without enhanced resolution.

**Comment by fr500** [comment]
Well.
I don't know what your options are, I know that with mine in my device running android that happens.

Updated the OP to reflect on those details.

**Comment by AnotherLife** [comment]
What commit hash does your core have? Like the one I posted of mine.

**Comment by fr500** [comment]
It was the latest master at that time.
Anyway whatever happens on linux is irrelevant.
Different platforms have different errors.

@retro-wertz that's curious... can you try on the latest master please?
My GT2 is version 1.2 (CHD) and my core is cadb885

My debug info is 7239

**Comment by fr500** [comment]
I just tried in AARCH64 (android too) and timedemos are fine there so I guess it's related to NEON.

**Comment by retro-wertz** [comment]
64bit builds are non-dynarec...

**Comment by fr500** [comment]
I know but on 32 bit arm it still happens with dynarec off on my devices

**Comment by notaz** [comment]
Possible duplicate of #135, assuming fixed.
