### ISSUE TITLE
Feature Request: This will fix several non-working PS1 games, including Jedi Power Battles!:)

### ISSUE THREAD

**Issue by KMFDManic** [libretro/pcsx_rearmed#294]
@retro-wertz  I think this would be right up your alley, since you did a great job helping get the Overclock Core Option exposed:)

Like the now exposed Overclock (Core) option, setting 57-70 fixing games, such as Parasite Eve II, NBA Live '98, 2000, etc...Last year, I played around with Overclock, hoping it would help with Jedi Power Battles.  Turns out, that Overclock mucking about ended up fixing Parasite Eve II, and other related games.  But, Jedi Power Battles remained broken.  In order to "fix" it, I would suggest exposing another few Core Options, most notably:

[Speed Hacks]
PSX CPU Clock, %: 70 (Already implemented! Fixes Parasite Eve 2 at 70, default should be 57)

**I can confirm the following does fix Jedi Power Battles:)**

Disable SMC Checks: Off (Should be OFF til the game is initially loaded.  THEN, via a Core Option, toggled ON, on the fly, and it will prevent Jedi Power Battles from crashing!)

Assume GTE Reqs Unneeded: Off (wouldn't hurt to implement this, as well)
Disable GTE Flags: Off (same as above)

Next up, another option helps other non-loading games, such as MERCS on Capcom Collection Vol 4:

Disable Frame Limiter: Off (With it ON, FPS, of course, will boost and be really fast.  But, it makes MERCS, and other games that get stuck on load, actually load and play.  Having the ability to at least turn this on should help find a median point on some of the other broken games.  Not to mention, one could toggle on High Definition Options to immediately lower FPS.

**Comment by retro-wertz** [comment]
Done, excluding **frame limiter** since this is not currently used in libretro and libretro has its own timing ( try disabling vsync or audio sync )
dynarec speedhacks requires core to be restarted (untested, i dont have decent device that can run with dynarec compiled in)

**Comment by KMFDManic** [comment]
@retro-wertz Exceptional work, as usual:)  I will give this a test run once home later today, and report results.  Jedi Power Battles finally working will make quite a few happy!

**Comment by KMFDManic** [comment]
@retro-wertz Can confirm the fix, as you applied it...works exceptionally well:)  I am now closing the issue.  I will post a video demonstration overview of this in action, sometime over the next few days, along with my regular release.  Thanks, as always!

**Comment by KMFDManic** [comment]
@retro-wertz Exceptional, everything coming together:)  Note, bslenul and myself also looked into the Silhouette Mirage issue, which I mention in this video.  Setting "Options, Pad 1 to Dual Shock" fixes it.  Hopefully, we can find solutions for other broken games, too.  I believe WWE In The House is another we still need to work with!  Thanks again:)

https://www.youtube.com/watch?v=I80CW-LFgLk

**Comment by AnotherLife** [comment]
> Disable SMC Checks: Off (Should be OFF til the game is initially loaded. THEN, via a Core Option, toggled ON, on the fly, and it will prevent Jedi Power Battles from crashing!)

I just have it On permanently for this game and I haven't encountered a problem.
