### ISSUE TITLE
 The game of fantasy8 disk 3 stuck in somewhere

### ISSUE THREAD

**Issue by sunshineoflife** [libretro/pcsx_rearmed#30]
Hi,
When i playing the game of fantasy8 disk 3, the core will stuck in somewhere. 
This can resolve it by setting the menu of  Configuration-->CD-ROM-->Cdrom Speed on the windows application PCSXR. I don't know how to set it on pcsx_rearmed, or it has interface in libretro core?
Thanks!

**Comment by dankcushions** [comment]
https://github.com/libretro/RetroArch/issues/228#issuecomment-189686206 same issue?

**Comment by sunshineoflife** [comment]
slove it
