### ISSUE TITLE
[Random crashes/Freeze/Annoying sound issue] Suikoden 2 // RPI

### ISSUE THREAD

**Issue by nemo93** [libretro/pcsx_rearmed#300]
Hi, 
###  Game freeze
**Description**: Suikoden 2 (french), at some point you have to beat a sort of giant spider (Abomination) in North window castle. During battle the game will crash, everytime. 

**Details**: issue that makes retroarch+pcsx core to freeze. You have to either reboot Pi (brutal) or kill (-9) the associated processes. I couldn't find an error message in logs as I'm using retropie. Yet by [googling](https://www.google.com/search?q=suikoden+2+crash) a bit I've discovered such issue is quite frequent at least very well known. I've checked also if the Pi was overheating but no it was not (55C max). I've disabled any speedhacks from RA menu and there's no overclock (stock 57). 

**Potential workaround for Abomination battle**: by reading [this post](https://www.ngemu.com/threads/suikoden-ii-crash-opcode.39536/#post-775288) the issue might be related to savestates. Which I do use a lot indeed in that game. To pass the Abomination battle you must not savestate during the fight. StateSaving before and after apparently is "safe". I'll test that as it's a bit my only hope to progress that amazing game. 
**UPDATE**: it **does** work indeed. Apparently you must NOT do any savestate at all after entering Neclord's "organ chamber" and till the fight is over.

### Random crashes
**Details**: from time to time game will crash back to whatever emu frontend you're using without error message. I tried to find some pattern but there's none really game could crash during a fight (see below workaround for at least one), on the world map or during a "cinematic" where characters talk with each other to progress main story.

 ### Annoying sound issue
**Details**: this one is also random yet it always appears during a fight. When using some rune magic during a battle the sound can turn to some just one long beep or very high pitch. It could be stopped by launching another magic spell yet sometimes it goes on even after battle is over. This one is really annoying as it can't be worked around by savestating. If you do that and load the state the sound bug will still be there. I'm attaching a savestate where this sound bug is on (I'm playing the French version of the game).

### Extra
I've compiled the latest pcsx core (including Commits on Jun 11, 2019). My Pi3B+ is up to date and Retropie does rely on RA 1.7.6. I'm also including below some saves from my current game (there's one savegame and various savestates before, during and after the battle).

 ### Savestates / Saves for Abomination battle (french version)
[Suikoden II.srm.txt](https://github.com/libretro/pcsx_rearmed/files/3294075/Suikoden.II.srm.txt)
Those 2 will crash/freeze game 100% of the time:
[Suikoden II.state43.txt](https://github.com/libretro/pcsx_rearmed/files/3294076/Suikoden.II.state43.txt)
[Suikoden II.state44.txt](https://github.com/libretro/pcsx_rearmed/files/3294077/Suikoden.II.state44.txt)

If you reload from this slot and do no savestate till Abomination you'll be able to complete the fight:
[Suikoden II.state42.txt](https://github.com/libretro/pcsx_rearmed/files/3294276/Suikoden.II.state42.txt)

Savestate right after battle:
[Suikoden II.state2.txt](https://github.com/libretro/pcsx_rearmed/files/3294282/Suikoden.II.state2.txt)

### Savestates for the sound bug (french version)
[Suikoden II.state1.txt](https://github.com/libretro/pcsx_rearmed/files/3317843/Suikoden.II.state1.txt)

**Comment by retro-wertz** [comment]
last time i played suikoden II i have issues but not crashed using pcsx. there are also known bugs with the game aside from the EU version which has lesser bug. try using the unofficial patched for this game if it helps you (hopefully you have used normal savefile as savestates cant be trusted 100% anyways, even mdfn_psx warns about using both states saves and saveram)

**Comment by nemo93** [comment]
thank you @retro-wertz for the feedback. I'm playing on the French version of the game (nobody's perfect :)). As I understood it comes with fewer bugs aside from the horrible translation. I have to add that I also randomly encounter crash to Retropie (games hangs and suddenly closes). I can't guess for sure when this happens and that's why I used savestates so extensively. I'm afraid that it's just a matter of being prudent, saving as much as possible and doing as little savestates. 

Please let me know if I can close this one off as I understand it's related to the game itself.

**Comment by notaz** [comment]
The crash bug seems to be one of old long fixed dynarec bugs.

> I'm attaching a savestate where this sound bug is on

This isn't useful, I need a savestate before the issue happens. Closing this for now, reopen if needed.
