### ISSUE TITLE
Jumping Flash! (NTSC-U) doesn't work when converted to CHD

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/pcsx_rearmed#301]
all it says is that's an unsupported CD image. bin/cue still works.

**Comment by AnotherLife** [comment]
I can confirm this. The CHD files gets loaded fine by Beetle PSX but not by the Windows build of pcsx rearmed (I updated today)

I converted it with this

```
chdman - MAME Compressed Hunks of Data (CHD) manager 0.209 (mame0209)
Output CHD:   Jumping Flash! (USA).chd
Input file:   Jumping Flash! (USA).cue
Input tracks: 1
Input length: 60:36:46
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
Logical size: 667,687,104
Compression complete ... final ratio = 40.8%
```

**Comment by retro-wertz** [comment]
does the game load uncompressed when using the .cue file(not the .bin)?

**Comment by AnotherLife** [comment]
Yes the cue works fine.

**Comment by retro-wertz** [comment]
wierd then :D.... some chunks probably compressed/decompressed incorrectly...

**Comment by negativeExponent** [comment]
updated libchdr should fix this problem, maybe others as well

![JumpingFlash](https://user-images.githubusercontent.com/54053706/83874627-5dc74800-a768-11ea-85a5-ad34c941650f.png)

**Comment by bmn001** [comment]
I realize this issue was closed three years ago, but I am seeing this exact behavior with Jumping Flash today, again with a CHD.

The build number on my core is r23l-4373c29, which is dated from February 2023.
