### ISSUE TITLE
Start Button doesn't work anymore

### ISSUE THREAD

**Issue by TesterNes** [libretro/pcsx_rearmed#304]
Using the latest build core (6fbd15c) the start button has no effect. 
tested on Chrono Cross, Diablo, The adventure of little ralph. 
Retroarch 1.7.7 Windows 7 64bits.

**Comment by Marcelo20XX** [comment]
Can confirm I have the same problem testing Castlevania Symphony of the night USA

**Comment by bslenul** [comment]
>Can confirm I have the same problem testing Castlevania Symphony of the night USA

Windows 7 too? I'm using W10 and no issue with that exact same version of the core with Chrono Cross, Diablo and SotN (havent tried Little Ralph), so maybe its specific to W7 :thinking:

**Comment by TesterNes** [comment]
> 
> 
> > Can confirm I have the same problem testing Castlevania Symphony of the night USA
> 
> Windows 7 too? I'm using W10 and no issue with that exact same version of the core with Chrono Cross, Diablo and SotN (havent tried Little Ralph), so maybe its specific to W7 thinking

Strange. I tested it in Win10 too and I had the same problem... Could you post your config and option files? I'd even reset to default but no change.

**Comment by bslenul** [comment]
i5 4670k
GTX 970
16GB of RAM
Windows 10 64bits (version 1903)

Core options by default (I use Beetle PSX on PC), I only have "Display Internal FPS" ON.

I am able to reproduce for Diablo only when I delete my BIOS files from system folder, I can still press Start for SotN and Chrono Cross.

**Comment by TesterNes** [comment]
Reading you I thought it was a BIOS problem but I checked every bios file I have and the ones stated in the libretro docs... but the problem's still there... 
however, build 2945189 that I think is from a few weeks ago, doesn't have this issue.

**Comment by dankcushions** [comment]
is it just the start button?

perhaps it's something to do with this recent input-related change: https://github.com/libretro/pcsx_rearmed/commit/6fbd15c831bb350dde3085d7eff18c9289b82047 (@twinaphex )

**Comment by TesterNes** [comment]
@bslenul Can you press the start button using the keyboard (Enter Key) or only using the Dualshock 4?

**Comment by hizzlekizzle** [comment]
Yes, it's probably related to the bitmask change, though it should be fixed now (at least in git; we're still waiting for fixed builds to filter down to the online updater). If you guys can get the updated core (when it arrives) and test, we'd appreciate it.

**Comment by Marcelo20XX** [comment]
It only happens with the start button, other keys seems to be responding and btw I am on Windows 7 64 Bits

**Comment by bslenul** [comment]
>Can you press the start button using the keyboard (Enter Key) or only using the Dualshock 4?

Both, no idea why I wasnt affected by this issue :p But hopefully it's now fixed for you!

**Comment by TesterNes** [comment]
with Latest commit a3c2efc now it works again. Thank you.

**Comment by hizzlekizzle** [comment]
Thanks for testing/verifying, @TesterNes
