### ISSUE TITLE
Analog Controller (SCPH-1110) Issues

### ISSUE THREAD

**Issue by mashboss** [libretro/pcsx_rearmed#305]
I haven't been able to get the Analog Controller working completely properly so far. 

I am running pcsxrearmed via retroarch via BleemSync 1.1 for PS Classic. 

I have tried about 10 different ps1/ps2 to usb adapters and so far have gotten just one of them to mostly work. 

When I go into the key config of an Analog Controller-supported game such as Ace Combat 2, the screen will properly show the analog controller in the button config (as opposed to the standard controller or dualshock screen you get if those are plugged in) and all the buttons are mapped correctly and work as they should. The issue is that the two joysticks do not "hold" their positions. Instead they continuously jump back and forth from the place you move them to and back to center. So if you're hold one joystick all the way to the right, the game reads it as if you were inputting Right, Center, Right, Center, Right, Center. 

Has anyone else experienced this? Is there are work-around? Have people gotten the Analog Controller to work 100% before with a particular adapter? Any help would be appreciated.

**Comment by AnotherLife** [comment]
I use the Dualshock for analog controls. The only game in which I was forced to use Analog as a pad type was the first Descent game. It worked perfectly after I calibrated everything in-game. 

In the Input settings, under User 1 Binds, you should have the type set as "Retropad w/ Analog" and the Analog to Digital set to None.

**Comment by mashboss** [comment]
The dualshock works fine for all games necessary (and is not relevant to my query) because there is a specific dualshock setting in the options menu (not the control user binds which are seemingly worthless). There is also a specific setting for the Analog Joysticks which succeeds in recognizing the SCPH-1110 in-game, but the problem I described occurs. 

> I use the Dualshock for analog controls. The only game in which I was forced to use Analog as a pad type was the first Descent game. It worked perfectly after I calibrated everything in-game.
> 
> In the Input settings, under User 1 Binds, you should have the type set as "Retropad w/ Analog" and the Analog to Digital set to None.
> 
> EDIT: I am talking about the Playstation Classic with Bleemsync 1.1 and an updated core that includes the recent hacks.

**Comment by AnotherLife** [comment]
I just realised you are trying to use the actual peripheral with a usb adapter, heh, oops!

You should test it on the desktop version of Retroarch+pcsxrearmed. The PS Classic has spotty device support, maybe it's not an emulator problem. In fact, you should connect the controller to your PC and use a tool to test its functionality (and the usb adapter's functionality)

**Comment by notaz** [comment]
If this is still an issue, IMHO things like deadzones of the peripheral device should be handled by the frontent, not the emu core.
