### ISSUE TITLE
Cannot use analog controls in Porsche Unleashed

### ISSUE THREAD

**Issue by AnotherLife** [libretro/pcsx_rearmed#306]
I have set up dozens of games just fine on my Playstation Classic to use pad type Dualshock and have analog controls with my Dualshock 4. Except two games: World's Scariest Police Chases and NFS Porsche Unleashed, both are NTSC-U.

I don't understand what is different for these games, seems like an emulation problem?

**Comment by retro-wertz** [comment]
someone should probably give attention (and probably add some to it) to that input bounty regarding KoroKoro Nin. fixing that (properly) would fix also this problem with dualshock input related issues.

**Comment by AnotherLife** [comment]
Was it you who said it was related to the multitap code being added? Is that where the problem started?

Can you revert those commits, having 3+ multiplayer is not more important than getting several broken games. (I have personally encountered several, maybe the true number is in the dozens)

**Comment by retro-wertz** [comment]
not entirely, but part of it. originally the standard digital controller was isolated from the analog/ds routines(which means a standard controller will not have dualshock function). the change forced every controller to pass through DS routine query thing and some games fails to initialize if its gonna use standard or analog/ds controls. some games can have input if your pre-select standard or analog/dualshock like legend of mana. but some wont have input at all (korokoronin) and is stuck at ds-config mode.

**Comment by AnotherLife** [comment]
Can you create a new pad type called "Standard (exclusive)" which skips the ds setup?

Or can you make the emulator skip it for the Standard controller is Multitap is disabled? And set Multitap to Disabled as default, too? That would fix every such game and there would be input problems only for people enabling Multitap to play 3+ multiplayer.

**Comment by bslenul** [comment]
Why these changes were made in the 1st place? That's probably a dumb question idk, I'd just like to understand why standard controller would have "dualshock function" for example.

Is it not possible to simply "revert" these changes if it causes so much trouble? Because I tried standalone PCSX and KoroKoro Post nin works like a charm for example.

Just to be clear I'm not criticizing or anything, I'm no dev and I'm sure there's a good reason behind it, just trying to understand :p

**Comment by dankcushions** [comment]
the changes were made years ago now and it would be very difficult to unpick them now. they added multitap support entirely, so it wasn't just a second multitap. also added vibration, etc.

best bet at this point is to donate to the bounty to get some attention on the input issues: https://www.bountysource.com/issues/57057724-korokoro-post-nin-doesn-t-respond-to-inputs

**Comment by bslenul** [comment]
Thanks for the answer :) Is it possible to rename a bounty? It would probably draw more attention if the title was more like "fix PCSX inputs" or something, right now it feels like the bounty is **only** for fixing KoroKoro Post nin and I guess a lot of people dont even know about this game and then dont care about the bounty.

**Comment by retro-wertz** [comment]
> Can you create a new pad type called "Standard (exclusive)" which skips the ds setup?
> 
> Or can you make the emulator skip it for the Standard controller is Multitap is disabled? And set Multitap to Disabled as default, too? That would fix every such game and there would be input problems only for people enabling Multitap to play 3+ multiplayer.

i did this awhile back but im not satisfied so i never pushed further than what i initially PR'ed (if this is even a word

@bslenul dunno if this was indicated in bounty(hopefully it is), but KoroKoro Nin supports both standard and analog sticks. I never pushed further than my initial test coz i cant make it work without break one or the other including dual-shock detection.

**Comment by gameblabla** [comment]
I believe this got fixed now with https://github.com/libretro/pcsx_rearmed/pull/468
