### ISSUE TITLE
Neon Enanched Graphic freezes on RPi3

### ISSUE THREAD

**Issue by lollo78** [libretro/pcsx_rearmed#31]
On Pi3, now we can enable the "Neon Enanched Graphic" into the Core options (pcsx_rearmed_neon_enhancement_enable = "enabled" inside retroarch-core-options.cfg) and play at full speed (60 fps), without lag. 
It's so nice to see this on a little Raspberry. The games looks so cool... 
But after few minutes (sometimes seconds) from the "graphic hack on" the games freeze! This appen also if I enable the Speed Hack options (pcsx_rearmed_neon_enhancement_no_main = "enabled"). But for all the time before the freeze... 60 fps! 
I hope that this issue could be fixed and that pcsx_rearmed will not be abandoned. For a weak hardware like Raspberry is the only choice.
Thx

**Comment by dankcushions** [comment]
i run the enhanced + speed hack options without issue.on an raspberry pi 3. I think you must have an overclock/power/temperature issue.

**Comment by lollo78** [comment]
OMG 
I not overclocked it. 
Maybe a faulty hardware...
Are u using some heatsink or fan?

**Comment by dankcushions** [comment]
nope, just a pi3 in a plastic case. no heatsink/fan. i have a 2A power supply.

**Comment by lollo78** [comment]
I have original Raspberry PU 2,5A and original RPi3 case.
I removed the top cover because it seemed too sealed... but the freeze happens however.
Are u using .PBP roms or .ISO?

**Comment by dankcushions** [comment]
.PBP
Retroarch on Retropie.
No problem :)

**Comment by lollo78** [comment]
OK I'll try with retropie.
thx a lot.

**Comment by dankcushions** [comment]
Can close this one I think. Lots of users are running this on the pi3 with the enhanced graphics options without issue.

**Comment by lollo78** [comment]
Yes close, please. I discovered thath the issue was my openelec imge. Now works fine. Thx

**Comment by dankcushions** [comment]
you are able to close your own issues
