### ISSUE TITLE
Can we let RA handle the cheat?

### ISSUE THREAD

**Issue by SumavisionQ5** [libretro/pcsx_rearmed#310]
I know that pcsx_rearmed itself can handle the cheat, but I want RA to handle the cheat too. I wanted to use cheat to active rumble for SOTN, but I found that pcsx_rearmed can not initialize cheat. 
So maybe RAM is not exposed to RA, yet?

**Comment by retro-wertz** [comment]
Done (after its merged)
Tested this using KoroKoro Post Nin sound driver bug: https://tcrf.net/Korokoro_Post_Nin
![Screenshot-1](https://user-images.githubusercontent.com/23315382/61183050-a072c400-a66e-11e9-834d-60b7b1c5d615.png)

**Comment by SumavisionQ5** [comment]
> Done (after its merged) #312
> Tested this using KoroKoro Post Nin sound driver bug: https://tcrf.net/Korokoro_Post_Nin
> ![Screenshot-1](https://user-images.githubusercontent.com/23315382/61183050-a072c400-a66e-11e9-834d-60b7b1c5d615.png)

Thank you very much!
