### ISSUE TITLE
A5 - A Ressha de Ikou 5 (Japan) - Crash/Freeze when loading 3D mode

### ISSUE THREAD

**Issue by Denshadego** [libretro/pcsx_rearmed#314]
The game A5 - A Ressha de Ikou 5 (Japan), sequel to A.IV - Evolution Global (released in english), crashes when loading the first person 3D mode in any vehicle.

To test this, one should load any map with already placed vehicles, like the third one, pick any moving vehicle and press circle like this bus right here:
![A5 - A Ressha de Ikou 5-190725-001737](https://user-images.githubusercontent.com/47835860/61845822-cf5d1700-ae72-11e9-9f41-be9e21423d9e.png)

Then pressing circle in the suitcase icon like this:
![A5 - A Ressha de Ikou 5-190725-001752](https://user-images.githubusercontent.com/47835860/61845987-5dd19880-ae73-11e9-8de6-723a45d7ea62.png)

Then a loading screen will appear and the program, Retroarch, will stop working, having to force close it. Tested on windows 10 and android with GL renderer.
![A5 - A Ressha de Ikou 5-190725-001801](https://user-images.githubusercontent.com/47835860/61845995-64601000-ae73-11e9-82ec-651d3c529b93.png)

It's a shame it doesn't work properly as it's one, if not the most deep simulation game on PSX.

**Comment by notaz** [comment]
This seems to be working now.
