### ISSUE TITLE
Final Fantasy VIII works as BIN/CUE not PBP

### ISSUE THREAD

**Issue by shirizaan** [libretro/pcsx_rearmed#32]
If I play Final Fantasy VIII from BIN/CUE the game plays fine. If I add those same working disc images to a PBP, the emulator will not start on Raspberry Pi 3.

**Comment by dankcushions** [comment]
Works fine on the latest build running a .PBP of FFVIII on a Raspberry Pi 3. Perhaps https://github.com/libretro/pcsx_rearmed/commit/cc3768145667aef20eab35da0908755d5bd395ab fixes it?

**Comment by shirizaan** [comment]
Confirmed. If I build from source it appears to work fine.
