### ISSUE TITLE
WCW Mayhem ROM - multitap issue

### ISSUE THREAD

**Issue by VnaMaster** [libretro/pcsx_rearmed#324]
All my psx roms (with multitap support) work fine except WCW Mayhem. When i launch WCW Mahyem and i enable multitap 1 (this rom is supposed to support multitap) leaving multitap 2 disabled, all my gamepads even if are detected they have all buttons disabled or for some reason the game won't recognize them. So basically i can't skip presentation and i can't do anything except entering into retroarch menu. 

My specs.
- Rapsberry Pi 3 B+
- Retropie 4.5 (last release)
- libretro pcsx rearmed (updated from this git last commit)

##Steps to reproduce

- launch indicated ROM without game setting file created
- enable multitap 1 
- create game option file
- exit from game
- launch game  

##When did the behavior start?

since first clean installation

**Comment by retro-wertz** [comment]
must be game specific compatibility since you stated multitap works in other games. try manually setting controller types for players 3-8, and/or enable multitap2 as well. restarting core after setting options would probably work. use standard controllers if possible. use official bios as well.

**Comment by notaz** [comment]
I assume the multitap rewrite fixes this. You can reopen if not.
