### ISSUE TITLE
Cannot update lr-pcsx-rearmed

### ISSUE THREAD

**Issue by acortcab** [libretro/pcsx_rearmed#329]
##Description

When I tried to update  lr-pcsx-rearmed from source in retropie I am getting this error:
"libretro.so not found"

I have attached the log

##Steps to reproduce
 
In order to reproduce the error, you just need to "update from source"

##When did the behavior start?

yesterday, when I tried to update the package and after that the emulator doesn´t work anymore

##Your device/OS/platform/architecture

Raspberry 3.
[rps_2019-08-05_165824.log.gz](https://github.com/libretro/pcsx_rearmed/files/3468251/rps_2019-08-05_165824.log.gz)

**Comment by retro-wertz** [comment]
as far as i have remember, retropie is suppose to already use static makefiles in building the core. they should have the correct updated script.

```
architecture        arm
platform            libretro
built-in GPU        neon
sound drivers       libretro
plugins             gpu_gles.so gpu_unai.so gpu_peops.so spunull.so 
C compiler          gcc
C compiler flags    -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -marm -fPIC -D_FILE_OFFSET_BITS=64 -Wno-unused-result
libraries           -lpng  -ldl -lm -lpthread -lz
linker flags         -shared -Wl,--no-undefined
enable dynarec      yes
ARMv7 optimizations yes
enable ARM NEON     yes
TI C64x DSP support no
tslib support       no
```

**Comment by acortcab** [comment]
Sorry, I dont understand your explanation, could you give me a further explanation please?

**Comment by retro-wertz** [comment]
since this is lr-pcsx-rearmed issue, go to retropie and ask for the correct script to get the core. they should have fixed this months ago by using the static makefiles to create the libretro core instread of the method you seems to use in your log

**Comment by acortcab** [comment]
ok thanks for the answer, as you said this is a lr-pcsx.rearmed issue, I thought here it was the right place to open the issue. 
Thanks for your time

**Comment by retro-wertz** [comment]
if it was a core problem like game issues etc you can post here, but since the problem is about creating the core, then they should have the correct tools to make one.

**Comment by acortcab** [comment]
ok, I got it, thanks ;)

**Comment by dankcushions** [comment]
i think we have actually fixed this already - just update the retropie-setup script before attempting to build pcsx

**Comment by acortcab** [comment]
As you can see, I am rookie on repropie setup, so what I did was:
1- Retropie Setup
2- I chose "Update" from the main menu
3- I selected "update the kernel"
4- When this process finished, I went to "manage packages"
5- "Manage main packages"
6- "lr-pcsx-rearmed"
7- "update from source"

I still got same problem. What did I do wrong?

**Comment by hhromic** [comment]
I can confirm this is a very old bug we fixed since a while now, just updating RetroPie and updating either from binary/source should get you going.

**Comment by acortcab** [comment]
ok thanks ;) I will looking forward for your news.
I already opened a new topic there:
https://retropie.org.uk/forum/topic/23177/cannot-update-lr-pcsx-rearmed

**Comment by retro-wertz** [comment]
a PR is sent to skip compiling the plugins when using this build method. using the static libretro makefile is still preferred.

**Comment by acortcab** [comment]
@retro-wertz Could you explain further? No idea what that means xD

**Comment by hhromic** [comment]
@retro-wertz we do NOT build lr-pcsx-rearmed using `configure` in RetroPie. We use the makefile directly like this (for neon devices for example):

    make -f Makefile.libretro ARCH=arm USE_DYNAREC=1 HAVE_NEON=1 BUILTIN_GPU=neon

Therefore your PR has no effect on RetroPie builds.

I suggest you wait for me (or another experienced dev to figure out what is the real problem (and even if there is a problem in the first place).

**Comment by retro-wertz** [comment]
in anycase the problem still is caused by building the plugins which were updated to make use the of static makefiles instead. you can refer to my own repor or the libnx build which the standalone plugins are updated to make use of standalone make or using static makefiles.

**Comment by hhromic** [comment]
Thanks for the heads-up, I will take a look at that too and come back to confirm the state of affairs.
@acortcab is using an outdated RetroPie installation according to his posted log file, I will verify with current RetroPie.

**Comment by acortcab** [comment]
well., I made this work. When I updated the retropie script, the console told me there were some modifications without committing, probably some updates made this changes because I didn´t do nothing at all. So basically I reverted those modifications and now it is working fine.
Thanks guys for your time and support, much appreciate it.

**Comment by hhromic** [comment]
I tested building this core now on a current RetroPie. All works as expected:
```
$ sudo ./retropie_packages.sh lr-pcsx-rearmed
(...)
$ ls -la /opt/retropie/libretrocores/lr-pcsx-rearmed/
total 1664
drwxr-xr-x 2 root root    4096 Aug  7 20:34 .
drwxr-xr-x 9 root root    4096 Aug  7 20:34 ..
-rw-r--r-- 1 root root    1680 Aug  7 20:34 AUTHORS
-rw-r--r-- 1 root root   18730 Aug  7 20:34 COPYING
-rw-r--r-- 1 root root   18956 Aug  7 20:34 ChangeLog.df
-rw-r--r-- 1 root root     294 Aug  7 20:34 NEWS
-rw-r--r-- 1 root root    1883 Aug  7 20:34 README.md
-rwxr-xr-x 1 root root 1618456 Aug  7 20:34 pcsx_rearmed_libretro.so
-rw-r--r-- 1 root root   16438 Aug  7 20:34 readme.txt
```
@retro-wertz nothing to worry about.
@acortcab good that you found out the problem by yourself, that also helps you learn more :)
