### ISSUE TITLE
Extreme Pinball - Missing flippers and ball

### ISSUE THREAD

**Issue by dan18774** [libretro/pcsx_rearmed#333]
The lr-pcsx-rearmed and PCSX-ReARMed emulators ran Extreme Pinball with missing flippers and ball. 

Pi 3 Model B +
RetroPie Version Used: 4.4
just updated Libretro pcsx rearmed

![Extreme Pinball-190812-005500](https://user-images.githubusercontent.com/53873302/62841863-d6f62b80-bc7a-11e9-88e8-9b6bee9edeb4.png)

**Comment by AnotherLife** [comment]
Try a PEOPS build

**Comment by dan18774** [comment]
> Try a PEOPS build

Thank you for the reply AnotherLife. I'm a noob and have no idea what a PEOPS build is or how to get that on RetroPie with my Pi 3 Model B +.

**Comment by dan18774** [comment]
Alright just found out what PEOSP is ( Psx Emulation Open Source project ). That's way to advanced for me. Was hoping for this game and few others with problems to all work with Libretro someday. Thanks again.

**Comment by AnotherLife** [comment]
You need someone to compile a PEOPS build for your platform. I have one for the Playstation Classic, for example, which is what I use.

I think you should ask in the Retropie forum or reddit for a PEOPS build, it uses a different graphics plugin which has better compatibility but is slower and doesn't support enhanced resolution.

**Comment by negativeExponent** [comment]
see if disabling dynarec shows any change. from what i know, most issues of the core are related to dynarec when enabled (its too slow with it disabled though but this simple quick test would give a more targetted area to fix for anyone who would want to look at the issue).

**Comment by dan18774** [comment]
Thanks for the reply NegativeExponent. I tried disabling dynarec and still missing flippers and ball. Just will have to play on pc like few others games. Thanks for your time.

**Comment by gameblabla** [comment]
Is it fixed now ? This is most likely a CDROM issue. Worms Pinball has a sort of similar issue to this, except that the remnants of the ball stay onscreen.

**Comment by notaz** [comment]
The ball is visible for me on NEON.
