### ISSUE TITLE
(Bounty) Add x86 32bit/64bit and ARM64 backends to the dynarec

### ISSUE THREAD

**Issue by twinaphex** [libretro/pcsx_rearmed#336]
PCSX ReARMed uses a modified version of the Ari64 dynarec from Mupen64 Plus, but it only has a backend for ARMv7 (32bit).

This bounty is for the following:
* Add dynarec backends for the following architectures:
   - ARM 64bit
   - x86 (32bit)
   - x86_64 (64bit)

- The 32bit/64bit x86 dynarecs should work on Linux, Windows (and Mac). 
- Code should be written in C (and ASM stubs for the parts that are needed) just like the Ari64 dynarec code in Mupen64plus.

Once we have confirmed that the new dynarec backends work with the libretro port, the bounty will be paid out.

**Comment by twinaphex** [comment]
Link here -
https://www.bountysource.com/issues/78750972-bounty-add-x86-32bit-64bit-and-arm64-backends-to-the-dynarec

**Comment by rimedo** [comment]
It's nothing much for now, but I feel I have to announce that I'm hard at work writing a dynarec for the MIPS I, and I've recently had a breakthrough of sorts. I believe I'll get a fast interpreter going in a week, then an x86/amd64 dynarec in two more. Once I'm done with the interpreter I'll put it up on Github. This'll be the culmination of my year-long foray into emulation, by the way.

I'd put some technical details in, but there was enough of those in the Beetle dynarec issue and they got nowhere. For now I'll reveal that I'm using the SSA approach (as in Xenia or Redream or Reicast), doing some bblock-level optimizations like constant folding, dead code elimination and fastmem and using Luajit as a dynamic assembler for backends. I'm also at a loss on how to recompile delayed loads in branch delay slots, heh.

See ya all in a week.

**Comment by pcercuei** [comment]
I've been using a slightly modified version of PCSX-ReArmed to develop my own dynarec, Lightrec (https://github.com/pcercuei/lightrec), which is being plugged into Beetle now (https://github.com/libretro/beetle-psx-libretro/issues/214). I'll see if I can plug it into this core as well.

**Comment by decadent** [comment]
I'm a bit confused. Retroarch set up on OSX lists two PCSX cores: ‘PCSX Rearmed’ and ‘PCSX Rearmed [Interpreter]’. I'd think that the non-interpreter one has dynamic recompilation. Are they in fact the same? The ‘interpreter’ binary is twice the size of the other core.

BTW, the olde PCSX-Reloaded has a ‘dynarec’ option on OSX, which definitely makes a difference on performance. Maybe it could be lifted for Rearmed.

**Comment by negativeExponent** [comment]
get the non-interpreted build if your device has dynarec, no reason to use interpreter unless it would run fast enough.

**Comment by pcercuei** [comment]
I now have support for the Lightrec dynarec in my branch:
https://github.com/pcercuei/pcsx_rearmed/tree/libretro

Should be working on Windows, Linux x86_64, Aarch64, MIPS32, MIPS64. Some other archs are still a bit buggy (ARM, x86). Stuff like readahead is not yet supported. The dynarec isn't well integrated, right now the dynarec exits back to C code after each compiled block, which has a ton of overhead. The speed should increase dramatically in the next versions. With that said, this first version is apparently already faster than Beetle.

I built a Linux .so and Windows .dll for x86_64, [in this zip](https://github.com/libretro/pcsx_rearmed/files/4136818/pcsx%2Bl.zip).

**Comment by negativeExponent** [comment]
using HLE bios instead of official bios now causes segmentation fault
https://pastebin.com/ByB1qH0Y

armeabi-v7a and armeabi-v7a-neon also fails to build
https://hastebin.com/xudedapusi.rb

there's build error for vita as well.
http://paste.libretro.com/191276

**Comment by twinaphex** [comment]
@negativeExponent The build failure there was unrelated to lightrec for armeabi-v7a and armeabi-v7a-neon, it's an issue that happens on newer NDKs because they have gotten rid of GCC now and moved over to LLVM.

Anyway, I pushed a commit here which gets past the compilation error, hopefully there won't be any side effects as a result.

https://github.com/libretro/pcsx_rearmed/commit/9c9d02e498a0ec5de6ea83f58b79fb972887c650

**Comment by twinaphex** [comment]
As for the Vita build failure - I pushed this for it -

https://github.com/libretro/pcsx_rearmed/commit/a62012a79925d0af4c2162be152d7800c669e6d6

I'm not sure if the ari64 new_dynarec would work with those ranges so I just created an ifdef for LIGHTREC where if LIGHTREC is defined ,it will use the new memory map addresses, otherwise it will default to what was the default previously. Apologies if this is not needed, if it is proven that Ari64 can work just fine with the newer addresses then we can get rid of these ifdefs.

**Comment by decadent** [comment]
I'd like to advertise PCSX-Reloaded's dynarec a bit, just to show what's possible. I currently have a Macbook without a battery, so the CPU is throttled to 800 MHz. The GPU is an embedded Intel HD 3000. With PCSXR's dynarec and Peops SoftGPU graphics plugin, Gran Turismo 2 runs at ~70–80 fps in the race when the frame limit is disabled. (Using OpenGL instead slows games down a lot.)

With Retroarch's PCSX and Beetle dynarecs, I wasn't able to squeeze more than ~15–20 fps—though I know that they're still rather early in development. (Possibly Retroarch itself slowed things down if it makes heavy use of the GPU.)

However, PCSX-Reloaded on Mac has persistent problems with analog controls—basically they work reasonably in only a subset of games.

**Comment by twinaphex** [comment]
RetroArch I think doesn't really have any performance impact at all (in fact, at times I think actually the opposite is true - some libretro cores perform faster). So what you're comparing here is entirely the performance of Lightrec vs. the bespoke dynarec in PCSX-R.

I believe issues with the bespoke dynarec in PCSX-Reloaded is that it is not PIC-compliant, so we cannot use it as a libretro core since it gets built as a dynamic library.

**Comment by pcercuei** [comment]
As I stated above the dynarec isn't well integrated in the PCSX-ReArmed which has a huge performance impact. Once it's plugged properly it should be as fast as PCSX-Reloaded, I believe.

**Comment by twinaphex** [comment]
Alright, Bountysource is throwing us for a loop here -

![image](https://user-images.githubusercontent.com/1075274/84867940-35025500-b07c-11ea-9a7c-c7a9ee0ea75f.png)

So what I'm doing is proceeding to closing this issue so that the two dynarec authors who did all the hard work right now can receive their bounty. I have full confidence that they would still want to improve things after the bounty, and they already put in an immense amount of work and effort into this, so I think it's justified they get it now.

I will close this and then zcrc can submit his solution on Bountysource. Let's make this happen before July 1.

**Comment by treyturner** [comment]
@twinaphex Hi there, I'm just curious about the status of this. I backed this bounty thinking it would result in a 64bit PCSX core for iOS, but I haven't seen one or heard anything about it. Someone in the Discord suggested that perhaps some build flags just needed to be turned on for the iOS build; I'm not quite so hopeful but I am curious if there's some place I should be watching for updates. Thanks for your time!
