### ISSUE TITLE
Rayman 2 Randomly crash [Odroid XU4 - Recalbox]

### ISSUE THREAD

**Issue by Docteur38** [libretro/pcsx_rearmed#337]
##Description
Rayman 2 crash and I return in Recalbox menu after few minutes...
It come in loading screen or also in the wold map !
I try with US and Eropean version, they dose the same thing !

##Steps to reproduce
Just start the game and try to finish the two first level, the game inevitably crash !

I try to change some parameter in PCSX (like the CPU clock 57 to 70) but no changes, the problem is still there.

**Comment by AnotherLife** [comment]
I have heard that from other people. They use save states to avoid it.

Does this happen in the Windows version of the core?

**Comment by retrowertz** [comment]
"Rayman 2 crash and I return in Recalbox menu after few minutes...", sound like overheating/power related problems to be. Since this is an ARM device, it could be one of those dynarec problems that happens on most games with it enabled compared to non-dynarec builds. Try to disable dynarec and see if still does crash, although things can be really really slow playing this way(if it is even playable).

**Comment by gameblabla** [comment]
Is this still an issue ? This does sound like an ARM dynarec issue.

**Comment by RiZom-91** [comment]
Yes it is with latest version. It is quite reproducible here, is there anything I could do to help like enabling more log?

**Comment by gameblabla** [comment]
> Yes it is with latest version. It is quite reproducible here, is there anything I could do to help like enabling more log?

Unfortunately this looks like an ARM dynarec bug. You could try it with lightrec to see if it happens there still.
Doing some regression testing on upstream and see if something broke rayman might be cool too.

**Comment by RiZom-91** [comment]
The issue is not happening with dynarec turned off. This is a long standing one, so I'm not sure testing older versions will help a lot. Let's see.

**Comment by CometHunter92** [comment]
Maybe https://github.com/libretro/pcsx_rearmed/commit/447f5a1dc9666a44e9785cb3634f0231c993f0c0 fixed it?

**Comment by RiZom-91** [comment]
I've played the game and no issue so far, so it seems to be fixed.
