### ISSUE TITLE
Second Memory Card Slot

### ISSUE THREAD

**Issue by RadRosko** [libretro/pcsx_rearmed#338]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

##Description

Please describe the issue. If this is a feature request, please add [feature request] to the title of the issue report.

##Steps to reproduce

How can we reproduce this issue? Please include all relevant steps, as well as any settings that you have changed from their default values, particularly including whether you are using the dynarec or interpreter CPU emulation.

##When did the behavior start?

If you can bisect the issue (that is, pinpoint the exact commit that caused the problem), please do. Someone has to do it, and having this already done greatly increases the likelihood that a developer will investigate and/or fix the problem. Barring that, please state the last time it worked properly (if ever).

##Your device/OS/platform/architecture

Such as Android, iOS, Windows 10, Linux, x86_64, a smart toaster, etc.

The issue is this- I just hacked my PS Classic with BleemSync v1.1 and am running the preloaded psx core on RetroArch.
I am trying to play Digimon World with my girlfriend.
The problem is- we can't play together unless there is a second virtual memory card in "slot2"
I have tried to manually activate the second "memory card" but have not been able to.
Is there a way to do this?
If not, will this be addressed in an update?
Thanks in advance :)

**Comment by negativeExponent** [comment]
did you at least restarted retroarch? and the 2nd memory card successfully created on disk? (pcsx_card2.mcd i think is the filename).  You may need to use an official bios as most games have problems with memory access if not using one.

**Comment by negativeExponent** [comment]
2nd memory card works. and there has been no update or follow up eversince last post...

**Comment by negativeExponent** [comment]
on after almost 2 years, i finally made the jump to test this out. And for me, Battle Mode works fine. Im not sure what "Competition Data" means, but its looking for one on your memory card saves. Downloaded some savesfiles from the net (those that are labeled complete), used this savefile for both memory card slots(enable memcard2 slot, and read docs page where to find the location of 2nd memory card and what filename it should be) and battle mode works fine.

either the memcards have bugs at the time of this writing, or was a user error.

In either case, this is a non issue with latest commits and should be closed.
@twinaphex @hunterk
