### ISSUE TITLE
analog issues in Medal of Honor

### ISSUE THREAD

**Issue by loganmc10** [libretro/pcsx_rearmed#34]
When I try to use the analog controller in Medal of Honor (Xbox One controller), the movement is very jerky, as if I am "tapping" on the analog stick over and over, instead of holding it in position.

I don't believe I'm the only one who has run into this:

http://blog.petrockblock.com/forums/topic/strange-analog-behavior/#post-106944

http://blog.petrockblock.com/forums/topic/strange-analog-behavior/#post-106949

http://blog.petrockblock.com/forums/topic/sudden-analog-issue-in-lr-pcsx-rearmed/#post-102417

https://www.reddit.com/r/RetroPie/comments/4hho18/choppy_ps1_analog_controls_pcsx_rearmed/d2pqhbj

I am using a Raspberry Pi 3

**Comment by loganmc10** [comment]
Another person that confirms this issue with a different game:

http://libretro.com/forums/showthread.php?t=5664&p=38122&viewfull=1#post38122

**Comment by alexis-puska** [comment]
Try with the latest version, i fix some lag with analog sticks. a similar bug were close in last few minutes

**Comment by loganmc10** [comment]
I don't have a chance to test this for a while, but I'll close it and reopen it if I ever come across this again.
