### ISSUE TITLE
[BUG][GPU] Bugs Bunny & Taz: Time Busters (PAL\SLES_028.96) Flickering issue

### ISSUE THREAD

**Issue by andreabellitto** [libretro/pcsx_rearmed#340]
## Description

Bugs Bunny & Taz: Time Busters (PAL\SLES_028.96) game the PAL version, has a massive flickering issue that make it uplayable, for some reason the issue is not present on the NTSC version of the game.

## Steps to reproduce

Just start the game and reach the game main menu

## OS/platform

Raspberry Pi 3 B+ with Retropie 4.5.1

## More details

Using a lot of emulators I found that this issue may be releated to the black borders of the frames that this game has on top and on bottom of his frames.

Only for your better understanding I can say that using ePSXe desktop emulator the issue is present using Pete's 2.6 OpenGL plugin, but it isn't present using Pete’s DX6 D3D Driver 1.77 directx or P.E.Op.S.OpenGl Driver 1.78.
Just for reference I have collected some old information about this issue that you can found here:

http://www.razyboard.com/system/morethread-petes-opengl2-version-29-bug-in-bugs-bunny-und-taz-time-busters-pete_bernert-41709-6325072-0.html

http://www.razyboard.com/system/morethread-problem-with-flickering-border-fix-pete_bernert-41709-457403-0.html

So i think the issue can be reconducted to the gpu plugin. I'm starting to look at the gpu plugins code right now, but it isn't easy at all, so I decided to open this issue to collect more informations and more support as possible even just to have some suggestion on how to look at.

**Comment by negativeExponent** [comment]
try forcing the game to run in PAL, it might have failed (similar to WildArms) to detect region...

**Comment by andreabellitto** [comment]
@negativeExponent tried it out, but the same exact result, screen continue to flicker.

**Comment by Ploggy** [comment]
This issue is now fixed :)

**Comment by andreabellitto** [comment]
> This issue is now fixed :)

Thanks, I can confirm that the issue is resolved, I tested it using Retropie on RaspberryPi 4
