### ISSUE TITLE
long load time (more than 20 seconds) to load CHD located on NAS SYNOLOGY with shield tv android

### ISSUE THREAD

**Issue by srk15372** [libretro/pcsx_rearmed#342]
Hi, 
I have a strange problem with pcsx rearmed core on shield tv android using CHD which are located on my NAS SYNOLOGY over network.
Each game take 20 seconds to load (retroarch is freezing during this). I test with BEETLE PSX HW core  and it load instantanely the CHD games without problem on the same folder location. 
All other cores using CHD (sega cd with gx genesis,,4do, etc.. ) haven’t this long load access behavior and load normally without delay from the NAS.
If I load CHD games from the internal storage of the shield tv, there isn’t this problem but my goal is to store large collections of isos on the NAS
Only occur over network with CHD on the SYNOLOGY. 
I test with bin+cue and the same behavior occurs.
Is there any way to have a look on this thanks since it’s the only core whitch give me this strange behavior.
thanks
regards

**Comment by negativeExponent** [comment]
i dont even know where to begin...

**Comment by AnotherLife** [comment]
If it also happens with bin+cue like you say, then it has nothing to do with CHD.

**Comment by notaz** [comment]
It did what I could and am assuming this is fixed now. You can reopen if not.
