### ISSUE TITLE
[Android] Issues in 64bit

### ISSUE THREAD

**Issue by IdiotBlueMage** [libretro/pcsx_rearmed#344]
These issues don't present themselves in 32 Bit, but they do in 64 Bit.

1. In-game text issues.  This seems to only happen with a couple of varities of text, but this Wipeout 3 picture is an example.  Straight lines can appear disorted or as if horizontal lines are through them (full disclosure: I took these pictures with hyllian multipass so please discount the scanlines).  A very similar thing happens in Chrono Cross, but only in battle with the action select and damage numbers, not in any other text.  There's other games with a slight bit of these issues but they aren't as apparent.
![WipEout 3 (USA)-190914-130048](https://user-images.githubusercontent.com/55328534/64912150-ca894680-d6f0-11e9-9c99-286a1bca09d5.png)

2. Texture issues.  This is a bit more specific, but an example is Ape Escape.  The lines across all parts of the helmet are a lot more muted in both 32 Bit and other emulators:
![Ape Escape (USA)-190914-130637](https://user-images.githubusercontent.com/55328534/64912172-1dfb9480-d6f1-11e9-8cf0-3199a6e1e556.png)

How to reproduce: run PCSX-ReARMed in 64Bit Android RetroArch.  Both the original Bios and HLE present these issues, and any other graphical changes don't seem to effect either issue.

**Comment by negativeExponent** [comment]
how and where did you get your 64bit core? 64bit platforms are built without dynarec, which can be slower than the 32 bit in those kind of system but i haven't heard any gfx problems that as severe as that. for the most part the non-dynarec core should be more stable(but slower as earlier said) based on the number of reported issues...

need more info like device used and if everything is using latest ra/core etc.

**Comment by IdiotBlueMage** [comment]
My core for 64Bit came from the online updater.  I'm using the latest RetroArch update obtained in the Play store, and I update my cores daily.

Device is an ASUS ZenPad 3S 10, running Android 7.0.

**Comment by IdiotBlueMage** [comment]
Strange, I went back to ReARMed and things seem to be fixed?  I'm  unsure what commit did it since it's mostly been concerning 3DS, but I tested all the effected games I've noted and they're all fixed.  Maybe it was something on my end or a bugfix in RetroArch itself, but I haven't changed anything.

Anyway, I guess it's time to close this one.
