### ISSUE TITLE
Bogus Memory Address Crash

### ISSUE THREAD

**Issue by ghost** [libretro/pcsx_rearmed#350]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

##Description

A crash on Playstation game "Crash Bandicoot" always at the same point in a particular level. Log output shows a "psxMap: warning" issue and a  "Compile at bogus memory address" issue:
Parameters:
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-pcsx-rearmed/pcsx_rearmed_libretro.so --config /opt/retropie/confi$
Memcard 2: enabled
Use memcard 2: /home/pi/RetroPie/roms/psx//pcsx-card2.mcd
Starting PCSX-ReARMed
Running PCSX Version 1.9 (May 28 2019).
psxMap: warning: wanted to map @80000000, got 0x6f43e000
Init new dynarec
testing if we can run recompiled code..
test passed.
warning: RAM is not directly mapped, performance will suffer
Mapped (RAM/scrp/ROM/LUTs/TC):
77000000/1f800000/1fc00000/08000000/700c3000
Loading memory card /home/pi/RetroPie/roms/psx//pcsx-card2.mcd
found BIOS file: SCPH1001.bin
RGB565 supported, using it
plugin: plugins/builtin_gpu
plugin: plugins/builtin_spu
plugin: plugins/builtin_pad
plugin: plugins/builtin_pad
Plugins loaded.
Loaded CD Image: /home/pi/RetroPie/roms/psx/crash_bandicoot.iso[2048].
selected sound output driver: libretro
CD-ROM Label: SCUS-94900
CD-ROM ID: SCUS94900
CD-ROM EXE Name: SCUS_949.00;1
ari64_reset
ari64_reset
branch in delay slot @000000c0 (000000b0)
branch in delay slot @00000360 (00000350)
Compile at bogus memory address: 00200000

##Steps to reproduce

Launch Crash Bandicoot 1 on the "Rolling Stones" level. Part way through the emulator crashes firstly with parts of the on-screen game image disappearing, leaving just the Bandicoot character and an enemy, then to an entirely black screen and no on-screen error message is given. 

##When did the behavior start?

Always happens at exactly the same point in the game, and has never worked without issue for me. No other games appear to have any issues that I have seen. I have tried re-ripping my CD-ROM and it has made no difference; I also am pretty sure there are no scratches or defects on the CD. I have also posted the issue at https://retropie.org.uk/forum/topic/23668/playstation-1-game-memory-address-crash. Apparently, another user there had no problems with the same game running RetroPie 4.1 on a Raspberry Pi 2 (I cannot confirm, do not have a Raspberry Pi 2).

##Your device/OS/platform/architecture

Pi Model 3 B+ Running at stock (no overclock)
5.1 V, 2.5 A Stontronics Power Supply
RetroPie Version 4.5.1
Built From Pi 2/3 image downloaded from Retropie.org and copied to SD card using Win32DiskImager
USB Devices connected: 2 Playstation 3 USB controllers; 32 GB Sandisk Memory stick
Controlled using Playstation 3 controller wired USB
Using the lr-pcsx-rearmed emulator with scph1001.bin BIOS (renaming to caps makes no difference)
ROMs stored on USB stick at retropie-mount\roms\psx\ (when attempting from SD card, ROMs stored at ~retropie\roms\psx; launching from SD card makes no difference)
The Pi gets to a max of ~66 degC during game load; it has ceramic heatsinks which appear to be doing a good job keeping temp from throttling.

**Comment by adrianmihalko** [comment]
Same problem here.
