### ISSUE TITLE
(Windows) Slowdown when running core on windowed mode

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/pcsx_rearmed#352]
##Description

Running the core on windowed causes dips to 30fps. This issue doesn't persist on fullscreen mode

##Steps to reproduce

- Run any PS1 game. (A good observation would be an intense 3D graphic game like Bloody Roar 2.)
- If fullscreen, set it to windowed (Default shortcut key F)
- Observe the framerates between fullscreen and windowed.

##When did the behavior start?

This kind of behavior has been existed for a long time.

##Your device/OS/platform/architecture

Celeron N2940, Windows 8.1, x86_64.

**Comment by negativeExponent** [comment]
this is not actually a core-related issue. core itself does not know if it is running fullscreen or not. your drivers/gpu is probably more of a culprit where it can handle exclusive fullscreen better than running in window-mode.

**Comment by arnoldsecret** [comment]
closing due to unrelated core issues.
