### ISSUE TITLE
Opening bug with duplicate image in tokusatsu games

### ISSUE THREAD

**Issue by spielvan** [libretro/pcsx_rearmed#356]
![Screenshot_2019-10-16-18-26-42](https://user-images.githubusercontent.com/17939556/66967767-760f1900-f058-11e9-93fe-6f969ad00cae.png)
![Screenshot_2019-10-16-18-26-53](https://user-images.githubusercontent.com/17939556/66967768-760f1900-f058-11e9-8708-0a422fe5b0ef.png)
![Screenshot_2019-10-16-18-28-51](https://user-images.githubusercontent.com/17939556/66967769-760f1900-f058-11e9-9664-80a054625def.png)

#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

##Description

Please describe the issue. If this is a feature request, please add [feature request] to the title of the issue report.

Duplicate image issue when opening Japanese Tokusatsu games: Kamen Rider Agito, Kamen Rider V3 ...

##Steps to reproduce

How can we reproduce this issue? Please include all relevant steps, as well as any settings that you have changed from their default values, particularly including whether you are using the dynarec or interpreter CPU emulation.

CPU dynarec, just start the game that will see the problem that occurs in the opening video of the game.

##When did the behavior start?

If you can bisect the issue (that is, pinpoint the exact commit that caused the problem), please do. Someone has to do it, and having this already done greatly increases the likelihood that a developer will investigate and/or fix the problem. Barring that, please state the last time it worked properly (if ever).

In all builds of PCSX_Rearmed.

##Your device/OS/platform/architecture

Such as Android, iOS, Windows 10, Linux, x86_64, a smart toaster, etc.

Box Android Tv MX3-G S912, Mali 450 com Open Gl 2.0ES e android 5.1.1

**Comment by gameblabla** [comment]
The videos issues were fixed as of my PR https://github.com/libretro/pcsx_rearmed/commit/6d9f0559579ea3a0c69976ad032c85441c200011, this was also affecting Galerians and R-types.
Good to know these were affected too.
