### ISSUE TITLE
QuaKe 2 graphic bug in the second phase

### ISSUE THREAD

**Issue by spielvan** [libretro/pcsx_rearmed#357]
QuaKe 2 graphic bug, in the second phase when it will exit the elevator, running by epsxe in the same box andrfoid, the game works perfectly.

![Screenshot_2019-10-16-18-50-34](https://user-images.githubusercontent.com/17939556/66967861-c7b7a380-f058-11e9-9ce3-5c766576ac05.png)
![Screenshot_2019-10-16-18-50-46](https://user-images.githubusercontent.com/17939556/66967862-c7b7a380-f058-11e9-86d3-08941386da97.png)

**Comment by negativeExponent** [comment]
use official bios file if your not using one. if this is dynarec, see if disabling dynarec(things will be slow) can at least remedy this problem (dynarec has lots more problems that is not present in interpreter build, but dynarec is still needed for slower, hardheld devices), else post a log if you can with this device.

**Comment by gameblabla** [comment]
I think this got fixed with https://github.com/libretro/pcsx_rearmed/commit/3df12a81179acad8406f1791ff716c76caefed31.
I had Funkey-S people try my newer build and they were able to play this game no problem.
I would try it again (i've also merged some other fixes as well).

**Comment by gameblabla** [comment]
Yup, the Funkey people told me it worked after the fix (that one used the NEON video backend) and i tried it myself on x86_64 as well and didn't get the corruption issue either. i've tried on both libretro and the upstream version. In fact, i went as far as going back to see if it could regress and at least up until the driver commit on the upstream version, i didn't get the issue either.
For anyone curious to look at it, here's a save with the supposed moment it is supposed to do that :
[Quake II.srm.zip](https://github.com/libretro/pcsx_rearmed/files/7270700/Quake.II.srm.zip)

Until i can confirm it only happens on, say, the Unai plugin and ARM, there's no reason to keep this open.
