### ISSUE TITLE
Alien resurrection bug

### ISSUE THREAD

**Issue by garay01a** [libretro/pcsx_rearmed#359]
Using:
Playstation classic - autobleem retroarch

In retroarch there is no option (as far as I know at least) to use the option: SPU IRQ always enabled. Without this option several doors do not open in alien resurrection.

It is included in the original emulator on ps classic, in the pcsx/options/advanced menu.

##Steps to reproduce
Alien resurrection - level 3, it is a well published bug with many emulators.

**Comment by negativeExponent** [comment]
Done. once merge, core options should now how "Spu Irq" at bottom. Not sure though if the option would behave the same in libretro, so just leave comment once its thoroughly tested.

**Comment by bslenul** [comment]
Hey! Any idea why it's taking so long for the option to be merged?

Works fine on PC at least: https://youtu.be/o5dZVl5lVbM
Can't try on my Android phone unfortunately because I have no clue how to compile the core for it :p

**Comment by negativeExponent** [comment]
> Hey! Any idea why it's taking so long for the option to be merged?
> 
> Works fine on PC at least: https://youtu.be/o5dZVl5lVbM
> Can't try on my Android phone unfortunately because I have no clue how to compile the core for it :p

i find it easier to compile android build on linux using the libretro-super script if need to.
