### ISSUE TITLE
Enable Forced Interlace produces incorrect results on 3DS

### ISSUE THREAD

**Issue by czarekkwasny** [libretro/pcsx_rearmed#362]
Hello,

The Enable Forced Interlace option doesn't seem to work correctly on the latest compile of Retroarch for 3DS (1.11.2019, 1.8.0 (r22 4b353f8). Basically instead of black lines, the color of the interleaved lines changes depending on the content displayed. Here's an example:

[https://prnt.sc/pr1bcy](https://prnt.sc/pr1bcy)

This makes the rendered content very difficult to read. I was also wondering if there could be a feature implemented where instead of black lines, the rendered lines could be repeated twice so they fill the whole screen vertically (120 lines gets scaled up to 240):

[https://prntscr.com/pr1fpj](https://prntscr.com/pr1fpj)

It turns out to be a very interesting compromise, given the games can be emulated at 100% speed (ie. 60fps/30fps internal) with a nice 20-30% overhead for computationally expensive frames.

**Comment by negativeExponent** [comment]
gpu_unai's interlace option is probably for performance rather than simulate tv-scanlines as you have discovered. it looks ugly at low-res, but acceptable with high-res games. recent port of the gpu_unai on other projects has removed this option.

**Comment by notaz** [comment]
It looks like the option is gone by now, closing.
