### ISSUE TITLE
Enhanced Resolution option is missing

### ISSUE THREAD

**Issue by welly321** [libretro/pcsx_rearmed#363]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

##Description

After the most recent nvidia shield update, the enhanced resolution option (along with the speed hack) is no longer an option in the quick menu (or anywhere) for pcsx rearmed.

##Steps to reproduce

Update Nvidia shield to the latest update. Open Retroarch and download the PCSX rearmed core. Launch any PSX game and try to enable enhanced resolution
##When did the behavior start?

The behavior started after the latest nvidia Shield update

##Your device/OS/platform/architecture

Nvidia Shield (Android TV Oreo 8.0)

**Comment by hizzlekizzle** [comment]
These options aren't available in the 64-bit build, and Google mandated that all packages include a 64-bit application alongside the old 32-bit application, and the OS will pick the "right" build for your device. This means most devices install the 64-bit build, which makes the options disappear.

You can sideload the 32-bit-only application, which is available at buildbot.libretro.com and running the 32-bit PCSX-ReARMed build through it should bring those options back for you.
