### ISSUE TITLE
Pcsx_rearmed ignores the offset settings

### ISSUE THREAD

**Issue by Roughtrade** [libretro/pcsx_rearmed#366]
I have Retropie 4.5 running on a Raspberry pi 3A+ in a Gameboy case. Due to the construction I can't see 32 pixels on the left side.
I have the following settings in config.txt:
overscan_left=32
#overscan_right=0
#overscan_top=0
#overscan_bottom=0

#overscan_scale=1
#framebuffer_width=480
#framebuffer_height=320
framebuffer_width=448
framebuffer_height=320

I start the emulation station with the following parameters:
emulation station --no-splash --screensize 448 320 --screenoffset 32 0

I can adjust the libretto cores to the resolution using the custom acpect ratio switch.
pcsx_rearmed ignores the settings and runs at 480x320. 
How can I change this ?

Thank you very much for your efforts in advance.
Regards Peter

**Comment by dankcushions** [comment]
#overscan_scale=1

remove comment:

overscan_scale=1

then your firmware overscan setting would be applied globally - no need to configure emulators/emulationstation
