### ISSUE TITLE
RetroAchievements not working in Nintendo Switch builds.

### ISSUE THREAD

**Issue by WasabiIceCream** [libretro/pcsx_rearmed#367]
##Description

When launching a RetroAchievements supported game, the core detects the supported achievements, but performing the required actions will not cause them to pop.

##Steps to reproduce

Been testing with Castlevania: Symphony of the Night, and Spyro the Dragon, because they're 2 games with very easy achievements early on. In Castlevania, just kill Dracula in the start, and the achievement is supposed to pop. With Spyro, just collect 100 gems, and free the 4 dragons in the starting level, and the achievement should pop.

##When did the behavior start?

Tested with earliest nightly build I could grab r22 7375bf9 (09/16/2019), latest stable build r22 7375bf9 (11/02/2019), and latest nightly build r22 7375bf9 (12/11/2019). None of them pop achievements. Tested against Windows and Android build r22 4b353f8, which works fine.

##Your device/OS/platform/architecture

Nintendo Switch (64-bit ARM).
Works fine on Windows and Android.

**Comment by negativeExponent** [comment]
are achievements working on that platform with other emu cores?

**Comment by WasabiIceCream** [comment]
Actually, it seems only the Switch builds are not working.
Android build r22 4b353f8 is working fine. I'll edit the above with this info.


> 
> 
> are achievements working on that platform with other emu cores?

Currently, this is the only core available for PS1 on Nintendo Switch (Not using Lakka).

**Comment by negativeExponent** [comment]
> Actually, it seems only the Switch builds are not working.
> Android build r22 [4b353f8](https://github.com/libretro/pcsx_rearmed/commit/4b353f8adc434d4168df88bca58e793becaa891b) is working fine. I'll edit the above with this info.
> 
> > are achievements working on that platform with other emu cores?
> 
> Currently, this is the only core available for PS1 on Nintendo Switch (Not using Lakka).

what i actually mean is if Switch supports achievements, by testing others cores that have achievements like fceumm/nes

**Comment by WasabiIceCream** [comment]
> 
> 
> what i actually mean is if Switch supports achievements, by testing others cores that have achievements like fceumm/nes

Oh, yeah. Every other platform I've tested works fine. Seems to just be this core, and only the Switch build.

**Comment by negativeExponent** [comment]
gpu_unai's interlace option is probably for performance rather than simulate tv-scanlines as you have discovered. it looks ugly at low-res, but acceptable with high-res games. recent port of the gpu_unai on other projects has removed this option.

**Comment by WasabiIceCream** [comment]
> 
> 
> I push a PR that uses alternate method to expose memory to libretro, see if that helps once the update is available in your device.

Thanks. Just grabbed the latest build for Switch from the buildbot. (7375bf9)
All achievements are now listed as "Unsupported".

**Comment by negativeExponent** [comment]
huh strange. the memmap method works fine on linux for me with with SOTN. is there a way you can post the log.

**Comment by WasabiIceCream** [comment]
> 
> 
> huh strange. the memmap method works fine on linux for me with with SOTN. is there a way you can post the log.

I'll grab logs for this build, and the previous one since they're behaving differently:
[logs.zip](https://github.com/libretro/pcsx_rearmed/files/3966369/logs.zip)

Both runs, I start a new game in Spyro, collect 100 gems, and free the 4 dragons in the starting level. Enough for the first achievement to pop (100% Artisans Home), but never does.

**Comment by negativeExponent** [comment]
ah yes.. forgot that Switch has its own pcsx repo, so these changes are not available in the switch-built pcsx rearmed
https://github.com/libretro/pcsx_rearmed_switch

you may want to ask there to add the recent changes for achievements and see if it works.

sorry for the confusion.

**Comment by WasabiIceCream** [comment]
Damn, thanks for the heads-up. I'll post the issue over there.
