### ISSUE TITLE
Failed to load plugins

### ISSUE THREAD

**Issue by brunotrevisan** [libretro/pcsx_rearmed#371]
Hello everyone, I am creating a frontend in C # and would like to use pcsx to emulate psx, but when I run the retro_load_game() command I get the error failed to load the plugins, In retroArch we have the following report:

[libretro INFO] plugin: plugins/builtin_gpu
[libretro INFO] plugin: plugins/builtin_spu
[libretro INFO] plugin: plugins/builtin_pad
[libretro INFO] plugin: plugins/builtin_pad
[libretro INFO] Plugins loaded.

But I can not find these plugins I'm using pcsx_rearmed_libretro, It seems that Retroarch uses the plugins embedded in the DLL how do I load these plugins?

**Comment by negativeExponent** [comment]
core does not use dll... not a core-related issue...

**Comment by notaz** [comment]
Closing as per explanation above.
