### ISSUE TITLE
Video Filter causes graphics corruption

### ISSUE THREAD

**Issue by MrCowKing** [libretro/pcsx_rearmed#372]
##Description

Setting the "Video Filter" option in the "Video" menu causes strange graphical corruptions. Flickers/interlaced between a normal frame render and a scaled, cropped render. Affects FMV, and 2d/3d render.

##Steps to reproduce

1. Set any video filter in the "Video" settings menu
2. Start any PSX game.
3. Observe

##When did the behavior start?

On my TODO

##Your device/OS/platform/architecture

Operating System: Manjaro Linux 
KDE Plasma Version: 5.17.4
KDE Frameworks Version: 5.64.0
Qt Version: 5.13.2
Kernel Version: 5.4.2-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Celeron® CPU J3160 @ 1.60GHz
Memory: 7.2 GiB of RAM

Retroarch: v1.8.1
PCSX ReARMed: r22 2ca9045

**Comment by negativeExponent** [comment]
fmv are usually very low res with weird dimension. video filters are deprecated anyways why do you need it to worl.

**Comment by MrCowKing** [comment]
I don't really need it to work, and didn't realize Video Filters was a deprecated. At any rate, I'm using the shader options now, so I'm closing this ticket.
