### ISSUE TITLE
Calling retro_deinit without loading a game causes a crash

### ISSUE THREAD

**Issue by Jamiras** [libretro/pcsx_rearmed#373]
## Description

`retro_deinit` calls `ClosePlugins`, but `OpenPlugins` is only called from `retro_load_game`, so the plugin pointers are all uninitialized. In my particular case, the crash occurred calling `CDR_close`.

## Steps to reproduce

The easiest way to reproduce this is to modify `command_event_init_core` in `retroarch.c` to call `current_core.retro_deinit` immediate after calling `current_core.retro_init`. Then build and run. Select the pcsx_rearmed core, then attempt to load a game.

My use case is external to RetroArch, and loads the core prior to loading a game. If the user selects a different core before loading a game, the error occurs.

## When did the behavior start?

https://github.com/libretro/pcsx_rearmed/commit/3d3bda68ad4f24314f43bf9de85cad3735d9050c
Commenting out the call to `ClosePlugins` fixes the issue.

## Your device/OS/platform/architecture

Windows 10 x64

**Comment by negativeExponent** [comment]
is moving ClosePlugins to retro_unload_game do any better?

**Comment by Jamiras** [comment]
Anything that moves it out of `retro_deinit` would address the issue.

Another solution is to wrap it in a check like this: <https://github.com/libretro/pcsx_rearmed/blob/9f2c632c7c04c7c86cf66ba3210b43c3e8394e48/frontend/libretro.c#L1267-L1270>

`retro_load_game` does call `ClosePlugins` if they're already open (see highlighted code above), so there shouldn't be any issues caused by not closing them in `retro_unload_game`.

It seems like it _should_ close them in `retro_unload_game` to pair with opening them in `retro_load_game`. It also seems like it should set `plugins_loaded` to 0 so `retro_load_game` doesn't try closing them again.

**Comment by negativeExponent** [comment]
hi
is this still an issue with latest commit?

**Comment by Jamiras** [comment]
Confirmed that switching cores without loading a game no longer crashes. Thanks.
