### ISSUE TITLE
Run Ahead does not work anymore

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/pcsx_rearmed#382]
##Description

Run ahead with 2nd instance was working before the new dynarec addition here on win7 x64.

##Steps to reproduce

Now when you start run ahead 2nd instance RA closes completely, with that in the log at the end (for the 2nd core instance I assume):
```
[libretro INFO] Starting PCSX-ReARMed 
[libretro INFO] Running PCSX Version 1.9 (Feb  9 2020).
[libretro INFO] mapping main RAM failed
[libretro INFO] PSX emulator couldn't be initialized.
[libretro INFO] PCSX init failed.
```

Run ahead with only 1 instance is freezing the game or crashing.

##When did the behavior start?

I suspect it's since the dynarec changes as it's the 1st time I'm testing it.

##Your device/OS/platform/architecture

Win7 x64, i5-3570k, RA nightly cd20966fc8, pcsx-rearmed 9c9d02e.

**Comment by Berzel1us** [comment]
Exacly the same happened to me when updating the core on W10 AMD A10 7890k.

**Comment by Berzel1us** [comment]
Now I know how to solve it. You've gotta go to Latency settings and set "Run-Ahead to redure Latency" off. I hope it helps.
