### ISSUE TITLE
Mac OSX r22 dfcd715 - core just crashes out

### ISSUE THREAD

**Issue by TyroneSlothrop** [libretro/pcsx_rearmed#385]
Since the new dynarec post then PCSX-ReARMed is just crashing out and exiting, without even an error report (as of r22 dfcd715), RetroAch 1.8.4. I am on MacOSx Mojave 10.14.6

I have logs at debug level but below is all that is shown, regardless of game and image type:

[libretro INFO] Starting PCSX-ReARMed 0
[libretro INFO] Running PCSX Version 1.9 (Feb 17 2020).
[libretro INFO] mapping main RAM failed
[libretro INFO] PSX emulator couldn't be initialized.
[libretro INFO] PCSX init failed.

Let me know if I can help with any more info.

**Comment by Ryunam** [comment]
I am experiencing the same exact outcome on Windows 10 x64, running the PAL version of UEFA Euro 2000 as an example. Upon launching the content the core simply crashes RA, without displaying any error notification.

**Comment by ZachCook** [comment]
If remember my debugging of beetle-psx correctly on Mac, this is due to MacOS X requiring mmap above 4G, either removing MAP_FIXED from flags in psxmem.c or changing the fixed address used for Mac should work.

**Comment by pcercuei** [comment]
There are already base addresses > 4 GiB in the supported_io_bases array, shouldn't that work?

**Comment by gingerbeardman** [comment]
Can also confirm on macOS 10.14 Mojave

> [libretro INFO] Starting PCSX-ReARMed 0
> [libretro INFO] Running PCSX Version 1.9 (Feb 26 2020).
> [libretro INFO] mapping main RAM failed
> [libretro INFO] PSX emulator couldn't be initialized.
> [libretro INFO] PCSX init failed.

Have also tried self-building core, problem persists.

**Comment by marios4code** [comment]
Can confirm the issue still happening with PCSX ReARMed.
Beetle PSX (non HW) core is the only one that seems to work at the moment.
MacOS 10.14.6, RetroArch 1.8.5 Stable.

**Comment by gingerbeardman** [comment]
This is happening in multiple cores on macOS, see linked issue above.

**Comment by gingerbeardman** [comment]
I just confirmed myself this is still an issue.

**Comment by csnover** [comment]
A simple hack of the binary (replacing the instruction `B9 12 10` with `B9 02 10`) validates [ZachCook’s comment](https://github.com/libretro/pcsx_rearmed/issues/385#issuecomment-588041173) that removing `MAP_FIXED` allows the emulator to run on macOS. I can’t reconcile why this flag is being used if it is not actually necessary.

**Comment by negativeExponent** [comment]
isnt MAX_FIXED suppose to be disabled?

https://github.com/libretro/pcsx_rearmed/blob/15cfb5599fe16d2dade317342ee4733cf3b8d9cc/libpcsxcore/psxmem.c#L66-L68

**Comment by csnover** [comment]
> isnt MAX_FIXED suppose to be disabled?
> 
> https://github.com/libretro/pcsx_rearmed/blob/15cfb5599fe16d2dade317342ee4733cf3b8d9cc/libpcsxcore/psxmem.c#L66-L68

Wrong line :-)

https://github.com/libretro/pcsx_rearmed/blob/15cfb5599fe16d2dade317342ee4733cf3b8d9cc/libpcsxcore/psxmem.c#L49

**Comment by negativeExponent** [comment]
your missing the point...
