### ISSUE TITLE
(Lightrec) Freeze when loading content or on reset

### ISSUE THREAD

**Issue by negativeExponent** [libretro/pcsx_rearmed#387]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

##Description

core crash on Reset

##Steps to reproduce

load game. do a Reset.

##When did the behavior start?

commit https://github.com/libretro/pcsx_rearmed/commit/04758b20151324552ada2f31460078f5c6eb01e2
or dunno, it the one i tested in a while

##Your device/OS/platform/architecture

Such as Android, iOS, Windows 10, Linux, x86_64, a smart toaster, etc.
linux x64

**Comment by ZachCook** [comment]
The change that caused this crash has been reverted, and just recently a better fix has been merged, thanks for reporting this quickly.

**Comment by negativeExponent** [comment]
![image](https://user-images.githubusercontent.com/54053706/75065916-cf1a1c80-5524-11ea-91b0-53143004e1df.png)

**Comment by negativeExponent** [comment]
a few more observations:
* with runahead enabled + 2nd instance + 1 frame before launching game: the RAM usage: seen on log keeps updating but screen remains black
* same settings above with 2 frames instead, same issue above, sometimes causes core to crash *if it did not crash try loading another game directly)

I have said a few times already that the option "Dynarec Recompiler" was suppose to be for the original dynarec only, but i admit i am wrong. This does allow switching to interpreter and disable lightrec in want to(psx overclock should be removed though). in anycase this has its own problems from my test:
* When Dynarec Recompiler is disabled, runahead enabled + 2nd instance, RA just freeze without labels appearing on its title bar when a game is launched. I dont use runahead at all at runtime but people have reported runahead to work in interpreter mode as long as its 2nd instance.

note: games tested: I am switching between Suikoden 1.1 and Wild Arms. testing under Linux x64 with "clean" core options on each test. if people are lucky enough to have no problems then safely close this post!

**Comment by negativeExponent** [comment]
i dont care about runahead on runtime, no one seems to be bothered by this issue nor my concerns with the changes since the start. and since i have been "silently" told not to touch the core ever since that unai was updated, might as well close this one.

**Comment by twinaphex** [comment]
Guys, let's not have tempers flare here and let's instead focus on fixing this.

**Comment by pcercuei** [comment]
Throwing a tantrum won't make us work on your issue faster or sooner.

**Comment by Ryunam** [comment]
I am experiencing the same issue with the latest core version (as of the time of this message) on Windows 10 x64. 
With Runahead and Runahead Second Instance both enabled and Dynamic Recompiler set to ON, RA will crash as soon as you select Restart from the Quick Menu.

**Comment by negativeExponent** [comment]
sadly, this freeze/crash can happen even without runahead, its just faster when runahead is used.

it freezes (or probably stuck in loop) calling function lightrec_free_recompiler(), happens during psxCpu->Shutdown or psxCpu-Reset calls

a faster way to recreate the error is to switch Dynarec Recompiler from core options to disabled / enabled a few times since this calls both ->Shutdown and ->Reset

bt: https://hastebin.com/yujazixeza.bash

**Comment by pcercuei** [comment]
@negativeExponent this was fixed?

**Comment by negativeExponent** [comment]
@pcercuei sadly, no its not. i was planning to redo this on a new and clean thread instead but i lost internet for a long time. im on a borrowed time where anytime my internet will be gone again.

anyways, since the problem i traced here is about when ->Shutdown is called, which sad is also used for ->Reset, can we take a look at this previous PR and maybe make this work at least to minimize the freezing during loading games?

https://github.com/libretro/pcsx_rearmed/commit/7070d5c660963aec56e1d667211b4a09a62d400d

since here "reset" does not call "shutdown" (im assuming it doesn't) maybe there's something there that can be used/reused without breaking runahead (which was the reason this PR was reverted)

**Comment by ZachCook** [comment]
I can replicate the runahead 2nd instance + reset crash, that stops crashing if https://github.com/libretro/pcsx_rearmed/commit/3eb073975e1816abadd8b15f53fe62f74ee1c7a8 is reverted, but then runahead is too slow to be useful, some other part of lightrec_state might need to be cleared on reset.

I'm unable to replicate the freezing you see without runahead on game load/reset, lightrec_plugin_shutdown() should be checking lightrec_state before calling lightrec_destroy() I think.

**Comment by negativeExponent** [comment]
Heres a backtrace of one of the "freeze" scenario that happens on load content (retro_load_game > SysReset > ...)

backtrace: https://hastebin.com/acazukokov.cs

it may or may not happen. but when it happens, it can happen on successive load content (like next 5 runs consecutively)

**Comment by ZachCook** [comment]
hmm, so that pthread isn't exiting as expected, does everything work fine if compiled without ENABLE_THREADED_COMPILER ?

**Comment by negativeExponent** [comment]
ENABLE_THREADED_COMPILER 0, seems to be working fine so far. no crash at load content, no crash at constantly changing core option>Dynarec ON/OFF (had to mask off some block->op_list_freed)

**Comment by pcercuei** [comment]
Try to set the 'bool' field of the 'struct recompiler' in recompiler.c as ```volatile bool stop;```

**Comment by ZachCook** [comment]
maybe lightrec_free_recompiler() sends the signal before lightrec_recompiler_thd() has entered cond_wait, so the recompiler thread is waiting for a signal to wake up, and the main thread is waiting for the recompiler thread to exit.

**Comment by pcercuei** [comment]
That's not possible; the signal is only sent when the mutex is locked, and the only two moments where it is unlocked, is in ```pthread_cond_wait```, and when the block is compiled inside ```lightrec_compile_list```, but on that last case, the "stop" variable is checked before the pthread_cond_wait, so it should exit regardless.

**Comment by ZachCook** [comment]
@negativeExponent can you run "thread apply all bt" so we can see what the other thread is doing

**Comment by negativeExponent** [comment]
**volatile bool stop** does not help.

**backtrace with threads:** https://gist.github.com/negativeExponent/d8bd6b81adec95968bb02e034a8f4555

**Comment by ZachCook** [comment]
does checking rec->stop before pthread_cond_wait instead of after in lightrec_recompiler_thd() fix it?

**Comment by negativeExponent** [comment]
moving check for rec->stop ahead of lightrec_recompiler_thd() seems to do better now. I spammed changing Dynarec on/off, no freeze.

**Comment by negativeExponent** [comment]
this should be working now. thanks.
