### ISSUE TITLE
[Request] Added PCSX ReARMed Core On RetroArch PSP

### ISSUE THREAD

**Issue by penzovakid** [libretro/pcsx_rearmed#393]
[Request] Added PCSX ReARMed On RetroArch PSP

Port Added PCSX ReARMed Core On RetroArch PSP

**Comment by AnotherLife** [comment]
PSP has better emulation integrated into the system!

Also, it is (I think) way too slow to run anything in pcsx-rearmed.

**Comment by penzovakid** [comment]
pcsx-rearmed  to try it add work possible

**Comment by gameblabla** [comment]
This would need the MIPS to MIPS dynarec from PCSX4ALL to be workable.
But honestly, the only games that PCSX Rearmed can run but the official PS1 emulator can't is Loonies 8192 and i believe a few games with modchip detection/tricks like Speed freaks.

**Comment by notaz** [comment]
There is lightrec now that could probably do the job, but still this is considerable effort for almost no reward, it's very unlikely anyone is going to do it, closing.
