### ISSUE TITLE
Parasite Eve 2 - freezes at opening screen [Winx64]

### ISSUE THREAD

**Issue by meowthed** [libretro/pcsx_rearmed#395]
##Description

It goes through the title screen, but by the time it plays the first cutscene (the date screen), it freezes. This occurs even with the applied fix.

##Steps to reproduce

Run the game and start it. This behavior would start a few moments after game start.

##When did the behavior start?

It's already been around since the last two years, at least with this arch in mind.

##Your device/OS/platform/architecture

Tested on two computers running RA64 in Windows 8.1 and Windows 10.

**Comment by AnotherLife** [comment]
Set the CPU clock to 70

**Comment by arnoldsecret** [comment]
@AnotherLife the CPU clock feature isn't present on the x86_64 version of the core.

**Comment by AnotherLife** [comment]
Interesting, I wonder why.

Also, that Parasite Eve 2 hack/fix is not working and should probably be removed.

**Comment by negativeExponent** [comment]
this is probably an upstream issue since i cannot even run it on the most vanilla version of pcsx_rearmed.

**Comment by notaz** [comment]
This is working by now on both dynarecs.
