### ISSUE TITLE
In PSX Doom (USA) in the map Club Doom the music does not loop

### ISSUE THREAD

**Issue by VGkav** [libretro/pcsx_rearmed#396]
Using the password Y0W6NXZSSS you can load the secret map "Club Doom". When the map starts some music is playing using the PSX SPU. When you go up the stairs the game starts playing CD track audio instead. Good so far. That CD track music should loop when it ends but it doesn't in pcsx-rearmed, there is just silence.

Tested using recent core builds on Windows using cue/bin and on the Playstation Classic using CHD. In Beetle PSX it loops properly.

**Comment by gameblabla** [comment]
Probably a CDDA bug like for Fantastic Pinball :
https://github.com/libretro/pcsx_rearmed/issues/229#issuecomment-927119765

Or it's a bug in the CHD code like for Punky Shunk, in which case please use bin/cue in the meantime.

**Comment by notaz** [comment]
Should work now.
