### ISSUE TITLE
1Xtreme/ESPN Extreme Games SCUS-94503

### ISSUE THREAD

**Issue by Jetup13** [libretro/pcsx_rearmed#398]
1Xtreme/ESPN Extreme Games internal frame rate drops to unplayable levels after race starts
Game ID: SCUS-94503

You'll start to see the frame drops almost instantly after the race starts. They drop to around 18FPS. The game also has graphically glitches (seems to be a neon problem, using KMFD's PEOPS PCSX-ReArmed fixes the graphical issues. But not the frame drops). 

Have not changed any of the core settings besides changing the PSX clock. Tried lowering it to 45 and got the same result. I've used real bios (both scph101.bin 6E3735FF4C7DC899EE98981385F6F3D0 and scphxxxx.bin 32C04484C234FD09D79625E9FE2EC232)

PS Classic Retroarch PCSX-ReArmed r22 dfcd715 core. This issue doesn't happen on my Samsung S10e.

**Comment by negativeExponent** [comment]
what device are you using? this is most likely a dynarec issue since no frame drops here in linux at least. also what peop's patch?

**Comment by AnotherLife** [comment]
Normal pcsx-rearmed on the Playstation Classic uses the NEON video "plugin". But there is also a PEOPS core. In this case the OP said that core build fixes the gfx problems but framerate is still low.

**Comment by negativeExponent** [comment]
exactly, what core build did he mean?

**Comment by AnotherLife** [comment]
The main one he is using is the one linked in his last sentence, commit dfcd715. For the Playstation Classic, so it defaults to NEON video plugin.

But a guy called KMFND provides alternative builds that have PEOPS video plugin. So he tested with that one as well.

**Comment by negativeExponent** [comment]
so where is this "alternate build" exactly. they should have provided the source if they are redistributing the binaries for opensource projects.

**Comment by AnotherLife** [comment]
It is this guy, he releases cores for the Playstation Classic and SNES/NES Classic consoles (when modded and running Retroarch of course)

https://github.com/KMFDManic/NESC-SNESC-Modifications/releases

But you just change a makefile option and build with PEOPS instead of NEON. I don't know if KMFDmanic has done source changes for pcsx-rearmed.

**Comment by negativeExponent** [comment]
i don't see the sources of any of these modifications.

**Comment by notaz** [comment]
I'm not noticing any issues on a r-pi4 so assuming fixed. Closing.
