### ISSUE TITLE
[PS Vita] Retroarch PSX rearmed core crashes when using pbp and multi disk

### ISSUE THREAD

**Issue by lamvuong2019** [libretro/pcsx_rearmed#400]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

##Description
Retroarch PSX rearmed core on PS Vita crashes when using pbp and multi disk

##Steps to reproduce
Using any PS vita firmware, and any retro arch version (nightly or 1.8.5 Stable), happen to all pbp that is multi disk.

1. Load game pbp
2. Go to option and disk control
3. Eject Disk
4. Select a disk index other than 1
5. Select insert disk.

Confirmed working on psx-rearmed on android.

##When did the behavior start?
Crashes retroarch and go back to system menu.

##Your device/OS/platform/architecture
PS Vita firmware 3.65 enso

**Comment by AssCabbage** [comment]
Possibly related to this:
https://retropie.org.uk/forum/topic/25635/retropie-completely-locking-up-requiring-hard-reboot-when-attempting-to-switch-from-disk-2-to-disk-1-in-multidisk-games/97?_=1587915715478

**Comment by lamvuong2019** [comment]
Tested the latest build and the problem seem to have been fixed.
