### ISSUE TITLE
cf98d47 commit totally destroys FPS if no bios present

### ISSUE THREAD

**Issue by tauonelectronics** [libretro/pcsx_rearmed#409]
cf98d47 commit totally destroys FPS if no bios present.
Looks like a poor fix of another issue

**Comment by Exalm** [comment]
From discussion on https://github.com/libretro/pcsx_rearmed/commit/cf98d473a9ddaa6a77bed1cb5af706a4cd50b8b0:

It should only be disabled for lightrec, but not for ARM dynarec.
