### ISSUE TITLE
Ios instant crash on the dynarec version (interpreter version works fine)

### ISSUE THREAD

**Issue by bsauvage1** [libretro/pcsx_rearmed#42]
Been experiencing instant crash to desktop since beginning of the year and it seems I'm not the only one. Not sure whether this is a core issue or retroarch implementation issue? 
The core used to work great on my old iPad 2 last year on retroarch 1.0.0 and stopped working right after update to 1.1xxxx

**Comment by twinaphex** [comment]
Are you sure you did not upgrade your iOS in the meantime? Newer iOS versions break backwards compatibility with the dynarec.

**Comment by bsauvage1** [comment]
Yes I did to 8.1.2 - which is by all standards an old version now.
But to get back to my point ppsspp (standalone) uses dynarec and doesn't
have that issue so I remain hopeful that something can be done?
At least good to know that's the os issue.

**Comment by twinaphex** [comment]
PPSSPP has nothing to do with PCSX ReARMed dynarec.

And yes it no longer works with any iOS version above 6.0. Sorry but it isn't worth the time to continue patching up ASM dynarec code whenever Apple launches a new OS version again that breaks everything. You should stick to old iOS versions if you want to be able to keep using software like this, otherwise you will just have to accept some performance being sacrificed.

**Comment by bsauvage1** [comment]
Sorry to hear that... Thanks

**Comment by notaz** [comment]
If you can get the crash dumps I might be able to take a look, no promises though. There should be a log file somewhere too.

(don't ask me how to get the dumps, I don't have any Apple devices and have no idea, but people would send me those in the past, so it's possible somehow)

**Comment by twinaphex** [comment]
OK, let me try to get those for you and contact you on IRC.

**Comment by bsauvage1** [comment]
were you able to figure out the crash cause?

**Comment by seadil** [comment]
@notaz: this weekend the PPSSPP submitted a workaround regarding iOS dynarec patching, see the following links:
https://github.com/hrydgard/ppsspp/issues/8122#issuecomment-241341746
https://github.com/hrydgard/ppsspp/issues/8122#issuecomment-242760910
https://github.com/hrydgard/ppsspp/commit/933949ddd2c2195de7dba13c893a7bde1f6b7ad3

Using this method allows dynamic recompiling on any iOS devices and firmwares.

**Comment by meepingsnesroms** [comment]
This is an IOS issue not a core or RetroArch issue.
IOS will not allow data execution,some jailbreaks fix this some dont.
Thats the whole principle of dynarecs,to convert the ROM from ps1 MIPS to host code(ARMv7 in this case),this code is stored in a buffer of writable data.
IOS security forbids the execution of writable code,blame apple.
