### ISSUE TITLE
Lightrec not enabled for classic_armv8_a35

### ISSUE THREAD

**Issue by sampadmohapatra** [libretro/pcsx_rearmed#427]
Is there any reason for choosing ari64 over lightrec as the DYNAREC on Playstation Classic.

I built with lightrec enabled and the emulation was very slow.
CC=arm-linux-gnueabihf-gcc make -f Makefile.libretro platform=classic_armv8_a35

My build env:
Ubuntu 16.04 - arm-linux-gnueabihf-gcc (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9))

**Comment by dankcushions** [comment]
ari64 is much faster for arm 32 bit targets. it is optimized for that specific system. lightrec is more generic.

**Comment by sampadmohapatra** [comment]
Thanks
