### ISSUE TITLE
Xenogears crashes in open space (when battle starts), in pcsxr not

### ISSUE THREAD

**Issue by noiseshaade** [libretro/pcsx_rearmed#432]
Xenogears.CD1.Russian.RGR-Megera.srm.zip https://github.com/libretro/RetroArch/files/4755354/Xenogears.CD1.Russian.RGR-Megera.srm.zip

Save is attached, first save
rearmed, windows

btw hmmmmmm may be 2x 3x whatever xy resolution scale?

**Comment by bslenul** [comment]
Yeah a log could be useful, I tried by curiosity anyway and your save works fine for me (redump USA version, RA and PCSX ReARMed up-to-date), I loaded the 1st save and finished a couple fights on the world map with no issue.

**Comment by negativeExponent** [comment]
since he's on windows, it could be that he is not using a bios file. we can only guess at this moment... i dont use windows, so i will never know...

**Comment by gameblabla** [comment]
It's possible he suffered from the issue with Zeus fight in Xenogears. This should be fixed since my PR https://github.com/libretro/pcsx_rearmed/pull/536.
I would try it again.

**Comment by notaz** [comment]
No response so assuming fixed. Reopen if this is still an issue.
