### ISSUE TITLE
[Linux/ARM/NEON] Video glitches/freezes in RockPro64(The Retro Arena)

### ISSUE THREAD

**Issue by litaniast** [libretro/pcsx_rearmed#434]
#This tracker is for pcsx-rearmed-libretro issues *only*.
##Description

When I run some games have videos, the videos glitch heavily with dynamic recompiler and freezes without dynarec.

![DSC_5852](https://user-images.githubusercontent.com/4857928/84554053-19800d00-ad51-11ea-85ac-745e140de92b.JPG)

I ran them in Windows x64 but its fine. Only the RockPro64(arm NEON Linux device) have this glitch.

Games:
FIFA World Cup 2002 (NTSC-U)
Tony Hawk's Pro Skater 2 (NTSC-U)
WipEout 3 (NTSC-U)
WipEout 3 Special Edition (PAL)

##Steps to reproduce

1. Run these games
2. In FIFA World Cup 2002, after the license and it says 'E A Sports', it frozen without dynarec and glitched with dynarec
3. In WipEout 3 Special Edition, it frozen/glitched after the 'Sony Computer Entertainment Europe presents'
4. Every else frozen/glitched immediately

##When did the behavior start?

I don't know that because I got those games recently(yesterday).

##Your device/OS/platform/architecture

RockPro64(small board computer, used RK3399)/Linux/The Retro Arena(fork of RetroPie)/armv7-neon

**Comment by notaz** [comment]
This was likely an old dynarec issue related to it being unable to handle some memory layouts. I'll assume this is fixed, you can reopen if not.
