### ISSUE TITLE
[Game/Linux/Libretro] Geppy-X bug.

### ISSUE THREAD

**Issue by fastpop72** [libretro/pcsx_rearmed#435]
##Description

In game Geppy-X just after the first logo animation the screen goes black and you can hear only the music of the Intro video. You can't skip anymore.

##Steps to reproduce

Load Geppy-X using Retroarch with libretro core.

##When did the behavior start?

Dunno. Same game runs well in beetle-psx core.

##Your device/OS/platform/architecture

Linux x64 (debian latest).

**Comment by negativeExponent** [comment]
works fine for me

**Comment by AnotherLife** [comment]
Are you using real bios?

**Comment by fastpop72** [comment]
Yes, i'm using real bios. I want to specify that if you skip the very first animation (the logo) the game loads ok. But if you don't skip the logo and let the fmv starts you can hear only the sound but got black screen, and you can't skip the intro anymore. The rom is ok because Beetle-psx runs it without flawless.

**Comment by negativeExponent** [comment]
ive tested with or without bios works fine for me.
tested with or without dynarec still ok
let the whole intro (logo thing+into stuff) run and it works ok
switching different inputs (some games do no like switching on-the-fly with controller types or if set other than standard), still worked fine.

i've tested on linux with latest buildbot core, disk 1 only of the game.

**Comment by fastpop72** [comment]
I updated RA and pcsx-rearmed core... same result.

Here's a video of the bug: https://www.youtube.com/watch?v=rf9Zj80MXCM

And the runcommand log too...

[runcommand.log](https://github.com/libretro/pcsx_rearmed/files/4871242/runcommand.log)

@negativeExponent  If i could provide you more info let me know...

**Comment by negativeExponent** [comment]
i was assuing you are using vanilla RA + core. you seem to be using retropie + the lr core dunno if they are in sync with vanilla RA and core and what config defaults they are using. you can try running without shaders and see if it does anything.

in anycase game works fine with vanilla RA and core

**Comment by negativeExponent** [comment]
no response?...
