### ISSUE TITLE
some disney games have malfunctions on input

### ISSUE THREAD

**Issue by ghost** [libretro/pcsx_rearmed#437]
Hi, I've tried to get The little mermaid 2 on latest retropie on rpi 4 and face this issue with this core. The character go left all the time, same on menu. I have a proper BIOS (tried different ones). Tried analog and without analog on retroarch... the same happened on Lilo y Stitch. 

hope you find a solution.

**Comment by negativeExponent** [comment]
its one of those game where it will have problems detecting analog/ds input modes (which is always enabled even when using a standard input type)

Just change input 1 type to analog or even dualshock since game has rumble support. You may need to restart game with that input setting in some cases.

**Comment by negativeExponent** [comment]
kindly test with latest commit.

**Comment by gameblabla** [comment]
Let's assume this is fixed for now.
