### ISSUE TITLE
Missing "shows the full area" for 16/9 hacks

### ISSUE THREAD

**Issue by Darknior** [libretro/pcsx_rearmed#438]
I've found some cool patch to activate 16/9 16/10 ... for PSX games like we can already do it on Saturn and Dramcast.

http://meduza-team.ucoz.net/publ/romkhaking/modifikacii/modifikacija_igr_dlja_psx_playstation_1/3-1-0-14

I've try them and they works fine. BUT like we don't have the option required for them we can't use them fine on Libretro.

![screenshot](https://user-images.githubusercontent.com/3703317/87234951-86310a80-c3d6-11ea-98de-934aaba824e5.gif)
`Note: To expand full viewing area of the screen you need to activate special fix “shows the full area in Capcom fighters” in Pete’s or P.E.Op.S. PSX video plugins settings.`

Will it be possible to add this option here to let peoples maybe make more patch in the future :)
Thansk

**Comment by vaguerant** [comment]
This would appear to be the same issue as #313. I wrote a long explanation of what I believe is going on there in a [comment](https://github.com/libretro/pcsx_rearmed/issues/313#issuecomment-2165510932) on that closed issue.

The short version is that the PS1 has a variety of supported video modes, but the 384-wide mode is often truncated down to a smaller resolution (~368) in PS1 emulators for historical reasons. This isn't something that happened on real hardware, it just approximates what might have happened on some televisions of the time (some picture going off the edges of the screen).

**Comment by notaz** [comment]
There is now an option called "Show horizontal overscan" with "Hack" selectable for this.
