### ISSUE TITLE
CHD support - Core is cutting off first couple of seconds of CD audio

### ISSUE THREAD

**Issue by TrollDecker** [libretro/pcsx_rearmed#439]
## Description

If I load a CHD image with redbook audio, whenever a track is played, the first two seconds are cut off.
This happens no matter how I structure the CUE file when creating a CHD image with `chdman` - With pregaps, with two indices per track, with one index per track, I've tried all sorts.

This problem doesn't arise in Beetle or DuckStation. In those cores, the audio tracks play from the very beginning without fail.

## Steps to reproduce

1. Create CHD.
2. Open CHD file in Retroarch using PCSX-ReArmed core.
3. Despair.

## When did the behavior start?

I can only assume it's been there since CHD support was added, but I don't actually know.

## Your device/OS/platform/architecture

Debian Stretch, x86_64
Lakka, RPi 3B+

**Comment by negativeExponent** [comment]
never noticed this. played audiocd through vib-ribbon though.

**Comment by TrollDecker** [comment]
I'm talking about redbook audio on the game disc itself (as in, a game that ships with redbook audio on its disc to use as its own music). If I run a BIN/CUE image directly in the emulator, everything plays fine, no problems. The problem arises with CHDs, at least the ones I've generated from those exact same CUE files, and after trying several other cores, only PCSX-ReArmed cuts off the first two seconds.

**Comment by KMFDManic** [comment]
@TrollDecker Out of curiosity, did you test V4, as well as V5 CHD Conversion?  I have had a few report oddities when doing one versus the other, missing or delayed sound, etc.  On my end, CHDs have been playing fine.  And, I assume you also tested bin+cue, just to be sure?

**Comment by negativeExponent** [comment]
mednafen cores, and pcsx uses the same libchd source from https://github.com/rtissera/libchdr. There were issues in its early days when using V4 converted files even off from original verified dumps but that might not be related to TS issue since he said he tried the same game (whatever this game is since its not mentioned) and it worked on beetle psx

**Comment by TrollDecker** [comment]
(She :wink: )

Took me a headache and a half to find a version of chdman that produced V4 files (v0.145 - eventually found it in the Ubuntu Precise repo) and... getting the same result with a V4 file as I am with V5, I'm afraid. And yeah, I checked the version number with `chdman info`.

So far, I've tried Bust-A-Move 2 Arcade Edition and a Mortal Kombat 3 demo (Long story, it's on an Official PlayStation Magazine UK disc and inadvertedly uses music from a Toshinden 2 demo on the same disc, so it's a lot easier to spot the cutoff when it occurs), and in all cases, the CHD copy suffers the cutoff, but the BIN/CUE doesn't.

**Comment by negativeExponent** [comment]
> (She wink )
> 
> Took me a headache and a half to find a version of chdman that produced V4 files (v0.145 - eventually found it in the Ubuntu Precise repo) and... getting the same result with a V4 file as I am with V5, I'm afraid. And yeah, I checked the version number with `chdman info`.
> 
> So far, I've tried Bust-A-Move 2 Arcade Edition and a Mortal Kombat 3 demo (Long story, it's on an Official PlayStation Magazine UK disc and inadvertedly uses music from a Toshinden 2 demo on the same disc, so it's a lot easier to spot the cutoff when it occurs), and in all cases, the CHD copy suffers the cutoff, but the BIN/CUE doesn't.
> 
> ====
> 
> [EDIT] Is it at all possible that this value might be the culprit?
> 
> https://github.com/libretro/pcsx_rearmed/blob/ddd39f209f4ce6f03ed3198d7d58c2e36565baa9/libpcsxcore/cdriso.c#L1067
> 
> Beetle PSX seems to be using a similar value here: https://github.com/libretro/beetle-psx-libretro/blob/4cda2d4597be2420476a13cff8e535e21ab0eeb5/mednafen/cdrom/CDAccess_CHD.cpp#L73
> 
> But in Beetle's case, it's a negative value. PCSX seems to be adding together `frame_offset` and `md.pregap` a little further down, too. I'm just spitballing here, though. thinking

this was changed from this commit: https://github.com/libretro/pcsx_rearmed/commit/60bac94cb2dde2c1c6d54f9e3c58a0f7f284df06#diff-2dda6cc4cd7811dfe7b14e2a12909ad8

try changing it back to 0 or even -150 if it makes any difference.

**Comment by TrollDecker** [comment]
Yep. Cloned and compiled without making any changes first to ensure the problem was still there, and then changed it to `0` and recompiled. That little change seems to have done the trick for me, and it's now playing the tracks correctly. :thinking:

**Comment by negativeExponent** [comment]
this doesn't seem right to me. testing with Bust-a-Move-2-Arcade-Edition > options > Music test, its now adding a longer start delay before music is played compared to Duckstation of Beetle.

**Comment by negativeExponent** [comment]
@TrollDecker can you try this modification if it does any difference to your test?

- set **int frame_offset = 150;** **to int frame_offset = 0;**
- then make this line:
https://github.com/libretro/pcsx_rearmed/blob/ddd39f209f4ce6f03ed3198d7d58c2e36565baa9/libpcsxcore/cdriso.c#L1094-L1095

to:

```
    int pregap = (numtracks == 0) ? 0 : (md.pgtype[0] == 'V') ? (-150) : md.pregap;
    int pregap_dv = (md.pgtype[0] == 'V') ? md.pregap : 150;
    frame_offset += pregap + pregap_dv;

    sec2msf(frame_offset, ti[md.track].start);
    sec2msf(md.frames - pregap_dv, ti[md.track].length);

```

reference to logic:
https://github.com/libretro/beetle-psx-libretro/blob/4cda2d4597be2420476a13cff8e535e21ab0eeb5/mednafen/cdrom/CDAccess_CHD.cpp#L139-L144

dunno anything about audio track handling, so...

**Comment by TrollDecker** [comment]
That seems to have made it worse, and causes it to cut off more of the track than before, unfortunately. :confused:

**Comment by negativeExponent** [comment]
huh, it shouldn't get worse, but ok.
what game is this exactly you are testing? and what exact track (if we can play it directly like in options>music etc).
If this is a demo game, it should be safe to link directly to it.

**Comment by TrollDecker** [comment]
Bust-A-Move 2 Arcade Edition again. I've tried most tracks but No. 2 in the Sound Test seems like the easiest one to compare.

As for the MK3 Demo, I need to figure out where to host it first, as nobody seems to have archived this particular disc yet (I might see if I can pop it up on Internet Archive soonish).

**Comment by negativeExponent** [comment]
to be honest, i test the same game and this track as the reference since it starts immediately.

i dunno if github has size limit but you can post zip files here by drag-and-drop.

**Comment by TrollDecker** [comment]
10MB limit, unfortunately. Not to worry, though: https://mega.nz/file/w6ZgAaCT#C0DRlbqykWNL8i7V9-asJ-esVco_VUz2bLM3TyBCcu8

(Yeah, I know, not the most descriptive filename, but I keep my images organised in separate folders)

**Comment by negativeExponent** [comment]
i need the raw cue/bin file, not chd. yeah i can extract from it but i wont

**Comment by TrollDecker** [comment]
Ah, whoops: Here's the BIN/CUE version: https://mega.nz/file/snZQWSTS#qSfFSP5fv_H1LZPKb6On9VC6MvlcXCnQ7vdU-JCemOY

**Comment by negativeExponent** [comment]
ok looks like pcsx-chd is not reading the length of audio tracks correctly for this game. dunno why:

Good length for this demo:
```
[libretro INFO] Track 01 (DATA) - Start 00:02:00, Length 47:38:56
[libretro INFO] Track 02 (AUDIO) - Start 47:40:56, Length 03:16:32
[libretro INFO] Track 03 (AUDIO) - Start 50:57:13, Length 00:09:01
[libretro INFO] Track 04 (AUDIO) - Start 51:06:14, Length 00:09:01
[libretro INFO] Track 05 (AUDIO) - Start 51:15:15, Length 00:09:01
[libretro INFO] Track 06 (AUDIO) - Start 51:24:16, Length 00:55:50
[libretro INFO] Track 07 (AUDIO) - Start 52:19:66, Length 00:09:02
[libretro INFO] Track 08 (AUDIO) - Start 52:28:68, Length 02:50:46
[libretro INFO] Track 09 (AUDIO) - Start 55:19:39, Length 00:11:40
[libretro INFO] Track 10 (AUDIO) - Start 55:31:04, Length 00:11:34
[libretro INFO] Track 11 (AUDIO) - Start 55:42:38, Length 03:01:32

```

Bad length:
```
[libretro INFO] Track 01 (DATA) - Start 00:02:00, Length 47:36:56
[libretro INFO] Track 02 (AUDIO) - Start 47:40:56, Length 03:12:32
[libretro INFO] Track 03 (AUDIO) - Start 50:55:13, Length 00:05:01
[libretro INFO] Track 04 (AUDIO) - Start 51:02:14, Length 00:05:01
[libretro INFO] Track 05 (AUDIO) - Start 51:09:15, Length 00:05:01
[libretro INFO] Track 06 (AUDIO) - Start 51:16:16, Length 00:51:50
[libretro INFO] Track 07 (AUDIO) - Start 52:09:66, Length 00:05:02
[libretro INFO] Track 08 (AUDIO) - Start 52:16:68, Length 02:46:46
[libretro INFO] Track 09 (AUDIO) - Start 55:05:39, Length 00:07:40
[libretro INFO] Track 10 (AUDIO) - Start 55:15:04, Length 00:07:34
[libretro INFO] Track 11 (AUDIO) - Start 55:24:38, Length 02:59:32
```
dunno why though...

**Comment by negativeExponent** [comment]
managed to lineup the tracks correctly(start time, lenght, lba etc) comparing to beetle and YET, it still does not hangle MK3 audio where it wants to start immediately without any silence at the beginning of the audio track.
its probably somewhere related to how audio tracks are decoded, like this track where there is no silence at all at the beginning (i have not yet ripped the tracks itself)
mind you, i have no clue what i am doing :p just doing some comparisons and testings...
someone feel free to chip in :p

**Comment by iax2RqPZbq** [comment]
Only tangentially related, but there is also [notaz/pcsx_rearmed issue 167](https://github.com/notaz/pcsx_rearmed/issues/167) which also has to do with the added start offset.

If I recall when investigating, pcsx_rearmed adds this offset when loading the disc (except with PBP files), then subtracts it elsewhere in the end, effectively "negating" it.

**Comment by negativeExponent** [comment]
the audio tracks are actually way offtrack as stated here
https://github.com/libretro/pcsx_rearmed/issues/439#issuecomment-671338219.

**Comment by negativeExponent** [comment]
chd audio timing-REVISITED

seems like i found a likely fix (or workaround or whatever)

change: **int frame_offset = 150;** to **int frame_offset = 0;**
remove (or comment out): **frame_offset += md.postgap;** to **//frame_offset += md.postgap;**

works for audio timing issue in Mortal Kombat 3 Demo disk (link somewhere above). Have not tested anything other than that game. If anyone more familiar with audio/cd/track handling and help check the better.

**Comment by hizzlekizzle** [comment]
Do you have any thoughts on this, by chance, @aliaspider? You've done some work with CHDs, right?

**Comment by negativeExponent** [comment]
here's what puzzles me
this is the reference track info if using the same disk in .CUE format
```
REFERENCE TRACKS in CUE
[libretro INFO] Track 01 (DATA) - Start 00:02:00, Length 47:38:56
[libretro INFO] Track 02 (AUDIO) - Start 47:40:56, Length 03:16:32
[libretro INFO] Track 03 (AUDIO) - Start 50:57:13, Length 00:09:01
[libretro INFO] Track 04 (AUDIO) - Start 51:06:14, Length 00:09:01
[libretro INFO] Track 05 (AUDIO) - Start 51:15:15, Length 00:09:01
[libretro INFO] Track 06 (AUDIO) - Start 51:24:16, Length 00:55:50
[libretro INFO] Track 07 (AUDIO) - Start 52:19:66, Length 00:09:02
[libretro INFO] Track 08 (AUDIO) - Start 52:28:68, Length 02:50:46
[libretro INFO] Track 09 (AUDIO) - Start 55:19:39, Length 00:11:40
[libretro INFO] Track 10 (AUDIO) - Start 55:31:04, Length 00:11:34
[libretro INFO] Track 11 (AUDIO) - Start 55:42:38, Length 03:01:32

```

here is the same disk in CHD:
```
[libretro INFO] Track 01 (DATA) - Start 00:02:00, Length 47:36:56
[libretro INFO] Track 02 (AUDIO) - Start 47:40:56, Length 03:12:32
[libretro INFO] Track 03 (AUDIO) - Start 50:55:13, Length 00:05:01
[libretro INFO] Track 04 (AUDIO) - Start 51:02:14, Length 00:05:01
[libretro INFO] Track 05 (AUDIO) - Start 51:09:15, Length 00:05:01
[libretro INFO] Track 06 (AUDIO) - Start 51:16:16, Length 00:51:50
[libretro INFO] Track 07 (AUDIO) - Start 52:09:66, Length 00:05:02
[libretro INFO] Track 08 (AUDIO) - Start 52:16:68, Length 02:46:46
[libretro INFO] Track 09 (AUDIO) - Start 55:05:39, Length 00:07:40
[libretro INFO] Track 10 (AUDIO) - Start 55:15:04, Length 00:07:34
[libretro INFO] Track 11 (AUDIO) - Start 55:24:38, Length 02:59:32
```

there is a large difference in the length of the tracks causing next tracks to start with incorrect offsets

**Comment by aliaspider** [comment]
yeah it seems to skip 2 seconds at the end and the start of each track for whatever reason. I'll take a look at it.

**Comment by aliaspider** [comment]
just made a PR, can you try it out ?

**Comment by negativeExponent** [comment]
sounds great. tested the audio track issue in MK3 from the demo (link above somewhere) and its fixed. track information is correct as well.

**Comment by aliaspider** [comment]
cool.
can this be closed then ?
