### ISSUE TITLE
(RetroPie/RPi 4) Freezing issues with two games

### ISSUE THREAD

**Issue by SeraphisCain** [libretro/pcsx_rearmed#446]
## Description

Freezing issues with two NTSC-J games: Zen-Nihon (or Zen-Nippon) Joshi Puroresu: Joou Densetsu and 
Chiisana Kyojin Microman. 

Zen-Nihon Joshi Puroresu: Prior to the most recent precompiled binary, the game simply would not start at all. Would boot to a black screen and stay there. As of the most recent (September 2nd) precompiled binary, the game now boots and plays fine up to the character select screen, but then hangs at a black screen after the wrestler intro FMVs are played.

Microman: Game hangs at the loading screen when loading the first stage.

## Steps to reproduce

No special steps needed. Have tested both with dynarec/interpreter, enhanced res on/off, official/HLE bios, compatibility hacks off/on, no differences. Have also tested multiple dumps for Zen-Nihon.

## When did the behavior start?

Neither game has ever worked properly as far as I know, though as I said above Zen-Nihon has improved somewhat with the most recent binary update.

## Your device/OS/platform/architecture

RPi 4 running latest RetroPie.

**Comment by provola1984** [comment]
Same problem here. Also Jikkyou J.League 1999: Perfect Striker black screen after boot

**Comment by gameblabla** [comment]
> Same problem here. Also Jikkyou J.League 1999: Perfect Striker black screen after boot

That game will be under its own https://github.com/libretro/pcsx_rearmed/issues/492 bug report. And yes, it does black screen even after my changes... I believe this game needs GPU busy state emulation.

As for the other games, i would suggest you try them again given the recent improvements i made.

**Comment by notaz** [comment]
Could get ingame in both games so this seems fixed now.
