### ISSUE TITLE
Fantastic Pinball Kyuutenkai - Screen stays black after selecting Memory Card on PSTV

### ISSUE THREAD

**Issue by xxx256** [libretro/pcsx_rearmed#447]
Kyutenkai hangs with a black screen, after selecting a memory card. Same issue (different core) as described here:

https://github.com/libretro/beetle-psx-libretro/issues/70

I am using PCSX-reARMed core on PS VITA TV. Please fix. Thank you!

![eb49246c-3a1d-11e6-9f0f-41cb1207aa72](https://user-images.githubusercontent.com/71329072/93212118-74ffd380-f762-11ea-9e3d-8da8cf29208d.png)

**Comment by negativeExponent** [comment]
duplicate https://github.com/libretro/pcsx_rearmed/issues/229

**Comment by gameblabla** [comment]
Let's close duplicates like this one.
