### ISSUE TITLE
game can write, but can't read memory card

### ISSUE THREAD

**Issue by thellin1** [libretro/pcsx_rearmed#45]
I built a Retropie on the new Raspberry pi 3. This is the emulator used for the PlayStation 1 system.

I'm having issues while playing The Legend of Dragoon game. During play I go into the game menu to save and i'm able to write to the memory card, yet when I go back in and save again I do not see the previous saved game in the slot. Looking in the rom's folder I see a .srm file was created. Even if i exit the game and come back in there is no saved data to continue.

I have Crash Bandicoot working as well, and i'm able to read and write to it's .srm file. I have the LoD CD's and I've tried installing the roms as both .bin and .iso files. Both versions can write but not read the saved data. 

I'm not sure if this is the emulator issue with the memory card or the game issue. 

Any ideas?

**Comment by AnotherLife** [comment]
This is an old issue but I tested this on the PSC (using the Retroarch core) and the game runs great. I saved, quit Retroarch and loaded just fine. Talking about the US version.

**Comment by negativeExponent** [comment]
this should be working in latest commits

@twinaphex @hunterk @hizzlesomething

**Comment by gameblabla** [comment]
Most likely got fixed by either my HLE patches (if you were even using HLE for that game) or some other changes. Feel free to reopen this if it happens again.

**Comment by slankka** [comment]
> If none of the above is found, PCSX_ReARMed will search for filenames starting with "scph" and use that instead. It doesn't seem to matter whatever BIOS version is used and from what region, as long as it's from a retail PSX/PS one. If no compatible BIOS is found, PCSX_ReARMed will revert to use the HLE BIOS, which can have compatibility issues (e.g. memory card issues in Suikoden games, some games just going into black screens, ...).

Some frontend core option defaults to HLE.(**EVEN** the actually needed BIOSes exit)

change HLE to auto works.

Use BIOS [pcsx_rearmed_bios] (**auto**|HLE)
