### ISSUE TITLE
Audio Fading Broken in Some Games

### ISSUE THREAD

**Issue by jeffkrull** [libretro/pcsx_rearmed#450]
In at least two games I've tested, Mega Man X3 (Europe) and Castlevania: Symphony of the Night (USA) (both Redump verified), in parts of the game where music is supposed to fade in/out, the effect is broken and sound just cuts out or in. 

- In Castlevania, this can be heard when you enter hallways that travel between areas of the castle. The sound is supposed to fade out as you enter the hallway, and the new track begins when you leave the hallway. Instead, the music just cuts out abruptly.
- In Mega Man X3, the stage music is supposed to fade out when you enter boss rooms, and after certain cutscenes. For example, Mac capturing X in the intro stage. The stage music is supposed to fade out, and then Zero's theme begins. Instead, the music just cuts out abruptly. There are similar problems with the music starting on the title screen.

I'm not sure how long this issue has been present, and I'm not sure if this is an upstream issue, though I can't find reference to it anywhere. I suspect this is a general problem, or at least one that affects multiple other games, but I have no way of knowing for sure. This issue was discovered in RetroPie, and I've confirmed it on both a Pi 3 B+ and Pi 4. I've tested this in Mednafen (through OpenEmu on Mac) and the problem is not present there. I've tried both BIN/CUE and CHD formats for both games, and the problem exists in both.

**Comment by gameblabla** [comment]
This sounds a lot like issues i had with CDDA music before my PR https://github.com/libretro/pcsx_rearmed/pull/552 greatly fixed those as currently, the CDDA Music code adds quite a bit of delay that's noticeable.

**Comment by notaz** [comment]
Is this still an issue? I could not notice anything wrong with Castlevania's transitions.

**Comment by jeffkrull** [comment]
I retested and I no longer see an issue with this.
