### ISSUE TITLE
[Feature Request] Have a crosshair on-screen when "guncon" is selected as controller.

### ISSUE THREAD

**Issue by bslenul** [libretro/pcsx_rearmed#452]
Hey!

At the moment if you want to play gun games (I mean Time Crisis, Point Blank series, etc.) using a mouse, you need your mouse cursor to be visible (which can be an issue on some platforms) or else you'll have no idea where you're aiming. So it would be really nice to have core option to show/hide a crosshair on-screen when you have "guncon" selected as controller :)

**Comment by capitaineflam25** [comment]
It would also help gun calibration when using an USB Mayflash Dolphinbar.

**Comment by bslenul** [comment]
I opened a similar issue on the RetroArch repo few months back, so it could benefit other cores as well: https://github.com/libretro/RetroArch/issues/12736

**Comment by Kelvfimer** [comment]
It would be great having crosshair.i requested too on the retroarch feature request.

**Comment by StormedBubbles** [comment]
Hello, the above pull request adds optional crosshairs and will be usable if/when those changes are accepted.

**Comment by bslenul** [comment]
Tested a bit and it seems to work great, thank you so much for this! ❤️
