### ISSUE TITLE
support for .CD1/CD2 file extension clarifications?

### ISSUE THREAD

**Issue by negativeExponent** [libretro/pcsx_rearmed#455]
why the need to hide the .cue files of a multidisk .m3u when you will still see the .bin/.iso/.img of the original cue sheet?

if you need to not see any of the disks in the m3u file, then its better to separate the multidisk games cue sheet or even chd and the m3u from each other using different folders and reference the actual game disks using relative paths (im not sure if absolute paths work, but it should technically)

I would prefer using standard, known file extensions than something of a workaround.

```
[INFO] [CORE]: Using content: /mnt/data/emulator/psx/ChronoCross/Chrono Cross (USA)-cdX.m3u.
...
[libretro INFO] switching to disk 1: "/mnt/data/emulator/psx/ChronoCross/Chrono Cross (USA) (Disc 2).cd2" #0
[libretro INFO] Loaded CD Image: /mnt/data/emulator/psx/ChronoCross/Chrono Cross (USA) (Disc 2).cd2[+cue].
[libretro INFO] Track 01 (DATA) - Start 00:02:00, Length 70:05:15
[INFO] Setting disc in tray: 2/2 - Chrono Cross (USA) (Disc 2)
[INFO] Closed virtual disc tray.
...
[INFO] Ejected virtual disc tray.
[libretro INFO] switching to disk 0: "/mnt/data/emulator/psx/ChronoCross/Chrono Cross (USA) (Disc 1).cd1" #0
[libretro INFO] Loaded CD Image: /mnt/data/emulator/psx/ChronoCross/Chrono Cross (USA) (Disc 1).cd1[+cue].
[libretro INFO] Track 01 (DATA) - Start 00:02:00, Length 69:36:02
[INFO] Setting disc in tray: 1/2 - Chrono Cross (USA) (Disc 1)

```
commit: https://github.com/libretro/pcsx_rearmed/commit/03f41c38234fece3e1b4efefb9f4efb381e24b46

**Comment by cmitu** [comment]
> why the need to hide the .cue files of a multidisk .m3u when you will still see the .bin/.iso/.img of the original cue sheet?

Consider front-ends that use the file extensions to show/create the gamelist, it's beneficial have just 1 entry for a multi-disc game (using and `.m3u` list referencing `.cd1`/`.cd2` (renamed from .cue) ), while still allowing `.cue` for single disc games. `.bin` files can be ignored - they can be started using the `.cue`.
