### ISSUE TITLE
R4 - Ridge Racer Type 4: negcon doesn't work for racing

### ISSUE THREAD

**Issue by iax2RqPZbq** [libretro/pcsx_rearmed#469]
## Steps to reproduce

Try playing Ridge Racer 4 with controller set to `negcon`. You can use the menus, even edit controller configuration. But you can't race (turn/accelerate/brake).

I've noticed if you switch controller type from `dualshock` to `negcon` the car's lights flash red (as if the brakes are triggered) for a second.

I was hoping #468 would fix it; maybe it's something similar since the game also supports DualShock/vibration.

## Your device/OS/platform/architecture

Linux, pcsx_rearmed compiled from source, commit `2ead2fb`

**Comment by negativeExponent** [comment]
negcon buttons (at least I and II and R2) are suppose to be analog types. Negcon code in pcsx is just the same as the dualshock or analog pad other than the PadID, so its incomplete and R4 does not like it.

what is you current gamepad? coz without a proper negcon-like controller with analogue buttons it would just not be the same. the analog buttons can probably emulated to use R2/L2 triggers or even on one of the analog sticks. dunno, i never had used negcon during the ps1 days.

if someone has suggestion or can send PR the better


thanks for the report.

**Comment by negativeExponent** [comment]
UPDATE:

ok found the problem. will get fixed on next update...

thanks for reporting.

**Comment by iax2RqPZbq** [comment]
You amazing person @negativeExponent!

**Comment by negativeExponent** [comment]
pushed fix. if you are able to compile yourself, then you can try it immediately.

**Comment by iax2RqPZbq** [comment]
Yep, tried your branch and it works fine. Amazing, thank you @negativeExponent!
