### ISSUE TITLE
(Bug) Pause Menu doesn't show texts on CRASH BASH (PAL)

### ISSUE THREAD

**Issue by toniosj** [libretro/pcsx_rearmed#478]
## Description

When you pause the game, pause menu texts are not displayed.

## Steps to reproduce

Start a game. 
When you are inside a mini game, press START.

## When did the behavior start?

It has never worked well.

## Your device/OS/platform/architecture

Windows 10 x64. Retroarch 1.9.0

## Screenshots 

PCSX Rearmed Core
![Crash Bash (Europe) (En,Fr,De,Es,It)-201122-210326](https://user-images.githubusercontent.com/20826760/99915906-f3e72e80-2d06-11eb-97c6-0f8b278110f3.png)

It should appear like this.
![8cszu4n2fukz](https://user-images.githubusercontent.com/20826760/99916003-9acbca80-2d07-11eb-89e0-a45d916f3fb7.png)

**Comment by toniosj** [comment]
Tested on last version, and problem still continues.

**Comment by alonsocr23** [comment]
The same thing happens to me too :(

**Comment by digitalLumberjack** [comment]
Hello, we are having the same issue on Recalbox :+1:

**Comment by toniosj** [comment]
Fixed on last version!
