### ISSUE TITLE
[RPI2] Analog controls not working for multiplayer games

### ISSUE THREAD

**Issue by leomontenegro6** [libretro/pcsx_rearmed#48]
I'm trying to play some games with analog controls using two PS2 controllers connected through a USB adapter. When I change Pad Type from 'standard' to 'analog' on controller 1, games such as Crash Bandicoot 3 and Legacy of Kain works fine on analog controls.

However, it works only for single player games. When I change Pad Type from 'standard' to 'analog' for two controllers, I'm getting a bug that the first controller is controlling both players, making it unplayable on multiplayer. It happened on games such as Moto Racer, Gran Turismo, Need For Speed 3, Quake 2 and Spec Ops Ranger Elite.

The workaround I'm using is changing Pad Type back to 'standard' on one of the players, since that solves the bug at the price of disallowing use of analog for multiplayer games. In other words: on Gran Turismo, only one of the players can use analog controls.

Summary: Analog controls are working only for single player games, not multiplayer ones.

I'm using latest version of PCSX Rearmed from source, compiled last week on my Raspberry Pi 2 (I updated the emulator core from source when I discovered someone implemented multitap support), running RetroArch 1.3.4 inside RetroPie 3.2. However, the same bug happened on the previous PCSX-Rearmed version, before I update it from source, so I'm guessing it's a bug from the emulator since then.

**Comment by dankcushions** [comment]
@alexis-puska is looking into this code to stop a different issue, so maybe he has an idea.

**Comment by alexis-puska** [comment]
I'm at the office, the analog pad has some latency in your version ? I fix the latency bug. some old code is used when an analog pad is declared in config file. When i'm go home I will test to reproduce your bug. But it's weird when i make some test with my girlfriend with 2 analog pad, i have no problem with the latency fix. i have some work on the pad, all psx request has not implemented and the analog pad is not correctly declared for the psx (very basic dualshock protocole implementation is make).

**Comment by leomontenegro6** [comment]
No latency problems here on analog games. All games I tested worked fine on both analog sticks. Even on Quake 2, that uses one analog to walk and other to aim, I got no lag on them.

The same happened on racing games, such as Moto Racer and Gran Turismo. Working fine, since I'm playing on solo.

**Comment by alexis-puska** [comment]
What is your platefrom ? Raspberry pi ?

**Comment by leomontenegro6** [comment]
Yes, Raspberry Pi 2, with Retropie 3.2.

**Comment by alexis-puska** [comment]
I fix this issue in my last commit. The open pull request add refactor of code for gamepad, fix this issue, add rumble features with compatible pad (test with PlayStation 3)

**Comment by leomontenegro6** [comment]
Thanks for the fix. I really appreciate this. \o/

Yesterday I tested PCSX-Rearmed on my RPI2, and confirmed that analog is now working for player 2, 3 and 4.

Games I tested: Moto Racer, Gran Turismo, Quake 2 and Spec Ops Ranger Elite. In Quake 2 specifically, I tested 4-player deathmatch, with analog combined, and all controllers worked like a charm.

In the weekend, I'll see if I can test another games, such as Need for Speed 3, Crash Team Racing, Crash Bash and Poy Poy.

**Comment by alexis-puska** [comment]
No problem, i always used the controller for pcsx_rearmed in standard mode (no analog sticks since 1 month, xin mo card with arcade stick wired on it), i modified the code to implement the multitap, i have broke something, i don't know if it was my dev, but now this was fix. Thank's for your test. 
PS : if you have a PS3 controler with the PS3 bluetooth driver installed (driver installed in retropie menu, if you use retropie), if you have no multitap configured, you may have rumble if you are in analog mode.
