### ISSUE TITLE
Touch screen doesn't work

### ISSUE THREAD

**Issue by Adnan1091** [libretro/pcsx_rearmed#481]
Pcsx doesn't recognize touch buttons.Tested with xiaomi redmi s2 using latest nighty core and stable retroarch.

**Comment by Cee123** [comment]
It doesn't work with the controller or keyboard either. Not sure what's going on with this latest version.

**Comment by Adnan1091** [comment]
Seriously?Someone opened one more issue about this and i had to wait for others to have this issue?

**Comment by Adnan1091** [comment]
#484
