### ISSUE TITLE
Controls no longer work on PCSX Rearmed for PC.

### ISSUE THREAD

**Issue by Cee123** [libretro/pcsx_rearmed#484]
## Description

Keyboard controls and even using a controller no longer work on PCSX Rearmed. So far, I've only tested the PC version, so I'm not sure if it's the same on other systems as well. Pressing buttons during games no longer does anything. 

## Steps to reproduce

Use the RetroArch online updater or core downloader, and update the core for PCSX Rearmed.

## When did the behavior start?

It happened right after I updated it.

## Your device/OS/platform/architecture

Windows 10 professional. I've tried on two different PCs now with very different specifications, and it's exactly the same on both.

**Comment by hizzlekizzle** [comment]
Change the core's multitap setting from 'auto' to 'disabled'

**Comment by Cee123** [comment]
> Change the core's multitap setting from 'auto' to 'disabled'

Thanks! Took me a while to find as i wasnt sure where that option was but i just found it under Quick Settings > Options. I turned off multitap 1 and multitap 2 and saved the config, reloaded the game, and it was still exactly the same unfortunately. Controls still wont respond.

**Comment by Cee123** [comment]
Aha! Fixed it! I turned off multitap 1 & 2, BUT I also had to switch from Dual Shock to Standard under the controls. Doing just one or the other didn't work. I needed to do both for some reason.
