### ISSUE TITLE
[Nintendo Switch] PCSX ReARMed core doesn't load PSX games in CHD format

### ISSUE THREAD

**Issue by Shinkaiser** [libretro/pcsx_rearmed#485]
## Description

PCSX ReARMed core in Nintendo Switch doesn't load PSX games in CHD format
I tried in Windows and they work OK
I updated to the last core version directly from Retroarch by using **Update installed cores** option but no change is visible
Also I have the BIOS properly placed

## Steps to reproduce

1. Select **Load Core** in Retroarch main menu
2. Select **Sony - PCSX-ReARMed** core
3. Select **Load Content** in Retroarch main menu
4. Search a .chd file containing a PSX game or a .m3u playlist
5. Select **Actual core - Sony - PCSX-ReARMed**
6. The screen remains in black until I use HOME button and force its closure.

## When did the behavior start?

I don't know because it is the first time I tried

## Your device/OS/platform/architecture

RetroArch: 1.9.0 (last version)
Core: PCSX-ReARMed (r22 3aa64bb)
OS: Nintendo Switch Firmware: 11.0.0

**Comment by hizzlekizzle** [comment]
I believe this is a known issue with all of the statically-linked platforms, as the core's CHD library symbols clash with those of RetroArch's own CHD lib.

**Comment by JamieRosenberg** [comment]
All my PSX games are in CHD format and work fine in latest firmware/retroarch/atmosphere.
However, the lates core breaks it - it crashes on BIOS reads (reckon it is this and not to do with CHD) - an old core - available from the stable release (not download cores in the app) 1.9.0 - PCSX-ReARMed (r22 ddd39f2) works

**Comment by negativeExponent** [comment]
please try latest commit.

**Comment by notaz** [comment]
No response so assuming fixed.
