### ISSUE TITLE
[All platform] Xenogears inaccurate/distorted sound effects

### ISSUE THREAD

**Issue by jmaneyrol69** [libretro/pcsx_rearmed#490]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

## Description

Most of Xenogears sound effects (ambiance, gunshot, effects in the option screen, etc.) are inaccurate and distorted.
Music, XA and video audio are not affected.

## Steps to reproduce

Play the game :slightly_smiling_face: . Using dynarec or interpreter CPU emulation, and/or sound filter, does not change the result.

## When did the behavior start?

This has always been present since early PCSX and still present with its various forks (Reloaded, ReARMed, PCSX4ALL, libretro core).

## Your device/OS/platform/architecture

Android, Windows 10, Linux, x86_64, x86, ARM and ARM64

## Logs (enable file logging and set log levels to DEBUG for core and frontend)

Not sure whether logs would help: this looks more like a lack of accuracy in sound emulation.

## Others (save states and/or save files nearest to the affected area, compressed)

Mednafen and Duckstation cores are the only libretro cores that render Xenogears sound effects properly.

**Comment by gameblabla** [comment]
Does it still happen ? I know you said that only Duckstation and Mednafen fixed this but it would help to have sound samples along with it to compare.

**Comment by gameblabla** [comment]
I know FF7 is a problem game also when it comes to the SPU (even Mednafen doesn't get it quite right unfortunately : P).
Still have to try on Redux

**Comment by notaz** [comment]
Closing as per notaz/pcsx_rearmed#171
