### ISSUE TITLE
Libretro RetroArch: PCSX ReARMed crashing on Final Fantasy 7 - ios 9.35

### ISSUE THREAD

**Issue by afhenriques** [libretro/pcsx_rearmed#491]
## Description
Hi everyone. I am using latest RA (v 1.9.0, built on 17 Jan 2021) on an iPad mini with iOS 9.3.5. I am trying to run Final Fantasy VII but unfortunately it keeps randomly crashing on “scene changes”, i.e.
    when entering a battle, sometimes crash;
    when exiting a battle, sometimes crash;
    when changing from on scenario to another, sometimes crash.
I’m starting the game from the beginning and I can’t play for more than 2 minutes before a crash occours.
All bios present and recongized by RA (scph5500, scph5501, scph5502).
I think this must be something specific to the core I am using (the only one I have available: PCSX ReARMed (r22 d56340b - which I also the latest).

## Your device/OS/platform/architecture
iPad mini iOS 9.3.5

## Logs (enable file logging and set log levels to DEBUG for core and frontend)
I enabled the log to file in RA with “debug” sensitivity, they get created but with no content (0 bytes files) so I am completely lost.

**Comment by notaz** [comment]
The random ARM dynarec crashes are thought to be fixed. Feel free to reopen if it still crashes, preferably with an explanation how to quickly reproduce.
