### ISSUE TITLE
Jikkyou J.League 1999: Perfect Striker black screen after boot

### ISSUE THREAD

**Issue by provola1984** [libretro/pcsx_rearmed#492]
## Description

black screen After boot

## Steps to reproduce

Load bin+cue iso from any redump

## Your device/OS/platform/architecture

Raspberry PI 4 4GB with Retropie 4.7.1

**Comment by gameblabla** [comment]
I would suggest to try it again as i have fixed a goof amount of CDROM controller bugs.

**Comment by gameblabla** [comment]
Very intriguing, this gets a black screen like a lot of other games (such as most of the Simple 1500 games) and none of the PCSX forks are compatible either.
This is most likely a CDROM or DMA issue.

**Comment by notaz** [comment]
I can get ingame so assuming fixed.
