### ISSUE TITLE
CHD that works in RetroArch Plus (Android) fails in iPadOS

### ISSUE THREAD

**Issue by chinarut** [libretro/pcsx_rearmed#493]
## Description

Conversion of bin/cue into chd works in RetroArch Plus (Android) and fails in RetroArch v1.9.0 iOS for core pcsx_rearmed (r22 778ad9c)

conversion of bin/cue for 3 other cores (yabause, flycast, beetle SGX) do not have any issues loading CHDs in iOS.

## Steps to reproduce

prerequisites
- RetroArch (iPadOS 13.4, iPadPro (2018)) ([v1.9.0, downloaded from retroarch.com](https://buildbot.libretro.com/stable/1.9.0/apple/ios/RetroArch.ipa) and sideloaded using AltStore)
- RetroArch Plus (Android 11, Pixel 3a) (Git Version 3c06338)
- chdman from SDL MAME 0.226 (macOS 10.15.6, mac mini server 2010)
- single-disc (or first disc of multi-disc) PSX game cue/bin (disc.cue, disc.bin)

steps
1. chdman createcd -i disc.cue -o disc.chd
2. load content: disc.cue in RetroArch iOS
3. observe game starts
4. load content: disc.chd in RetroArch iOS
5. observe “Failed to Load Content”
6. load content: disc.chd in RetroArch Plus Android
7. observe game starts

## When did the behavior start?

as soon as I tried to leverage chd support instead of uncompressed cue/bin.
games load just fine using bin/cue.

## Your device/OS/platform/architecture
iPadPro (2018) 256GB LTE, iPadOS 13.4, RetroArch (v1.9.0, official) w PCSX-ReARMed (r22 778ad9c)

## Logs (enable file logging and set log levels to DEBUG for core and frontend)

_At the moment there are no logging docs available for iOS._  ([Generating Logs](https://docs.libretro.com/guides/generating-retroarch-logs/))

## Screenshots (if needed for visual confirmation)
![IMG_0803](https://user-images.githubusercontent.com/6845061/105925558-3a058a80-5ff5-11eb-9b88-f483046fc7c1.png)

## Others (save states and/or save files nearest to the affected area, compressed)

I’ve confirmed it is specific to this core as CHDs work in 3 other cores (on iOS):
1. Yabause (Saturn)
2. Flycast (Dreamcast)
3. Beetle SGX (PC Engine CD)

**Comment by notaz** [comment]
No response so assuming fixed, reopen if not.
