### ISSUE TITLE
[iOS 5.1.1] Loading core ReARMed does not allow unloading app RetroArch

### ISSUE THREAD

**Issue by dagazik** [libretro/pcsx_rearmed#495]
I understand that iOS5 is not the target platform, but all of maybe the solution will be simple. In addition, it is possible that this bug affects relatively new 32-bit versions ios(but differently: something like random app crashes).

## Description
Loading core ReARMed does not allow unloading app RetroArch(Snes9x, PicoDrive, FBNeo - no such problem). This leads to many inconveniences: one of which is the inability to load from the save snapshot.

## Steps to reproduce
Load the any ReARMed core after 2016 year(b715d67, d56340b, 15cfb55): and try: close application, put the device to sleep, restart the game, or boot from the save snapshot. 

My test results:
- if try close the application in the multitasking panel, then reopening it will cause iOS to freeze.
- if try close the application in the terminal with command `killall - 9 RetroArch`, then it will cause iOS to freeze. Wherein cmd 'top' command will show that app process is in fact in RAM.
- if put the device into sleep state, then wake up it will cause iOS to freeze.

The only way to complete the process is to hold down the "Home" and "Power" buttons to power off the board in hardware.

Whether use i version "dynarec" or version "interpreter" - the behavior remains the same.

RetroArch 1.9.0 for ios5(Cydia Repo): http://johan.margueritte.free.fr/repo 

## When did the behavior start?
With versions of core ReARMed before 2016 the app no such problem.

## Your device/OS/platform/architecture
iPad1Gen, SoC A4, 256Mb RAM, IOS5.1.1 + RetroArch 1.9.0 + ReARMed different years of make(built with support ios5 from Weedy_Weed_Smoker). 

## Logs
Log file and Crash Report, unfortunately, are not created :(

## Demo Video
Video in YouTube(freezes at the moment of loading the save): https://www.youtube.com/watch?v=W3yJ9tax5-8

**Comment by dagazik** [comment]
I have compiled several dozen versions to pinpoint the commit: d148d26

At this moment, dyneric starts working on the iOS 5.1.1, but at the same time the application stops unloading from the RAM and any failure causes the entire system to freeze!!!

The code that is responsible for this is in the frontend/libretro.c file, commented as: "magic sauce to make the dynarec work on iOS". After removing this code, the application can be unloaded from RAM.

**Comment by dagazik** [comment]
It's also worth noting that this fixed some issues, but didn't fix the loading from snapshot issue. :)

**Comment by negativeExponent** [comment]
probably leave it open until a real fix is applied and merge.

sadly, i dont think there is an active ios maintainer.

**Comment by dagazik** [comment]
I have no way to check for sure, but I do not think that the problem persists on more recent versions of iOS. Perhaps there it really helps the work(as written in notaz comment), but on iOS 5.1.1 it creates a problem.

I jast wanted to use my old iPad from 2010 because it is dear to me and emulation is a good use for it. :) However, a lot of people use it vryatly. 

Removing this code on iOS 5.1.1 allows you to deliberately exit the application or, in case of an error, enable it to crash without freezing the entire system!
