### ISSUE TITLE
Can't get core to run in RetroArch (Raspberry Pi 2 / OpenELEC)

### ISSUE THREAD

**Issue by chewvodka** [libretro/pcsx_rearmed#50]
When I try to load a game in PCSX_ReARMed under RetroArch, the core fails to load and crashes RetroArch.  The error I'm getting is:

RetroArch [INFO] :: Loading dynamic libretro core from: "/storage/.config/retroarch/cores/pcsx_rearmed_libretro.so"
RetroArch [ERROR] :: Failed to open libretro core: "/storage/.config/retroarch/cores/pcsx_rearmed_libretro.so"
RetroArch [ERROR] :: Error(s): /storage/.config/retroarch/cores/pcsx_rearmed_libretro.so: undefined symbol: gteNCLIP_arm
RetroArch [ERROR] :: Fatal error received in: "load_dynamic()"

I've post the issue over at RetroArch's [GitHub](https://github.com/libretro/RetroArch/issues/3196) but they seem to think the problem is with the core itself and suggested I look here for a solution.  The problem apparently comes from BuildBot.  Whenever a nightly build of the core is released, BuildBot creates the binary that RetroArch grabs through it's built-in "Online Updater".  What some Google [searching](https://www.google.com/search?q=undefined+symbol%3A+gteNCLIP_arm&ie=utf-8&oe=utf-8) has revealed is that the core is being compiled without the specific ARM flags in place.  I wouldn't mind compiling this on my own if I knew how.  The trouble is, I'm running OpenELEC for Kodi (retro gaming is a side bonus) and there don't seem to be any tools included to let you compile.  In fact, you can't even apt-get or anything to download stuff.  Everything has to be done through Kodi.  When I'm outside Kodi and running RetroArch, the only thing I have available to me is to use the Online Updater, or to send a precompiled .so file over through SFTP.

**Comment by notaz** [comment]
Pushed something, but it's hard to tell if it will help as RetroArch BuildBot doesn't show what arguments and environment it uses when it calls make.

**Comment by chewvodka** [comment]
I have a working copy now.  I had to reinstall the GameStarter Kodi addon I was using to launch RetroArch.  The precompiled version that author includes is working.

So what I think happened is his copy always worked, but I went through and did the Online Updater inside RetroArch on everything to make sure I have the latest versions.  Ever since then, I couldn't get a proper compiled to run.  One version I found online required dependencies that OpenELEC didn't have.  Another one was looking for a settings file that somehow was locked and I couldn't tell RetroArch where to find the substituted one.  Anyway, I did a bunch of Google searching and found a few people had reported this issue as well, but the solution was always the same: "Compile your own version".  Since I'm using OpenELEC, there are no compile options, and I'm stuck using the binaries that Buildbot creates.

Since everything is working on my end, I will experiment this for you.  I'll backup my SD card, then try to run the Online Updater and see if it borks it or not.  If it helps, somebody over at Libretro's [GitHub](https://github.com/libretro/RetroArch/issues/3196#issuecomment-231133781) suggested the Makefile.libretro needs looked at.  I really don't know anything about this stuff.. so I'm just passing it along!  I'll report back my findings.

**Comment by chewvodka** [comment]
Ok, so I made a backup.  I then went in through SFTP and renamed the working "pcsx_rearmed_libretro.so" to "pcsx_rearmed_libretro.so - working".  I then tried to load a game I know works, and it crashed (unknown file, etc because it couldn't find the core).  I then ran the Online Updater, which downloaded and extracted "Version: 1.3.4, Git: c7e93af".  I then tried to run the same game again, and it still crashes..:

RetroArch [INFO] :: Version: 1.3.4
RetroArch [INFO] :: Git: c7e93af
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [CPUID]: Features:
RetroArch [INFO] :: Config: loading core-specific config from: /storage/.config/retroarch/config/pcsx_rearmed_libretro.so.cfg.
RetroArch [INFO] :: Loading dynamic libretro core from: "/storage/.config/retroarch/cores/pcsx_rearmed_libretro.so"
RetroArch [ERROR] :: Failed to open libretro core: "/storage/.config/retroarch/cores/pcsx_rearmed_libretro.so"
RetroArch [ERROR] :: Error(s): /storage/.config/retroarch/cores/pcsx_rearmed_libretro.so: undefined symbol: gteNCLIP_arm
RetroArch [ERROR] :: Fatal error received in: "load_dynamic()"
RetroArch [ERROR] :: Failed to start audio driver. Will continue without audio.
RetroArch [INFO] :: Saving config at path: "/storage/.config/retroarch/config/pcsx_rearmed_libretro.so.cfg"
RetroArch [INFO] :: Saved new config to "/storage/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

So it's still failing at that "undefined symbol: gteNCLIP_arm".

**Comment by notaz** [comment]
OpenELEC builds are reportedly working by now.
