### ISSUE TITLE
Gran turismo 2 bug (android)

### ISSUE THREAD

**Issue by nick13444** [libretro/pcsx_rearmed#501]
The game breaks when the car collides with the edges.

[Gran turismo bug video](https://youtu.be/HtWHrkQU_Yo)

**Comment by negativeExponent** [comment]
issue templates are there for a reason. The very least, at least provide the specifc device(x32,x64 etc), bios file used, logs etc.

**Comment by gameblabla** [comment]
Video is not available anymore and the bug report is scarce on details. Feel free to try it again as i've merged a couple of fixes since then but for now, i'm closing this.
