### ISSUE TITLE
Grandia (USA) [SCUS] - right side of the screen constantly flickers

### ISSUE THREAD

**Issue by slacknk** [libretro/pcsx_rearmed#504]
Please, fix it https://www.reddit.com/r/RetroArch/comments/etxwg7/its_harder_to_pick_up_on_camera_but_the_right/
> It's harder to pick up on camera, but the right side of the screen constantly flickers in Grandia. Using latest RetroArch Switch nightly + PCSX ReARMed

On Linx64 yet: Blinking right-corner vertical line in menu, gameplay. RetroArch-1.9.0-x86_64. Tried with HLE bios and without - too, test on `video_driver = "glcore"` with
* notaz/pcsx_rearmed: `r22.101_1105_git20200704.fbf19ce`
* libretro/pcsx_rearmed:` r22.1182_1819_git20210221.e3e1b86`

Window: [![](https://i.postimg.cc/XBK1xj2Q/screen-210224-012809.png)](https://postimg.cc/XBK1xj2Q) Fullscreen: [![](https://i.postimg.cc/MnRTZgFq/screen-210224-041357.png)](https://postimg.cc/MnRTZgFq)

```
pcsx_rearmed_async_cd = "precache"
pcsx_rearmed_dithering = "disabled"
pcsx_rearmed_drc = "disabled"
pcsx_rearmed_duping_enable = "disabled"
pcsx_rearmed_gpu_peops_old_frame_skip = "disabled"
pcsx_rearmed_memcard2 = "enabled"
pcsx_rearmed_multitap1 = "disabled"
pcsx_rearmed_multitap2 = "disabled"
pcsx_rearmed_nocdaudio = "disabled"
pcsx_rearmed_noxadecoding = "enabled"
pcsx_rearmed_pad1type = "standard"
pcsx_rearmed_show_gpu_peops_settings = "enabled"
pcsx_rearmed_spu_interpolation = "off"
pcsx_rearmed_spu_reverb = "disabled"
```

(Maybe help, I'm tried `libretro_beetle-psx-20201002.2446_07bc4eec_0.9.44.1-x86_64` - works fine without right side flickers/blinking right-corner vertical line)

**Comment by negativeExponent** [comment]
overscan, which is normal. your link already suggested a solution, which is either use overlay or use shader that reduces horizontal pix

**Comment by slacknk** [comment]
Ok, but why  is not in `beetle-psx` overscan, without overlay and use shaders?

**Comment by notaz** [comment]
Closing as per #712.
