### ISSUE TITLE
[PS Vita] Mega Man Legends Audio cutoff

### ISSUE THREAD

**Issue by Plasmap0wer** [libretro/pcsx_rearmed#505]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

## Description

The start of the voice lines gets cut off whenever they're played in game. This doesn't occur when using the PS1 emulator built into the Vita.

## Steps to reproduce

Just start up the game and get to the first part where Roll stops you and lectures you. The lines sound off when they're cut off at the beginning.

## When did the behavior start?

It was like this when I first started the game on the emulator.

## Your device/OS/platform/architecture

PS Vita

## Others (save states and/or save files nearest to the affected area, compressed)

[Mega Man Legends (USA) (Track 1).zip](https://github.com/libretro/pcsx_rearmed/files/6052190/Mega.Man.Legends.USA.Track.1.zip)

**Comment by gameblabla** [comment]
I believe this should be fixed as of https://github.com/libretro/pcsx_rearmed/commit/068a6133171b026956bbfd91e9bf4666def8823d but this game is known to be a pain to properly emulate...

**Comment by notaz** [comment]
This seems to be fixed now.
