### ISSUE TITLE
No multitap support on pi for Twisted Metal III/4 or NFL GameDay 2000

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/pcsx_rearmed#510]
Issue occurs with Pi 3B running RetroPie Version 4.7.1 using lr-PCSX-ReARMed 1.8.8.

Twisted Metal III and 4 (USA versions) are supposed to support 4 players via one multitap. I believe the multitap is supposed to be plugged into port 2. If multitap 1 is enabled at all, no controllers work in game. If multitap 1 is disabled and multitap 2 is enabled (with controller ports 1-4 set to "standard"), user 1 can control player 1, but no other controllers work. When the multitap is used (in port 2) on a real PlayStation, I think the game expects an empty port 1 (no controller OR memory card) and all four controllers as well as any memory card(s) to be in the multitap. However, I haven't found a way to completely replicate this setup on lr-PCSX-ReARMed 1.8.8 on a Pi 3B. My understanding (based on how other games behave) is that the equivalent would be port 1 set to "none" and ports 2-5 set to "standard" for controllers (which is possible) and no memory card 1. There is an option to toggle memory card 2, but card 1 seems to always be there. This leads to my two questions:

**1. Does setting a controller to "none" force the emulator to ignore that port entirely?**
**2. Is there a way to disable the memory card that gets auto-generated with gamename.srm?**

NFL GameDay 2000 (USA) confuses me further. It is supposed to allow up to 8 players via two multitaps, but no combination of multitap 1 and/or 2 works. It seems that any connected controller can skip the opening cinematics, but none of them is able to do anything after that. I am at a complete loss on this one.

I tried various BIOS and game versions. The issues I brought up with the Twisted Metal games are my best guesses at the issues, but I have no clue what is going on with NFL GameDay 2000. Any help would be greatly appreciated!

**Comment by negativeExponent** [comment]
lr-PCSX-ReARMed 1.8.8.??? whats that version number suppose to be? which commit?

in any case you probably need to reset/restart core once you have changed multitap options and set the controller types on each input (probably only standard controller type works.

refer to this guide as well as which player port is which once multitaps are enabled https://docs.libretro.com/library/pcsx_rearmed/#multitap

**Comment by StormedBubbles** [comment]
Hello! Thank you for your kind response!

I grabbed the "1.8.8" from the RetroArch Quick Menu -> Information. It says "1.8.8 - PCSX-ReARMed (r22 e3e1b86)." Sorry for causing any confusion.

The information in the link you posted was what I used to get the other multitap games working and agrees with the information I presented above. According to the link, Twisted Metal III and 4 should have User 1 = "none" and Users 2-5 = "standard," but that doesn't work.

I wasn't clear that I did indeed save changes and then quit and re-launch the games after making said changes. Bomberman: Party Edition is another game that requires the multitap to be in port 2, but that one works correctly with a similar setup (but it can keep User 1 = "standard" because it supports up to 5 players).

**Comment by negativeExponent** [comment]
this probably is a mis-information in wiki for such games and compatiblity(probably). TM3 says "waiting for other console", which probably means it uses ps1 link-cable instead of multi-tap (to avoid split-screen probably)

In anycase, mednafen, duckstation says the same waiting screen.

**Comment by StormedBubbles** [comment]
Thank you for following up!

TM3 does support the link cable, but it does also support the multitap. I believe the link mode even allowed up to 8 players across two linked consoles. 

When you select "New Game" from the main menu of TM3, you will see the "Linked Game?" menu with a Yes/No prompt. Selecting "Yes" will take you to that waiting screen, but selecting "No" will take you to another menu where you can select Tournament or Deathmatch. Tournament only allows up to 2 players, but Deathmatch will allow you to select up to 4 players when the second multitap is enabled.

No controllers work at all when multitap 1 is enabled. It is my understanding that this is actually how the real PlayStation worked for this game.

When multitap 2 is enabled (and multitap 1 disabled), User 1 can control the menu and acts as player 1, but no other players can do anything. I even tried setting one controller to control all 8 users (saving and exiting between attempts). There seems to be no obvious combination of active/inactive users 1-8 to make players 2-4 work. 

Following the instructions in the docs link you shared would mean disabling User 1 and setting Users 2-5 to Standard (i.e., port 1 empty and all four controllers plugged into the multitap in port 2), but that doesn't work. I tried other combinations just to see if anything worked by chance, but I have no logical explanation for other combinations.

**Comment by negativeExponent** [comment]
thanks for the reply. I'll admit, i did just a quick test, and totally forgot about a 2 player mode or 4 player deathmatch. a normal 2 player game works. but not multitap. Pcsx had always had input compability on some games. I have fixed a few, but i did not add the multiplayer mode for the core, so no promises here (atm).

**Comment by negativeExponent** [comment]
UPDATE:

i had no luck... yet with this. i can only make TMIII detect when an input is plugged or unplugged. BUT i cannot make any inputs works. Interestingly, Quake II which supports  multitap from port 2 only works fine.

**Comment by bslenul** [comment]
> refer to this guide as well as which player port is which once multitaps are enabled https://docs.libretro.com/library/pcsx_rearmed/#multitap

I'm a bit confused by this, I just tried with Crash Bash in 4 players mode (multitap in port 1 only) and Shaolin in 8 players mode (multitap in both ports), user 2 = player 2, user 3 = player 3, and so on... User 2 is not player 3, user 5 is not player 2, etc. like the doc says 🤔

**Comment by negativeExponent** [comment]
doc has been updated. but probably not merged yet. player assignments should be sequential

**Comment by bslenul** [comment]
Ah OK, didn't see your pending PR in the docs repo!

**Comment by StormedBubbles** [comment]
Thank you for looking further into this.

I found a list of games with special requirements for the multitap on actual hardware:

http://www.rlauncher.com/archive/index.php/t-4408.html

Down at the bottom of the first post, the following games are listed as requiring the multitap to be in port 2:

- Bomberman: Party Edition (up to 5 players if there's a controller in port 1)
- Jigsaw Madness
- S.C.A.R.S.
- South Park: Chef's Luv Shack

Twisted Metal III and 4 are not listed as having that requirement, so maybe it is supposed to work in port 1 for those games too.

P.S. Quake II allows both multitaps to be used so that all 4 players can use a mouse with a controller. I tested this out myself and got it working. Users 1-4 should be standard controllers, while users 5-8 should be set to mouse. You will have to adjust the mouse indices for each user to get multi-mouse to work. For me, the indices were 0, 2, 4, and 6. You also have to enable mouse use for each individual player from Quake II's options/controls menu within the game.

**Comment by negativeExponent** [comment]
> Thank you for looking further into this.
> 
> I found a list of games with special requirements for the multitap on actual hardware:
> 
> http://www.rlauncher.com/archive/index.php/t-4408.html
> 
> Down at the bottom of the first post, the following games are listed as requiring the multitap to be in port 2:
> 
> * Bomberman: Party Edition (up to 5 players if there's a controller in port 1)
> * Jigsaw Madness
> * S.C.A.R.S.
> * South Park: Chef's Luv Shack
> 
> Twisted Metal III and 4 are not listed as having that requirement, so maybe it is supposed to work in port 1 for those games too.
> 
> **EDIT: Bomberman: Party Edition and S.C.A.R.S. specifically mention in their instruction manuals to put the multitap in port 2. There is no mention of this in the Twisted Metal manuals. I am having difficulty finding manuals for the other games listed above.**
> 
> P.S. Quake II allows both multitaps to be used so that all 4 players can use a mouse with a controller. I tested this out myself and got it working. Users 1-4 should be standard controllers, while users 5-8 should be set to mouse. You will have to adjust the mouse indices for each user to get multi-mouse to work. For me, the indices were 0, 2, 4, and 6. You also have to enable mouse use for each individual player from Quake II's options/controls menu within the game.

i've never expected a mouse to be used in multitap, let alone in a controller+mouse configuration. Glad that it works (i'll have to make some small changes to mouse inputs then just to avoid some possible issues).

Thanks for the confirmation.

This leads me to think that TMIII issue might be more of a timing issue

**Comment by StormedBubbles** [comment]
Ah, timing could be an issue. I remember some game manuals stating rather specific instructions for the multitap. For example, Rampage Through Time (which works fine on my current build) states that a controller should be plugged into port A of the multitap BEFORE plugging the mulititap into port 1 of the PlayStation. It also states that further controllers should be plugged in sequentially.

There's nothing like that in the Twisted Metal manuals, but maybe some games don't like the timing of when the emulator activates the controllers. Without using the code you added in your PR, the best I could try to replicate "turning off the console and turning it back on with the controllers connected" was to wait for the controllers to activate and then restart the software from within the RetroArch menu. However, that didn't change anything. I am not at all familiar with running forks, but I'll help check things out once the request gets merged.

**Comment by StormedBubbles** [comment]
A few hours ago, I updated from RetroArch 1.8.8 to 1.9.4 and also updated this emulator from binary. I noticed the changes to the multitap options and adjusted accordingly. The games that worked before still work, and I am getting the same behavior from the games that had issues before. Are there any other settings I can change that are included in the recent updates that might affect this?

**Comment by negativeExponent** [comment]
no, no changes with regards on some multiplayer-related issues

**Comment by StormedBubbles** [comment]
Commit a11d0b9 fixed the issue with these games.
