### ISSUE TITLE
Wrong inputs on arm

### ISSUE THREAD

**Issue by kivutar** [libretro/pcsx_rearmed#518]
Tested in LudOS today. See https://github.com/libretro/LudOS/issues/21 for more info.

I was on a RPi3, with the core from the libretro buildbot, armv7 neon hf.

I was using the HLE BIOS on FFT.

**Comment by notaz** [comment]
This is/was unlikely a core issue since it works for me on RPi4 (and apparently for others, otherwise there would have been tons of bug reports).
