### ISSUE TITLE
(New 3DS) Rayman won't launch.

### ISSUE THREAD

**Issue by ClickPond** [libretro/pcsx_rearmed#521]
Upon trying to launch rayman (in chd format) the 3ds encounters an arm11 error and promptly shuts down.
This is caused after the 1.9.3 retroarch update.
![20210519_130340](https://user-images.githubusercontent.com/52369212/118861954-b53fc480-b8a2-11eb-89f3-eca75f911da4.jpg)

**Comment by gameblabla** [comment]
Tested Rayman on x86_64 and lightrec and it doesn't crash as of my latest changes.
Maybe i fixed it along the way or we are dealing with an ARM dynarec bug.

**Comment by bulzipke** [comment]
@gameblabla 
I tried to build with 3283ce2 and ran Rayman(chd). However, it seems that there is still a crash

**Comment by gameblabla** [comment]
Was fixed according to https://github.com/libretro/pcsx_rearmed/issues/534#issuecomment-932749017, the PR has been merged since then

**Comment by qamichele594** [comment]
I tried about 2 mins to load on PSX2PSP EBOOT Convertor.
