### ISSUE TITLE
Lightrec makes emulation slower on aarch64.

### ISSUE THREAD

**Issue by plaidman** [libretro/pcsx_rearmed#523]
## Description

Aarch64 support in lightning isn't working very well. When enabled on aarch64 lakka, it produces a speed loss.

## Steps to reproduce

Load the core on an aarch64 device, verify dynarec is enabled, then play a game.

## When did the behavior start?

I'm not sure, I haven't been able to find anybody who has tested lightrec with aarch64, so I am assuming that it has never given a speed gain.

## Your device/OS/platform/architecture

Switch Lakka Aarch64. Building with platform=arm64, and setting DYNAREC="lightrec"

**Comment by pcercuei** [comment]
Compared to the interpreter? If you compare to another dynarec then lightrec is probably a bit slower, yes.

**Comment by notaz** [comment]
Aarch64 support was added to ari64, so this should no longer be an issue.

**Comment by pcercuei** [comment]
Btw - Lightrec is slow on pcsx_rearmed because it exits after each block of code, instead of running for a given number of cycles, as (when I ported it, at least) pcsx_rearmed doesn't provide the info on how many cycles the CPU core should run.

With that fixed, Lightrec should be very fast too.

**Comment by notaz** [comment]
After the recent refactoring, the scheduler used for ari64's dynarec is always compiled and can be called. Calling `gen_interupt()` will update a global variable `next_interupt`, so `next_interupt - psxRegs.cycle` is the amount of cycles you can run. On write memhandler return `next_interupt` may also have changed and should be checked.

**Comment by pcercuei** [comment]
@notaz I'll take a look, thanks!
