### ISSUE TITLE
[PS Vita] Formula One '99 can't get to the main menu

### ISSUE THREAD

**Issue by Ale-G-95** [libretro/pcsx_rearmed#524]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

## Description

When I try to run Formula One '99 through PCSX-Rearmed core in RetroArch, it shows the first screens, in which there is the presentation of the software house. It goes on, showing the introductive video, and gets to the loading screen, where a car and 5 lights appear, with the lights turning on and getting coloured in red. After the last one is turned on and gets coloured, there is a black screen for a couple of seconds and then it crashes, going back to the LiveArea.

## Steps to reproduce

First I copy my game files (.ccd, .cue, .img, .sub, and the .sbi file required for LibCrypt) in my ROMS folder, then I open RetroArch, I load PCSX-Rearmed core (if not loaded) and I load the files I copied before. 

## When did the behavior start?

It started since I first copied the game's files.

## Your device/OS/platform/architecture

Playstation Vita

## Logs (enable file logging and set log levels to DEBUG for core and frontend)
[retroarch__2021_06_05__00_13_21.log](https://github.com/libretro/pcsx_rearmed/files/6601501/retroarch__2021_06_05__00_13_21.log)
[retroarch__2021_06_05__00_14_28.log](https://github.com/libretro/pcsx_rearmed/files/6601502/retroarch__2021_06_05__00_14_28.log)
[retroarch__2021_06_05__00_15_37.log](https://github.com/libretro/pcsx_rearmed/files/6601503/retroarch__2021_06_05__00_15_37.log)
[retroarch__2021_06_05__00_15_59.log](https://github.com/libretro/pcsx_rearmed/files/6601504/retroarch__2021_06_05__00_15_59.log)
[retroarch__2021_06_05__00_17_05.log](https://github.com/libretro/pcsx_rearmed/files/6601505/retroarch__2021_06_05__00_17_05.log)
[retroarch__2021_06_05__00_17_24.log](https://github.com/libretro/pcsx_rearmed/files/6601506/retroarch__2021_06_05__00_17_24.log)

**Comment by negativeExponent** [comment]
emulation bug. happens with or without dynarec, can sometimes cause to reboot back to bios logo, randomly stops after loading screen, or be able to show menu but cant go any further.

anyone on windows, can test out other pcsx-based standalone emus and see if issue are the same?>

**Comment by gameblabla** [comment]
My PR for icache emulation https://github.com/libretro/pcsx_rearmed/pull/545 should fix this game.
Unfortunately, it's likely that like F1 2001, it will only work properly on the interpreter and not lightrec.
Apparently someone will look into it to fix it.
As for the ARM dynarec, no one stepped up yet.

**Comment by gameblabla** [comment]
As of https://github.com/libretro/pcsx_rearmed/commit/7a8117168d6b9ad083757e013049c0e45734f3fb, this is now fixed in interpreter mode.
Lightrec/ARM dynarec are still broken however. Lightrec gets further before it crashes ingame so you will have to use interpreter for this one.

**Comment by notaz** [comment]
There is now a hack for the ARM dynarec, and other platforms can switch to the interpreter to play this game.

**Comment by pcercuei** [comment]
I think this is fixed in the master branch now.
