### ISSUE TITLE
Parasite Eve II freezes after training prologue [Switch]

### ISSUE THREAD

**Issue by jodilark** [libretro/pcsx_rearmed#525]
By turning on the PE fix in settings and starting a new game with disc 2,  then switching to disc 1 when prompted you can get past the opening scene to the gun range. After the gun range, the game freezes.

This same sort of thing happens on the playstation classic version, but you can remedy it by changing the clock speed to at least 70 though people say they turn it all the way up to 80 for best performance.

The switch retroarch version of pcsx-rearmed won't allow you to increase the clock speed that much. Is there any build of the switch version that will let you increase the clock speed that high?

I tried to compile my own version, but keep running into compilation errors in visual studio.

## Steps to reproduce
Load disc2 bin file for the rom.
Turn on PE 2 fix in pcsx-rearmed retroarch options.
Start a new game
switch to disc 1 bin file
User is able to get into the training part of the prologue.
Exit the training prologue.
Game freezes.

**Comment by negativeExponent** [comment]
- PE fix is for timing-related issue, not sure if its still even working (haven't tested the game and this fix ever), tried switching PE fix?
- clockspeed / overclock changes only works on arm/old dynarec builds. Switch i believe uses lightrec
- dito
- why would you use vc to compile?

**Comment by gameblabla** [comment]
It's well known. Seems to be an issue with the number of cycles. PCSX Revolution and PCSX4ALL fixed the issue and i intend on merging the former at some point.

**Comment by notaz** [comment]
Closing as per #395.
