### ISSUE TITLE
[Android 11] Crash on game load: mapping main RAM failed

### ISSUE THREAD

**Issue by ShadArt** [libretro/pcsx_rearmed#526]
## Description

When attempting to launch any PS1 game, RetroArch closes.

I tried launching games with and without BIOS files (JP, US, EU), all of which are named properly and have the proper checksum. I've also made sure all the bin and cue files have properly corresponding names. Reinstalling the core or reinstalling both the core and RetroArch doesn't do anything.

Funny enough, even though this doesn't regard ReARMed directly, I have also tested my games with other available cores: Beetle PSX HW and SwanStation. Beetle failed to launch content (I've added the log for Beetle too), while SwanStation launched without any issues.

I have also run the same images together with the same BIOS files on other devices (first gen Nvidia Shield TV and my desktop computer) with ReARMed before without any issues. However, I don't have access to the Shield TV right now, so I can't check if this behavior occurs on the latest version of the core on it.

The log for ReARMed says "mapping main RAM failed" without any additional information. Beetle PCSX HW reports "TOC first(99)/last(98) track numbers bad.", again, without any additional information.

Edit: I did try setting the pcsx_rearmed_drc parameter in the config file to "disabled", nothing changed other than the fact that now the core sees that there are overrides.

## Steps to reproduce

1. Install RetroArch for the first time.
2. Launch any game with the core.
3. Games work.
4. Time passes, possible device restart. 
5. Launch any game again.
6. RetroArch crashes.
7. Return to step 5.

I did not mess with any of the settings in RetroArch regarding the core, nor touched any configuration files. I also can't change them through the UI anymore since to access the core settings I actually need to load a game.

I'm not sure this issue is easily reproducible given all the unknowns when it comes to devices that run Android.

## When did the behavior start?

The behavior did not manifest immediately: after the first install of the core the games worked fine, however, after some time it just stopped working (by some time I mean about a day). Pretty sure this started occurring after I restarted my device. The initial install happened about 2-3 days ago, the issue manifested today.

The only game I tried while the emulator was working was Tekken 3 (US). Since it stopped working I tried Driver (US), Gran Turismo 2 (US) and Soul Blade (US), all of which give the exact same "mapping main RAM failed" error.

Edit: ~~Since 1.9.6 just came out and the issue timing kinda lines up, it could be the recent RetroArch update.~~ Nope. Tried the old version of RetroArch and it didn't affect anything.

## Your device/OS/platform/architecture
Asus ZenFone 8 Flip (Snapdragon 888) running Android 11 with the latest public version of RetroArch (1.9.6).

## Logs
PCSX ReARMed crash: https://pastebin.com/SMtB6tR7
Beetle PSX HW failing to load content: https://pastebin.com/4SpwdRm7

I have also tried to make an adb log with the ReARMed crash, however, I don't think it has any useful information: https://pastebin.com/Btf5sw1M

## Others
There is a single savestate I managed to create while the emulator worked is for the US version of Tekken 3, however, I'm not sure if it's of any use: https://drive.google.com/file/d/1hkEzSDAgRmYK0z0HzomC_exTY90DhjnI/view

**Comment by negativeExponent** [comment]
try disabling Dynarec

**Comment by ShadArt** [comment]
> 
> 
> try disabling Dynarec

Just saying that the setting is not accessible through the UI anymore since I can't load games, however, I did try setting pcsx_rearmed_drc in the config file to "disabled". The change had no effect. The behavior persists.

**Comment by Zzombiee2361** [comment]
Why did you close this? Is it working for you now?

**Comment by ShadArt** [comment]
> 
> 
> Why did you close this? Is it working for you now?

The cores suddenly started working after a firmware upgrade on my phone, so I assumed that was the issue.

**Comment by Zzombiee2361** [comment]
Unfortunately for me the cores stopped working as soon as I updated to android 11, and haven't worked again since. There's another system update after that, but still no luck.
