### ISSUE TITLE
[Android 9] Gran Turismo broken on RetroArch 32 with PCSX ReARMed Core (r22 31d1b18)

### ISSUE THREAD

**Issue by Eispfogel** [libretro/pcsx_rearmed#527]
#This tracker is for pcsx-rearmed-libretro issues *only*.

## Description

I updated RetroArch from 1.9.0 to 1.9.5(well i reinstalled and started from scratch).
The Problem now is, that Gran Turismo has graphical corruptions and is very slow. 

- I tried HLE Bios - No video
- Disabled Dynamic Recompiler - the corruption is gone but the game runs at a slow speed with sound issues.

This also happens on my Android phone which i sadly also updated to RetroArch 1.9.5. 

Other cores are fine, but slow(tried Beetle HW, Beetle, Swanstation and Duckstation).

Only disabling Dynarec helps.

## Steps to reproduce

Download RetroArch 32 Bit 1.9.5 and then the PSCX ReARMed Core (r22 31d1b18)

## When did the behavior start?

After Updating to RetroArch 1.9.5

## Your device/OS/platform/architecture

Lenovo Tab M10 with Android 9, Sony Experia 10, Xiaomi Redmi 7A

## Logs (enable file logging and set log levels to DEBUG for core and frontend)
Not applicable

## Others (save states and/or save files nearest to the affected area, compressed)
Not applicable

**Comment by notaz** [comment]
The ARM dynarec bugs are thought to be fixed. Feel free to reopen in case there are still issues, preferably with an explanation how to quickly reproduce.
