### ISSUE TITLE
Strange Strider 1 HLE freeze issue that only happens on the libretro frontend code

### ISSUE THREAD

**Issue by gameblabla** [libretro/pcsx_rearmed#546]
## Description

Strider (1) for the PS1 and PCSX Rearmed works fine, even with the HLE Bios.
It will even work if this libretro fork is modified to run as standalone with libpicofe.
However... if the game is run over libretro in HLE, it will freeze.
With the libretro frontend unlike the standalone version (or if this is compiled as standalone), it needs the BIOS for Strider 1.

This tells me that something is off about the libretro implementation of their frontend when it comes to initializing the HLE.
I noticed that unlike the upstream code, you are patching the HLE bios in retro_run to skip the BIOS stuff (because it doesn't exist in HLE). Removing it does not do anything regarding that.

## Steps to reproduce

Just run Strider 1 PS1 without a BIOS.

## When did the behavior start?

The game only got fixed with my HLE pull request : it also froze before that. So we can only say that it happened since then.

## Your device/OS/platform/architecture

Linux x86_64 (interpreter)

**Comment by notaz** [comment]
Works now. No surprise since most differences between forks have been eliminated.
