### ISSUE TITLE
Punky Skunk buggy BGM

### ISSUE THREAD

**Issue by eadmaster** [libretro/pcsx_rearmed#549]
## Description

While playing Punky Skunk the BGM does not play correctly in stages following the first one (it does not start or it loops after a few seconds). Verified with a good dump coming from redump.org, converted to CHD.

## Steps to reproduce

- boot the game
- select CONTINUE and load the attached memory card
- load the level "MUSHROOM ROMP"

## When did the behavior start?

After a few seconds of playing.

## Your device/OS/platform/architecture

test #1: Ubuntu 18.04.2 LTS, x86_64
test #2: Android 9, Amlogic S905X3

## Logs (enable file logging and set log levels to DEBUG for core and frontend)

(running with `retroarch --verbose` did not show any error on the console)

## Others (save states and/or save files nearest to the affected area, compressed)
[Punky Skunk (USA).srm.zip](https://github.com/libretro/pcsx_rearmed/files/7033323/Punky.Skunk.USA.srm.zip)

**Comment by gameblabla** [comment]
I couldn't reproduce it on my side (at least with a bin/cue build) on both the libretro core and the stock pcsx_rearmed.

**Comment by gameblabla** [comment]
It appears that this issue only affects the CHD related code, not the bin/cue format. In fact, the titlescreen has no music on the CHD version whereas bin/cue plays it as normal, which just points us towards the CHD format being to blame.

I thought that it was possibly a thread issue with the CDDA music code as well so i tested it with my PR https://github.com/libretro/pcsx_rearmed/pull/552 but it doesn't do anything different for this game.

**Comment by eadmaster** [comment]
Thank you for reporting this, so now i know a workaround... if it is a CHD-related bug there may be other games affected... btw guess libchdr itself it's fine because i've tested the very same chd file with the libretro-beetle-psx core and was working fine.

**Comment by ZacharyFoxx** [comment]
> Thank you for reporting this, so now i know a workaround.
> 
> If it is a CHD-related bug there may be other games affected. Btw I guess libchdr itself it's fine because i've tested the very same chd file with the libretro-beetle-psx core and was working fine.

Hi.

I can confirm this issue.

I tried the Rage Racer in the follow situations:

1 cue and 17 bin files (which match with redump's SH1 hashs);
1 cue and 1 bin file (the same 17 bin files combined); and
1 chd (created with the 1 cue and 17 bin files or 1 cue and 1 bin file).

Using cue and bin files the game works perfectly, in any situation. Using the chd versions I had the same problem in both situations: The music after choosing the car runs wrong. If you try to choose the soundtrack, the game plays a wrong track and only the final part of it. If you don't choose a soundtrack, the game won't play a song.

Games with one or two bin files, like Guilty Gear, work perfectly.

I test on 3 different machines:

My laptop running linux and using flatpak retroarch;
My OUYA console using retroarch download from the official website; and
My Raspberry Pie 4 with retropie in 4.8.

Retroarch in version 10.

**Comment by notaz** [comment]
Seems to be playing correctly now.
