### ISSUE TITLE
[New 3DS 1.9.8 Stable] Doom USA Crashes 

### ISSUE THREAD

**Issue by DragonautMk** [libretro/pcsx_rearmed#550]
Doom USA Just crashs on boot 

## Steps to reproduce

Just boot the game

## When did the behavior start?
I dont know

## Your device/OS/platform/architecture

N3DS

## Logs (enable file logging and set log levels to DEBUG for core and frontend)
Crash Dump: https://drive.google.com/file/d/1APUO6XXzh7ftB5GpsKXSo0i--osEorvV/view?usp=sharing

**Comment by bulzipke** [comment]
I'm curious. What is the extension of the game you played?
(cue, bin, chd, pbp, etc..)

**Comment by DragonautMk** [comment]
CHD

**Comment by gameblabla** [comment]
This would need someone to do some regression testing against the libretro pcsx rearmed core and see which commit exactly caused the issue otherwise we will have no idea what caused it.

**Comment by bulzipke** [comment]
@gameblabla 
Thank you for your hard work :)
This is the result of my test.

```
	    	MegamanX4	Rayman
c91c9a0		o		x
022a8aa		o		x
5d24686		o		x
6d10ad9		ctr build failed
f07738d		ctr build failed
b24e7fc		ctr build failed
b943502		ctr build failed
4ee722a		x		x
```

Megaman(chd) currently plays well.
Rayman(chd) used to run in the past (probably 1.9.3).

I tested it while building while changing HEADS.
But the moment I change to before 4ee722a, crash occurs in all games.
Is there anyone who can tell me what to add to change to the previous head?

**Comment by Syko7956** [comment]
Games with multiple tracks on CHD will guarantee crash. That's why some CHD games work and some don't.

**Comment by gameblabla** [comment]
https://github.com/libretro/pcsx_rearmed/issues/534 was fixed with my Kyuukentai CDDA PR so i wonder if this suffers from the same issue too. Most likely in my opinion.

**Comment by bulzipke** [comment]
I just ran Doom(chd) on N3DS with 1.9.11 Stable official build.
It runs without a crash :)

**Comment by gameblabla** [comment]
Good to know, i can close this then.
