### ISSUE TITLE
Night Raid Dynarec Graphic Glitches

### ISSUE THREAD

**Issue by KMFDManic** [libretro/pcsx_rearmed#556]
@gameblabla awesome commits you've been doing lately! I noticed you have been working in some Mednafen fixes.  Night Raid (great shmup, by the way!) is a special case scenario game, that works fine in Mednafen.  But, in PCSX, if dynarec is toggled on, all background graphics turn to black.  With it off, game displays fine, but too slow to be playable.  In Mednafen, game shows graphics absolutely fine, with dynarec enabled.  Hopefully, you have an idea of a potential fix that could be carried over from mednafen to pcsx.

**Comment by gameblabla** [comment]
Very likely to be an ARM dynarec issue if that's the case. I know that there are a few things that are wrong with it and i have talked to a few people about it but i wouldn't get my hopes up for dynarec-only issues for now... : /
Are you using lightrec or the ARM dynarec ?

**Comment by KMFDManic** [comment]
@gameblabla Unfortunately, for lower spec platforms, dynarec is the primary way to be able to run a game, such as Night Raid.  Johnny Bakookatone shares similar issue, with missing layers of graphics, with dynarec enabled.  I was hoping you had an idea of a potential fix for this.  Might as well simply be something inherent with using dynarec, which is definitely not as optimal for accuracy on a lot of games.  Thanks for your feedback and checking into things!  A few other games, in the past, I was able to pinpoint issues with, which got coding fixes added to this branch, such as Jedi Power Battles, NBA Live Games, Parasite Eve II, etc.

**Comment by KMFDManic** [comment]
@gameblabla For now, I am gonna close this issue, as I realize arm is the problem in this case.  Unless something comes along that truly helps fix up the countless inherent issues with using Arm Dynarec, some games are simply hit and miss as far as playability!  Thanks for all your recent crossover additions to PCSX ReArmed, however!  

I also typically do demonstrations and showcases of WIP and fixes on my YouTube.  This is where I have Night Raid, currently.  But, would love to add a proper ARM fix!  

https://www.youtube.com/watch?v=cdkyxfYYn10
