### ISSUE TITLE
Audio stutter with latest commit 65ead111f56d95a8099b7d996bd1c623219037de

### ISSUE THREAD

**Issue by christianhaitian** [libretro/pcsx_rearmed#557]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

## Description

On the RPI3 build, there's an audio stutter present now with this latest commit.  You can best hear it when playing Castlevania - Symphony of the Night.  When you first encounter Dracula in the beginning, you can clearly hear the stutter at the beginning of each characters speech.  The last commit that I tried where the audio was fine was cf71346b180ca485e67a43fc199232c51be9459b.  

## Steps to reproduce

Using a armhf build of the core with this commit, play Castlevania and just run straight to dracula, takes less than a minute, richter speaks fine but then every line after that has an initial stutter.

## When did the behavior start?

Some time after commit cf71346b180ca485e67a43fc199232c51be9459b.

## Your device/OS/platform/architecture

Odroid Go Advance
Ubuntu 19.10
RK3326
aarch64 and armhf

## Logs (enable file logging and set log levels to DEBUG for core and frontend)
See attached.
[retroarch.log](https://github.com/libretro/pcsx_rearmed/files/7157941/retroarch.log)

**Comment by gameblabla** [comment]
This would need further regression testing. That said, i have some CD improvements that should fix some CD related issues, which i believe is what you are actually suffering from.
There's also an issue with the CDDA code simply being borked, i will also address that in the Fantastic Pinball PR.

**Comment by gameblabla** [comment]
Possible suspects if it is indeed a regression is either
The Cdrom timings changes
https://github.com/libretro/pcsx_rearmed/commit/9601ca6d16dcef59d123539f5e2af07e504ac329
OR
The SPU fix for Diablo
https://github.com/libretro/pcsx_rearmed/commit/9601ca6d16dcef59d123539f5e2af07e504ac329

But i don't really have your hardware so i'm afraid that you will need to go through each commit and test them one by one until you find the culprit. (as i did for the warning commit that turned out to break games)

**Comment by dhwz** [comment]
I think @gameblabla linked to the wrong commit:
cdrom timing changes
https://github.com/libretro/pcsx_rearmed/commit/068a6133171b026956bbfd91e9bf4666def8823d

**Comment by TheRozitaKnight** [comment]
The culprit of this issue is commit 068a613. The previous commit (c54faa9) works without issues.

**Comment by gameblabla** [comment]
> The culprit of this issue is commit [068a613](https://github.com/libretro/pcsx_rearmed/commit/068a6133171b026956bbfd91e9bf4666def8823d). The previous commit ([c54faa9](https://github.com/libretro/pcsx_rearmed/commit/c54faa9105622e0d0dbf66651322610c96216501)) works without issues.

Thank you. This means i guess the delay is too high and causes audio drop.
Reverting this is out of question as it fixes a couple of other games but perhaps we could lower the delay a bit.

If someone wants to test, i have released a branch here :
https://github.com/libretro/pcsx_rearmed/commits/cdrom_audio_fix_attempt

And automated builds here :
https://git.libretro.com/libretro/pcsx_rearmed/-/pipelines/58475

**Comment by gameblabla** [comment]
Ok so, lowest CTR's intro works properly before it goes to shit is 12. However even at 12, there is still the noticeable delay in Castlevania. At 1 (the way it was), i could actually still hear some static noise and stutter before the speeches but Dracula's voice is OK after that.
I'm honestly don't think it's entirely related to that. That said, i also tried it in PCSX redux where they merged the patch and there's still the stutter before the speeches.

**Comment by TheRozitaKnight** [comment]
There's still some slight stuttering that wasn't present in c54faa9, but it's much better than before.

**Comment by gameblabla** [comment]
So clearly this does not entirely fix it and i'm sick right now... i'm thinking of either :
- Putting an ugly hack
- Revert the CD timings changes
- Do nothing and wait for a proper fix from Redux (could take forever)

**Comment by notaz** [comment]
I've reworked the code removing most of the hacks discussed here, and the games mentioned in commends still work for me. It should be possible to lift more accurate seek timings from more accurate emulators without side effects now, but I'm not sure it will help any actual games.

@gameblabla you mentioned you have a list of problematic games, could you check if they still work?
