### ISSUE TITLE
Rumble causes lag

### ISSUE THREAD

**Issue by bsos** [libretro/pcsx_rearmed#56]
When running on a RP3 with a Bluetooth PS3 controller, each time the controller activates rumble, the game lags. This is easy to see in Crash Team racing. Previous versions would turn rumble off when the core options had the controller set to standard, now it is present in standard or anolog.  It would be ideal if it could be active without lagging, however an option to turn off rumble would do the trick.

**Comment by bsos** [comment]
Getting a number of users on the retropie forumns having the same issue: https://retropie.org.uk/forum/topic/3028/disable-ps3-controller-rumble-lr-pcsx-rearmed/9

**Comment by pjft** [comment]
+1 here. Yet another thread about this.

https://retropie.org.uk/forum/topic/9360/psx-stuttering-in-some-3d-games/50

**Comment by notaz** [comment]
This sounds like a frontend issue, if turning on rumble is slow it should do it from another thread or something. Anyway this is very old so I'm going to assume it was fixed.
