### ISSUE TITLE
Star Wars Episode I: Jedi Power Battles Closing Alone

### ISSUE THREAD

**Issue by spielvan** [libretro/pcsx_rearmed#560]
Star Wars Episode I: Jedi Power Battles closing alone, right at the beginning of the first phase, he exits the game and closes the retroarch.

**Comment by KMFDManic** [comment]
https://github.com/libretro/pcsx_rearmed/issues/294

**Comment by gameblabla** [comment]
This should be fixed properly though, we can't expect everyone to change it on the fly like that.

**Comment by notaz** [comment]
The random ARM dynarec crashes are thought to be fixed. Feel free to reopen if it still crashes, preferably with an explanation how to quickly reproduce.
