### ISSUE TITLE
Input not working on keyboard in PCSX

### ISSUE THREAD

**Issue by kmccluretech** [libretro/pcsx_rearmed#565]
Description
I am having an issue playing psx games with my keyboard as an input source. I have mapped all of the keyboard keys to inputs and they work fine in other emulators just not any psx emulators. I have tried pcsx-rearmed, beetle, beetle hw and duckstation. I have confirmed multitap is set to "OFF" I have also tried setting controller type to "standard" "retropad with analog" and "dualshock". There is no option to set controller type to "keyboard." Same issue is not present in emulators for other systems. Content files are all .bin and .cue, happens with all games. Retroarch keyboard shortcuts still work.

Steps to reproduce
Seems to be happening regardless of how I try to load files or what configuration I set. I'm not sure how to un-reproduce the error.

When did the behavior start?
This started from my fresh install of retroarch.

Your device/OS/platform/architecture
ubuntu_21.04/x64

[retroarch__2021_10_05__14_37_30.log](https://github.com/libretro/pcsx_rearmed/files/7288430/retroarch__2021_10_05__14_37_30.log)

**Comment by gameblabla** [comment]
Does this happen with the other cores as well ?

**Comment by kmccluretech** [comment]
> Does this happen with the other cores as well ?

Initially I thought it did not happen in other cores because it was working in bsnes, When digging a little deeper it looks like my keyboard does not function as a gamepad in bsnes.

**Comment by gameblabla** [comment]
Then we can rule out a core-specific issue. This is (most) likely a retroarch issue or an issue on your side. Closing
