### ISSUE TITLE
[HLE] No sound effects in Herc's Adventures

### ISSUE THREAD

**Issue by Kekun** [libretro/pcsx_rearmed#57]
There is no sound effects in Herc's Adventures (US version) with the HLE BIOS, though music plays as intended.

**Comment by hooby3dfx** [comment]
looks like duplicate of https://github.com/libretro/pcsx_rearmed/issues/59

**Comment by negativeExponent** [comment]
for better compatibility, an official bios should be used

**Comment by gameblabla** [comment]
This probably got fixed with my newer HLE changes anyway although i would have to check this... (Digimon World still has missing sound on HLE despite my fixes)

**Comment by notaz** [comment]
Sound seems to work now.
