### ISSUE TITLE
Some games have a 'screen dimming' effect during certain actions

### ISSUE THREAD

**Issue by Dangerdash** [libretro/pcsx_rearmed#58]
Observed on the RPI 3 model B running RetroPie 4.0

when playing certain ps1 games with the pcsx-rearmed plugin, the screen dims during an action and stays dimmed until the screen refreshes into a different scene.

Most Noticeable while playing 'Metal Gear Solid' during the 'meet and die' cutscenes with the DARPA Chief and the President of ARMS Tech.

i re-loaded my saves prior to triggering and ran through the cutscenes multiple times to find what produces the error, but i can't really see anything other than the fact that the issue happens a few seconds before the person dies of a heart attack.

probably texture or graphics error? lighting?

**Comment by notaz** [comment]
Probably related to #40. Anyway it's likely to be fixed by now, if not please provide a savestate or instructions how to reproduce to someone who doesn't know the game well.
