### ISSUE TITLE
Crash on start on x86 with run_ahead_enabled

### ISSUE THREAD

**Issue by eadmaster** [libretro/pcsx_rearmed#580]
I've tested both the [latest build from buildbot](https://buildbot.libretro.com/nightly/linux/x86_64/latest/) and one compiled by me, they both crash on start with this error on my Linux x86 machine:
````
ERROR: Unable to recompile block at PC 0xb0004c00
Exiting at cycle 0x00ffdf72
````
(full verbose log:  [log.txt](https://github.com/libretro/pcsx_rearmed/files/7608402/log.txt) )

 I've tried resetting the core options and with other content,   the result was the same.

**Comment by eadmaster** [comment]
nevermind, i've just figured out this was due to the `run_ahead_enabled==true` in my default config. Setting to false solved the issue.

(not sure if it is the expected behavior though)

**Comment by hizzlekizzle** [comment]
i think dynarec issues with runahead are to be expected.

**Comment by eadmaster** [comment]
No problem, i will keep runahead off with this core.
