### ISSUE TITLE
[WIP] Add core options to adjust the volume of the various audio sources before they get mixed

### ISSUE THREAD

**Issue by eadmaster** [libretro/pcsx_rearmed#581]
[Full story here](https://eadmaster.altervista.org/wordpress/archives/90).

I'd like to add a core option to re-balance the CDDA vs the SPU audio output volumes before they get mixed.

If you can give me some pointers where this happens in the code , please post here.

**Comment by notaz** [comment]
There are lots of volume controlss in structs defined in `plugins/dfsound/externals.h` but they are meant to be controlled by the game.

Closing as nobody showed interest in this for almost 2 years.
