### ISSUE TITLE
[Nintendo Switch] Final Fantasy Tactics Poor Performance/Speed Issue (and Two Miscellaneous Issues)

### ISSUE THREAD

**Issue by ThisNekoGuy** [libretro/pcsx_rearmed#582]
## Description

In many parts of the game (including the new game prologue video, prologue exposition scene (the narrator scene), in-game cutscenes [conversations], and combat), the game has pretty bad performance/speed with largely noticeable frame dips and audio that stretches across these occurrences poorly.

Also, the new game video (with characters riding chocobos) had aggressively irratitc static around it?
(~~Maybe because I had the aspect ration set to 16:9?~~ I had frameskip set to 2 at the time, maybe that was it? I did disable that later, so the performance issues are still valid)

And I wasn't getting logged into Retro Achievements when the game start either :thinking: 

I recognize that, for the Switch, there's an overclock feature in RetroArch to assist with this but the "prolonged use of overclocking can damage your Switch" warning was alarming enough to me to steer way from it. :/

## Steps to reproduce

- All core settings were the default
- Both RetroArch (`1.9.13`) and PCSX ReARMed (`r22 589bd99`) were the latest versions
- The core information menu reads: `Permissions: dynarec`
- A US bios was used
- Aspect ratio was set to 16:9

Steps:
1. Ensure the bios is detected by RetroArch
2. Run the game from a playlist or directly (I did so from a playlist)
2b. If logged into Retro Achievements in RetroArch, you won't be logged in for the game at this point for some reason
3. Reach the main menu
3b. Optionally, for a "quick" demonstration, select "Tutorial" and select any tutorial and you'll notice a ~20-25 frame drop most of the time and the game speed slows down considerably
4. Start a new game and proceed until you reach the first battle (doesn't take too long to reach but it does have small exposition beforehand)

## When did the behavior start?

This is my first time using PCSX ReARMed and emulating the game, so I don't know when these issues were introduced.

## Your device/OS/platform/architecture

**Nintendo Switch**
- My Switch is an "old" model: `HAC-001`
- System firmware is: `13.2.0`
- [Atmosphere version is: `1.2.5`](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.2.5)
- [Hekate bootlader is version: `5.6.5`](https://github.com/CTCaer/hekate/releases/tag/v5.6.5)
- SD card is a 256 GB SanDisk, FAT32 formatted

## Logs (enable file logging and set log levels to DEBUG for core and frontend)

[DEBUG-Log-Level-Logs.zip](https://github.com/libretro/pcsx_rearmed/files/7652857/DEBUG-Log-Level-Logs.zip)

## Screenshots and videos (if needed for visual confirmation)

![FinalFantasyTactics_20211203_165347_00](https://user-images.githubusercontent.com/28468662/144685126-e10ecb83-75c1-4c3b-8def-8ae477bf8789.jpg)

![FinalFantasyTactics_20211203_163919_00](https://user-images.githubusercontent.com/28468662/144685084-cc3b3047-5a82-493a-aebb-a2289ddbdccd.jpg)

![FinalFantasyTactics_20211203_164146_00](https://user-images.githubusercontent.com/28468662/144685102-06868c7e-91ca-4f9a-be70-4f41023309b7.jpg)

**(I had to upload the video clips somewhere else because the file size was too large to upload directly, even if I used 7zip)**
[FinalFantasyTactics-ScreenshotsAndVideoClips.zip](https://mega.nz/file/JiRAjDQa#XEzRTIL6K_rE3eFjMpKJ_GEES3MQiVcaROJQCQJ3Rmw)

## Others (save states and/or save files nearest to the affected area, compressed)
[savestate.zip](https://github.com/libretro/pcsx_rearmed/files/7652917/savestate.zip)

**Comment by DerinQyu** [comment]
This issue should be closed, the game is working fine on my switch with latest nightly build.
