### ISSUE TITLE
R-Type Delta menu graphic glitches

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#584]
## Description
Graphical glitches in the menus. Sparkles of light and various glitches: in game graphic seems ok.

## Steps to reproduce
Just load the game: it starts just at the memory card loading screen, just play with the menu, a lot of strange "flashes" on screen.
It happens in unai an PeOpS plugin too. PeOpS is somehow worse.

## When did the behavior start?
From what I remember, always has been like this.

## Your device/OS/platform/architecture
Libretro core, RPi4, PS Classic, RG351V.

**Comment by notaz** [comment]
There is now "(GPU) Slow linked list processing" option to solve this. However I'm reluctant to enable it by default as it will make the emulator use more resources (and drain the battery faster) the whole time just to show this short boot screen correctly.

**Comment by CometHunter92** [comment]
Perfect!
