### ISSUE TITLE
Latest commit broke WipEout 3: Special Edition (and more glitches with new dynarec)

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#589]
Just enter a single race and somewhere, before the race ends a random crash will occur.
Screen freezes and audio get stuck in a loop. Unplayable.

Happens only after the latest commit (https://github.com/libretro/pcsx_rearmed/commit/12fc12797064599dfca2d44043d5c02a949711ef)

## Your device/OS/platform/architecture

RPi4, RG351V (arm32)

P.S: noticed that latest commit got rid of some issues like the polygons issue in CTR and the stutter at the start of a race in Gran Turismo

**Comment by CometHunter92** [comment]
P.S  Dino Crisis also has random freezes strange graphic glitches with the latest commit. In this case too https://github.com/libretro/pcsx_rearmed/commit/eeb8a52bd5407c5e595aad7983944b1f16b1bbf0 is ok, aside from notorious audio repetitions.

**Comment by notaz** [comment]
Tried there and could see no problems. Maybe you have some hack options enabled? It can also be caused by old savestates (various corruption can be transferred through savestates from older versions).

**Comment by CometHunter92** [comment]
I don't use savestates, however I just recompiled the core with the laste changes and at least WipeOut 3 SE works now. Didn't test Dino Crisis, however I just noticed that I erroneously compiled the core with -Ofast and/or probably messed something as I compile my own cores.
I'll close it now. Thanks!

**Comment by CometHunter92** [comment]
Nope, still crashes 2 times on 3 just entering a single race and before the race ends it crashes (it's a softlock, you can close the frontend).
Tested on different devices, same behaviour.
Bios SCPH1001, default settings. DualShock, tested with and without rumble. 
SCES-02845, works on oldest commits and other emulators.
Latest commit to work is https://github.com/libretro/pcsx_rearmed/commit/589bd99ba31de8216624dbf0cbbc016f0663ce3d.
Ported the latest audio & CD commits to this commit and still works, so probably it's an issue with the new dynarec.

**Comment by CometHunter92** [comment]
From https://github.com/libretro/pcsx_rearmed/commit/12fc12797064599dfca2d44043d5c02a949711ef on it seems that Need for Speed: High Stakes suffers from glitches.
Glitches present themselves as random polygon objects on track during a race (not the obstacles, I'm talking about weird poligons). In https://github.com/libretro/pcsx_rearmed/commit/7c8454e3f3028b38d9dbb73d59fdcdcf64b75b5b random polygons are gone but sometimes parts of the track scenery are not rendered or texture are glitched out, for example, in the zone between 50-100 meters before the car there is a strip of glitched textures in the scenery.
I'll take a screenshot as soon as I can.

**Comment by notaz** [comment]
Can you retry with the latest commits? NFS: HS looks ok for me.

**Comment by MuPendulum** [comment]
game: Wipeout 3: Special Edition (PAL)
commit: ab51e9e2
device: RK3326/RG351V

| Dynarec  | GPU | Status |
| ------------- | ------------- | ------------- |
| arm64 (ari64) | unai | Works |
| arm (ari64) | neon | Hardlocks |
| Disabled | neon | Works |

Reproduction steps:
Select single race, press X until in race, play until hardlocks.

<details>
<summary>Build information</summary>

```
# RK3326 devices
else ifeq ($(platform), rk3326)
	CPUFLAGS := -mcpu=cortex-a35+crypto -O2 -fno-plt -fno-semantic-interposition -ftracer -fgcse-sm -fgcse-las -fipa-pta -DNDEBUG
	CPUFLAGS += -marm -mfloat-abi=hard
	LTOFLAGS := -flto=auto -ffat-lto-objects -fdevirtualize-at-ltrans
	CACHESIZES := --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=256
	TARGET := $(TARGET_NAME)_libretro.so
	fpic := -fPIC
	CFLAGS += $(CPUFLAGS) $(LTOFLAGS) $(CACHESIZES)
	CXXFLAGS += $(CPUFLAGS) $(LTOFLAGS) $(CACHESIZES)
	LDFLAGS += -Wl,-O1,--sort-common,--as-needed -flto=auto
	ARCH := arm
	HAVE_NEON = 1
	BUILTIN_GPU = neon
	DYNAREC = ari64
```

</details>

Testing was done with a clean install and save. I'm not sure when I'll be able to test the latest commits or minimal compiler optimizations/debug.

**Comment by CometHunter92** [comment]
> Can you retry with the latest commits? NFS: HS looks ok for me.

Ok, I compile it and test it now! Thanks a lot for your work however

**Comment by CometHunter92** [comment]
Ok, tried briefly the latest commit and it seems to not softlock anymore in WipeOut 3: SE.
NFS High Stakes seems to not randomly glitch anymore.
Nice! Thanks! I'll close it now.
