### ISSUE TITLE
No sound with some games when using hle bios

### ISSUE THREAD

**Issue by bochecha** [libretro/pcsx_rearmed#59]
I do have sound working just find for most of my games.

However, there is one (so far) for which I get no sound: Tactics Ogre - Let us Cling together.

This is with the builtin BIOS.

I'm happy to help debugging this issue further, but I'll need some guidance on what to try.

**Comment by notaz** [comment]
There has been no significant development of the builtin BIOS since original PCSX, you should just use the real one.

**Comment by bochecha** [comment]
> There has been no significant development of the builtin BIOS since original PCSX, you should just use the real one.

The real BIOS? or the real PCSX?

(your sentence could be understood both ways, at least to me, a non-native English speaker)

**Comment by LEGOAnimal22** [comment]
Real BIOS.

**Comment by Kekun** [comment]
We have a mostly working free software BIOS implementation, fixing it sound like a better idea to me than relying on the official but illegal to distribute one.

Having a working built-in BIOS is the reason why I prefer pcsx_rearmed:
- it makes it easier to distribute as there is no need to illegally ship an official BIOS
- it makes it easier to use as the end user doesn't need to look for a working BIOS ROM on thousands of websites.

I'm willing to help fixing this problem but I know nothing about this kind of development.

**Comment by notaz** [comment]
I agree a more compatible built-in BIOS would be great, but it's not something that can be easily fixed and would require quite a lot of time and effort to get it done.

To do it, one needs to have a good understanding of how the BIOS works, there is some documentation in leaked PSX SDK, also Martin (nocash) has documented quite a bit of it in his psx-spx. Then the broken games would need to be traced and compared between emulated and original BIOS to try to find where things are going wrong. To trace the original BIOS, emulator modifications would be needed. Ideally a test suite (PSX exe) could be written that would call all the BIOS functions and verify that they are behaving properly. This could be used to prevent regressions and even improve other emulators that have a built-in BIOS.

**Comment by hooby3dfx** [comment]
Another game with missing sound effects in HLE is Syphon Filter.
Player gunshot sound effects and in-level background music are missing.

**Comment by negativeExponent** [comment]
for better compatibility, an official bios should be used instead of HLE

**Comment by notaz** [comment]
Too little too late or not, but after 7 years it seems to be fixed.
