### ISSUE TITLE
#552 broke Vib-Ribbon

### ISSUE THREAD

**Issue by bslenul** [libretro/pcsx_rearmed#590]
Hey!

Just seen this Reddit issue: https://www.reddit.com/r/RetroArch/comments/roorte/struggling_to_get_vib_ribbon_to_work_on_retroarch/ where it states that Vib-Ribbon isn't working properly on 3DS, there's no soundtrack and no gameplay, it just shows a flat line without any obstacles or anything.

I don't have a 3DS but I was able to reproduce the issue on PC as well (even when using an audio CD), then I bisected and the issue started with 66425c25db8a6e4d33488977bf745af73dbe8b39

**Comment by bslenul** [comment]
Happening in upstream as well, I've opened an issue there too, should I close this one?

**Comment by medievil1** [comment]
happens on pc/windows version too....

**Comment by bslenul** [comment]
Fixed with the latest commits thanks to notaz, closing!
