### ISSUE TITLE
(3DS) Core crash with latest dynarec fixes

### ISSUE THREAD

**Issue by MrHuu** [libretro/pcsx_rearmed#592]
## Description

The core crashes when loading a rom. Any rom.
Crash occurs on both .3dsx and .cia builds.

I've only been able to test .pbp and a single .chd.

## Steps to reproduce

Load any game,
either through playlist or load content.

## When did the behavior start?

After merging: https://github.com/libretro/pcsx_rearmed/pull/587

Latest working build is from Dec 14 2021.

## Your device/OS/platform/architecture

3DS/CTR platform, ARM11/ARMv6k

## Logs

```log
[libretro INFO] Starting PCSX-ReARMed 
[libretro INFO] Running PCSX Version 1.9 (Dec 21 2021).
[libretro INFO] psxMap: warning: wanted to map @80000000, got 0x13000000
[libretro INFO] psxMap: warning: wanted to map @77000000, got 0x13000000
[libretro INFO] psxMap: warning: wanted to map @1f800000, got 0x12800000
[libretro INFO] psxMap: warning: wanted to map @1fc00000, got 0x12c00000
[libretro INFO] Init new dynarec
[libretro INFO] testing if we can run recompiled code...
```
..followed by an ARM exception

## Screenshots
![image](https://user-images.githubusercontent.com/561623/147883318-63931f2e-ea7c-4a04-afd8-ee5e08b02f4f.png)

**Comment by Kiahnte** [comment]
I was also having this problem. It was a fresh install of the nightly build for me. I also was loading .bins or .cues (checked both) and had the same problem regardless.

**Comment by notaz** [comment]
Pushed something but it's a shot in the dark. If it still doesn't work, please provide logs from the latest commit and also the last working version.

**Comment by MrHuu** [comment]
Hey that looks promising! After pulling the latest commit and building, the emulator seems to be running again.
Haven't tried running many roms so far, but since the crash seems unrelated to the loaded content, i think you've been able to pinpoint this issue and fix it.

Once the new build is available on the libretro buildbot, i'll make sure to verify that's working as-well.

This is very very much appreciated!

**Comment by MrHuu** [comment]
The latest nightly builds, both .3dsx and .cia, are fully functional again.
Performance is great on every game i've been able to test. Without any stability issues so far.

This issue is solved, and the emulator seems to be running better than ever.
Thank you @notaz

**Comment by MrHuu** [comment]
@twinaphex 

With Retroarch v1.10.0 just released, i can imagine most users will grab the latest stable release.
In an attempt to avoid confusion among users, would it be a possibility to include this latest commit, and rebuild the v1.10.0 release?

**Comment by MrHuu** [comment]
@notaz With everything working, for sake of completeness, here is the current log:

```
[libretro INFO] Starting PCSX-ReARMed 
[libretro INFO] Running PCSX Version 1.9 (Jan 23 2022).
[libretro INFO] psxMap: warning: wanted to map @80000000, got 0x13000000
[libretro INFO] psxMap: warning: wanted to map @77000000, got 0x13000000
[libretro INFO] psxMap: warning: wanted to map @1f800000, got 0x12800000
[libretro INFO] psxMap: warning: wanted to map @1fc00000, got 0x12c00000
[libretro INFO] Init new dynarec
[libretro INFO] testing if we can run recompiled code @0x9b5000...
[libretro INFO] test passed.
[libretro INFO] warning: RAM is not directly mapped, performance will suffer
[libretro INFO] psxMap: warning: wanted to map @08000000, got 0x11000000
[libretro INFO] Mapped (RAM/scrp/ROM/LUTs/TC):
[libretro INFO] 0x13000000/0x12800000/0x12c00000/0x11000000/0x9b5000
```
