### ISSUE TITLE
ERROR: Segmentation fault in recompiled code: invalid load/store at address 0x16c1b49c 

### ISSUE THREAD

**Issue by Bommel24** [libretro/pcsx_rearmed#595]
In Retroarch (PCSX-ReARMed r24l 12fc127) in "Crash Bandicoot 2 - Cortex Strikes Back" (SCES00967)
I tested this specifically during the N.Gin Bossfight.
To reproduce:
Save a savestate.
Close the emulator.
Restart the emulator and load the savestate.
Wait 10 seconds and the core crashes with a Segmentation fault.

Savestate attached:
[SCES00967_Crash_Bandicoot_2.zip](https://github.com/libretro/pcsx_rearmed/files/7900946/SCES00967_Crash_Bandicoot_2.zip)

Windows 11 64bit

**Comment by pcercuei** [comment]
So it does not happen if you don't create a savestate then reload?

**Comment by pcercuei** [comment]
Most likely fixed by #650.

**Comment by notaz** [comment]
The attached save isn't crashing in the current version.
