### ISSUE TITLE
N3DS: Crash Team Racing crashes on latest commits 

### ISSUE THREAD

**Issue by MarioKartFan** [libretro/pcsx_rearmed#597]
Running the latest nightlies (which are fantastic on N3DS with performance smoother than ever after @notaz pushed the CDDA improvements). Unfortunately Crash Team Racing now crashes the N3DS shortly after start. I tested using an NTSC chd and a PAL pbp. 

You can pick your racer, get through the introductory monologue but as soon as you start driving towards the first warped the system crashes.

**Comment by DerinQyu** [comment]
Hello, try to test if the crash stiil happens on last saturday nightly f8a8da8 before the commits that fixed the ps vita version were pushed

**Comment by notaz** [comment]
CTR PAL version is librypt copy-protected and is intentionally made to crash at the point you describe. To emulate the protection you need to use a format that supports subchannel data (and that is supported by the emu, apparently chd is not one of them - #535) or [get a .sbi from from redump.org](http://redump.org/disc/897/) and name it same as the main file, just with .sbi extension (no idea if it will work on 3DS though).

NTSC version should just work though (it does for me), maybe what you have is really PAL version or the is some problem with chd code.

**Comment by MarioKartFan** [comment]
Thanks @notaz. I appreciate the explanation. Very interesting. In terms of performance is there any reason to prefer PAL over NTSC? The changes you pushed re CDDA sound stuttering appear to have meaningfully improved performance on N3DS. It’s not clear from your comment when you pushed those changes whether those changes disproportionately improve PAL performance.

**Comment by notaz** [comment]
IMO PAL timing is not emulated that well, everything was tuned for NTSC.

And I'm surprised there is any effect on performance from cdda commits. Are you sure it's not the dynarec fixes? 3DS support was broken before the cdda commits, so the dynarec fixes alone could not be tested on 3DS?

**Comment by MarioKartFan** [comment]
@notaz Maybe it was the dynarec fixes alone.  

Either way, I confirmed a few minutes ago that this crash happens regardless of whether it is an NTSC or PAL version and whether it is PBP or CHD.  Same spot.

**Comment by DerinQyu** [comment]
This same crash also happens on the ps vita (only retroarch crashes not the whole ps vita os). Driving close to the first warped zone triggers it. Tested on .chd .pbp and .iso

Here are some logs:
[retroarch__2022_01_26__22_14_59.log](https://github.com/libretro/pcsx_rearmed/files/7947580/retroarch__2022_01_26__22_14_59.log)
[retroarch__2022_01_26__22_15_14.log](https://github.com/libretro/pcsx_rearmed/files/7947581/retroarch__2022_01_26__22_15_14.log)
[retroarch__2022_01_26__22_11_41.log](https://github.com/libretro/pcsx_rearmed/files/7947582/retroarch__2022_01_26__22_11_41.log)

This does not happen on the December 14 nightly commit 589bd99

**Comment by DerinQyu** [comment]
Here is what the vita's crash dump reports:
![2022-01-26-221448-933785](https://user-images.githubusercontent.com/5404017/151293114-9e380243-62bf-43aa-9617-78ea8d86ea9c.jpg)
![2022-01-26-221444-696590](https://user-images.githubusercontent.com/5404017/151293116-6a106fbf-81f2-4409-8645-451830668f3c.jpg)

**Comment by MarioKartFan** [comment]
@notaz your recent commits fixed this. Game run likes a dream on N3DS now. Thanks.
