### ISSUE TITLE
Mouse Support?

### ISSUE THREAD

**Issue by brenthunter** [libretro/pcsx_rearmed#60]
Could mouse support be added to support games like Time Crisis?

**Comment by AaronRays468** [comment]
i am thinking about quake 2

**Comment by Febbweiss** [comment]
+1 for lightgun games

**Comment by abelbriggs1** [comment]
There already seems to be code for the guncon itself, in plugins/dfinput/guncon.c (per a PCSX-R update 6 years ago by notaz that added touchscreen support for the Pandora version), but it's not selectable as a input option in Retroarch, and probably would need to be rewritten to support a real mouse anyway.

The core doesn't use the controllers API, so hooking this up will probably be a little more than just changing some variables.

Placed a $5 bounty. I'd really love to be able to play Elemental Gearbolt and other PSX-exclusive light gun games on my RPI with a mouse(specifically a Dolphinbar and a Wiimote) and an old CRT someday, and this core needs some love for the amount of usage it gets.

**Comment by TradeDraft** [comment]
I tried the most Recent Core and there is no support for the Mouse.

Just comes up with Retropad when I try and Change the Input/Controller Device

**Comment by negativeExponent** [comment]
done.

this should be working in latest commits

@twinaphex @hunterk @hizzlesomething

**Comment by TradeDraft** [comment]
Awsome @negativeExponent 

Tested it and Works Fine

**Comment by TradeDraft** [comment]
My Pleasure @negativeExponent 

I only Tried Time Crisis and Red Alert Retaliation and they worked fine
