### ISSUE TITLE
Colony Wars - Aspect/Resolution not switching correctly

### ISSUE THREAD

**Issue by Qyr3n** [libretro/pcsx_rearmed#617]
## Description

Game not displaying in correct aspect ratio/resolution during transition scenes (starting/ending missions).

Normal gameplay is rendered at 512x384 high-res and works fine. However, certain transition cutscenes are rendered at the usual 320x240 and displayed letterboxed. These scenes are being stretched to a full 4:3 aspect when they should be in a 16:9 letterbox with borders. Aspect ratio and resolution settings have no effect. These scenes are displayed correctly in Duckstation. Seems the top and bottom borders are being cropped incorrectly. 1:1 PAR results in a full-screen 16:9 image, instead of 16:9 within 4:3, and upon transition back to gameplay remains stretched to wide-screen. Something is not switching/scaling/cropping correctly.

## Steps to reproduce

Boot game, start campaign and skip first briefing. Scene showing ship coming up an elevator before mission starts should be letterboxed. Look at the back of the ship - this should be circular.

## When did the behavior start?

Unsure.

## Your device/OS/platform/architecture

Pi 4B 2GB
Batocera v33

**Comment by notaz** [comment]
Current version seems to match random recordings from youtube so assuming fixed.
