### ISSUE TITLE
Recap of some bugs I found

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#620]
- <s>LMA Manager and Premier Manager games all softlock eventually, even with very old commits, in memory card access menu or during loading screens.</s>
- <s>Sled Storm crashes as soon as you enter option menu</s>
- <s>V-Rally 2 is unable to use analog sticks input (?)</s>
- <s>Theme Hospital doesn't play music from the intro but has a strange sound instead. (maybe CD-Rom related issue)</s>
- <s>Tombi 2! has severe audio issues (music skipping and glitching)</s>
- Bust a Groove desyncs heavily, unplayable (needs testing)
- <s>Felony 11-79, Road Rash, Side by Side Special 2000, Power Shovel still have engine noise stuck during pause</s>
- Dino Crisis infamous speech stuttering
- <s>Crash Bash doesn't show menu during pause</s>
- <s>Ridge Racer Type 4 has reverb kicking in randomly during races, and not when in tunnels</s>
- Anna Kournikova's Smash Court Tennis: shadows from players are swapped

**Comment by notaz** [comment]
At least some of these should be fixed by now. Can you open new issues (one per game) for those that remain for easier tracking?

**Comment by CometHunter92** [comment]
Yes, I'll close this.
