### ISSUE TITLE
Bad dummy resolutions reported

### ISSUE THREAD

**Issue by rtomasa** [libretro/pcsx_rearmed#621]
## Description

Many game resolution changes are report dummy resolutions before setting the correct one.
Sometimes those timings really affects the game geometry, other ones (most of the cases) occurs on video transitions, splash screens, etc. so do not affect any geometry.
When this happens, it normally causes 2 or more resolutions changes in a row.

This totally breaks the gameplay when using real CRT + on the fly native resolutions.

## Steps to reproduce

A good example to reproduce all issues described above is:
1. Run Wipeout XL (NTSC) via RetroArch from CLI in verbose mode
2. Some bad 640x478 happens.
3. From the main menu, enter on the ship menu option > this results in many vertical resolution changes.
4. Start a new game and leave other ships to impact you with a bomb > this results in many vertical resolution changes.

## Your device/OS/platform/architecture

Raspberry Pi4. Raspbian. RA and core instaled via RetroPie setup scripts

## Logs

Examples of bad timings seen in the log:
/Untitled-1
[INFO] [Environ]: SET_GEOMETRY: 640x478, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 320x234, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 320x239, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 320x236, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 320x238, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 320x233, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 320x235, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 320x237, Aspect: 1.333.

**Comment by CometHunter92** [comment]
If I remember correctly that's how WipeOut XL works

**Comment by rtomasa** [comment]
You are completely right about the WipeOut XL. I saw in a YT video. What a tricky effect.
In any case the issue is still valid for all other games, specially when transitioning from videos and menus.

**Comment by notaz** [comment]
Since some time ago this is now handled differently and should switch the resolutions less. However it's still rather common for a game to switch to different resolutions for FMVs, title screens, etc. It's just how the games are coded. The core could scale all of them to some fixed resolution before passing the frames to the frontend (RetroArch or whatever), but I don't think it's the right thing to do because the core has no idea what will be done with the frames before they are displayed.

**Comment by notaz** [comment]
Closing this a per previous explanation.
