### ISSUE TITLE
Players disappearing towards the back in Madden 2004/2005, NCAA Football 2001

### ISSUE THREAD

**Issue by agentmith** [libretro/pcsx_rearmed#622]
It's possible this is happening in more games, but it's definitely happening in Madden 2004/2005 and NCAA Football 2001. Spot checked against Mednafen core on PC and this isn't happening. Pretty sure it didn't used to happen on Retropie either, it may have been introduced in a recent patch but not 100% positive. I tried messing around with every possible setting in the menu, shaders, overclocking, etc and nothing has made any impact.

## Description

Character models will disappear randomly in the back, leaving only their shadow on the ground. Particularly noticeable when at line of scrimmage. The defensive team's safety, cornerback, and ref will disappear. Unfortunately this also happens if your receivers run towards the back of the screen too, making it impossible to play.

## Steps to reproduce

Current release lr-pcsx-rearmed on retropie 4.7.21, play Madden 2004/2005 until gameplay starts. Nothing special, it eventually happens once you get to the field.

## When did the behavior start?

Just noticed this recently, not sure when it was introduced.

## Your device/OS/platform/architecture

Raspberry Pi 4, retropie 4.7.21, using default PSX associations and config.

## Logs (enable file logging and set log levels to DEBUG for core and frontend)

n/a

## Screenshots (if needed for visual confirmation)

will provide if necessary

## Others (save states and/or save files nearest to the affected area, compressed)

will provide if necessary

thanks!

**Comment by notaz** [comment]
Should be fixed now.
