### ISSUE TITLE
Analog mode not enabling in some games

### ISSUE THREAD

**Issue by pierre-quelin** [libretro/pcsx_rearmed#623]
I can't play to Gran Tourismo 2 in analog mode. I love this game but it is unfortunately not usable only because the controller remains in digital mode.
With the real console, it is necessary to press the "analog" button after starting the game to switch to analog mode.

To reproduce, it's very easy just start the game ;-) but you need the rom.

Hardware:
    
    Raspberri-Pi 2 (Arm V7 BCM2836R)
    DualShock 4 + Official USB dongle

Used Operating system 1:

    LibreElec 9.2.8
    Kodi 18.9.0
    PCSX ReArmed 22.0.0.92
    Playstation DualShock 1.0.14

or Operating System 2:

    Recalbox 8.0-Electron

see : https://github.com/kodi-game/game.libretro.pcsx-rearmed/issues/25

Thank you

**Comment by CometHunter92** [comment]
No problems for me, maybe it's something in your OS configuration.
However the screen in GT2 where you have to sets the binding to the analog sticks is another one; that screen you posted was reserved for wheels configuration.

**Comment by pierre-quelin** [comment]
You're right, the screen is another one.
I checkout my original game and playstation just to compare.

* On the original game, it is impossible to start with analog configuration. You always start in digital mode.
On the pcsx_rearmed I always have the boot configuration as you can see on this screen :

![pcsx_rearmed resized](https://user-images.githubusercontent.com/16599148/157321672-2cfa5fc7-5607-479c-b206-4c23e5f92e8f.jpg)


* On the original game, when you press analog button, the touch configuration change as you can see on this screen :

![original resized](https://user-images.githubusercontent.com/16599148/157321343-8540e946-89d6-4f0d-9ca5-b8efc234122b.jpg)

I can't do that on pcsx rearmed.
I create a copy base on my original game. Do you know if there are several versions of this game?

Thank you very much

**Comment by pierre-quelin** [comment]
"it is impossible to start with analog configuration" WRONG SRY.
But I don't understand where I need to configure the analog mode.

**Comment by pierre-quelin** [comment]
I select Dualshock again and it works ???
sry and thank you

**Comment by CometHunter92** [comment]
I'm happy you solved!

**Comment by pierre-quelin** [comment]
I understood what happened.
In order to obtain a functional analog mode, it is necessary to perform the following procedure every time you want to play:
- Start the game
- Open the settings
- Choose a default joystick and validate
- Choose a dualshok joystick and validate
Let's go !!!

Now I have to understand why there's no vibration and why the dead zone is much bigger than on the original. ;-)
