### ISSUE TITLE
Performance regression with latest commits

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#632]
After https://github.com/libretro/pcsx_rearmed/commit/e09212db7aff5064a7eaaa9008f8c69d465c54f7 there is an heavy performance regression.
I need to test more, but probably the frameskip cpmmits are the ones.

**Comment by MarioKartFan** [comment]
Hi, on what platform? I am not seeing regressions on N3DS. If anything the auto skip helps dramatically on a few high demand games.

**Comment by CometHunter92** [comment]
Mmm I'll retry, maybe it's my fault

**Comment by CometHunter92** [comment]
My fault, @twinaphex you can revert the revert.
Sorry guys
