### ISSUE TITLE
PCSX-REARMED SaveStates do not work on 32 bit compilation . Core does not support save states

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/pcsx_rearmed#635]
## Description

Savestates do not work on PCSX-REARMED 32 bits (arm compilation) stating core does not support save states however on the 64 bit (aarch64) compilation works.

## Steps to reproduce

Compile the emulator on arm arch, run the emulator and try to save a state. I'm having this in latest EMUELEC version. "Core does not support save states" meassge pops up

## When did the behavior start?

When updating to https://github.com/libretro/pcsx_rearmed/commit/db0df4bd25f7f13fb6c6d02fc82a952a9c1baa23 , 4 months ago versions work.

## Your device/OS/platform/architecture

Odroid n2+ EMUELEC 4.4

**Comment by hizzlekizzle** [comment]
Is it possible your build is using an old/incorrect core info file that does not include the stavestate status information?

**Comment by Kelvfimer** [comment]
Thx for the answer but I'm using latest one.

**Comment by Kelvfimer** [comment]
Seems to be an issue on retroarch https://github.com/EmuELEC/EmuELEC/issues/882 . We solved rewriting info files.

**Comment by hizzlekizzle** [comment]
Ah, looks good. Yeah, having info files for those builds seems like a good idea in general.
