### ISSUE TITLE
70's Robot Anime: Geppy-X - freezes on FMVs (Android)

### ISSUE THREAD

**Issue by mSchul4** [libretro/pcsx_rearmed#639]
#This tracker is for pcsx-rearmed-libretro issues *only*.

If the issue also occurs in standalone PCSX-ReARMed, the upstream repo is probably a better place for it.

That said, we would suggest that you also try it on other PCSX-based forks such as PCSX Reloaded, PCSX Redux and the upstream version
as well because these share a similar codebase (or derive from it) and are helpful for regression testing, thus making it more 
likely for the bug to be fixed if it is indeed specific to the libretro core only.

## Description
Game in question is 70's Robot Anime - Geppy-X - The Super Boosted Armor (Japan)

Game freezes at any FMV, 2/3 of the first frame is garbled pixels, no input accepted (See Screenshot 1 below)
Screen soon shifts to only be about 1/6 garbled (no actual video playback, see Screenshot 2)
FMV audio plays out, to then start playing 4 other audio tracks from elsewhere in the game
When it runs out of those (approx. 3:30 later), silence.
My own research has shown the tracks it plays are each the first segments of the disc's main XA files.

Mainly run as an M3U playlist of CHDs, but the same behavior occurs with individual CHDs and BIN/CUE
No other CHD games with FMVs I've tested on the same hardware & core have this problem.

Runs fine on Windows with same core commit #861f92d
It worked perfectly only a few days prior to this post (approx. March 26) before an update to Retroarch v1.10.2 and update of PCSXRearmed core

## Steps to reproduce
Load up game (w/any disc); Disc 1 is easiest as it immediately starts with an FMV
Booting any of the other discs separately will get you to actual menus, but will freeze upon the next FMV (i.e. loading a save file) 
(only change of behavior is now it will play through the audio of every FMV after it on-disc, before looping to the bootup FMV as explained above, going from there.)

Same behavior with both dynarec and interpreter emulation

## When did the behavior start?
approx. Mar 26 2022

## Your device/OS/platform/architecture
Android 9.0 / Retroid Pocket 2+ / AArch64

## Screenshots (if needed for visual confirmation)
![Screenshot_20220331-115323](https://user-images.githubusercontent.com/26718599/161334724-37e1510d-3dc8-4b34-9926-53f3308c04d3.png) [Screenshot 1]
![Screenshot_20220331-115304](https://user-images.githubusercontent.com/26718599/161334754-0350ec3e-71b2-4c80-953f-3538abdd4971.png) [Screenshot 2]
## Others (save states and/or save files nearest to the affected area, compressed)
[70's Robot Anime - Geppy-X - The Super Boosted Armor (Japan) (Disc 1).state.zip](https://github.com/libretro/pcsx_rearmed/files/8400728/70.s.Robot.Anime.-.Geppy-X.-.The.Super.Boosted.Armor.Japan.Disc.1.state.zip)

**Comment by notaz** [comment]
Seems to be working on the latest version, closing.
