### ISSUE TITLE
parasite eve 2 stuck and cant play on Nintendo Switch

### ISSUE THREAD

**Issue by winsenwonady** [libretro/pcsx_rearmed#640]
## Description

I Try to play parasite eve 2 but it got stuck on published by ( i tries US version ) and it got stuck after pressing new game ( on JP version). currently im on retroarch 1.10.2 and i have tried to try parasite eve 2 fix on option but it doesnt seem to be working.

Please describe the issue. If this is a feature request, please add [feature request] to the title of the issue report.

## Your device/OS/platform/architecture

Nintendo Switch

**Comment by CometHunter92** [comment]
Did it work before 1.10.2?

**Comment by DrunkenMonk0001** [comment]
Dynarec is broken and has been for a little bit, either enable HLE bios to disable dynarec or modify config.

Known issue #626

**Comment by CometHunter92** [comment]
x86 dynarec has nothing to do with the arm and aarch64 dynarec.
I don't have issues on arm and aarch64

**Comment by DrunkenMonk0001** [comment]
> x86 dynarec has nothing to do with the arm and aarch64 dynarec. I don't have issues on arm and aarch64

I'll clarify, I've tested and encountered the same issue on switch personally and traced it back to the same issue. Disabling dynarec "fixes" all of the issues and accessing the memory card no longer causes crashes. Something is fundamentally broken with the dynarec that causes it not to work on any platform I've tested so far.

**Comment by DrunkenMonk0001** [comment]
The last known confirmed working version is 7e3ce9a

**Comment by notaz** [comment]
For x86, the dynarec is unmaintained and should not be used.

As for ARM, the core was likely compiled incorrectly, see https://github.com/libretro/Lakka-LibreELEC/issues/1651#issuecomment-1089361666 .

**Comment by pcercuei** [comment]
@notaz Lightrec is maintained and still being worked on, what are you talking about?

**Comment by notaz** [comment]
I take that back, sorry.

I just saw #626 being open for almost a month and assumed you have lost interest, but it turned out you weren't aware.

**Comment by gusklein** [comment]
> > x86 dynarec has nothing to do with the arm and aarch64 dynarec. I don't have issues on arm and aarch64
> 
> I'll clarify, I've tested and encountered the same issue on switch personally and traced it back to the same issue. Disabling dynarec "fixes" all of the issues and accessing the memory card no longer causes crashes. Something is fundamentally broken with the dynarec that causes it not to work on any platform I've tested so far. Which again, reverting to a known working version is also a fine option.

Maybe there is something related to bios. I've tested the 1.9.13 stable core with PE2 Fix chkd and HLE bios. Sometimes works, sometimes freezes. Under N Switch no overclocking.

**Comment by gusklein** [comment]
Maybe this could be the solution?
https://github.com/libretro/pcsx_rearmed/issues/237

**Comment by DerinQyu** [comment]
This issue should be closed, parasite eve 2 opens and reach ingame status on nintendo switch using pcsx rearmed latest nightly build.
![2022080222374100](https://user-images.githubusercontent.com/5404017/182519317-3307a3da-ea1a-47cb-87d9-de6048abc199.jpg)
