### ISSUE TITLE
Lightrec causing abrupt crashes in some scenarios

### ISSUE THREAD

**Issue by DrunkenMonk0001** [libretro/pcsx_rearmed#645]
Using the latest core bundled with retroarch on steam as of today 16/04/2022 where the majority of the previous issues had been alleviated.

There are still some issues in some games I've already seen reported on the new retroarch update that included the last fix that propagated onto the steam pcsx rearmed core - I have a save state that causes an instant crash using lightrec upon loading, but disabling lightrec or using ari on another platform doesn't have this problem. 

This appears to be repeatable without a save state also, the process is to start a new game on digimon world (eur, ntsc unchecked), stop and reload the emulator then load the save and attempt to progress to the beginning of the game and it will crash after going through all of the prompts and the screen fades to black

I've been largely unsuccessful in finding when this exactly began occurring, the core included in retroarch 1.10.0 stable still appears to have this same problem. I can attempt to split the issue further, but debugging is difficult as a frontend user, the log also doesn't provide any information.

This occurs on Windows x86_64

The debug log provides no information, last entry is enabling GLSL shaders

Attached is a save state in which it occurs instantly
[Digimon World (Europe).zip](https://github.com/libretro/pcsx_rearmed/files/8499502/Digimon.World.Europe.zip)

@pcercuei If you need, I can glide through more iterations in attempt to bisect further

**Comment by pcercuei** [comment]
@DrunkenMonk0001 the first thing to test would be to disable the threaded compiler, here: https://github.com/libretro/pcsx_rearmed/blob/master/include/lightrec/lightrec-config.h#L9

**Comment by pcercuei** [comment]
I believe it is similar to #595.

**Comment by pcercuei** [comment]
@DrunkenMonk0001 it might be fixed by #650.

**Comment by pcercuei** [comment]
@DrunkenMonk0001 Try with a fresh new savestate.

**Comment by DrunkenMonk0001** [comment]
@pcercuei Seems to have worked with a fresh savestate! Unable to reproduce in a few localized tests.
