### ISSUE TITLE
Front Mission 3 freeze during battles

### ISSUE THREAD

**Issue by ljorg** [libretro/pcsx_rearmed#646]
## Description

Front Mission 3 will often freeze randomly during battles. Most of the times it is frozen with a stuttering sound where it is possible to reload latest snapshot and try again. Other times it crashes the whole system and I need to pull the power plug.

Might be related to Dynamic Recompiler, from what I can google.

## Steps to reproduce

Since this is random, it is hard to reproduce it. It happens when somebody is attacking during battle. Sometimes it freezes, I can reload snapshot and do the same attack without problems.

## Your device/OS/platform/architecture

Raspberry Pi 4B running RetroPie.

**Comment by VGkav** [comment]
Is this about the well-known freeze when the mech's legs get blown up?

**Comment by ljorg** [comment]
I didn't know about that. I'll investigate and get back!

**Comment by NeonLightning** [comment]
apparently epsxe used to have it too but fixed it somehow

**Comment by notaz** [comment]
I couldn't reproduce this on the first level so maybe fixed. If it still happens please provide a savestate where it's more likely to happen.
