### ISSUE TITLE
[BUG] Problem with the sound of games in CHD format.

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/pcsx_rearmed#648]
#This tracker is for pcsx-rearmed-libretro issues *only*.

I test on 3 different machines:

My laptop running linux (Manjaro 64bits) and using retroarch from flatpak;
My OUYA console (Android 4.1) and using retroarch download from the official website; and
My Raspberry Pie 4 with retropie in 4.8.

Retroarch in version 10 and the last core release.

CHD games created from games that have multiple bin files (Rage Racer, Dead or Alive for example), the game will have issues with sounds like:

- Do not play the music during the race (Rage Racer);
- A huge delay to start the stage music (Dead or Alive).

I tried the Rage Racer in the follow situations:

- 1 cue and 17 bin files (which match with redump's SH1 hashs);
- 1 cue and 1 bin file (the same 17 bin files combined); and
- 1 chd (created with the 1 cue and 17 bin files or 1 cue and 1 bin file).

Using cue and bin files the game works perfectly, in any situation. Using the chd versions I had the same problem in both situations: The music after choosing the car runs wrong. If you try to choose the soundtrack, the game plays a wrong track and only the final part of it. If you don't choose a soundtrack, the game won't play a song.

Games with one or two bin files, like Guilty Gear, work perfectly.

**Comment by notaz** [comment]
This should be fixed by now.
