### ISSUE TITLE
FF8 crashes when using bios

### ISSUE THREAD

**Issue by beauxq** [libretro/pcsx_rearmed#656]
## Description

FInal Fantasy 8 crashes at the title screen if using bios 1001 or 5501.
It does not crash if using HLE bios (but with HLE bios, can't use memory cards).
It does not crash with bios 1001 in PCSXR.

## Your device/OS/platform/architecture

Ubuntu 20.04
RetroArch 1.10.3 pcsx-rearmed r23l 7dee1e8

**Comment by hizzlekizzle** [comment]
I believe this is a known issue related to the dynamic recompiler. You can set your CPU to "interpreter" in the core options to fix it, IIRC.

**Comment by pcercuei** [comment]
Wasn't know to me.
Does that happen on PC, or on an ARM device?

**Comment by beauxq** [comment]
on PC, Ubuntu 20.04

**Comment by pcercuei** [comment]
Fixed in latest Lightrec master: https://github.com/pcercuei/lightrec/commit/c1eae2b9510826841a977a90cbc67237fa515e02
