### ISSUE TITLE
Resident Evil: DC (DS Ver.) - Memory card is not inserted

### ISSUE THREAD

**Issue by robwill80** [libretro/pcsx_rearmed#658]
The game "Resident Evil: Director's Cut (Dual Shock Version)" no longer recognises the emulator's concept of a memory card, or its corresponding save data.

Choosing the load game option from the main menu brings up the loading screen (a background picture of a typewriter), with the message "Checking memory card/s. Do not pull out the memory card." It takes around 30 seconds before it says "Memory card is not inserted."

Playing a new game up until the point where the player can save their progress yields the same outcome.

I have a completed [save file](https://github.com/libretro/pcsx_rearmed/files/8794331/Save.Game.zip) stored in the appropriate folder for this game, and the same thing happens when that file is removed. 

I do not know when the behaviour started. I only became aware of it as I swapped the Google Play Store version of RetroArch Plus for the newly released version of RetroArch on the Samsung Galaxy Store.

This was observed on a Samsung Galaxy A41 running Android 11, and also an Amazon Fire TV Cube (2nd Gen) running Fire OS 7.

**Comment by bslenul** [comment]
Seems to be a dynarec issue, the memory card works fine when disabled.

**Comment by bslenul** [comment]
Finally learned how to compile for Android, so I was able to bisect, looks like the issue started with 630b122be82914a74fac752688abe5d5dd798aa8

@notaz you asked to ping you in the comment of this commit.

**Comment by bslenul** [comment]
Seems to be fixed with latest commit 👍

**Comment by robwill80** [comment]
I see that this was dealt with alongside another issue. Thanks to all involved for their help.
