### ISSUE TITLE
Inherited  'Analog controls do not reach the full range of the "up" axis for the left and right joysticks.'

### ISSUE THREAD

**Issue by thorst** [libretro/pcsx_rearmed#66]
I'm not sure about the depth of changes in this branch, but I'm running Retropie 4.0.3 and I'm having an issue with Ape Escape. The below issue from the main project seems to exist in this project. Basically everything works correctly if you change the inputs to analog EXCEPT pushing straight up on either the left or right analog stick does not register as going the complete way up. So for the left analog stick you walk instead of run and on the right you wont deploy your net or sword.

https://github.com/notaz/pcsx_rearmed/issues/46

Any fix would be MUCH appreciated.

**Comment by mitchellcairns** [comment]
Also having this issue.

**Comment by negativeExponent** [comment]
this probably already have been fixed.
