### ISSUE TITLE
[Lightrec] Resident Evil - black screen

### ISSUE THREAD

**Issue by bslenul** [libretro/pcsx_rearmed#660]
While trying to reproduce #658 I noticed that Resident Evil boots to a black screen on Windows, I tested 3 USA versions: the original, the Director's Cut and the Director's Cut - Dual Shock Ver.

After bisecting, looks like it started with 2bf88032209c32c6a2a920905cced1ab0f69d5a1, the game boots fine with the previous commit (f4f9f2a415665fd9cbb7ac404c3d9d34397d3023).

@pcercuei

**Comment by pcercuei** [comment]
Can't reproduce. Latest master runs Resident Evil (Director's Cut Dual Shock) just fine.

**Comment by pcercuei** [comment]
Try to reset to the default configuration. I installed RetroArch stable from scratch (never installed it on Windows before) and tested with a fresh build of the core and it just works.

**Comment by bslenul** [comment]
This is as fresh as it could be, default settings in RA (the only setting I changed is the loading content notification, but it doesn't change anything about the issue) and core is running with default settings. It boots fine with the HLE BIOS however 🤔

**Comment by pcercuei** [comment]
Ok, I can reproduce it if I use a BIOS file.

**Comment by pcercuei** [comment]
It does not happen on my standalone build of PCSX, which is based on commit 3c89130 from notaz' repository.
However, it *does* happen on the standalone build if I rebase my commits on top of notaz/master.

Can anybody test this on ARM with Ari64's dynarec? Does it show the same behaviour?

@notaz, I'm under the impression that between 3c89130 and master, something changed with `next_interupt`. I used to only have to call `gen_interupt` before calling the dynarec, then after calling psxHwRead* or psxHwWrite* reset the dynarec to exit at `next_interupt` and it would work. After rebasing the Lightrec plugin on top of your master branch, this bug appears, unless I also call `gen_interupt` right after calling the hardware I/O function - but I really don't want to do that (the dynarec should exit before handling IRQs) and I don't see why it would be required now. Thoughts?

**Comment by bslenul** [comment]
> Can anybody test this on ARM with Ari64's dynarec? Does it show the same behaviour?

Dumb question but is there a way to know which dynarec it's using? My phone is an old 32bit one, if I understand [this post](https://www.libretro.com/index.php/pcsx-rearmed-now-has-dynarec-support-across-multiple-platforms/) correctly it's using Ari64? If that's the case I can confirm it doesn't happen, however it fails at the memory card check as mentioned in #658

**Comment by pcercuei** [comment]
@notaz I actually handle MTC0 and RFE internally, it doesn't change the "next_interupt" variable or call gen_interupt(), but it will exit the dynarec as soon as there's an interrupt pending: https://github.com/pcercuei/lightrec/blob/master/lightrec.c#L455-L466

**Comment by pcercuei** [comment]
I take that back, it's definitely a bug within Lightrec - if I disable a specific optimization pass the game works fine.

**Comment by bslenul** [comment]
Seems to be fixed with latest commit 🤔 Should I close the issue or you still want to investigate on the Lightrec side?

**Comment by pcercuei** [comment]
It does seem to fix the black screen, yes. The intro looks correct now.

However... When starting a new game, at the character selection screen, the two character's IDs are invisible. This does happen with my interpreter as well (so not a codegen issue), and didn't happen when my code was based on 3c8913013a3bb1908186342759f881baa16602b9.

**Comment by bslenul** [comment]
Ah weird, didn't notice because it doesn't happen for me if I boot the game with the dynarec already enabled, however if I boot without it and then enable it during the characters selection screen, then yeah the cards disappear.

**Comment by pcercuei** [comment]
Nevermind, just a tiny change that got left over when I rebased my local code to notaz' latest master. So it works now, and this bug report can be closed.

@notaz: My explanation is that Lightrec can run for thousands of cycles in the case where IRQs have been disabled through the CP0. In that case, it will return only after IRQs are enabled again.

**Comment by bslenul** [comment]
> this bug report can be closed.

OK! Thank you to both of you for your time :)
