### ISSUE TITLE
can't adjust cpu cycle_multiplier on Switch

### ISSUE THREAD

**Issue by gusklein** [libretro/pcsx_rearmed#671]
Please , expose cpu cycle_multiplier as an option in the Nintendo Switch Retroarch menu.

**Comment by notaz** [comment]
I've tried to enable the dynarec, can you try the nightly build?

**Comment by DerinQyu** [comment]
hello tried commit 80bf8832784199adf6eb5ab5a63dafed086d3401 on my nintendo switch (atmosphere 1.3.2 ofw 14.1.2) and the core crashes if I try to load a game. Heres logs
[retroarch.log](https://github.com/libretro/pcsx_rearmed/files/9124343/retroarch.log)

**Comment by notaz** [comment]
Thanks for testing. Please try 3f4fa7fc3a9a0226079d2a463e9fb1f9aaa90fae when you can get it.

**Comment by gusklein** [comment]
Typically slow games are now running wonderfully on Nintendo Switch and without overclocking. Even a historically difficult game, Parasite Eve 2, is working very well. Thanks!
