### ISSUE TITLE
Audio bugs across multiple games

### ISSUE THREAD

**Issue by Lykantier** [libretro/pcsx_rearmed#674]
## Description

For convenience's sake, here's a recording of the bugs I'm about to describe: https://youtu.be/wf2nDt12ccE

1. Discworld II, some voice lines are buggy.
2. Discworld Noir, longer voice lines get cut off after approx. 10 seconds.
3. Harry Potter and the Sorcerer's Stone, audio bugs at the start of the game.
4. Rayman 2, occasional audio bugs that get stuck repeating even throughout the pause menu until the level is exited.
5. Spyro 2, the well-known audio cut-off at the end of the longer cutscenes.

These audio bugs were not present when testing the same games on the SwanStation core, but that's still a little too intense for my phone so here we are.

## Steps to reproduce

These bugs keep happening across all the settings I've tried (so far) and both in BIN and CHD format.

1. Skip the cutscenes using x until you can control the main character, then go back to the Dining Hall and interact with things.
2. Skip the cutscenes using triangle until you can control the main character, then interact with things in the guy's office -- look for the longer voice lines.
3. The first bug is at the title screen; the second and third are right after the introductory storybook cutscene. Change the PSX CPU clock speed from 57 to about 70 if the aforementioned cutscene freezes.
4. Get near the end of the first (very short) proper level, then go back to the crying kids and further until you hear their crying bug out.
5. Start the game, skip the first cutscene and wait out/fast-forward the next one until the main villain shows up.

## When did the behavior start?

The Spyro 2 and Rayman 2 bugs were almost definitely already there since I started using RetroArch last autumn or so, doubt the others are new either. In other words, I don't remember playing these games on PCSX-ReARMed without those bugs.

Here's a very old thread where someone resolves the Spyro 2 bug on their PSP, does PCSX-ReARMed somehow simulate fast disc load speed by chance?
https://gamefaqs.gamespot.com/boards/198753-spyro-2-riptos-rage/49439579

## Your device/OS/platform/architecture

Android 10, 32-bit

**Comment by notaz** [comment]
Most of these should be fixed by now, if there are some left, please open new issue, one for each game (because they have to be debugged and fixed separately).
