### ISSUE TITLE
x86_64 wrong comp option?

### ISSUE THREAD

**Issue by dmanlfc** [libretro/pcsx_rearmed#675]
## Description

Compiled libretro pcsx_rearmed for x86 seems to have an incorrect compilation flag.

## Steps to reproduce

if set to the default - LIGHTREC_CUSTOM_MAP=1 on emulation start pcsx_rearmed crashed with a mmap error.
setting to LIGHTREC_CUSTOM_MAP=0 fixes the problem.

## When did the behavior start?

May 30th commit.

## Your device/OS/platform/architecture

x86_64

**Comment by pcercuei** [comment]
Please paste your `device/OS/platform/architecture` with details. I don't even know if you're using Windows or Linux.

**Comment by notaz** [comment]
Closing due to no response.
