### ISSUE TITLE
32 bit arm compiled with PEOpS plugin doesn't work anymore

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#676]
Seem to work before https://github.com/libretro/pcsx_rearmed/commit/ffe97735d2c5683cb3ebc91299c047c417d2322d. After that compiling a 32 bit arm core with the PEOpS plugin results in heavy glitches and crashes at booting.

**Comment by notaz** [comment]
Just curious, why would you want PEOpS on arm32?

**Comment by CometHunter92** [comment]
For example FF VII, FF VIII, Ape Escape, Metal Gear Solid, No Fear Downhill, Battle Arena Toshinden, Cool Boarders 4 and more have graphical issues with the NEON one. On my Pi4 I use it; iirc that's basically the only way to play Chrono Cross on it, as SwanStation has issues too.

**Comment by notaz** [comment]
Can you give more details? I know FF7 battle swirl was wrong but I've patched it up recently. As for Battle Arena Toshinden, if it's notaz/pcsx_rearmed#236 it should also be fixed.

It would be great if you could retry and open separate detailed issues for each bug.

**Comment by CometHunter92** [comment]
Sure! Do you want videos of the glitches as well?

**Comment by notaz** [comment]
It might help but is not strictly necessary, more important is to be able to quickly reproduce.

**Comment by CometHunter92** [comment]
https://github.com/libretro/pcsx_rearmed/commit/9775fc330a05a1fe0bf61c3cc6d1ee1cf3d27df8 arm 32 PEOpS build is fixed now. Tried MGS, Ape Escape, No Fear Downhill, no more issues (tried Battle Arena Toshinden too, didn't know it was fixed) on the NEON build. Nice!
