### ISSUE TITLE
request option to multiply the native resolution of the emulated psx on Switch

### ISSUE THREAD

**Issue by gusklein** [libretro/pcsx_rearmed#678]
First thing, thanks to the latest updates on dynarec. Typically slow games are now running wonderfully well on Nintendo Switch and without overclocking. Even a historically hard game, Parasite Eve 2, is working very well. The games I've tested are working so well that I would like to ask to enable/expose the config to multiply the native resolution of the emulated psx by 2 or 3X. If possible. Congratulations to everyone who made dynarec and PE2 happen.

**Comment by gusklein** [comment]
@LibretroAdmin @notaz 
possible?

**Comment by notaz** [comment]
Try the latest nightly, there is now a NEON GPU port from 32bit ARM that offers double resolution.

3x may be possible but it's too much work to implement.

**Comment by gusklein** [comment]
Tried lates build: 
![911C7314-EC17-44BB-AE20-77A0149F8FC3](https://user-images.githubusercontent.com/87046201/184459815-75b87e15-2475-4955-bc80-39f37e58d3c9.jpeg)

Parasite Eve 2 showed artifacts with GPU double res hack disable:
![FCD8F820-B622-4872-B4AA-4AE37F3B827F](https://user-images.githubusercontent.com/87046201/184459871-b1596d7a-33af-4d00-bca2-8a3c2a85d31d.jpeg)

And enable: 
![3EA1A989-08EE-49F9-967F-5AC82E144412](https://user-images.githubusercontent.com/87046201/184459893-51ade0b0-7246-4f78-a543-4fa7fa123e2c.jpeg)

Also showed glitch artifacts on shadows (any place):
![4B9BC81D-F69B-4860-B742-B76D1C8B5A0F](https://user-images.githubusercontent.com/87046201/184459928-6611ca64-0350-490a-b81a-07df7b5aa70f.jpeg)

these bugs occurs on any PE2 scenario. Not tested other games yet.

**Comment by notaz** [comment]
Can you try the latest nightly?

**Comment by notaz** [comment]
No response, assuming fixed.
