### ISSUE TITLE
CD drive state inconsistent with retroarch's UI after a reset

### ISSUE THREAD

**Issue by vpelletier** [libretro/pcsx_rearmed#679]
## Description

It is possible to boot a game while retroarch shows the drive state as open (action "Insert Disc" visible).

## Steps to reproduce

1. enable BIOS boot: `Core Options -> System -> Show BIOS Boot Logo` (unsure if this steps is technically needed, but this scenario makes a lot more sense with this option enabled)
2. boot a game
3. eject its disc: `Disc Control -> Eject Disc`
4. restart the core: `Restart`
5. if the bug happens, the game will boot again, despite the drive being still in ejected state

For context, I triggered this while trying to reach the BIOS's memory card management tool. As a workaround, I need to eject the disc after `Restart` but before the game would boot.

## Your device/OS/platform/architecture

New3DS, retroarch 1.10.3 (release), PCSX-ReARMed r23l d38927c

**Comment by notaz** [comment]
Should be fixed now.
