### ISSUE TITLE
Background music doesn't play during round 2 in Digimon Rumble Arena

### ISSUE THREAD

**Issue by shaum257** [libretro/pcsx_rearmed#681]
The background music in Digimon Rumble Arena during round 2 does not play at all, it only plays during the first round. 
This also goes for Digimon Tamers Battle Evolution which is the Japanese version of Digimon Rumble Arena.
I'm running both versions of the game on RetroPie with the lr-pcsx_rearmed core.

**Comment by shaum257** [comment]
You mean I should update the core from source instead of binary?

**Comment by notaz** [comment]
I don't know when RetroPie updates it's cores. RetroArch has https://buildbot.libretro.com/nightly/ where you can get the latest cores, maybe there is something similar with RetroPie.

**Comment by shaum257** [comment]
I recently updated the core, and the music now also plays during the second round. It's all good :)
