### ISSUE TITLE
Some games have graphical glitches on Windows with the 32bit version of the core

### ISSUE THREAD

**Issue by bslenul** [libretro/pcsx_rearmed#682]
Seen this Reddit thread today: https://www.reddit.com/r/RetroArch/comments/wt1z2i/having_trouble_with_pcsx_on_retroarch_32bit/

I was curious so I grabbed the 32bit version of RA (https://buildbot.libretro.com/nightly/windows/x86/RetroArch.7z) and indeed it crashes on boot. I wanted to get some GDB output to maybe help devs with this but once built with `DEBUG=1` it doesn't crash anymore... From what I tried, it crashes when built with anything else than "-O0".

Idk much about debugging but I tried building the core with "-Og" instead (from what I read it's the closest thing to "-O0"?) but the GDB output is useless:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt full
#0  0x00000000 in ?? ()
No symbol table info available.
```
no idea if it helps (this is Chinese to me :p) but here's the output of "info reg":
```
(gdb) info reg
eax            0x0                 0
ecx            0x0                 0
edx            0x7f48a8            8341672
ebx            0x2a                42
esp            0x7f4cd8            0x7f4cd8
ebp            0x0                 0x0
esi            0x7f4e04            8343044
edi            0x1670f388          376501128
eip            0x0                 0x0
eflags         0x10202             [ IF RF ]
cs             0x23                35
ss             0x2b                43
ds             0x2b                43
es             0x2b                43
fs             0x53                83
gs             0x2b                43
```

It doesn't seem to be anything new, I tried a random commit from July 2020 and it crashes too. Only tried on Windows 10, no idea if this is happening on Linux too.

**Comment by notaz** [comment]
I've patched it up and the interpreter works for me (under wine on Linux).

@pcercuei on win32 lightrec just reads or writes to some weird address from generated code. I wasn't able to disassemble the full code (winedbg wasn't behaving for me).
```
Threaded recompiler started with 1 workers.
_jit->code.ptr 0A270000-0A270132 (mmap rwx)
_jit->code.ptr 0A270000-0A270132 (mmap rwx2)
_jit->code.ptr 0A270000-0A271132 (mprotect rx)
_jit->code.ptr 0A280000-0A28016C (mmap rwx)
_jit->code.ptr 0A280000-0A28016C (mprotect rx)
Memory map is sub-par. Emitted code will be slow.
M=0xc9a0000, P=0xcba0000, R=0xa860000, H=0xa740000
_jit->code.ptr 0A290000-0A2900FB (mmap rwx)
_jit->code.ptr 0A290000-0A2900FB (mprotect rx)
wine: Unhandled page fault on write access to 0000002C at address 0A29001A (thread 05e4), starting debugger...
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:0a29001a ESP:0163f968 EBP:0163faa4 EFLAGS:00210246(  R- --  I  Z- -P- )
 EAX:0000002c EBX:000008a0 ECX:ffffffff EDX:00000000
 ESI:00000000 EDI:0e460020
Backtrace:
=>0 0x0a29001a (0x0163faa4)
  1 0x0e460020 (0x0bd7fd80)
0x0a29001a: addb        %al,0x0(%eax)
Modules:
Module  Address                 Debug info      Name (226 modules)
PE      001a0000-001ed000       Deferred        win32u
PE      00400000-01336000       Deferred        retroarch
```

**Comment by pcercuei** [comment]
Noted.

**Comment by bslenul** [comment]
Tested a bit with a few games, seems to work fine with interpreter indeed 👍 

However there are now build errors for Apple platforms, which prevent the core from the online updater to be updated (even for platforms where it builds fine): https://git.libretro.com/libretro/pcsx_rearmed/-/jobs

The following is about Lightrec only:

It's pretty hit or miss, some games work flawlessly, some crash and some have messed up polygons (Crash Bandicoot 2 and 3 and CTR for example):

![image](https://user-images.githubusercontent.com/33353403/187406846-0cb0e2d1-e957-4884-8c0e-c697f5891373.png)

On Ape Escape the lights from the apes' hat are glitched too, I think this is 2D:

![image](https://user-images.githubusercontent.com/33353403/187409732-51877fe3-d7a4-44cc-b53d-2aaa27c313c8.png)

And restarting game always crashes RetroArch.

Crash Bandicoot crashes on boot with this in logs:
```
Threaded recompiler started with 1 workers.
Memory map is sub-par. Emitted code will be slow.
Lightrec RAM usage: IR 126 KiB, CODE 417 KiB, MIPS 86 KiB, TOTAL 3265 KiB, avg. IPI 4.823349
ERROR: Segmentation fault in recompiled code: invalid load/store at address 0xfffffeee
ERROR: Was executing block PC 0x80013970
Exiting at cycle 0x10170d04
```
Nothing for the restart crashes however :/ 

Still, that's a HUGE progress for 32bit users, thank you for this!

**Comment by bslenul** [comment]
After double checking, the crashes (Crash Bandicoot and the restarts) happen on the 64bit version as well. Same for the Ape Escape glitch, the polygon glitches are exclusive to the 32bit version however.

**Comment by pcercuei** [comment]
Doesn't happen on Linux.

**Comment by pcercuei** [comment]
I booted Crash Bandicoot 2 on retroarch win32 + latest pcsx_rearmed_libretro, the menu looks fine, nothing like what yours show.
With that said... If I go a bit further in-game I see textures that show the same problem. I don't get crashes, though.

I did see a few "no registers available, abandon ship" error messages which is never a good sign. I pushed a fix to lightrec master and those errors disappeared (at least on Crash 2) but the texture issues are still there.

**Comment by bslenul** [comment]
Yeah sorry, that screenshot was from Crash 3 title screen.

**Comment by pcercuei** [comment]
Ok, I get it in Crash 3.

Running with Lightrec's interpreter (setting `LIGHTREC_INTERPRETER=1`) does not make the problem disappear, which is kind of a good news - that means it is not a code generation problem.

**Comment by pcercuei** [comment]
@notaz I pushed lots of threading fixes to the lightrec master branch (those were being worked on for a while), it should be *almost* race-free now. Do you still get crashes?

**Comment by bslenul** [comment]
Tested with your repo (Windows only):

* RetroArch 64bit: black screen with all the games I tested. They run fine with `LIGHTREC_INTERPRETER=1`.
* RetroArch 32bit: Crash Bandicoot doesn't crash anymore, however all the games I tried are very sloooooooow, and I mean internal FPS, the "real-time" FPS or whatever it's called is normal at 60:

![image](https://user-images.githubusercontent.com/33353403/187681887-225cbe0d-a055-4bf8-b5cc-52c78ec390cb.png)

just like for the 64bit version, it runs perfectly fine with `LIGHTREC_INTERPRETER=1`.

Same for the restart crashes, they don't seem to happen with `LIGHTREC_INTERPRETER=1`.

**Comment by notaz** [comment]
> @notaz I pushed lots of threading fixes to the lightrec master branch (those were being worked on for a while), it should be _almost_ race-free now. Do you still get crashes?

It turned out to be a compilation issue. In my setup, if deps/lightning/lib/lightning.o is compiled without `-fno-strict-aliasing` it somehow starts inserting 00 00  `add %al,(%eax)` into the instruction stream which naturally crashes. I haven't investigated further.

**Comment by bslenul** [comment]
So about the black screen (RA 64bit) and poor performance (RA 32bit) issues on Windows, I bisected a bit for both 64bit and 32bit with your repo @pcercuei:

On RA 64bit this is first commit where the black screen started: https://github.com/pcercuei/lightrec/commit/dd5bbfb5533251c47932c833699139d2fb2c5473

On RA 32bit the same commit \*seems\* to be the first one where games started to run very slowly, however the 2 previous commits (https://github.com/pcercuei/lightrec/commit/f29bb851744aea3f6c5209c8b168ffd283d6ddbb and https://github.com/pcercuei/lightrec/commit/b8a68533acec9642460e6ed2e6094a04351e4c81) crash RetroArch, so I can't confirm at 100%.

**Comment by pcercuei** [comment]
Try this patch:
```
diff --git a/regcache.h b/regcache.h
index 255d7bd..eb42486 100644
--- a/regcache.h
+++ b/regcache.h
@@ -21,6 +21,10 @@
 /* JIT_R0 is callee-saved on PowerPC, we have to use something else */
 #  define LIGHTREC_REG_CYCLE _R10
 #  define FIRST_TEMP 0
+#elif defined(__i386__) || defined(__x86_64__)
+#  define NUM_TEMPS (JIT_R_NUM - 1)
+#  define LIGHTREC_REG_CYCLE (JIT_R(JIT_R_NUM - 1))
+#  define FIRST_TEMP 0
 #else
 #  define NUM_TEMPS (JIT_R_NUM - 1)
 #  define LIGHTREC_REG_CYCLE JIT_R0

```

**Comment by bslenul** [comment]
It closes RA and leaves retroarch.exe open in the background (I have to close it with the task manager), on both 32/64 versions.

**Comment by pcercuei** [comment]
Well now the behaviour is similar, that's progress! ;)

**Comment by pcercuei** [comment]
Before working on the crashes and slowdowns, we need to figure out why Crash 3's textures are garbled. This happens with Lightrec's interpreter too, so it must be something wrong in the glue code, either for the GTE or hardware regs.

**Comment by pcercuei** [comment]
@bslenul Can you try the latest git master? It does seem to work fine here on Windows x64 (I only tested Crash 2 & 3 though).

**Comment by bslenul** [comment]
AFAICT all good on both RetroArch 32 and 64bit, no more crashes, no more black screens, no more games running at 5fps, etc. I'll test a few more games tomorrow to be sure.

In any case, the 32bit crash on load is fixed so I'll close this issue, should I open a new one for the graphical glitches on the 32bit version (+ the Ape Escape one that happens on 64bit too)? If yes, here or on your lightrec repo?

Thank you to both of you as usual! 👍

**Comment by pcercuei** [comment]
@bslenul Let's keep this one open, maybe rename the title to "Windows 32-bit issues". Then we can close it when Windows x86 is on-par with the other architectures.

You can open a bug report for Ape Escape on Lightrec's repo, it seems to happen on all architectures, including on Lightrec's own interpreter (so not a code generation issue).

**Comment by notaz** [comment]
I assume this can be closed by now.
