### ISSUE TITLE
Misadventures of Tron Bonne audio cue issues

### ISSUE THREAD

**Issue by ZapBlaze** [libretro/pcsx_rearmed#683]
there seem to be some audio hiccups in the core for this game. notably, the title screen only has one voice as opposed to several (it's supposed to be tron and the servbots, but you only hear tron) and the recorded audio in the game seems to cut out early. so it might seem like things are fine at first as several voice bubbles will play totally fine, but whichever one is the end of the recording will cut out early at the end. so you get something like "blah blah blah blah bl-" 

dynamic recompiling and clock speed do not appear to have an effect on this, and the always active SPU turns off voice recordings entirely without altering the timing. 

since it appears to be an issue with the core, it's easily repeatable if you just listen to the cutscenes in the game. it's very consistent in where it cuts out. one such spot is at the beginning where tiesel meets bon and he says "the gustav is doing gr-". it's a consistent issue with the audio throughout the game. 

sound effects and music play fine, this appears to be an issue with recorded lines specifically.

**Comment by notaz** [comment]
I have no idea what's wrong with the title screen voices. Such issues take forever to track down so there is little motivation to sink days into it, so unless somebody knows (and is willing to share) what the game is doing there this is unlikely to get fixed.

I've tried to patch the cut outs, try a newer build.

**Comment by ZapBlaze** [comment]
i believe i'm using the newest build available. either way, i just thought i'd bring some attention to it. you guys have been good at fixing this stuff without specific fixes lately. it probably just requires further development to accurately emulate the source hardware, and i understand that it probably won't be  time soon. i'm just glad more knowledgeable people still care about stuff like this.

**Comment by notaz** [comment]
BTW if you don't start the game wait for the demo/story, when it comes back to the title again it plays many voices. There is also at least one video on youtube with a single voice: https://youtube.com/watch?v=DURLct8TpQA

I suspect it might be intended to be random by the game devs, and on different emulators it behaves different because it's RNG gets seeded differently. It would be interesting to see if it's random on the real console.

**Comment by ZapBlaze** [comment]
that's very good to know. that's a very real possibility for the title screen. it could be. or i could have just noticed something and i didn't double check. it's been a couple weeks now, so it's not a bad idea to rule out the possibility. honestly, the stuff that happens in game, the spoken dialogue, is a much more egregious problem.  at least that's one less thing to worry about, no?

**Comment by notaz** [comment]
The audio no longer cuts out for me in this game.
