### ISSUE TITLE
PCSX-Rearmed Unai on N2DSXL bottom_menu.png

### ISSUE THREAD

**Issue by mahirahman** [libretro/pcsx_rearmed#684]
Error message when loading content on the bottom screen: bottom_menu.png not found in assets/ctr folder
Running the latest PCSX Core version and Retroarch from last weeks nightly build.
I've checked the folder, and the file bottom_menu.png is present. It seems to not be able to find it for some reason?

**Comment by notaz** [comment]
Is this really an emu core issue? There is no such png file anywhere in the repository, and it doesn't need such a file for emulation.

**Comment by hizzlekizzle** [comment]
Yeah, I believe this is a RetroArch thing rather than a core thing.

**Comment by mahirahman** [comment]
Thanks, it seems a similar issue occurred with a different core. Most likely an issue with Retroarch. Will forward to them.
