### ISSUE TITLE
 Syphon Filter 2 does not change disk

### ISSUE THREAD

**Issue by spielvan** [libretro/pcsx_rearmed#689]
Syphon Filter 2 does not change disks, I tested several versions of syphon filter 2 in several versions of pcsx_rearmed and even in pcsx_rearmed of psx mini, and they all gave the same result, I load disk 2 first and when it asks for disk 1 and change it from disk error, then I load the game through epsxe and do the same process and it works normally when changing disks.

**Comment by notaz** [comment]
For someone unfamiliar with the game, can you give a guide how to reproduce the issue?

**Comment by spielvan** [comment]
> For someone unfamiliar with the game, can you give a guide how to reproduce the issue?

I'm using the last retroarch on the android tv box, I load the retroarch and then the pcsx_rearmed core, soon after I load the disc 2 of the syphon filter 2 game, I go to it until it asks for the change of disc for disc 1, in the menu of retroarch mute for disk 1 it will load but it gives a disk error message "Wrong disc inserted", then loading the same game in epsxe in the same android box the game changes disk normally.

Note: The bug also occurs in psx mini both in retroarch and in the standard player.

**Comment by bslenul** [comment]
> For someone unfamiliar with the game, can you give a guide how to reproduce the issue?

Start the game with disc 2, select "new game", the game will ask to insert disc 1, insert it and you should get a "wrong disc" error.

Note that you can save in-game after each mission so until it's fixed you can still load disc 2 then load your in-game save. I'm not familiar with the PS Classic tho, you may have to rename the save file for it to work with disc 2 (make a backup first, just in case).

**Comment by CometHunter92** [comment]
Something similar happens with the PAL Metal Gear Solid: Special Missions too. 
To play the game you have to launch the Special Missions disc, then insert the Metal Gear Solid disc 1, and then reinsert the Special Missions disc again: when the game asks for the Metal Gear Solid disc 1 it says "wrong disc inserted", and so it's unplayable.

**Comment by bslenul** [comment]
> Something similar happens with the PAL Metal Gear Solid: Special Missions too.

Idk if it was fixed recently or if it's platform specific, but I can't reproduce with latest commit (5507b49e3a9c46591ebe099961f76000a2ea1b45 when typing this) on my old Android phone and on Windows 10, it switches just fine.

**Comment by CometHunter92** [comment]
> > Something similar happens with the PAL Metal Gear Solid: Special Missions too.
> 
> Idk if it was fixed recently or if it's platform specific, but I can't reproduce with latest commit ([5507b49](https://github.com/libretro/pcsx_rearmed/commit/5507b49e3a9c46591ebe099961f76000a2ea1b45) when typing this) on my old Android phone and on Windows 10, it switches just fine.

Oh you're right, it's solved now!

**Comment by notaz** [comment]
> Syphon Filter 2 does not change disks

Please try a version with the latest commits.

**Comment by spielvan** [comment]
> 

The bug was fixed in commint (c4e6218), now the syphon filter 2 switches disks perfectly. Thank you very much for your help and I will continue to inform you if I find bugs in other games.

**Comment by spielvan** [comment]
@notaz I had to reopen the post, because in the last build the disk swap bug returned, the same had been fixed in the commint (c4e6218) in September, but I ended up updating it to the last version and not making a backup, I could have make commit (c4e6218) available again? until I know I can fix the bug again. Thank you so much.

**Comment by notaz** [comment]
Turns out there were multiple bugs causing this issue, the second bug was uncovered recently by unrelated changes. Hopefully it won't return now.

**Comment by spielvan** [comment]
> Turns out there were multiple bugs causing this issue, the second bug was uncovered recently by unrelated changes. Hopefully it won't return now.

Thanks for the help, the problem was solved on Commin 48e85d1 now I made a backup of it.
