### ISSUE TITLE
Enhanced Resolution for 64-bit

### ISSUE THREAD

**Issue by ozgurkazancci** [libretro/pcsx_rearmed#690]
Greetings.

Any plan to bring the "enhanced resolution" feature for 64-bit version of lr-pcsx-rearmed?

**Comment by ds22x** [comment]
It's already available for both x86-64 and arm64 with the latest version of the core.

**Comment by eadmaster** [comment]
It seems missing in the android builds...

**Comment by hizzlekizzle** [comment]
@eadmaster are you using the version from the Play Store? if so, it's stuck on an old RetroArch and old core versions.

**Comment by eadmaster** [comment]
> @eadmaster are you using the version from the Play Store? if so, it's stuck on an old RetroArch and old core versions.

nervermind, just updated to the latest core and the option is back again in the "GPU Plugin" section.
