### ISSUE TITLE
Crackling sound in Intro fmv of Suikoden II and similar sound issues, with other games.

### ISSUE THREAD

**Issue by abj00** [libretro/pcsx_rearmed#691]
Raspberry PI3B , official psu
RetroPIe 4.8.2 (Rasbian Buster LIte 32 bit)

I have issue with crackling/chop sound  in the Intro fmv of Suikoden II(USA). 
Also, a similar problem occurs momentarily, during the intro of Gran Turismo 2(USA) ,Final Fantasy IX(USA), in the beginning of a battle in Final fantasy IX(USA) , Grandia (USA).

I have validated Roms and Bios files. The above issues don't happen with lr-swanstation. Thanks!

[runcommand.log](https://github.com/libretro/pcsx_rearmed/files/9675242/runcommand.log)

**Comment by Refaze** [comment]
I am actually currently experiencing the exact same thing.  These audio drops happen in game too but very intermittently.  The FMV issues look like it maybe multiple titles.  Final Fantasy 9 and Suikoden 2 are just some examples.  The FMV intros after you start a game seem to stutter constantly.  The audio drop outs that happen in game I've noticed the most in are the entire Final Fantasy series,  Tales series and Starocean.

**Comment by Refaze** [comment]
@notaz They have for me yes;  but I am unsure about Suikoden 2.

**Comment by abj00** [comment]
Thanks for the reply and for continue work to improve this emulator!

I test an older commit f788d30 and it looks that Suikoden II have the same issue. Also, the same with FF IX.

**Comment by notaz** [comment]
I've patched Suikoden II and Philosoma. I couldn't notice any FF IX FMV stutter on the pandora device (1GHz singlecore ARM), at least with the intro FMV and the one after starting the a game. Unsure what to look for in the other games either (except the expected short stutter after the game loads things).

**Comment by wmmxoxo** [comment]
for FF IX, there are certain audios that exhibit crackling sounds, such as chime sound effect when the battle turn has come during the combat, and the similar chime sound effect while in load/save.  It was possible to circumvent this issue in standalone pcsx-rearmed with Threaded SPU off tho.

**Comment by abj00** [comment]
Thanks a lot, Suikoden ii works fine now! Yes, I believe the short stutter that i saw was when the game loading stuff, nothing critical.

**Comment by Refaze** [comment]
wmmxoxo said it best.  I tested duck station and these audio issues are not there.  The FMV also plays fine without the stuttering.  These are not critical at least for me anyways.  Keep up the good work.
