### ISSUE TITLE
Suikoden 1 Looping audio

### ISSUE THREAD

**Issue by Refaze** [libretro/pcsx_rearmed#693]
Rasperry Pi Retropie
Latest version of this core

I am so sorry to bug you as you speedily fixed some other issues.  Suikoden 1 now has looping audio.  It will play the same 3 second string per whatever area you are in.  This wasn't present in the core the last time I played which was a few months back.  Now I did test with Duckstation and the looping audio is not present.  I have also not changed any settings so everything remains the same.  I know Final Fantasy 9 was mentioned in the last post;  there is also something definitely going on with the audio.  Same stuttering that was present in Suikoden II.  These are litterally the only 2 games that have issues.  I have been testing literally 100s of games,  this is one awesome emulator.  Cheers.

**Comment by notaz** [comment]
> Suikoden 1 now has looping audio

Where exactly? I gave it a quick try and failed to see any issues.

What CD image format are you using? Are you using savestates?

**Comment by Refaze** [comment]
Yikes!  I just checked my config file and it looks like SPU IRQ was enabled for some strange reason.... no idea why this was even turned on one of the kids must of done it... This fixed my audio issues and Final Fantasy 9 and Suikoden 1.  Sorry if I wasted your time but I will be closing the top now,  thanks for the help.
