### ISSUE TITLE
Fails to build on s390x arch with new lightrec

### ISSUE THREAD

**Issue by tim77** [libretro/pcsx_rearmed#694]
## Description

Fails to build on `s390x` arch with new `lightrec 20220910`.

## When did the behavior start?

Latest version which successfully compiles is 3e629be971c683d914844b487e366e0acf55539a. Since ba3814c189d3bd2332b66fb6c633a7d028e618fe won't compile on `s390x` arch.

## Your device/OS/platform/architecture

Fedora Linux; s390x arch.

## Logs (enable file logging and set log levels to DEBUG for core and frontend)

Full build [log](https://kojipkgs.fedoraproject.org//work/tasks/5807/92275807/build.log).

---

Should we try to fix this or just exclude this arch from Fedora? Before it compiles successfully for [6 arches](https://koji.fedoraproject.org/koji/taskinfo?taskID=92275736). I'll be glad for any help.

**Comment by notaz** [comment]
@pcercuei

**Comment by pcercuei** [comment]
Looks like an upstream Lightning bug, I'll report it.

**Comment by pcercuei** [comment]
@tim77 does #698 fix the s390x build?

**Comment by tim77** [comment]
@pcercuei [Yes](https://koji.fedoraproject.org/koji/taskinfo?taskID=93033022). Thank you!
