### ISSUE TITLE
lightrec should use cycle_multiplier

### ISSUE THREAD

**Issue by notaz** [libretro/pcsx_rearmed#695]
@pcercuei
There is now `Config.cycle_multiplier` that is used by ari64 dynarec and the interpreter (since yesterday). It says how many cycles an instruction should consume times 100, for example 200 means 2 cycles/instruction. This value is used to get more time sensitive games to work, examples:
- iS - Internal Section - needs >= ~200
- Parasite Eve II - needs < ~125

There is (a very incomplete) libpcsxcore/database.c with some games.

Of course the proper solution would be to emulate cache miss and IO latencies, but for now I have no plans for that.

**Comment by pcercuei** [comment]
@stenzek suggested to me that emulating more or less accurately the cycle accounting (without taking cache miss and IO latency into account) would already fix a lot of games. That's something I definitely want to try at some point.

**Comment by notaz** [comment]
There are some games relying on both extremes though, and there is no way to get them to work without such hacks IMO (while not doing cache misses and IO latencies).

**Comment by notaz** [comment]
I've added this myself to get parity with interpreter and ari64 dynarec and allow the likes of Parasite Eve to boot.
