### ISSUE TITLE
Yeh Yeh Tennis (Europe), doesn't work.

### ISSUE THREAD

**Issue by Wiindg** [libretro/pcsx_rearmed#699]
- Raspberry PI3B+
- RetroPie 4.8.1 (Debian Buster lite 32 bit)

The game is unplayable. It's soft-locking in the beginning  with the music looping, after you have to choose the language. I test with the latest version of lr-pcsx_rearmed, commit: (8622c9d).Thanks

[verbose.log](https://github.com/libretro/pcsx_rearmed/files/9791098/verbose.log)

**Comment by abj00** [comment]
It looks that the Japanese version of the game with the name : **Love Game's: Wai Wai Tennis 2** is working without issues, (maybe because it have a different intro ?). Also, the menu is in English, so we have a working version of the game.

**Comment by notaz** [comment]
While the Eur version is still not working this issue should stay open.

**Comment by VGkav** [comment]
Soft-locking? Have you tried changing that PSX clock option?

**Comment by abj00** [comment]
> Soft-locking? Have you tried changing that PSX clock option?

Yes, i change the psx clock from the default(57) to 70 and 100 but the problem still occurred. Thanks

**Comment by w1ndg** [comment]
Thank you very much game is working !!
