### ISSUE TITLE
No rumble in Snobow Kids Plus despite having rumble enabled

### ISSUE THREAD

**Issue by shaum257** [libretro/pcsx_rearmed#701]
The rumble function in Snowbow Kids Plus doesn't work even though having it enabled within the core's option settings and also within the game's settings. (It's enabled by default within the game's settings)
And yes, I have the device type set to DualShock.
I'm running the game on RetroPie with the lr-pcsx_rearmed core.

**Comment by notaz** [comment]
I don't have a rumble device but I'm seeing rumble commands being sent by the game, so this was likely fixed.
