### ISSUE TITLE
Bug on loading screens in Spyro: Year of the Dragon

### ISSUE THREAD

**Issue by RetroMarioBros** [libretro/pcsx_rearmed#703]
Loading screens of the game Spyro: Year of the Dragon have a bug is that start to move, and vibrate instead of remaining static.
A example:
https://user-images.githubusercontent.com/6499349/198978880-67958f71-396c-4016-b7d7-e88ea59e4afb.mp4

**Comment by toniosj** [comment]
I've tested the game and I have the same issue. It's PAL version.

**Comment by RetroMarioBros** [comment]
I just tried the game and it seems that this is already fixed, the screens do not flicker

**Comment by pcercuei** [comment]
@notaz do you remember how this problem was fixed? I have the same issue in CubeSX.

**Comment by notaz** [comment]
It's GP1 commands to set the fb position on the screen. It draws one frame 320x240 with 8 line top and bottom borders in fb itself, and then 320x224 without borders but with adjusted position, or something along these lines.
