### ISSUE TITLE
Need for Speed III - Hot Pursuit | Sound issue-freeze.

### ISSUE THREAD

**Issue by abj00** [libretro/pcsx_rearmed#704]
## Description

I start a new single game in Need for Speed III - Hot Pursuit (USA). During the race i press start to close the music. After that the game is loosing the sounds and if i choose to restart the race is freezing.

## Steps to reproduce

1.Start a single race
2.During the race press the "start" button and low down the Music and go back to race
3. If you press again the start and choose to restart the race the game will freeaze.

## When did the behavior start?
I don't know when this start, i  play this game months ago and i don't remember to have this issue.

## Your device/OS/platform/architecture
RPi3B+, I am using RetroPie 4.8.2(Debian Lite Buster 32 bit)

I test and the latest version of lr-pcsxreamred (commit: ca37f77), the same issue occured.
I try an older version(commit: 7e3ce9a) and the issue don't happen here
## Logs (enable file logging and set log levels to DEBUG for core and frontend)

[verbose.log](https://github.com/libretro/pcsx_rearmed/files/9923329/verbose.log)

THanks.

**Comment by CometHunter92** [comment]
There is an issue with the voiceover countdown just before the race too: not all the numbers are played.

**Comment by abj00** [comment]
I try an older version of the core (commit: 7e3ce9) and the issue don't happen here.

**Comment by abj00** [comment]
You fixed the issue, thank you very much!
