### ISSUE TITLE
OpenBIOS issue

### ISSUE THREAD

**Issue by davidhedlund** [libretro/pcsx_rearmed#708]
**Disclaimer: This issue must be solved first: 240pTestSuitePS1-EMU issue for retroarch package 1.12.0 for Ubuntu 22.04 - https://github.com/libretro/pcsx_rearmed/issues/709**

I can reproduce the issue for Windows 11 (RetroArch 1.10.3), and GNU/Linux (retroarch package 1.12.0-r202210180049+840c4481ab-163~ubuntu22.04.1).

# Retroarch setup
* Retroarch: To avoid conflicts, delete ~/.config/retroarch/, and start Retroarch to generate a new settings directory
* Retroarch: Main menu -> Online Updater -> Update Assets -- this will fix the fonts for the menu, and the assets are also required to run 240pTestSuitePS1-EMU.cue
* Retroarch: Main menu -> Online Updater -> Content Downloader -> Sony PlayStation -> 240pTestSuitePS1-EMU.zip
* Retroarch: Main menu -> Online Updater -> Update Core Info Files
* Retroarch: Main menu -> Online Updater -> Core Downloader -> Sony PlayStation (PCSX ReARMed)
* openbios.bin extracted from pcsx-redux-nightly-11167.20221114.1-x64.zip downloaded from https://install.appcenter.ms/orgs/grumpycoders/apps/pcsx-redux-win64/distribution_groups/public (link listed in https://github.com/grumpycoders/pcsx-redux/#where)

 I can use 240pTestSuitePS1-EMU.cue with the OEM BIOS, but not with OpenBIOS (black screen, and no error message in the terminal:
* retroarch --libretro ~/.config/retroarch/cores/pcsx_rearmed_libretro.so ~/.config/retroarch/downloads/240pTestSuitePS1-EMU.cue

OpenBIOS + PCSX ReARMed works fine with other roms: retroarch --libretro ~/.config/retroarch/cores/pcsx_rearmed_libretro.so ~/Downloads/PlayStation\ Demo\ Disc\ Version\ 1.4\ (USA)/PlayStation\ Demo\ Disc\ Version\ 1.4\ (USA).cue

**Comment by davidhedlund** [comment]
I updated the issue. I was writing it when I was tired yesterday.

**Comment by notaz** [comment]
After some fixes the core and ARM dynarec should work well with openbios, but lightrec still has problems with it.

@pcercuei openbios+lightrec seems to work with LIGHTREC_INTERPRETER set, indicating a problem with code generation.

**Comment by pcercuei** [comment]
Latest Lightrec master (since may or so) can boot some games when using OpenBIOS, but the compatibility is lower than with the regular bios.

Is there a game in particular that works with Lightrec's interpreter + OpenBIOS, and fails with the dynarec?

**Comment by notaz** [comment]
With what's in this repo it dies early somewhere in BIOS before game even starts to load unless LIGHTREC_INTERPRETER is set. Haven't tried Lightrec master.

**Comment by pcercuei** [comment]
Using libretro's pcsx_rearmed it doesn't seem to boot, indeed. However I generally test with an older version of the standalone emu, and it works there.

**Comment by pcercuei** [comment]
@notaz latest libretro/pcsx_rearmed (3c53dce313) works with `openbios.bin` extracted from pcsx-redux-nightly-15413.20230628.2-x64.zip, as long as you are running the standalone emulator.

**Comment by notaz** [comment]
It doesn't for me. Are you sure it picks up the right bios (Options->BIOS/Plugins) and the dynarec is not disabled (Options->Advanced->Disable dynarec)?

**Comment by pcercuei** [comment]
I compiled it without support for Lightrec, ooops. Indeed it doesn't boot.

It definitely works with my older standalone pcsx build though, so maybe the bug is not directly inside Lightrec but in the glue?

**Comment by pcercuei** [comment]
I seem to get some sort of memory corruption somewhere in the PSX RAM.

This is a diff when running Libretro master standalone (+) vs. my own standalone build (-), with the exact same Lightrec configuration:
```diff
 DEBUG: Disassembled block at PC: 0x00002040
-0x00002040 (0x0)       lw      ra,20(sp)                                           (Memory access)
+0x00002040 (0x0)       lw      ra,1556(sp)                                         (Memory access)
 0x00002044 (0x4)       nop                                                         
 0x00002048 (0x8)       jr      ra                    addiu   sp,sp,0x0018          (switched branch/DS, -sp)
 0x0000204c (0xc)       addiu   sp,sp,0x0018          jr      ra                    (switched branch/DS, -ra)
 DEBUG: Block size: 4 opcodes
 DEBUG: Blocks created: 229
```

**Comment by notaz** [comment]
It's hard to blame the glue when LIGHTREC_INTERPRETER, ari64 and pcsx's interpreter all work.

It should be "lw ra,20(sp)", according to interpreter this code writes to 0x00002040:
```
ROM:BFC081F8 loc_BFC081F8:
ROM:BFC081F8                 bne     $v1, $a2, loc_BFC08208
ROM:BFC081FC                 addu    $a0, $a1, $v1
ROM:BFC08200                 jr      $ra
ROM:BFC08204                 nop
ROM:BFC08208
ROM:BFC08208 loc_BFC08208:
ROM:BFC08208                 lbu     $a3, 0($a0)
ROM:BFC0820C                 addu    $a0, $v0, $v1
ROM:BFC08210                 sb      $a3, 0($a0)
ROM:BFC08214                 b       loc_BFC081F8
ROM:BFC08218                 addiu   $v1, 1
```

**Comment by pcercuei** [comment]
I'm not blaming anything, I'm just wondering why OpenBIOS works with my version of the standalone emulator. I absolutely do not discard it to be a bug with the dynarec.

**Comment by pcercuei** [comment]
@notaz ok, it is definitely a glue issue :)

If you make `lightrec_can_hw_direct()` return false, the games will boot. I suppose one of the listed addresses should return "false", we just need to figure out which one.

FYI this function should return "true" if the I/O access is a simple register read or write that does not trigger any mechanism. In that case, Lightrec will access it with fastmem. If it returns "false" then the execution jumps to a C routine.

**Comment by notaz** [comment]
You can use `new_dyna_pcsx_mem_init()` as a reference, where it does `map_item` on `mem_iortab` and `mem_iowtab`.

**Comment by pcercuei** [comment]
I had a quick look yesterday, it's enough for 32-bit reads targetting IREG / IMASK (0x1070 / 0x1074) to return "true" (with everything else returning "false") to trigger the problem. This doesn't really make any sense IMHO, since these are clearly direct-memory accesses according to psxhw.c.

So it might actually be triggering the bug somewhere else...

**Comment by pcercuei** [comment]
Should be fixed now.

**Comment by davidhedlund** [comment]
> Should be fixed now.

Thank you for all your hard work!
