### ISSUE TITLE
OpenBIOS issue with 240pTestSuitePS1-EMU

### ISSUE THREAD

**Issue by davidhedlund** [libretro/pcsx_rearmed#709]
Issue valid for:
* Ubuntu GNU/Linux 22.04 + OpenBIOS + RetroArch 1.12.0 + 240pTestSuitePS1-EMU
* Windows 11 + OpenBIOS + RetroArch 1.10.3 + 240pTestSuitePS1-EMU

# RestroArch setup
* Retroarch: To avoid conflicts, delete ~/.config/retroarch/, and start Retroarch to generate a new settings directory
* Retroarch: Main menu -> Online Updater -> Update Assets -- this will fix the fonts for the menu, and the assets are also required to run 240pTestSuitePS1-EMU.cue
* Retroarch: Main menu -> Online Updater -> Content Downloader -> Sony PlayStation -> 240pTestSuitePS1-EMU.zip
* Retroarch: Main menu -> Online Updater -> Update Core Info Files
* Retroarch: Main menu -> Online Updater -> Core Downloader -> Sony PlayStation (PCSX ReARMed)
* OpenBIOS: openbios.bin extracted from pcsx-redux-nightly-11167.20221114.1-x64.zip downloaded from https://install.appcenter.ms/orgs/grumpycoders/apps/pcsx-redux-win64/distribution_groups/public (link listed in https://github.com/grumpycoders/pcsx-redux/#where)
* Cannot run: retroarch --libretro ~/.config/retroarch/cores/pcsx_rearmed_libretro.so ~/.config/retroarch/downloads/240pTestSuitePS1-EMU.cue

**Comment by hizzlekizzle** [comment]
works fine for me.

**Comment by davidhedlund** [comment]
> works fine for me. EDIT: ah, I see this is with OpenBIOS, as per #708?

No, I cannot use this command with any BIOS:
* retroarch --libretro ~/.config/retroarch/cores/pcsx_rearmed_libretro.so ~/.config/retroarch/downloads/240pTestSuitePS1-EMU.cue

**Comment by hizzlekizzle** [comment]
I loaded it just fine with an official BIOS in Ubuntu Mate 22.04 using the RA package from the nightly PPA and whatever the latest PCSX-ReARMed build is. I checked and the dynarec was even enabled.

**Comment by davidhedlund** [comment]
> I loaded it just fine with an official BIOS in Ubuntu Mate 22.04 using the RA package from the nightly PPA and whatever the latest PCSX-ReARMed build is. I checked and the dynarec was even enabled.

Thanks for your help!

Can you please try this with a brand new ~/.config/retroarch/ directory, see instructions at the top post, it doesn't work for me.

**Comment by davidhedlund** [comment]
> works fine for me. EDIT: ah, I see this is with OpenBIOS, as per #708?

Sorry, yes.

**Comment by davidhedlund** [comment]
> I loaded it just fine with an official BIOS in Ubuntu Mate 22.04 using the RA package from the nightly PPA and whatever the latest PCSX-ReARMed build is. I checked and the dynarec was even enabled.

Thanks.

**Comment by davidhedlund** [comment]
Same issue in both Ubuntu and Windows with:
* retroarch --libretro ~/.config/retroarch/cores/pcsx_rearmed_libretro.so ~/Downloads/PlayStation\ Demo\ Disc\ Version\ 1.4\ \(USA\)/PlayStation\ Demo\ Disc\ Version\ 1.4\ \(USA\).cue

So it's not specifically a 240pTestSuitePS1-EMU issue
