### ISSUE TITLE
scph5501.bin cannot be used in RetroArch 1.12.0 + Ubuntu 22.04

### ISSUE THREAD

**Issue by davidhedlund** [libretro/pcsx_rearmed#710]
scph5501.bin + RetroArch 1.12.0 + Ubuntu 22.04

* sudo apt-get update && sudo apt-get install retroarch
* Retroarch: Online Updater -> Content Downloader -> Sony PlayStation -> 240pTestSuitePS1-EMU.zip
* Retroarch: Online Updater -> Core Downloader -> Sony PlayStation (PCSX ReARMed)
* Copied an original PlayStation BIOS, scph5501.bin (dumped from a console) to ~/.config/retroarch/system/
* retroarch --libretro ~/.config/retroarch/cores/pcsx_rearmed_libretro.so ~/.config/retroarch/downloads/240pTestSuitePS1-EMU.cue

output:

`
Regular mmap to address 0x10000000 succeeded
Regular mmap to address 0x10200000 succeeded
Regular mmap to address 0x10400000 succeeded
Regular mmap to address 0x10600000 succeeded
Regular mmap to address 0x2fc00000 succeeded
Regular mmap to address 0x10800000 succeeded
Memory map is sub-par. Emitted code will be slow.
Using 32-bit LUT
`
* Same error with another .cue file that are working great in Windows 11 or in Ubuntu with the other PlayStation libreto-cores: --libretro ~/.config/retroarch/cores/pcsx_rearmed_libretro.so ~/Downloads/PlayStation\ Demo\ Disc\ Version\ 1.4\ (USA)/PlayStation\ Demo\ Disc\ Version\ 1.4\ (USA).cue

scph5501.bin + RetroArch 1.10.3 + Windows 11 worked fine for 240pTestSuitePS1-EMU. Also, the other libretro-cores are working fine with scph5501.bin :
* retroarch --libretro ~/.config/retroarch/cores/mednafen_psx_hw_libretro.so ~/.config/retroarch/downloads/240pTestSuitePS1-EMU.cue
* retroarch --libretro ~/.config/retroarch/cores/mednafen_psx_libretro.so ~/.config/retroarch/downloads/240pTestSuitePS1-EMU.cue
* retroarch --libretro ~/.config/retroarch/cores/swanstation_libretro.so ~/.config/retroarch/downloads/240pTestSuitePS1-EMU.cue

**Comment by hizzlekizzle** [comment]
I can't reproduce this. All of my testing has been with scph5501.bin, RA 1.12.0 nightly and Ubuntu 22.04.

**Comment by davidhedlund** [comment]
Sorry, it is actually working. I deleted the .retroarch directory and started all over. I'm very sorry that I stole your time but I respect you very much for your help!
