### ISSUE TITLE
Grandia Display issues 

### ISSUE THREAD

**Issue by Refaze** [libretro/pcsx_rearmed#712]
Batocera V35
Raspberry Pi 4
Windows 10 (No special systems,  just Retroarch)

Good day,  having some display issues with Grandia.  I have tried different roms /formats (ISO, CHD etc).  I get a flashing bar going down the right hand side of the screen. Its very small but its there.  Any ideas?  I tried running the game with Swanstation and it works fine.  I am overclocked to 1800 -  I have no special settings enabled.  Everything is set to auto.  You would think it just being a small bar it would be ok but its very distracting.  I also loaded the core on my windows PC and having the same issue with Grandia so I suspect its across multiple devices if not all devices.  Please see the below link,  its not from me but it will show you exactly what's going on;

https://www.reddit.com/r/RetroArch/comments/etxwg7/its_harder_to_pick_up_on_camera_but_the_right/ 

Now with everything being said;  you can just stretch your overlay and BAM its gone.  Sorry to report such a small issue but I strongly believe your core to be one of the best!

**Comment by Vexnik** [comment]
This also happens on Super Puzzle Fighter II Turbo & D where the screen is not aligned properly leaving a giant black bar.

**Comment by notaz** [comment]
The Grandia issue should be fixed.

Super Puzzle Fighter II Turbo seems to be programmed that way, vertical miscentering + FMV flicker and slight horizontal miscentering are visible in hardware captures like [this](https://www.youtube.com/watch?v=ri4f015fTzs) and [this](https://www.youtube.com/watch?v=I8tUCYjl7Ck) too. There are now new options to override game's centering to deal with that.
