### ISSUE TITLE
ToCA World Touring Cars doesn't work on the arm64

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#713]
As the title, this game doesn't work with the arm64 version of the core, it crashes just at the beginning of the title screen.
The arm32 version works flawlessy.

**Comment by hizzlekizzle** [comment]
Have you tried disabling the dynamic recompiler to see if it works any better on 'interpreter'?

**Comment by notaz** [comment]
Should be fixed, including interpreter and even lightrec.

@pcercuei take a look at e57621e0f476eaec8770927da94f3eea8304341f

**Comment by CometHunter92** [comment]
Solved, thanks!

**Comment by pcercuei** [comment]
@notaz thanks (and welcome back). Fixed in https://github.com/pcercuei/lightrec/commit/fcf239e7e9d42fedb7a8de64057d6895acf3ceee
