### ISSUE TITLE
Brave Fencer Musashi is unplayable with recent updates

### ISSUE THREAD

**Issue by ViperAcidZX** [libretro/pcsx_rearmed#714]
## Description

I recently updated my Raspberry Pi 3B+ to a newer update of PCSX-ReARMed libretro core through RetroPie and whatever this new update for the core did rendered it unplayable beyond the opening cutscenes or even skipping when starting a new game. I tried various suggested fixes/alterating settings from Reddit users and RetroPie forum users and none of them worked and the one on the latter forum suggested is no longer available because the Parasite Eve II and Vandal Hearts fixes are stripped out of the recent builds of PCSX-ReARMed. I have tried updating the BIOS file for PS1 emulation and same problem persists. I also tried reproducing the same problems on my Windows computer with RetroArch and the game still fails to play past the opening cutscenes when starting a new game. I wanted to play this on my Raspberry Pi 3B+ but this problem rendered the game unplayable and Raspberry Pi 3B+ is sadly not good enough to play Brave Fencer Musashi on DuckStation because of severe performance problems it has with that game.

## Steps to reproduce

Try running Brave Fencer Musashi on current releases of PCSX-ReARMed libretro core via RetroArch, start a new game, game freezes on loading screen. Attempted lowering the CPU Speed from 57 to 55, and turning off dynamic recompiler.

## When did the behavior start?
Circa 2022; I had an older version of this core and it was playable just fine before this new update broke it.

## Your device/OS/platform/architecture
Raspberry Pi 3B+ (ARM v7) running RetroPie v4.8. Problem also happens with Windows on RetroArch v1.14.0.

**Comment by hizzlekizzle** [comment]
Seems okay here in Win64. I had a black screen on a new game right before the actual action started, but once I set the dyamic recompiler to OFF (didn't even have to restart the core), it snapped out of it.

**Comment by abj00** [comment]
I tested with the latest pcsx-rearmed commit in RetroPie 4.8.2(i choose to build the core from source). I had the same issue but when i changed psx cpu clock from 57 to 72 game is working fine.

**Comment by ViperAcidZX** [comment]
> I tested with the latest pcsx-rearmed (commit [aced3eb](https://github.com/libretro/pcsx_rearmed/commit/aced3eb3fcaa0fe13c44c4dd196cdab42555fd98) ) in RetroPie 4.8. 2 (i choose to build the core from source). I had the same issue but when i changed psx cpu clock from 57 to 72 game is working fine.

This worked but I had to revert the clock speed back to 57 since after that issue if it is left at 72 the game's audio begins to desync.

**Comment by Vexnik** [comment]
I can confirm this is happening too on my Miyoo Mini, game simply went into a black screen after selecting new game

**Comment by notaz** [comment]
This issue is considered fixed in the latest version. Feel free to reopen if that's not the case.
