### ISSUE TITLE
Policenauts crashes Retroarch 

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#719]
Policenauts seems to work fine if you wait till the menu screen. If you press START at the very start of the game to jump the Konami and the intro sequence, Retroarch will crash. 
Tested on various devices, I'm talking about the 32 bit arm version of the core.
Doesn't happen on the arm 64 bit version of the core.

**Comment by notaz** [comment]
Doesn't reproduce for me on 32bit ARM (pandora). Have you tried things like disabling dynarec, double resolution? Can you get any logs?

**Comment by CometHunter92** [comment]
Happens either with the english patched version or the original japanese version. Tried to disable dynamic recompiler and it crashes too. Enabling double resolution strangely permits to go the main menu without crashes, but after pressing START for a brief moment the "KONAMI" screen appears but cutted in half. After that you go in the main menu without issues. Didn't tested it further. Devices are an RG552, and RG353P and an RG35XX, cores compiled by myself at the latest commit. I don't have any other devices where to test it now.

**Comment by CometHunter92** [comment]
Here's the log from the RG35XX. It ends abruptly.
[retroarch__2023_07_06__23_38_20.log](https://github.com/libretro/pcsx_rearmed/files/11972727/retroarch__2023_07_06__23_38_20.log)

**Comment by notaz** [comment]
I feel like I tracked it down, please give it a try.

**Comment by CometHunter92** [comment]
Ok, solved! Thanks
