### ISSUE TITLE
Various graphical issues

### ISSUE THREAD

**Issue by Alevam-Inc** [libretro/pcsx_rearmed#720]
Issue 1: The width of certain sprites in a number of 2D games is increased by one pixel.

![Gekioh - Shooting King (USA)-230309-092137](https://user-images.githubusercontent.com/50853470/224106440-3d538e6a-4eb0-4b33-b3ab-c7f4ffbb103b.png)

![Raiden Project, The (USA)-230309-091054](https://user-images.githubusercontent.com/50853470/224106460-c063ed4d-f766-4dba-b1e8-9b5c7fc2a68a.png)

Issue 2: Some of the graphics in certain games are missing altogether.

![AirGrave (Japan)-230309-092717](https://user-images.githubusercontent.com/50853470/224107292-a837ae86-b062-4221-9537-aef6161ef950.png)

![Extreme Pinball (USA)-230309-092636](https://user-images.githubusercontent.com/50853470/224107319-03d819c2-1229-4ffc-9b39-03faff2e2538.png)

This started about a year ago.
I am running the latest version of Windows 10 on a six-core AMD Ryzen 5 PC.

**Comment by notaz** [comment]
Can you list the games in question?

**Comment by Alevam-Inc** [comment]
Yes I can:
Shienryu
Raiden Project
Raiden DX
Airgrave
Extreme Pinball

**Comment by notaz** [comment]
> Issue 1: The width of certain sprites in a number of 2D games is increased by one pixel.

Are you sure this is not the correct behavior? Looking at real hardware captures like [this](https://www.youtube.com/watch?v=-ThTHq8T-j0) and [this](https://www.youtube.com/watch?v=d5yY9mDoVm4) one, the rightmost projectiles look wider to me.

> Issue 2: Some of the graphics in certain games are missing altogether.

I can't reproduce this (Linux 64bit). Maybe it was fixed? Also make sure frameskip is off (Core options -> Video -> Frameskip), try disabling the dynarec.

**Comment by notaz** [comment]
Closing due to no response.
