### ISSUE TITLE
Turning on enhanced resolution slow causes crash

### ISSUE THREAD

**Issue by Kor-El** [libretro/pcsx_rearmed#721]
## Description

I haven’t checked for multiple games yet but on Legend of Dragoon if I turn on enhanced resolution slow it does as it says and makes the models look way better and as long as I keep the game running it’s fine. But once I close the game if I try to go back and re open it it causes retroarch to crash. I know this is the problem because I did a bunch of testing and if I go into the content config and disable it there through a file browser/manager the game works again. I’m just curious if anyone knows a way to make it stop doing that so I don’t have to remember to turn it off again before closing my game out.
Oh idk if relevant but
## Steps to reproduce

1. start a pcsx game.(I’ve only played Legend of Dragoon so idk if it’s just this game or not)
2. Turn on enhanced resolution slow in the GPU plugin settings.
3. Close game
4. Try to reopen game

## When did the behavior start?

Immediately after closing game for first time and trying to open it again later.

## Your device/OS/platform/architecture

I’m on retroarch on the Nintendo switch running pcsx rearmed

**Comment by notaz** [comment]
Can you try the latest version?

**Comment by notaz** [comment]
Closing due to no response. You can reopen or open another issue if needed.
