### ISSUE TITLE
No rumble in a Dualshock 4 connected via bluetooth

### ISSUE THREAD

**Issue by schusterro** [libretro/pcsx_rearmed#726]
## Description

There is no vibration in a Dualshock 4 controller, connected via BT to an Anbernic RG353M with ArkOS and the new PCSX-ReARMed-rumble r23l 54604e03.
Always just the console vibrates, not the controller. And reducing the rumble strength to 0% in Retroarch 32 does nothing, I have to disable it from within the game menu (Alien Resurrection [USA]) to stop the device from falling off the table because of the vibrations.

## Steps to reproduce

Start a PS1 game with rumble (Alien Resurrection [USA]), set the DS4 controller connected via BT to "dualshock", then make sure that vibrations are enabled in the game menu - it doesn't vibrate, only the Anbernic RG353M on which I am playing on.

## When did the behavior start?

I haven't tested pcsx-rearmed-rumble before commit 54604e03, only pcsx-rearmed, but that doesn't launch anymore since 54604e03 (it did before this commit, though). pcsx-rearmed-rumble is anyway preferred.

## Your device/OS/platform/architecture

Anbernic RG353M running the latest ArkOS from June 2023, with the PCSX-ReARMed-rumble core (r23l 54604e03), under Retroarch 32.

**Comment by notaz** [comment]
The emulation core only returns the values of "strong motor" and "weak motor" of the emulated PS1 dualshock controller to the frontend, then it's the frontend's job to control the device. Hence this is not an emu core bug, but whatever frontend you are using (ArkOS I guess?).
