### ISSUE TITLE
MediEvil missing sfx and music

### ISSUE THREAD

**Issue by KoyMcCloud** [libretro/pcsx_rearmed#733]
Whenever I start the game, and begin the first level, the intro music seems to be missing, or even different from what it's supposed to be, and the echo or reverb cannot be heard when characters speak, despite being supposed to hear an echo/reverb in the game.

**Comment by pcercuei** [comment]
Running on what platform / OS?

**Comment by KoyMcCloud** [comment]
PC, Windows 11, but I find it also does the same on Nintendo Switch.

**Comment by pcercuei** [comment]
Try again with the very latest version? I am testing on Linux PC, and it works fine.

**Comment by KoyMcCloud** [comment]
Nope, still the same issue. 

https://github.com/libretro/pcsx_rearmed/assets/140045780/cacbfdae-31cf-4336-b66e-5852c2622965

First video is with the PCSXRearmed Core.

This next video is with Swanstation, and how it's supposed to sound.

https://github.com/libretro/pcsx_rearmed/assets/140045780/8c0c8f60-099d-4c91-b1af-54758fa4f8e4

**Comment by pcercuei** [comment]
That's funny, I never noticed that the music was different. It seems to change at random. Are you sure it is not a feature? :)
Sometimes I can get the same intro music as in Swanstation, sometimes it's a different one.

It also happens with the interpreter, so at least it is not a dynarec thing.

And yeah these voices are missing some reverb.

**Comment by KoyMcCloud** [comment]
It's mainly the reverb I'm focused on fixing.

**Comment by notaz** [comment]
This issue is considered fixed in the latest version. Feel free to reopen if that's not the case.

**Comment by pcercuei** [comment]
@notaz I think reverb is broken again? I can't hear any reverb when the statues are talking, with the latest master (and the Reverb option enabled).

**Comment by notaz** [comment]
Works for me. Are you using threaded SPU? It's not implemented there, among some other breakage, as the UI tries to warn.

**Comment by pcercuei** [comment]
@notaz OK, I thought it has some *threading* bugs, but it otherwise was the regular SPU, threaded.

Indeed, with the threaded SPU disabled, reverb works.
