### ISSUE TITLE
Add Support for ps3 bios

### ISSUE THREAD

**Issue by newhinton** [libretro/pcsx_rearmed#734]
## Description

The most easy way to get a bios is the ps3 firmware upgrade one. However, that bios file does not work on my retropi (pi4) or my smartphone (lemuroid).

When  i use this file with retropi, the emulator just hangs with a black screen and this shows up when i start it via cli:

```
write_biu: unexpected val: 00000cc4
write_biu: unexpected val: 00000cc0
write_biu: unexpected val: 00000c04
```
After that, it never continues.

If i pull and compile the current git version on my pc, the bios-file can be selected and seems to be used just fine. (Albeit it complains about a non-standard bios-file).

## Steps to reproduce

1. Put the bios file in the bios-folder, and rename it to scph_X.bin
2. Start a psx game
3. It never boots.

## When did the behavior start?
Always

## Your device/OS/platform/architecture
Raspberry Pi4, Retropie

## Logs (enable file logging and set log levels to DEBUG for core and frontend)
No logs besides the runcommand

## Screenshots (if needed for visual confirmation)
None.

## Others (save states and/or save files nearest to the affected area, compressed)
None.

There were two commits enabling/disabling this bios, but they only allowed the file to be found.

**Comment by newhinton** [comment]
Interesting found: 

The first 512KB of the PS2 Bios are also a valid PS1 Bios.

 It runs fine in Duckstation and the standalone pcsx_rearmed, but not on android. (Just a black screen) I will test the same bios in retropie later.

**Comment by teconmoon** [comment]
Similar issue I posted upstream a long time ago: https://github.com/notaz/pcsx_rearmed/issues/273

Despite no dev activity on the specific issue posted, the latest comment there leads me to believe that this is fixed upstream and hasn't made it down to the RetroArch core yet.

**Comment by newhinton** [comment]
That was my own comment :D

The issue seems arm-specific, both upstream and this repo are able to run those bios on x86. On arm-devices (my android emulator and retropie on rasperry pi) they crash.

**Comment by teconmoon** [comment]
Oh duh, didn't notice that was you! On my original issue I had tested with RetroArch on Windows x64 and still had the same issue.

**Comment by newhinton** [comment]
Okay i just now tested it again on the pi with building from source, and with that it seems to work! At least the ps2 version, i will check the ps3 one later. 

Retropie probably needs a newer binary build for the emulator.

**Comment by notaz** [comment]
@pcercuei ps1_rom.bin now works with interpreter or the other dynarec, but lightrec is unhappy again:
```
ERROR: Segmentation fault in recompiled code: invalid load/store at address 0x1f808268
```
Probably some PS3 specific register or some backdoor to their emulator. Either way I think you shouldn't be killing the whole emu in such cases...

**Comment by pcercuei** [comment]
Do the interpreter and new_dynarec also see this load/store at address `0x1f808268`?

**Comment by notaz** [comment]
Yes, the bios has an register value init table at bfc024b0 that looks like this:
```
0xbf801020, 0x1225
0xbf80101c, 0xff
0xbf801004, 0x1f802000
0xbf80101c, 0xd2077
0xbf802070, 0xfe
0xbf801008, 0xff
0xbf801000, 0x1f000000
0xbf801008, 0x142455
0xbf801014, 0x200931e1
0xbf801018, 0x20843
0xbf80100c, 0x153044
0xbf8010f0, 0x7777777
0xbf808268, 0x40000000
0xbf808240, 0x6060a05
0xbf808248, 0x6060a05
0xbf808250, 0x6060a05
0xbf808258, 0x6060a05
0xbf808244, 0x50400
0xbf80824c, 0x50400
0xbf808254, 0x50400
0xbf80825c, 0x50400
```

**Comment by pcercuei** [comment]
I can increase the area size of hardware registers to 0x8000 and it would cover these.
However it also does I/O access to `0x1fa00000`, do you know what's there?

**Comment by notaz** [comment]
Expansion region similar to 0x1f000000, according to nocash.

**Comment by pcercuei** [comment]
Fixed in https://github.com/libretro/pcsx_rearmed/pull/742.
