### ISSUE TITLE
official pbp not working

### ISSUE THREAD

**Issue by Jimmy-Z** [libretro/pcsx_rearmed#74]
works in Mednafen PC, but not in PCSX rearmed Android and PSV

pbp converted from bin/cue by psx2pbp works on both

**Comment by AnotherLife** [comment]
This issue is about PBP files from the PSN store? I think some of them have mp3 music instead of audio tracks to bring the size down and such. PSX2PBP doesn't do that, it just uses gzip.

No reason to use or support lossy PBP files, usermade ones work great, I have used dozens. Someone should close this old issue.

**Comment by negativeExponent** [comment]
> This issue is about PBP files from the PSN store? I think some of them have mp3 music instead of audio tracks to bring the size down and such. PSX2PBP doesn't do that, it just uses gzip. Maybe that's the problem. Or maybe it's because of the format difference, don't the official PBPs have a manual embedded?
> 
> No reason to use or support lossy or SONY-customised PBP files, usermade ones work great, I have used dozens. Someone should close this old issue.

interesting. i've thought thos PSN ones needs some decrypting or something which pcsx doesn't have. only a few pbp works, non so far of the PSN ones. ill just still to cue/bin/raw format either way

**Comment by Jimmy-Z** [comment]
> This issue is about PBP files from the PSN store? I think some of them have mp3 music instead of audio tracks to bring the size down and such. PSX2PBP doesn't do that, it just uses gzip. Maybe that's the problem. Or maybe it's because of the format difference, don't the official PBPs have a manual embedded?
> 
> No reason to use or support lossy or SONY-customised PBP files, usermade ones work great, I have used dozens. Someone should close this old issue.

You may argue this is not an important issue, but an issue is an issue.

**Comment by negativeExponent** [comment]
> > This issue is about PBP files from the PSN store? I think some of them have mp3 music instead of audio tracks to bring the size down and such. PSX2PBP doesn't do that, it just uses gzip. Maybe that's the problem. Or maybe it's because of the format difference, don't the official PBPs have a manual embedded?
> > No reason to use or support lossy or SONY-customised PBP files, usermade ones work great, I have used dozens. Someone should close this old issue.
> 
> You may argue this is not an important issue, but an issue is an issue.

no one said its not an issue (don't put words in my mouth especially when you are not washing it!!!!). but atm its not important for gameplay, considering CHD is far better to use than PSN, unless its an exclusive.

**Comment by Jimmy-Z** [comment]
> > > This issue is about PBP files from the PSN store? I think some of them have mp3 music instead of audio tracks to bring the size down and such. PSX2PBP doesn't do that, it just uses gzip. Maybe that's the problem. Or maybe it's because of the format difference, don't the official PBPs have a manual embedded?
> > > No reason to use or support lossy or SONY-customised PBP files, usermade ones work great, I have used dozens. Someone should close this old issue.
> > 
> > 
> > You may argue this is not an important issue, but an issue is an issue.
> 
> no one said its not an issue (don't put words in my mouth especially when you are not washing it!!!!). but atm its not important for gameplay, considering CHD is far better to use than PSN, unless its an exclusive.

You're suggesting closing the issue, I don't want to get near your mouth.

**Comment by negativeExponent** [comment]
@this thread should be closed!

@twinaphex @hunterk

**Comment by Jimmy-Z** [comment]
Marking it won't fix is fine, if indeed not supporting mp3 audio is the reason.

Give some information to the user like a message saying the reason such a pbp will not work would be nicer, or just add one line in readme, just letting it crash without any explanation is confusing for most if not all users.

**Comment by gameblabla** [comment]
For encrypted PBPs, we might want to add support for them at some point... but then again this may be a violation of the DMCA.
