### ISSUE TITLE
PSX Mortal Kombat 4 doesn't show Character Bios

### ISSUE THREAD

**Issue by pablokks** [libretro/pcsx_rearmed#740]
Hi, I experience a game crash whenever I try to watch Character Bios, it just exits to Emulationstation. You can access it via Options ->Kombat Theater and pushing LT1 button on a controller. I have checked in ePSXe on Windows and it's working flawlessly so it's not a ROM thing. I have also try with different format (chd) but with same result. I have tried also tweaking things in Retroarch (e.g. increasing processor speed, disabling hacks) but without any luck.

Interestingly other videos like intros are seems to be working, I checked the bin file and they have the same extension like Bios videos ".STR". However in Bios folder there are also ".TGA" files. They are pictures with bio text for each character, maybe they are problematic for lr-pcsx_rearmed?

The game also crashes when you stay idle for a while, intro video is being played, than demo fights, winning streak ladder and when the Character Bio should popup the game crashes in the same manner when you try access the Bio via Kombat Theater.

I know that this only a minor thing and it doesn't stop you with playing a game, but nobody has mentioned about it before and maybe it will be useful for someone. I think it's always good to try emulate game as much flawlessly as possible and maybe there is a easy fix for it. At the bottom I am putting what runcommand.log is saying whenever a crash appears. Four digits after "line 1314" and before "Segmentation fault" are different each time.

Pi Model or other hardware: 3B+
Power Supply used: official Raspberry
RetroPie Version Used: 4.8.4
Built From: Pre made SD Image on RetroPie website
USB Devices connected: No
Controller used: 8bitdo M30
File: \retropie\roms\psx\Mortal Kombat 4 (USA).cue
Emulator: lr-pcsx_rearmed
How to replicate the problem: go to Options -> Kombat Theater -> and press L1 on any of the videos

Runcommand.log:

```
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-pcsx-rearmed/pcsx_rearmed_libretro.so --config /opt/retropie/configs/psx/retroarch.cfg "/home/pi/RetroPie/roms/psx/Mortal Kombat 4 (USA).cue" --appendconfig /dev/shm/retroarch.cfg
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1314:  2302 Segmentation fault      /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-pcsx-rearmed/pcsx_rearmed_libretro
```

**Comment by pablokks** [comment]
Hi guys, I see you partially fixed this. There is no crash, video is playing with character spinning around , however bio text is missing (.TGA" files), its just empty background on the right hand side.

**Comment by pablokks** [comment]
There is a small white dot on the top of the screen, little on the left, which probably shouldn't be there, but bios are showing, thanks guys for fixing.

**Comment by notaz** [comment]
I'm closing this since the original issue is fixed. As for the white dot, I don't have a display that would show the topmost lines so can't check this on the real hardware.
