### ISSUE TITLE
[Wii] X2 - No Relief crashes after initial FMV cutscenes

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/pcsx_rearmed#741]
Hi, i'm trying to play X2 - No Relief with the newly released PCSX-ReARMed official core for the Nintendo Wii (on RetroArch Wii, NOT to be confused with Wii U).

The problem is when i try to play it, and even with the correct BIOS files, the game crashes and softlocks the Wii after passing the initial FMV cutscenes / videos and won't let me start the game because of the crashes.

I tried with different game ISOs and regions and still same problem.
On latest PCSX-ReARMed on RetroArch on Windows this problem doesn't occur.

What's happening here?

**Comment by notaz** [comment]
> What's happening here?

Wii's CPU is using different byte order compared to others making it more difficult to develop for and opens an additional class of bugs to deal with. There is no convenient development platform like raspberry-pi to do development for such a CPU, leaving just testing this emulator in another emulator which is just asking for trouble.

That said you can try disabling dynamic recompiler and see of that helps.

**Comment by Ploggy** [comment]
I know this is a Wii issue but just popping in to say this game runs fine on the WiiU Core, so I don't think its an endian issue.

**Comment by pcercuei** [comment]
Is that still happening? The game works fine in WiiSX Beta 4.0 too.

**Comment by saulfabregwiivc** [comment]
> Is that still happening? The game works fine in WiiSX Beta 4.0 too.

Sorry for late reply.
I just rechecked that game in latest PCSX-ReARMed core for Wii, and it doesn't crash anymore.
Closing this issue since it's solved, btw...
