### ISSUE TITLE
Alundra 2: A New Legend Begins (USA) [SLUS-01017], issues with loading screens and ingame videos

### ISSUE THREAD

**Issue by IoanZzZ** [libretro/pcsx_rearmed#744]
I'm_Raspberry Pi4
RetroPie 4.8.4 (Bebian Buster Lite , 32 Bit)_
_lr-pcsx-rearmed , commit:_ 6fffa2ff148630fc82e3b3ed5efa7596e38be4d0
_verbose log:_  [runcommand.log](https://github.com/libretro/pcsx_rearmed/files/12269937/runcommand.log)

Game have issues, with loading screens, it's weirdly strecthed, and with the cut scenes videos, are out of center(stuck to the upper side of the screen). Except that, game it looks to working fine. Thanks.

Pictures with the issues : 

![Alundra 2 - A New Legend Begins (USA)-230806-173925](https://github.com/libretro/pcsx_rearmed/assets/135106393/cdc8a928-3ab5-47d1-b9b4-e7195ef4f6b0)

![Alundra 2 - A New Legend Begins (USA)-230806-174058](https://github.com/libretro/pcsx_rearmed/assets/135106393/1ed3c7d5-5dde-4bdd-9418-619869b86600)

Pictures without the issues:
![Alundra 2 - A New Legend Begins (USA)-230806-174409](https://github.com/libretro/pcsx_rearmed/assets/135106393/5bd3a869-d627-4fc8-bf36-afbc90d35165)
![Alundra 2 - A New Legend Begins (USA)-230806-174445](https://github.com/libretro/pcsx_rearmed/assets/135106393/bec94619-4540-40ba-a904-0f709aaa2083)

**Comment by bslenul** [comment]
Can you retry with latest version of the core please? Seems fixed for me:

![image](https://github.com/libretro/pcsx_rearmed/assets/33353403/853898ec-751d-4b21-9c0c-175f5da2b3f8)

![image](https://github.com/libretro/pcsx_rearmed/assets/33353403/3b6ad8bf-0327-40b5-9e9d-44fe38db3955)

**Comment by IoanZzZ** [comment]
Yes it got fixed. Thank very much notaz !!
