### ISSUE TITLE
Digimon World (USA) [SLUS-01032] - Game doesn't work with the default settings.

### ISSUE THREAD

**Issue by w1ndg** [libretro/pcsx_rearmed#758]
Raspberry Pi4
RetroPie 4.8.5 (Debian Buster Lite , 32 Bit)
lr-pcsx-rearmed , commit: 15fdca9
Verbose log : [runcommand.log](https://github.com/libretro/pcsx_rearmed/files/12589505/runcommand.log)

Game is freezing, in the new game screen menu, with the default settings. If i change the psx_cpu from the default 57 to 65, then the game is working without issues. Thanks!

How to reproduce: Start the game, after the intro press start, in the next screen you can't choose anything.

**Comment by notaz** [comment]
I've changed it to apply you setting by default as fixing it properly is difficult due to the design of this emulator.

**Comment by w1ndg** [comment]
Thank you very much and thanks again for everything you are doing for this emulator!
