### ISSUE TITLE
Roswell Conspiracies - Aliens, Myths & Legends (USA) - Missing music and in game cutscene voices

### ISSUE THREAD

**Issue by joepogo** [libretro/pcsx_rearmed#762]
There is total silence when music, background ambient or notes are supposed to play, basically all streamed audio. When you receive a note/item and check it in the select menu, it almost starts playing but the voice get cut off immediately. Of all emulators tested only ePSXe works fine with this game. (does not work on pcsxr rearmed, duckstation, beetle psx, etc)

**Comment by joepogo** [comment]
Thanks for taking a look at this Notaz! I'll give it a test in a little bit and report it back here so we can close the issue.

 Is this some sort of weird edge case that not a lot of ps1 emus are emulating or something?

**Comment by notaz** [comment]
Just some unintuitive behavior of the CD controller that the game relies on.

BTW this has been fixed in mednafen almost 5 years ago, but the beetle fork is severely outdated and lacks the fix.

**Comment by joepogo** [comment]
Definitely working now! Thanks notaz!! 👊
