### ISSUE TITLE
EA Sports F1 2000 crashes at license screen

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/pcsx_rearmed#764]
Like the title says the EA Sports (aka Electronic Arts) version of F1 2000 (not confuse with the Midway one) in all regions the game crashes at the license screen.

This game only boots fine in Interpreter but it runs slow.

I asked in Lightrec repo but it seems its not a Lightrec bug.

**Comment by notaz** [comment]
Is this the same F1 that's mentioned in #763?

**Comment by Ploggy** [comment]
That PR does fix the issue above at the licence screen but the game will still crash a little later on on Wii and WiiU at least, seems to be fine on PC..

WiiU footage.
https://www.youtube.com/watch?v=HowMVV5zB3c

**Comment by saulfabregwiivc** [comment]
> Is this the same F1 that's mentioned in #763?

Yeah that one and like @Ploggy said, it now gets past the license screen but it crashes on further screens.

**Comment by pcercuei** [comment]
I just tested it on GameCube (with WiiSX) and it does crash as the same spot as in the video above.

However... when running it under PowerPC Linux (with qemu-user), it works perfectly fine. That's going to be a hard one to debug.

**Comment by pcercuei** [comment]
We fixed it in WiiSX and the bug was neither in PCSX-ReArmed, nor in Lightrec: https://github.com/emukidid/pcsxgc/commit/9f1d5ae4bf38ded679acecd5b4db39fce91d0829

So this bug report can be closed.

**Comment by saulfabregwiivc** [comment]
alright, thanks for addressing said issue.

btw, i think EA Sports F1 2000 (as well as some other games) also requires ICache emulation?

can anyone help telling me the relevant commits which add ICache emulation to Lightrec?

Thanks. Gonna close this issue since it's solved.

**Comment by pcercuei** [comment]
Lightrec has a workaround for the Midway F1 games, it does not emulate icache at all. But F1 2000 (EA version) does not seem to need it, it goes in-game without it.

**Comment by saulfabregwiivc** [comment]
> Lightrec has a workaround for the Midway F1 games, it does not emulate icache at all. But F1 2000 (EA version) does not seem to need it, it goes in-game without it.

I see, thanks ;)
Btw, can u link the commit(s) which added said workaround?

**Comment by pcercuei** [comment]
https://github.com/libretro/pcsx_rearmed/commit/8bccdd17109b041fc6a3a4ab72877d5bb2843ebe

**Comment by saulfabregwiivc** [comment]
Thanks.
> But F1 2000 (EA version) does not seem to need it, it goes in-game without it.

I see in that merged PR that EA Sports F1 2000 also needed ICache emulation :/
https://github.com/libretro/pcsx_rearmed/pull/545

**Comment by pcercuei** [comment]
> Thanks.
> 
> > But F1 2000 (EA version) does not seem to need it, it goes in-game without it.
> 
> I see in that merged PR that EA Sports F1 2000 also needed ICache emulation :/ #545

I think it was a mistake (or a typo), it's the other F1 2000 game by Midway which needs icache emulation.
