### ISSUE TITLE
Formula 1 '97 Championship Edition (NTSC) DualShock not detected

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#765]
As in the title, even if a "DualShock " is plugged in the libretro controller port 1, the game doesn't enable the analog mode. In the main menu, if you press SELECT to enter the option menu, and select "Controller Setup" it says "option not available", so the analog steering is not enabled.
Tried it at the latest commit.

**Comment by notaz** [comment]
I don't see any attempts by this game to enable the analog mode. Perhaps the user has to press "ANALOG" button on the pad for this game? It would make sense to start emulating this button, but I don't know how to do it from a libretro core as all "retropad" buttons are already used...

**Comment by CometHunter92** [comment]
Yes, exactly, you have to press the "ANALOG" button on the pad. I thought that when "DualShock" was selected as a controller type, the "ANALOG" mode was enabled and persistent. I don't know, maybe it can be assigned to a combination of buttons or simply to a toggle in the input sub-menu in the core options.

**Comment by notaz** [comment]
> I thought that when "DualShock" was selected as a controller type, the "ANALOG" mode was enabled and persistent.

It was like that before but apparently it was causing problems like notaz/pcsx_rearmed#309 as the game expects the pad to be in digital mode on startup. That's also how the real hardware behaves...

> maybe it can be assigned to a combination of buttons

It can but it's not very intuitive and people will keep reporting bugs from not knowing.

> or simply to a toggle in the input sub-menu in the core options

The problem is that the analog mode can be toggled both by the user and by the game, I'm unsure if the emu core can change option in the frontend. If it can, on restart the frontent will remember the last setting and trigger the RE issue again...

**Comment by CometHunter92** [comment]
Yes, it makes sense, it seems a dead-end problem. 
BTW how about a "force analog mode" toggle? When a "DualShock" is selected and this option is toggled, it will force the previous behavior of having the analog mode persistently enabled; so games that need the analog mode enabled by the user (at least those that don't need to start in digital mode) can behave properly as before the https://github.com/notaz/pcsx_rearmed/commit/06c11e4a2d5b058897c39c49bd29e2612c7ed511.
I've just tested it and before this commit the game enables the analog steering when the DualShock pad type is selected, as it would have been expected.

**Comment by CometHunter92** [comment]
Update: I'm founding more games that have non working analog mode now, Dino Crisis, Gran Turismo 2 are some examples.

**Comment by notaz** [comment]
I've implemented another solution where it auto-enables analog after some delay to give time for the game's initialization to finish. Try how that works for you.

**Comment by CometHunter92** [comment]
Tested F1 97 and Gran Turismo 2, now it enables analog mode correctly. 
Thanks!

**Comment by notaz** [comment]
I've changed my mind about this as it's annoying even while testing to switch the controller type option every time. It now defaults to digital with a list of analog defaults in database.c and there is a new `L+R+Select` combo now like in the other core. You can send patches like 99104c0456c7c923f40a474c1cbefb89a092b966 to update the list, or just open an issue.

**Comment by CometHunter92** [comment]
Basically every game I've tried sticks to digital now (I know, it's the intended behaviour now), you have to enable the Analog mode every time, and is not consistent: for example in racing games you have to enable it at every race starts in the same gameplay session, football games at every match starts etc. 
Couldn't be possible to have an option to select the previous behaviour of forcing the analog mode? Like an "automatic" option for Analog Mode Toggle. Otherwise it would be very tedious to enable it every time, or in the case of adding those games to the list in database.c, it would result in a very very long list.

**Comment by notaz** [comment]
> Basically every game I've tried sticks to digital now (I know, it's the intended behaviour now)

Hmm not really, the goal is to get analog enabled by default for games that support it.

> for example in racing games you have to enable it at every race starts in the same gameplay session, football games at every match starts etc.

Please list those games if the issue still persists. It's likely an unrelated bug.

> it would result in a very very long list

I still hoping that with the right heuristics it wouldn't but we'll see I guess.

**Comment by CometHunter92** [comment]
Ok, seems to work better now. Some games still needs to enable the Analog mode manually (as on real hardware, iirc), but at least now the mode is consistent during gameplay.
