### ISSUE TITLE
[DualShock] Can't enable analog sticks for Need for Speed - High Stakes

### ISSUE THREAD

**Issue by WillySteichen** [libretro/pcsx_rearmed#766]
The game supports the DualShock and using the left analog for stearing, but you'd have to toggle it on yourself as the game doesn't auto-enable it on boot.
Problem is that PCSX-ReARMed currently doesn't have a way to either force analog to be always on, or to toggle it manually, rendering the functionality inaccessible.

**Comment by CometHunter92** [comment]
Try the latest commit, it works.

**Comment by WillySteichen** [comment]
Could have sworn I updated the core before this, but you're correct, it is working now.
