### ISSUE TITLE
Building issue latest commit main.c:(.text+0x1258): undefined reference to `plugin_link'

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/pcsx_rearmed#767]
## Description

When compiling latest commit https://github.com/libretro/pcsx_rearmed/commit/e34ef5ac7dbcc2d96abef8f16ac17b156c86df53

I'm getting the following error

/home/kelv/newc/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/toolchain/lib/gcc/aarch64-libreelec-linux-gnu/12.2.0/../../../../aarch64-libreelec-linux-gnu/bin/ld.bfd: frontend/main.o: in function `SysLoadSym':
main.c:(.text+0x1258): undefined reference to `plugin_link'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:412: pcsx_rearmed_libretro.so] Error 1

## Steps to reproduce

Build latest commit https://github.com/libretro/pcsx_rearmed/commit/e34ef5ac7dbcc2d96abef8f16ac17b156c86df53 using EMUELEC toolchain gcc 12.2.0 SDL 2.28.3 

## When did the behavior start?

The issue started on commit https://github.com/libretro/pcsx_rearmed/commit/e34ef5ac7dbcc2d96abef8f16ac17b156c86df53

## Your device/OS/platform/architecture

WSL 2.0 ubuntu 22.04 toolchain EMUELEC targeted to odroid n2+

## Logs (enable file logging and set log levels to DEBUG for core and frontend)

/home/kelv/newc/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/toolchain/lib/gcc/aarch64-libreelec-linux-gnu/12.2.0/../../../../aarch64-libreelec-linux-gnu/bin/ld.bfd: frontend/main.o: in function `OpenPlugins':
main.c:(.text+0x1068): undefined reference to `LoadMcds'
/home/kelv/newc/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/toolchain/lib/gcc/aarch64-libreelec-linux-gnu/12.2.0/../../../../aarch64-libreelec-linux-gnu/bin/ld.bfd: frontend/main.o: in function `SysLoadSym':
main.c:(.text+0x1258): undefined reference to `plugin_link'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:412: pcsx_rearmed_libretro.so] Error 1
make[1]: Leaving directory '/home/kelv/newc/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/pcsx_rearmed-e34ef5ac7dbcc2d96abef8f16ac17b156c86df53'
FAILURE: scripts/build pcsx_rearmed:target during make_target (package.mk)
*********** FAILED COMMAND ***********
make -f Makefile.libretro GIT_VERSION=${PKG_VERSION} platform=CortexA73_G12B
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************

FAILURE: scripts/install pcsx_rearmed:target has failed!

**Comment by notaz** [comment]
I don't see how that can happen. Are you using any patches? Can you post the complete compiler output?

> When did the behavior start?
> The issue started on commit https://github.com/libretro/pcsx_rearmed/commit/e34ef5ac7dbcc2d96abef8f16ac17b156c86df53

Are you saying the previous commit compiles? It just doesn't make sense.

**Comment by notaz** [comment]
I took my time to set up EmuELEC and it compiled fine with the latest hashes patched in. Try `./scripts/clean pcsx_rearmed` and rebuilding, or something.

**Comment by Kelvfimer** [comment]
I did it fixed it thx
