### ISSUE TITLE
Android - Some games have slowdowns, although the RA shows 60 FPS

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/pcsx_rearmed#77]
Before the updates which happened around September 9th, the PCSXReArmed was at the same level of performance than ePSXe.
After September 9th, first the core was broken and now some games presents slowdowns, even with the RA showing 60FPS like Rage Racer and Dead or Alive.
Rage Races had already slowdowns if you keep the rear mirror actived, but you only needed turn the option off. Now, the game shows slowdowns ever if you turn it off.
With Dead or Alive, the performance of game is worse than before.
I tried the same versions of RA and the core, both in the Ouya as in the Nexus 5, having the same results.

**Comment by notaz** [comment]
Could be related to #56 , the input changes around that time weren't great with all the crashes, lag and stuff.

Could anyone try a build from my tree? Would a .so file be enough for you to test?

**Comment by ZacharyFoxx** [comment]
Hi,

I have no idea how build the core but I can test it!
