### ISSUE TITLE
Legend of Legaia (Pal) is crashing with the 64bit core.

### ISSUE THREAD

**Issue by Cooper010** [libretro/pcsx_rearmed#773]
I am trying to play Legend of Legaia (Europe) with Batocera 38 64 bit and lr-pcsx-rearmed. Game is crashing randomly in fights after few minutes (5-10 maybe less). I tried it with the RetroPie 4.8 32 bit and the game is doesn't crash here.  I think Batocera is using lr-pcsx-reamed commit 4373e29 .

To reproduce it just start random fights in the fields (press rapidly the x button to hit the enemy) after a while it will crash.

Logs: 
[es_launch_stderr.log](https://github.com/libretro/pcsx_rearmed/files/12841137/es_launch_stderr.log)
Save file:
[Legend of Legaia (Europe).zip](https://github.com/libretro/pcsx_rearmed/files/12841146/Legend.of.Legaia.Europe.zip) (Try save file No.2)
Save state from a fight:
[Legend of Legaia (Europe).zip](https://github.com/libretro/pcsx_rearmed/files/12841210/Legend.of.Legaia.Europe.zip)
Game crash 6/10 times during this fight.

**Comment by notaz** [comment]
> 64bit core

ARM64 or PC/x86? From the log it seems to be ARM, but it would've need easier if you specified.

> lr-pcsx-reamed commit 4373e29de72c917dbcd04ec2a5fb685e69d9def3

That's almost 8 months old, there were tons of changes that might affect this, can't you try a newer version?

**Comment by Cooper010** [comment]
Sorry i forgot it. It's a Raspberry Pi4 4gb. 
I can't upgrade the core with Batocera. But i will ww

**Comment by Cooper010** [comment]
Sorry i forgot it. It's a Raspberry Pi4 4gb. 

I can't upgrade the core with Batocera. But i will try with RetroPie 64 bit to install the latest version of the core in few hours and i will report back soon.

**Comment by Cooper010** [comment]
I try the latest version of the emulator with RetroPie Bullseye 64bit and the game running without issues! Thanks and sorry for the inconvenience.
