### ISSUE TITLE
Hot Wheels - Turbo Racing crashing after initial FMV scene

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/pcsx_rearmed#775]
With the latest PCSX-ReARMed core with UNAI plugin, the game "Hot Wheels: Turbo Racing" isn't working anymore, resulting in crash after first FMV scene.

On older versions of PCSX-ReARMed which used P.E.Op.S. GPU, it works if you enable the following hack **(GPU) Fake 'GPU Busy' States**.

EDIT: Maybe it's related to this one? https://github.com/notaz/pcsx_rearmed/issues/225

**Comment by notaz** [comment]
Which version exactly is "the latest"? There was some code added a few days back that should work regardless of the plugin.

**Comment by saulfabregwiivc** [comment]
Sorry i forgot to say the version.
PCSX-ReARMed r23l 80bc142

I will try to test with the updated core.
