### ISSUE TITLE
Wii U - freezing immediately

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/pcsx_rearmed#777]
## Description

In the last couple of days, the Wii U build has been freezing immediately on launch/load, according to this report: https://www.reddit.com/r/RetroArch/comments/176qdvp/pcsx_rearmed_on_wii_u_was_so_amazing_then_i/ and confirmed by Ploggy in discord

## Steps to reproduce

On Wii U, at least, it's immediate. Just load a game or a state.

## When did the behavior start?

Just in the past couple of days. According to Ploggy's testing, it was one of these 4 commits:
https://github.com/libretro/pcsx_rearmed/commit/e53fec7170e512a8d315c6d8d04a5492b4f14312

https://github.com/libretro/pcsx_rearmed/commit/492a6fbbc06968dd93f7ec470327b0e463d9f3ed

https://github.com/libretro/pcsx_rearmed/commit/9a18263477619dad5f4d51c7b00f5929da15843a

https://github.com/libretro/pcsx_rearmed/commit/55ff71307db44c3122500104b83c21273853025c
My first guess was that maybe the new compile-time switch isn't being set to the necessary value?

## Your device/OS/platform/architecture

Wii U

**Comment by Ploggy** [comment]
Bisecting has narrowed down the commit to this?

55ff71307db44c3122500104b83c21273853025c is the first bad commit
commit 55ff71307db44c3122500104b83c21273853025c
Author: notaz <notasas@gmail.com>
Date:   Tue Oct 10 00:39:57 2023 +0300

    add a nasty hack for gpu busy timing

    with a hope to remove it someday
    notaz/pcsx_rearmed#225

 libpcsxcore/database.c            |  7 ++++++
 libpcsxcore/new_dynarec/pcsxmem.c | 29 ++++++-------------------
 libpcsxcore/psxcommon.h           |  1 +
 libpcsxcore/psxhw.c               | 45 +++++++++++++++++++++++++++++++++------
 libpcsxcore/psxhw.h               |  3 +++
 5 files changed, 56 insertions(+), 29 deletions(-)

**Comment by Ploggy** [comment]
That fixed the issue thank you @notaz :)
