### ISSUE TITLE
Driver 2 (SLUS-01318) not swapping discs correctly or with huge delay

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/pcsx_rearmed#779]
Hi there @notaz, thanks for this great emulator of PS1!

Btw, i'm having trouble playing **Driver 2 (USA) (v1.1) (SLUS-01318) (2 discs)** on PCSX-ReARMed.
When i try to play the missions which require the Disc 2 to be able to play, i can't play them.

Specifically, the mission im trying to get in is "Chase the Gun Man".
**This mission requires to swap to Disc 2 for play this mission, but i just can't swap it, cause when i try to swap it it still displays "INCORRECT DISC INSERTED".**

![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/f3243371-9c8a-4eb7-a8b8-9b1e8d37f393)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/f30e11ec-583d-4dd8-bc0a-b4567ba02fef)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/2cd50d67-3776-46f6-a60f-4118e6116693)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/2c16f640-4ef7-4a5e-ba6c-68fc56886ec2)

Using PCSX-ReARMed r23l fe56428.

I will leave a savefile for trigger this issue quickly.
[Driver 2 (USA) (Disc 1) (v1.1).srm.zip](https://github.com/libretro/pcsx_rearmed/files/13043741/Driver.2.USA.Disc.1.v1.1.srm.zip)

For trigger it:
1. Put the savefile i attached here in **retroarch/saves/**
2. Load **Driver 2 (USA) (Disc 1) (v1.1)** on PCSX-ReARMed
3. Enter to "Undercover" mode, then "Load Game"
4. Load the savefile as normally do
5. The game will ask you to swap to Disc 2, go to the emulator menu, the go to Disc Control and select "Insert New Disc".
6. Load **Driver 2 (USA) (Disc 2) (v1.1)**
7. It should be displayed the disc was swapped, but it's still "INCORRECT DISC INSERTED".

Thanks ;)

**Comment by saulfabregwiivc** [comment]
Unfortunately latest PCSX-ReARMed r23l 81a5a20 still struggles in disc swapping in this game.

It takes too long for the Disc 2 to be detected.

**Comment by bslenul** [comment]
Seems a bit random for me, sometimes it loads absolutely fine, meaning the "Incorrect DISC inserted" changes to "Checking..." as soon as I insert disc 2 and it loads pretty quickly.
And sometimes the "Incorrect DISC inserted" stays on screen after inserting disc 2, it loads eventually but it feels longer and it never changes to "Checking...".

I made a quick video to show the 2 behaviors (first attempt loads normally, 2nd attempt at 0:25 is the weird one):

https://github.com/libretro/pcsx_rearmed/assets/33353403/e309b0a7-7222-4de6-bd75-16cb1780e21d

**Comment by notaz** [comment]
It should work better now but I recommend testing cd change in other games for regressions as that stuff is rather fragile.

**Comment by bslenul** [comment]
Tested ~15 multi-discs games by starting a new game while disc 2 is inserted and not a single issue when switching disc 👍 Only tested on Windows 10 tho.

**Comment by notaz** [comment]
Thanks for testing. I consider this fixed now.
