### ISSUE TITLE
[Vita] 512x240 resolutions rendered incorrectly

### ISSUE THREAD

**Issue by ParzivalWolfram** [libretro/pcsx_rearmed#785]
### PCSX-ReARMed Version

r23l-??? (no version written to logs, running retroarch 1.16.0 stable)

### Your device

PS Vita

### Operating System of your device

Other (consoles, etc.)

### CPU architecture

ARM 32bit

### Issue description

PS1 games that run in 512x240 (good example is Symphony of the Night, during file select and status/item menus) are skewed diagonally. Both HLE BIOS and real BIOS cause the issue.

### Step-by-step reproduction and logs

Symphony of the Night: Press Start during gameplay or on title screen.

Examples (photos of screen, as screenshots do not work on the Vita):

- File Select screen
![IMG_20231026_164742__01](https://github.com/libretro/pcsx_rearmed/assets/30007617/aa0beae1-f2fc-4e2e-9572-6f2e6dd7b2e3)

- Status screen
![IMG_20231026_165907](https://github.com/libretro/pcsx_rearmed/assets/30007617/a6a2533f-f6bb-4862-a4aa-f8268f766363)

- Log
[retroarch__2023_10_26__16_52_23.log](https://github.com/libretro/pcsx_rearmed/files/13183259/retroarch__2023_10_26__16_52_23.log)

**Comment by notaz** [comment]
Did this ever work before?

This doesn't happen on other devices even when the code is mostly the same. I've checked all the Vita specific code and noticed some suspicious things, but I doubt they are related. Still you can try the latest version.

**Comment by ParzivalWolfram** [comment]
Issue is not present in r23l-b7f50ee, which is the current nightly build on libretro's buildbot page. Guess a fix didn't make it into stable or something?
