### ISSUE TITLE
Vib-Ribbon PAL (and possibly other PAL games) incorrectly stretched

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/pcsx_rearmed#786]
Since long time ago, even on latest PCSX-ReARMed r23l [501a8ca](https://github.com/libretro/pcsx_rearmed/commit/501a8ca6852cd6c7d892ad321ebeb4b6950fd3aa), the PAL version of the game Vib-Ribbon is being incorrectly stretched when played on PCSX-ReARMed.

On other emulators (Beetle PSX, DuckStation) this doesn't happen.

This happens supposedly on all GPU plugins, including the default one.

**PCSX-ReARMed:**
![pcsx1](https://github.com/libretro/pcsx_rearmed/assets/66485640/8c97709d-77aa-490d-b955-f4535f73489b)

**How it should be displayed according to Beetle PSX:**
![beetle](https://github.com/libretro/pcsx_rearmed/assets/66485640/753c3513-f298-4dea-94c5-4ad512abe50f)

It's hard to notice it but it is being stretched in the vertical lines.

**Comment by notaz** [comment]
It's returning 256 lines which is the amount the hardware renders in non-interlaced PAL mode. If other emulators add extra overscan lines it's they business, I don't see the point. People already complain of more borders than before in newer versions and this emu never emulated overscan before. If you think the aspect is wrong, well it varied widely on CRT TVs too, and it should be the frontend's (RetroArch or whatever) job to allow to change it to your liking, not the emulation core's.

**Comment by notaz** [comment]
Closing as per previous explanation.
