### ISSUE TITLE
Star Wars: Episode I - The Phantom Menace, does not start and makes automatically close the emulator.

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/pcsx_rearmed#787]
Like the title says, the game **Star Wars: Episode I - The Phantom Menace** doesn't work.

When trying to boot the game, after the BIOS screen, the game doesn't even start, it just makes the emulator to be closed automatically.
What is happening here? Any fix for this?

Thanks a lot @notaz ;)

**Comment by w1ndg** [comment]
I have the same issue. After i choose to start the game it never start. screen stay black.

Raspberry Pi4, RetroPie 4.5.8, lr-pcsx-rearmed (commit 501a8ca).

**Comment by w1ndg** [comment]
Thank you very much! Game is working in my system.

**Comment by saulfabregwiivc** [comment]
Fixed and it's working now, thank you @notaz! 🗡️
