### ISSUE TITLE
Formula One Arcade (PAL) (SCES-03886) - Various crashes on PCSX-ReARMed

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/pcsx_rearmed#788]
So i was playing **Formula One Arcade (PAL) (SCES-03886)** on PCSX-ReARMed r23l [501a8ca](https://github.com/libretro/pcsx_rearmed/commit/501a8ca6852cd6c7d892ad321ebeb4b6950fd3aa) on Windows and [WiiSX](http://github.com/emukidid/pcsxgc) and in both versions i encountered these crashes:

- **If you try to skip the introductory video where all the racers are shown before the start of the race (at the first second of the video), it crashes the emulator, resulting in automatic exit.** If you let it play entirely, the game works fine.
- **After you finish ANY race, the game crashes and results in automatic exit of the emulator.**

Any fix for these issues? Thanks ;)

**Comment by notaz** [comment]
Doesn't happen for me. Try disabling the dynarec ("ICache emulation" must be on) and see if it helps. If so, probably lightrec's workaround for this game isn't sufficient.

**Comment by pcercuei** [comment]
I can't reproduce the first one, skipping the drivers introduction does not cause any crash.
I can reproduce the second one.

**Comment by saulfabregwiivc** [comment]
> I can't reproduce the first one, skipping the drivers introduction does not cause any crash. I can reproduce the second one.
It happens if you try to skip in the instant when the video fades for the first time (in the first sec of the video). After that, when you try to skip it, it just skips fine. It only shows a black screen if you skip at second 1 of the video.

**Comment by pcercuei** [comment]
The second crash seems to happen when it tries to access address `0x1ffe0000`. The question now is whether it's a valid address or not.

**Comment by saulfabregwiivc** [comment]
Thank you @pcercuei and @notaz, now Formula One Arcade doesn't crash anymore when trying to skip at the 1st sec of the presentation video, and it doesn't crash anymore after finishing a race.
