### ISSUE TITLE
Missing elements in-game / Tomb Raider

### ISSUE THREAD

**Issue by RetroTomb** [libretro/pcsx_rearmed#79]
For me the "save crystals" won't appear in-game, which is quite annoying since I don't remember where they all are.

I asked this question on ngemu and got this response:

-ICatButler
"As to the missing save crystals, those require Framebuffer Textures/Effects to be enabled for me to see them using Pete's OpenGL plugins. I would assume this is a problem with the way your current GPU plugin is handling those, I don't know if you can change to a different plugin (Pete's software plugin displays the crystals in PCSX-Reloaded). Other than that I can't really help."

Is this for everyone a issue or is it just me?

**Comment by meepingsnesroms** [comment]
The RetroArch version has no plugins,do you mean here?
[https://pcsxr.codeplex.com/](url)

**Comment by externo6** [comment]
Turn off High Res Speed Hack.

**Comment by meepingsnesroms** [comment]
It has been 2 months and the owner has not replied nor has anyone else experienced this issue so I am going to close it.

If the owner wants it reopened they can respond and I will reopen it.
