### ISSUE TITLE
Moto Racer World Tour (Europe) softlocks after winning a championship

### ISSUE THREAD

**Issue by CometHunter92** [libretro/pcsx_rearmed#790]
### PCSX-ReARMed Version

501a8ca6852cd6c7d892ad321ebeb4b6950fd3aa

### Your device

Pi4

### Operating System of your device

Other (consoles, etc.)

### CPU architecture

ARM 64bit (AArch64)

### Issue description

It's a thing that happens even on PS2 and PS3, after winning a championship the game displays a trophy screen, after pressing X to return to the main menu, the game softlocks. The only core that doesn't hang at that point is Beetle-PSX (but it has other issues with this game, that pcsx_rearmed doesn't have so far).

### Step-by-step reproduction and logs

I attached a savestate, just press X to select "Continua" (sorry, I played it in italian), then wait for the trophy screen and then press X again to return to the main menu: at this point the game softlocks.
[Moto Racer World Tour (Europe).zip](https://github.com/libretro/pcsx_rearmed/files/13219611/Moto.Racer.World.Tour.Europe.zip)

**Comment by notaz** [comment]
Can you provide a matching Beetle's savestate too?

From some investigation it looks like a game bug. It has a delayed pause for music, but on that trophy screen it starts loading the main menu too early and pause ends up pausing the loading process instead. If you wait for the music to end (takes quite a while) before continuing it will load without problems. I'm curious how all that manages to work in beetle/mednafen.

**Comment by CometHunter92** [comment]
Hi, here's the savestate. Same thing, press X, "Continue" (used english this time) and you will have the Trophy screen.
I have to point that with beetle-psx the game has some issues (not appearing in pcsx_rearmed): the game will directly load into Arcade mode after the fmv intro, you have to exit the race to load the menu screen, and basically every music beside the one during races, stutters and loop itself (in the trophy screen, in particular, the music won't play at all).
[Moto Racer World Tour (Europe) (Beetle-Linux-arm64).zip](https://github.com/libretro/pcsx_rearmed/files/13454163/Moto.Racer.World.Tour.Europe.Beetle-Linux-arm64.zip)
