### ISSUE TITLE
S.C.A.R.S. (PAL) (SLES-01286) - Analog Controls have left drift

### ISSUE THREAD

**Issue by gamecubefan1990** [libretro/pcsx_rearmed#792]
There is a problem with the game S.C.A.R.S.
I installed the latest version of RetroArch on my Samsung Galaxy S22 and downloaded the current core from pcsx_rearmed.
If you set the controls from "Standard" to "Analog" or "DualShock", the car steers slightly to the left.
If you set the controls to "Standard" so that the analog stick doesn't work, the car will drive straight.
I can't detect any drift in other games like South Park Rally, Muppet RaceMania or the Need for Speed series.

**Comment by pcercuei** [comment]
Random thought here, but...
Is it possible that it's a bug in the game itself? Does it happen in other emulators?

**Comment by gamecubefan1990** [comment]
I also tested it on PS1 emulators on the Wii console.
When I play it on "WiiSX Beta 3.0" or old versions of "WiiSXRX" on my Wii console, the game runs perfectly in analog mode with no drift.
It's not a bug in the game itself.

**Comment by saulfabregwiivc** [comment]
This also happens to me too, in Windows.

**Comment by gamecubefan1990** [comment]
I think with the new commit the bug has been fixed.
If I switch the controls to “Analog” or “DualShock”, I no longer notice any left drift.
