### ISSUE TITLE
Pcsx_reamred for iOS 8 (r22) crashes every time! Could you please provide a compiled r23 version compatible with iOS 8?

### ISSUE THREAD

**Issue by SoFasttt** [libretro/pcsx_rearmed#793]
### PCSX-ReARMed Version

r22

### Your device

iOS 8.4.1 32-bit

### Operating System of your device

Apple (iOS, tvOS, macOS etc.)

### CPU architecture

ARM 32bit

### Issue description

I want to play PSX games using Retroarch on my old iPad Mini 1 (which runs iOS 8.4.1 32-bit). All games currently load and run very well, however, there's a bug that randomly freezes the iPad after 3-5 minutes of playing.

The same problem as in this (now closed) issue: https://github.com/libretro/pcsx_rearmed/issues/503 (I've tried both of the compiled versions for iOS 5 and iOS 9, none worked)

It seems like that bug was fixed in the r23 version. However, I can't find any compatible build of that version that is compiled to work with **iOS 8.4.1 32-bit**.

Here's the link to r23 source code: https://github.com/notaz/pcsx_rearmed/releases/tag/r23

Could anyone please help compile one for me? I've tried to do it myself but it seems super complicated (I'm not familiar with programming) and may require a Mac.

I believe the output file should be in ''pcsx_rearmed_libretro_ios.dylib'' format

Thank you very much!

**Comment by notaz** [comment]
The nightly builds are: https://buildbot.libretro.com/nightly/apple/ios9/latest/

But this has no dynarec and I have no idea if it will work on iOS 8. Either way this will be difficult as I don't think anyone of the active contributors of this project develop for iOS.

**Comment by notaz** [comment]
I'm closing this since there is nothing I can do, and there is almost no chance anyone else will do something.
