### ISSUE TITLE
No GUI in Spyro 3 with OpenBIOS

### ISSUE THREAD

**Issue by pcercuei** [libretro/pcsx_rearmed#795]
### PCSX-ReARMed Version

r22-1502-gc396a646b9

### Your device

PC

### Operating System of your device

Linux (or Linux-based like RetroPie etc.)

### CPU architecture

x86-64 (64bit Intel, AMD, etc.)

### Issue description

Spyro 3 - Year of the Dragon does not boot properly when using OpenBIOS: the GUI does not appear after the egg appears. A "Press X" text should appear at the bottom of the screen. With OpenBIOS, it does not.

This is reproductible with both Lightrec and PCSX' interpreter.

### Step-by-step reproduction and logs

Start the game, let the intro play.

**Comment by notaz** [comment]
Do we know if this works on real hardware? The game is famous for it's anti-piracy features where it checksums its code repeatedly and subtly breaks itself if something differs. Maybe those checks include the BIOS too.

**Comment by pcercuei** [comment]
For some reason I was under the impression that OpenBIOS had near-perfect compatibility with PSX games, but it does not seem to be the case, as the project's README links to a compatibility sheet. So I'll just assume (for now) that this is an OpenBIOS issue.
