### ISSUE TITLE
Built-in cheats code game can't run

### ISSUE THREAD

**Issue by mzy1996** [libretro/pcsx_rearmed#797]
### PCSX-ReARMed Version

r23l a4e249a1

### Your device

new 3DS XL

### Operating System of your device

Other (consoles, etc.)

### CPU architecture

Other

### Issue description

Edson Ferreira‘s cheats edition games can't run after choose needed cheats code, and screen frozen.
games I get from here: https://www.facebook.com/groups/1439027973056620/user/100031402911298/

### Step-by-step reproduction and logs

Choose the cheats code I need and press X button, the game frozen and can't enter the game title menu.

**Comment by notaz** [comment]
Your link doesn't work here and you didn't specify the game in question so there is nothing I can do.

**Comment by mzy1996** [comment]
Maybe I Can upload the games to Google Drive so you can use to solve the question

**Comment by notaz** [comment]
Up to you.

**Comment by mzy1996** [comment]
I'm uploading the game to Google Drive now, all 15 games won't boot after the first screen choose th cheats, but all of them work fine on duckstation and ePSXe

**Comment by mzy1996** [comment]
Here is the link, you can use to fix the bug:https://drive.google.com/drive/folders/1zlRtMV6w3PMeGUnMQCTx3xJy_V2CP87W?usp=sharing

**Comment by mzy1996** [comment]
is this issue fix now?

**Comment by notaz** [comment]
Maybe, why don't you try yourself? I don't have a N3DS to try on myself.

**Comment by notaz** [comment]
Closing this since it works on PC now.
