### ISSUE TITLE
Disney's The Emperor's New Groove - Audio error during speech output

### ISSUE THREAD

**Issue by gamecubefan1990** [libretro/pcsx_rearmed#799]
There is a problem with the game Disney's The Emperor's New Groove.
I play with the German PAL version (SCES-03015), my ISO is Redump verified.
I installed the latest version of RetroArch on my Samsung Galaxy S22 and downloaded the current core from pcsx_rearmed.

It can sometimes happen that the speech output stops in the middle of a sentence.
In addition, the voice output sometimes sounds as if it was being read from a scratched CD.
It only affects the voice acting, the music and other sound effects always seem to work.
As I said, the error only occurs sometimes when you talk to the characters.

**Comment by notaz** [comment]
When exactly does it happen? Couldn't see any problems with the few NPCs at the start of the game.

You should also check your exact version in the menus. The play store version of RetroArch has (or had) extremely outdated version of the core.

**Comment by gamecubefan1990** [comment]
Unfortunately I can't say an exact NPC as it happens randomly.
When I played the first two missions, the audio error mostly occurred.
I don't have the PlayStore version, I always download the current version of Retroarch from buildbot.libretro.
I always keep the cores up to date.

**Comment by gamecubefan1990** [comment]
I played it again and I have a tip.
When you start the first mission, go to the left, there should be an old man with a stick.
Simply speak to him again and again using the circle button until the error occurs, the man has nice long sentences and you can trigger the error there.

**Comment by notaz** [comment]
I've tested this on real hardware and it seems to be a game bug:

https://www.youtube.com/watch?v=XyX9-vklRwU

I've added a hack to at least stop the audio from cutting out (which also happens on real hardware), but the hack will promptly be reverted if it turns out to affect any other games negatively.
