### ISSUE TITLE
Harry Potter and the Sorcerer's Stone (USA) - Stuck right before transfiguration lesson

### ISSUE THREAD

**Issue by paradadf** [libretro/pcsx_rearmed#80]
When you try to enter the transfiguration lesson, the game gets stuck at this screen:
![screenshot](https://cloud.githubusercontent.com/assets/15956550/20484342/1523167c-aff7-11e6-9f5f-de0e6bc158ba.png)

.srm and .state files can be downloaded [here](http://s000.tinyupload.com/index.php?file_id=17425959008012617504).
The save state is right before entering the room.

Update: I'm not really sure where  *right* upstream would be, but I also opened an issue [here](http://pcsxr.codeplex.com/workitem/12405).

Update2: As the above uploaded files expired long ago, I was able to download the savestate I uploaded to codeplex before it gets shut down. Here they are [Harry Potter and the Sorcerer's Stone (USA) SAVES.zip](https://github.com/libretro/pcsx_rearmed/files/6371931/Harry.Potter.and.the.Sorcerer.s.Stone.USA.SAVES.zip)
.

**Comment by negativeExponent** [comment]
another HLE bios issue?

**Comment by paradadf** [comment]
I was using the real bios. The European "Harry Potter and the Philosopher's Stone" version doesn't have this issue.

**Comment by notaz** [comment]
Seems to be working here.
