### ISSUE TITLE
Arc the Lad III (USA) disc swap not working

### ISSUE THREAD

**Issue by XenoKino96** [libretro/pcsx_rearmed#804]
### PCSX-ReARMed Version

99104c0

### Your device

PC

### Operating System of your device

Windows

### CPU architecture

ARM 64bit (AArch64)

### Issue description

When the game prompts you to swap to disc 2 it sits on the disc swap prompt after switching to disc 2. I have attempted it with the game in both CHD and CUE/BIN formats.  The game swaps discs fine on the swanstation core but not the beetle psx and pcsx-rearmed cores.

### Step-by-step reproduction and logs

Load the last save file on the card titled "Cariot Secret Hanger" which puts you right at the part where you are prompted to swap discs.
[Arc the Lad Collection - Arc the Lad III (USA) (Disc 1).zip](https://github.com/libretro/pcsx_rearmed/files/13420611/Arc.the.Lad.Collection.-.Arc.the.Lad.III.USA.Disc.1.zip)

**Comment by bslenul** [comment]
No idea if it helps but looks like this is the commit that fixed it on DuckStation: https://github.com/stenzek/duckstation/commit/0e0bd2852f5aae307c81d808f347fef89e16b3b7

**Comment by XenoKino96** [comment]
Commit 801a962 fixed this issue so closing this now.
