### ISSUE TITLE
CTR: Crash Team Racing (USA) (SCUS-94426) having several GFX (graphical) glitches.

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/pcsx_rearmed#809]
I don't know in what exact commit caused this issue but i believe before the adding of GPU timing check, the game **CTR: Crash Team Racing (USA) (SCUS-94426)** was perfectly playable, now with latest commits **now the game graphics (GFX) are starting acting like this, with exploding vertices, glitchy racers and even the text is broken, making it nearly unplayable.**

Also, it seems the screen is not centered anymore in this game.

All the rest of the game seems to work fine, though.

Using latest PCSX-ReARMed r23l [963f416](https://github.com/libretro/pcsx_rearmed/commit/963f41620dce6ddb2527b7e3dced09564031f783).

Please fix this, thank you notaz ;)

![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/0bd33441-e225-420d-b89a-969314fdc920)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/82266e19-91c1-4632-aa46-f4882f41972d)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/19e52f64-4aed-44eb-9a5e-ed4d3af8cfa6)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/198362d7-88eb-4c07-8b10-42d1effa9020)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/d7b6e970-cd0c-4fba-b2d0-5cdccc344d3b)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/3f7a6170-edf9-481a-8275-5b3637c0ed1a)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/671c6936-6088-4bba-a801-9934423bdf9a)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/6bca588f-bbf6-49f6-a650-49ab3560f948)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/4c0e98b4-2cc8-48ac-a5d0-61e950f4832c)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/a2a7830a-6699-4503-baaa-279afb70abd0)

**Comment by pcercuei** [comment]
I can reproduce, first bad commit is f99193c2c2 ("gpu: start doing some basic gpu timing").

**Comment by notaz** [comment]
I've reworked the code again, but all this timing stuff is very fragile. It would be best if everyone gave at least their favorite games a try.

**Comment by saulfabregwiivc** [comment]
i've tested some games so far

Time Crisis - no glitches
CTR: Crash Team Racing - no glitches
Gran Turismo - no glitches
Driver 2 - had glitchy FMVs, now it seems there are no glitches in FMVs anymore
Vib-Ribbon - no glitches
Pepsiman - no glitches

**Comment by notaz** [comment]
Thanks for testing, I consider this fixed then.
