### ISSUE TITLE
Corrupted background graphics when enabling enhanced resolution

### ISSUE THREAD

**Issue by ds22x** [libretro/pcsx_rearmed#813]
### PCSX-ReARMed Version

r23l dcbfae8

### Your device

PC

### Operating System of your device

Windows 11, SteamOS 3.5.7

### CPU architecture

x86-64 (64bit Intel, AMD, etc.)

### Issue description

When enhanced resolution is enabled, parts of the background get corrupted.
The games I've noticed it happening with so far are Destruction Derby and G. Darius, but there most likely even more games affected by this.
Tried and happens on both Windows 11 and Steam Deck, and the first bad commit is https://github.com/libretro/pcsx_rearmed/commit/c296224f47ceebab4d6fbd071959bff294e80293
![G  Darius (USA)-231226-162913](https://github.com/libretro/pcsx_rearmed/assets/45218067/bb5ea616-f47d-47e6-8cdf-4a6d6df0fbc9)
![Destruction Derby (USA)-231226-162833](https://github.com/libretro/pcsx_rearmed/assets/45218067/0762d8c6-5e3a-4a9a-8cce-6cfcff50a8a3)

### Step-by-step reproduction and logs

Have default settings and only enhanced resolution enabled, load an affected game, and wait until you reach a point where you'll notice the corrupted graphics.

**Comment by notaz** [comment]
Thanks for taking your time to bisect this, should hopefully be fixed now.

**Comment by ds22x** [comment]
Can confirm it is indeed fixed.
Thanks for looking into it and fixing the issue.
