### ISSUE TITLE
Looney Tunes: Sheep Raider (USA) (SLUS-01369) crashes after Infogrames logo.

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/pcsx_rearmed#814]
In all platforms, the game **Looney Tunes: Sheep Raider (USA) (SLUS-01369)** soon after it starts, plays the INFOGRAMES logo and then crashes at a white screen and it doesn't load anything.

Using latest PCSX-ReARMed r23l cf6f7ca.

![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/b51534ce-76b6-4574-af2a-758ae2a28adc)

Btw, Happy New Year 2024 to all.

**Comment by notaz** [comment]
Should work now.

**Comment by saulfabregwiivc** [comment]
It's working now, thank you @notaz! :D

![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/dd605389-6915-41e2-9c40-72481a6a19a5)
![image](https://github.com/libretro/pcsx_rearmed/assets/66485640/d636f56f-17e9-48f6-848f-929aba230993)
