### ISSUE TITLE
Problem introduced only in the new core versions

### ISSUE THREAD

**Issue by gusklein** [libretro/pcsx_rearmed#815]
### PCSX-ReARMed Version

r23lcf6f7ca

### Your device

Nintendo Switch

### Operating System of your device

Other (consoles, etc.)

### CPU architecture

ARM 64bit (AArch64)

### Issue description

On Parasite Eve 2, with the GPU Plugin Enhanced Resolution activated, the main character's reflections flicker and the HP/MP dynamic bars misalign and behave strangely. Older versions works perfectly.

https://github.com/libretro/pcsx_rearmed/assets/87046201/2dc66291-70e1-4921-8b7b-4dbc9d1f2a34

### Step-by-step reproduction and logs

On Parasite Eve 2, just look to the HP/MP bars and cross in front of mirrors walking or running.

**Comment by notaz** [comment]
This was meant to fix something else. Made it optional now and disabled by default.
