### ISSUE TITLE
White noise in V-Rally 2

### ISSUE THREAD

**Issue by pcercuei** [libretro/pcsx_rearmed#816]
### PCSX-ReARMed Version

r22-1571-g5ee1c9269d

### Your device

PC

### Operating System of your device

Linux (or Linux-based like RetroPie etc.)

### CPU architecture

x86-64 (64bit Intel, AMD, etc.)

### Issue description

CD-Rom code is SLES01907. Using a .bin/.cue format.
When going in-game, a very loud white noise is present.

### Step-by-step reproduction and logs

Boot the game all the way to the main menu; pick 1 player, create/pick a player, then press X until you are in-game. Right after the countdown, a loud white noise can be heard.

**Comment by notaz** [comment]
Doesn't happen here with both split/multifile .cue/bin and a .chd. Can you post the log, where it prints out the CD TOC at least? From your description it's likely to be some CDDA issue.

**Comment by pcercuei** [comment]
I tried with a CHD now (the .bin/.cue I tested previously was just the extracted CHD).

This is the TOC printed by PCSX:
```chd: TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:193666 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0
chd: TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:6841 PREGAP:150 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0
chd: TRACK:3 TYPE:AUDIO SUBTYPE:NONE FRAMES:18156 PREGAP:6 PGTYPE:VAUDIO PGSUB:NONE POSTGAP:0
chd: TRACK:4 TYPE:AUDIO SUBTYPE:NONE FRAMES:14397 PREGAP:14 PGTYPE:VAUDIO PGSUB:NONE POSTGAP:0
chd: TRACK:5 TYPE:AUDIO SUBTYPE:NONE FRAMES:15568 PREGAP:16 PGTYPE:VAUDIO PGSUB:NONE POSTGAP:0
chd: TRACK:6 TYPE:AUDIO SUBTYPE:NONE FRAMES:20282 PREGAP:11 PGTYPE:VAUDIO PGSUB:NONE POSTGAP:0
chd: TRACK:7 TYPE:AUDIO SUBTYPE:NONE FRAMES:15473 PREGAP:26 PGTYPE:VAUDIO PGSUB:NONE POSTGAP:0
chd: TRACK:8 TYPE:AUDIO SUBTYPE:NONE FRAMES:13896 PREGAP:21 PGTYPE:VAUDIO PGSUB:NONE POSTGAP:0
Loaded CD Image: /media/paul/ULTRASLIM/Games/psx/V-Rally 2.chd[+chd][+sbi].
Track 01 (DATA) - Start 00:02:00, Length 43:02:16
Track 02 (AUDIO) - Start 43:06:16, Length 01:31:16
Track 03 (AUDIO) - Start 44:35:38, Length 04:02:06
Track 04 (AUDIO) - Start 48:37:52, Length 03:11:72
Track 05 (AUDIO) - Start 51:49:51, Length 03:27:43
Track 06 (AUDIO) - Start 55:17:14, Length 04:30:32
Track 07 (AUDIO) - Start 59:47:61, Length 03:26:23
Track 08 (AUDIO) - Start 63:14:04, Length 03:05:21
```

**Comment by notaz** [comment]
I think your rip is bad, compare the track lengths to a known good dump: http://redump.org/disc/1063/

**Comment by pcercuei** [comment]
Looks like you're right. I made my own dump so maybe it wasn't properly done.
