### ISSUE TITLE
[Lightrec] PSX CPU Clock Speed only updates when toggling Lightrec off and on

### ISSUE THREAD

**Issue by ds22x** [libretro/pcsx_rearmed#818]
### PCSX-ReARMed Version

r23l 5ee1c92

### Your device

Steam Deck

### Operating System of your device

Linux (or Linux-based like RetroPie etc.)

### CPU architecture

x86-64 (64bit Intel, AMD, etc.)

### Issue description

A bit of an interesting one, but when the Lightrec is enabled, changing the "PSX CPU Clock Speed" doesn't work unless you disabled the Lightrec, go into the running game, and then re-enable the Lightrec again.

**Comment by notaz** [comment]
@pcercuei this is missing `lightrec_invalidate_all` call before `lightrec_set_cycles_per_opcode` but for whatever reason it doesn't work. Is lightrec restoring unmodified blocks with old cycles_per_opcode even if they are invalidated, or something? It would be silly having to fully destroy/reinit lightrec in this situation.

**Comment by pcercuei** [comment]
If the underlying RAM did not change, the invalidated blocks will mark themselves as still valid, so they don't need to be recompiled needlessly. That's why it doesn't work here.

I'd need to add a mechanism to unconditionally free all the compiled blocks, as there's no way to do that currently.

**Comment by notaz** [comment]
@pcercuei take a look if that's not too terrible (despite the botched clock/block commit message). Seems to work at least.

**Comment by pcercuei** [comment]
Why not simply re-create the Lightrec instance?

**Comment by notaz** [comment]
Some things are done from the vsync handler which returns to recompiled code. But looking at it again both standalone and libretro properly exit the dynarec to enter the menu (the only way to change the multiplier). And my method still destroys the memory it would return to I guess.

Anyway I'll leave it as-is until it causes problems or somebody sends a patch.

**Comment by ds22x** [comment]
The CPU clock speed now updates without having to toggle the Lightrec.
