### ISSUE TITLE
FIFA 98 (spain) black screen after EA logo

### ISSUE THREAD

**Issue by josete2k** [libretro/pcsx_rearmed#82]
It works OK in the lr_PCSX_rearmed included in retropie 4.0.2

But once I've updated it to 4.0.3 (and 4.1) the game sets in a black screen after the EA logo. I can exit with success so is not a freeze...

**Comment by notaz** [comment]
If this is "FIFA - Road to World Cup 98" it seems to be getting ingame by now.
