### ISSUE TITLE
Why PSX CPU default frequency is 57 Mhz if the console is 33,8 MHz ?

### ISSUE THREAD

**Issue by Augusto7743** [libretro/pcsx_rearmed#820]
Hello.
Thanks for reading my topic.
In PCSX ReARMed configuration in CPU clock setting the default is 57.
However the PSX CPU is 33,8 MHz.
Why the CPU is overclocked ?

**Comment by notaz** [comment]
This is percentage, not MHz, so it's at ~half the nominal MHz actually. I've changed the option description to make this clear.

**Comment by Augusto7743** [comment]
Thanks for your reply.
Have an nice week.
