### ISSUE TITLE
My device iOS iPad Air4 sideload Retroarch and play Dokapon PS1 can't save in the game

### ISSUE THREAD

**Issue by LerningCom** [libretro/pcsx_rearmed#821]
### PCSX-ReARMed Version

1.17.0

### Your device

iPad Air 4

### Operating System of your device

Apple (iOS, tvOS, macOS etc.)

### CPU architecture

Other

### Issue description

![426724449_805663544922065_3273176069137702818_n](https://github.com/libretro/pcsx_rearmed/assets/159910600/f117597d-04b8-4aba-9760-01143787535c)

how can i save in the game please let me know

i want to play this game

**Comment by notaz** [comment]
Should be fixed now. Alternatively you can add a BIOS file and it will work with the older versions too.
