### ISSUE TITLE
Resident Evil and Dino Crisis has a longer pause when switching to different scenes

### ISSUE THREAD

**Issue by shoddydev** [libretro/pcsx_rearmed#824]
I notice in the latest build of pcsx rearmed there's a slightly longer pause when transitioning to different scenes. I tested it on Windows and the PlayStation Classic.

here's how it look on the latest pcsx rearmed:
https://github.com/libretro/pcsx_rearmed/assets/42045893/da3e082c-ce85-4291-9247-31ed2c4ef5c4

And here's a older build of pcsx rearmed from 2022
https://github.com/libretro/pcsx_rearmed/assets/42045893/70580f19-4f20-46f9-bce9-46f133d10657

**Comment by notaz** [comment]
I'm not sure how close it is now but do try the latest commit.

**Comment by shoddydev** [comment]
> I'm not sure how close it is now but do try the latest commit.

I made a comparison video and it definitely improved a lot from the last build
https://www.youtube.com/watch?v=xOHhTbVsE2k

I also compared it with a 2022 build and that build is slightly faster. Scene transitions are the same but I noticed it finished the cut scene faster. Maybe it's because I added real cdrom support?

**Comment by notaz** [comment]
The remaining difference is likely from timing changes from compatibility fixes. If the CD controller responds too fast, some games are unable to handle it and crash, so some things were slowed down to fix it.

With that in mind there is now a new option `Speed hacks / Turbo CD` that tries to feed data to the game as fast as it accepts it. It speeds a lot of games but breaks a lot too. Kind of experimental, unsure how I feel about it.

**Comment by shoddydev** [comment]
I've tested the feature briefly and I love this new addition.
https://www.youtube.com/watch?v=iBlIrZ50F50

I remember watching some Sega Saturn videos where it seem to skip loading altogether and I've always wondered why more emulators don't implement that. I assume it's because they're trying to be faithful to the original experience, and due to it being unstable. It's a great option to have i think
