### ISSUE TITLE
dynamic recompile feature setting behaves differently now

### ISSUE THREAD

**Issue by theflyingape** [libretro/pcsx_rearmed#832]
### PCSX-ReARMed Version

r24l-31-gdb02598e

### Your device

Raspberry Pi4 and Pi5

### Operating System of your device

Linux (or Linux-based like RetroPie etc.)

### CPU architecture

ARM 64bit (AArch64)

### Issue description

As of this git release, I must **disable** dynamic recompile (drc) on **Pi 4**, but have it **enabled on Pi 5**.

### Step-by-step reproduction and logs

The emulatory hangs upon first drive access and requires a hard power off with this option set as:
**Pi 4**: pcsx_rearmed_drc = "enabled"
**Pi 5**: pcsx_rearmed_drc = "disabled"

... but works absolutely fine reversed using:
**Pi 4**: pcsx_rearmed_drc = "disabled"
**Pi 5**: pcsx_rearmed_drc = "enabled"

**Comment by theflyingape** [comment]
OK, strike all of this -- lol -- not sure what changed recently here (i.e., did the opt file internals change?), but now **both** models are working perfectly fine with drc = "disabled", and will only **hang** if drc is set to **enabled**.

**Comment by notaz** [comment]
That's not supposed to happen. What game are you trying to run? Can you get the log?
