### ISSUE TITLE
PSX Memory Card enabled by default

### ISSUE THREAD

**Issue by mixpc** [libretro/pcsx_rearmed#84]
Hello,

I think it would be a great add-on as it would enable to save gamestates. Could this be implemented?

Thank you and regards!

**Comment by dankcushions** [comment]
it already is. do you have a valid BIOS?

**Comment by mixpc** [comment]
Good! Yes, SCPH1001.BIN

**Comment by gingerbeardman** [comment]
Saving was broken for me in 1.4.0

Now works again in 1.4.1

**Comment by retro-wertz** [comment]
i dont get what is asked about here. enable memcard in savestates?

**Comment by negativeExponent** [comment]
more details required

**Comment by gameblabla** [comment]
There really isn't a need to keep open strange "bug" reports like this so let's close this.
If saving ever breaks in the future, please open a new issue.
