### ISSUE TITLE
Gran Turismo demo (SCED-01279) crashes before menu

### ISSUE THREAD

**Issue by jamesravi** [libretro/pcsx_rearmed#843]
### PCSX-ReARMed Version

r24l 8847df5

### Your device

PC

### Operating System of your device

Windows

### CPU architecture

x86-64 (64bit Intel, AMD, etc.)

### Issue description

After the legal disclaimer ("Notice"), the game will remain at a black screen for around 30 seconds before RetroArch crashes. Seems to crash on Linux as well. Also seems to crash regardless of whether the internal HLE BIOS is being used or the official ones, but I could be wrong.

### Step-by-step reproduction and logs

Load the .cue with RetroArch and the PCSX-ReARMed core, wait for the game to load and crash. Tried to produce a log on Windows but it didn't seem very descriptive, but I got this fragment on Linux:
```
Regular mmap to address 0x10000000 succeeded
Regular mmap to address 0x10200000 succeeded
Regular mmap to address 0x10400000 succeeded
Regular mmap to address 0x10600000 succeeded
Regular mmap to address 0x2fc00000 succeeded
Regular mmap to address 0x10800000 succeeded
Memory map is sub-par. Emitted code will be slow.
Using 32-bit LUT
ERROR: Segmentation fault in recompiled code: invalid load/store at address PC 0x1605013d
ERROR: Was executing block PC 0x8007479c
Exiting at cycle 0x273be3f4
```

**Comment by notaz** [comment]
@pcercuei confirmed. Note this is the demo and not the release version (which works fine), also known as "Gran Turismo (France) (Demo)".

**Comment by pcercuei** [comment]
Ok, I can see it. It looks like an issue with the constant propagation mechanism.
