### ISSUE TITLE
Image cropping glitch in sol divide ps1 using pcsx from retroarch

### ISSUE THREAD

**Issue by geysonazevedo27** [libretro/pcsx_rearmed#846]
### PCSX-ReARMed Version

1.19.1

### Your device

PC

### Operating System of your device

Windows

### CPU architecture

x86-64 (64bit Intel, AMD, etc.)

### Issue description

In retroarch pcsx, sol divide on ps1 has a glitch making it look like the image is cut off in the game's intro

### Step-by-step reproduction and logs

in the intro of the sol divide of the ps1 through the retroarch pcsx core, the screen has a glitch making it look like the image is cut off, can you fix this please?
![Sem título4](https://github.com/user-attachments/assets/68ce1fe2-15f2-4325-ac08-2c029f76c0af)

**Comment by notaz** [comment]
Should be fixed now.
