### ISSUE TITLE
[Switch] pcsx_rearmed core crashes

### ISSUE THREAD

**Issue by RetroMarioBros** [libretro/pcsx_rearmed#847]
Some of the commits added today cause the emulator to crash when starting a game.

**Comment by notaz** [comment]
Any logs, crash screen or anything? I don't have the device so can't see for myself.

**Comment by RetroMarioBros** [comment]
yes!
Retroarch Logs
[retroarch__2024_10_01__13_43_19.log](https://github.com/user-attachments/files/17205310/retroarch__2024_10_01__13_43_19.log)
[retroarch__2024_10_01__13_43_38.log](https://github.com/user-attachments/files/17205312/retroarch__2024_10_01__13_43_38.log)

Atmosphere cfw logs:
[01727783019_010024601bb16000.log](https://github.com/user-attachments/files/17205333/01727783019_010024601bb16000.log)

**Comment by notaz** [comment]
Thanks for the logs. Could you try 6d4dbe7a2b2b6ad967401437dce3a355546e682a and post the logs again in case it crashes?
