### ISSUE TITLE
Eagle One - Harrier Attack (USA) (En,Fr,Es) - Sound issues, game freezes.

### ISSUE THREAD

**Issue by wwndg** [libretro/pcsx_rearmed#848]
### PCSX-ReARMed Version

r24l 778896e

### Your device

Raspberry Pi5

### Operating System of your device

Linux (or Linux-based like RetroPie etc.)

### CPU architecture

ARM 64bit (AArch64)

### Issue description

Hello, I'm having an issue with this game. After selecting either missions or training, the voice that provides instructions starts speaking in multiple languages, and the game freezes.

### Step-by-step reproduction and logs

Start the game.
Choose a training mission.
Press the X button several times.
The narrator will begin speaking in multiple languages, and the game will eventually freeze."

[runcommand.log](https://github.com/user-attachments/files/17308008/runcommand.log)

**Comment by wwndg** [comment]
It seems that if I set the PSX CPU from Retroarch settings from the default 57 to 65, it fixes the issues with this game.

**Comment by notaz** [comment]
Weirdly this I couldn't reproduce this in standalone build, but it indeed happens when compiled as a libretro core from the same source.

Anyway I now made your setting the default for this game.
