### ISSUE TITLE
Dithering Pattern doesnt work on Crash Bash PAL 

### ISSUE THREAD

**Issue by RetroMarioBros** [libretro/pcsx_rearmed#853]
I have tried with other games enabling and disabling the option and it does have the expected effect, but in the game Crash Bash (PAL), it seems to do nothing about it (color banding artifacts)
[Nintendo Switch]
Examples:
![2024113009450800-0F1AC0B1C5B7094E21BE0C101EE24B7F](https://github.com/user-attachments/assets/fc8b44b2-c841-4f28-8320-697c9cefb083)
![2024113009465200-0F1AC0B1C5B7094E21BE0C101EE24B7F](https://github.com/user-attachments/assets/5faddfed-2614-41cf-85a3-e043888c4d28)
![2024113009465800-0F1AC0B1C5B7094E21BE0C101EE24B7F](https://github.com/user-attachments/assets/d9ea5ab4-3a26-49b9-bad8-46aa74a51729)
![2024113009474700-0F1AC0B1C5B7094E21BE0C101EE24B7F](https://github.com/user-attachments/assets/064043b1-1ae3-4e6f-b28e-4fc23ef064f3)
![2024113009475300-0F1AC0B1C5B7094E21BE0C101EE24B7F](https://github.com/user-attachments/assets/a8c119dc-01c0-47b1-bdc3-4446b12520f1)
![2024113009475700-0F1AC0B1C5B7094E21BE0C101EE24B7F](https://github.com/user-attachments/assets/f35d5888-7477-4544-b9c9-1607ec67c6a2)
![2024113009481200-0F1AC0B1C5B7094E21BE0C101EE24B7F](https://github.com/user-attachments/assets/10b2e92e-3e8a-4fc6-8054-7ed0de4fbeb5)

**Comment by notaz** [comment]
This happens on real hardware. The devs chose to disable dithering for whatever reason.
![cb](https://github.com/user-attachments/assets/6eea25af-6239-4af0-bbce-d48be92459f7)
real hw vram dump:
![vram](https://github.com/user-attachments/assets/3b2cf279-f0fa-4da6-8e37-9aa519de36ee)

**Comment by RetroMarioBros** [comment]
Oh! It's true I just tried it on PSone & PS3  and there is no Dithering, I never noticed that.
Thank you very much

**Comment by RetroMarioBros** [comment]
Great.
Force option works great, now the game looks much better
Thanks you!!!
@notaz
