### ISSUE TITLE
Vita version crashes

### ISSUE THREAD

**Issue by zoltanvb** [libretro/pcsx_rearmed#856]
### PCSX-ReARMed Version

custom (see description)

### Your device

PS Vita

### Operating System of your device

Other (consoles, etc.)

### CPU architecture

ARM 32bit

### Issue description

Vita version has started to crash on content load. 
First unsuccessful build from d196572c99265e596252915cc8820cf733f69f50
Last successful build from 3c3a80b2408d5a98521746c26502cd7addf3b365
Between the two, I ran into compile failures so I did not bisect further.

### Step-by-step reproduction and logs

Load content (probably any content).
Log from unsuccessful case:
[retroarch__2024_12_15__08_01_42.log](https://github.com/user-attachments/files/18139261/retroarch__2024_12_15__08_01_42.log)

**Comment by notaz** [comment]
Please retry with the latest and post the log in case it still crashes.

**Comment by zoltanvb** [comment]
Log is different, but there is still crash.
[retroarch__2024_12_16__06_21_42.log](https://github.com/user-attachments/files/18145180/retroarch__2024_12_16__06_21_42.log)

**Comment by notaz** [comment]
Looks like it's caused by the new "dynarec thread" thing, I've pushed another try to fix it.

If it still crashes I'll need a screenshot of the crash screen (IIRC Vita had one with hex addresses and stuff?), also `retroarch_vita.elf.unstripped.elf` from your build for debug symbols. Alternatively I can disable this thread thing for Vita since I have no way to debug it.

**Comment by DerinQyu** [comment]
Hello I tested 26be283 with a .chd game, my vita still crashes when booting the game, here's the log file and the crash dump.

> [INFO] === Build =======================================
[INFO] Funcionalidades: NEON 
[INFO] Version: 1.19.1
[INFO] Built: Dec 16 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "vita".
[INFO] [Overrides]: Redirigiendo archivo de guardado a "ux0:/data/retroarch/savefiles/PCSX-ReARMed/CTR - Crash Team Racing (USA).srm".
[INFO] [Overrides]: Redirigiendo guardado rápido a "ux0:/data/retroarch/savestates/PCSX-ReARMed/CTR - Crash Team Racing (USA).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[DEBUG]    Puerto 1:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Puerto 2:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Puerto 3:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Puerto 4:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Puerto 5:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Puerto 6:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Puerto 7:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Puerto 8:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "3".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[DEBUG] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: GET_MESSAGE_INTERFACE_VERSION.
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_memcard2 = "disabled"
[libretro INFO] Memcard 2: disabled
[libretro INFO] Starting PCSX-ReARMed 26be283 (cc 10.3.0 32bit armv7 neon ari64 gpu=neon)
[libretro INFO] build time: Dec 17 2024 00:27:26
[libretro INFO] old fpscr = 63000010
[libretro INFO] 4 cpu core(s) detected
[libretro INFO] psxMap: tried to map @80000000, got 0x86000000
[libretro INFO] psxMap: tried to map @77000000, got 0x86000000
[libretro INFO] psxMap: tried to map @1f800000, got 0x84880000
[libretro INFO] psxMap: tried to map @1fc00000, got 0x84800000
[libretro INFO] Init new dynarec, ndrc size 1000000, pgsize 4096
[libretro INFO] ndrc config: mul=175, ha=0, pex=0
[libretro INFO] (0x811e92c8) testing if we can run recompiled code @0x82300000...
[libretro INFO] test passed.
[libretro INFO] RAM is not directly mapped
[libretro INFO] Mapped (RAM/scrp/ROM/LUTs/TC):
[libretro INFO] 0x86000000/0x84880000/0x84800000/0x0/0x82300000
[libretro INFO] psxMap: tried to map @08000000, got 0x84000000
[libretro INFO] compiler thread enabled
![2024-12-16-232855-898460](https://github.com/user-attachments/assets/4e0aac1f-273b-4d3a-93ea-187971d33011)

**Comment by zoltanvb** [comment]
Logs with .elf, ps2dmp and some kind of decoding using a core parser I found, since my crash screen was just an error message:
[crashlogs.zip](https://github.com/user-attachments/files/18171597/crashlogs.zip)

**Comment by notaz** [comment]
Thanks, although I don't see how it could get to the place it crashed with all those `0xdeadbeef` registers without crashing much earlier. I suspect the problem comes from `-fno-optimize-sibling-calls` that I removed without thinking, something is probably missing on vita causing that opt to not work and it was probably there for a reason. Please try again.

**Comment by DerinQyu** [comment]
Hello just tested c3f78cc on my vita with chd games, still crashes. Here are the crash dumps and log

> [INFO] === Build =======================================
[INFO] Capabilities: NEON 
[INFO] Version: 1.19.1
[INFO] Built: Dec 17 2024
[INFO] =================================================
[ERROR] Couldn't find any video driver named "gl1"
[INFO] Available video drivers are:
[INFO] 	gl
[INFO] 	null
[WARN] Going to default to first video driver..
[INFO] [Input]: Found input driver: "vita".
[INFO] [Overrides]: Redirecting save file to "ur0:/vitaroms/system_data/savefiles/Saban's Power Rangers - Lightspeed Rescue (USA).srm".
[INFO] [Overrides]: Redirecting save state to "ux0:/data/retroarch/savestates/Saban's Power Rangers - Lightspeed Rescue (USA).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[DEBUG]    Port 1:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Port 2:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Port 3:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Port 4:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Port 5:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Port 6:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Port 7:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[DEBUG]    Port 8:
[DEBUG]       "standard" (1)
[DEBUG]       "analog" (261)
[DEBUG]       "dualshock" (517)
[DEBUG]       "negcon" (773)
[DEBUG]       "guncon" (260)
[DEBUG]       "konami gun" (516)
[DEBUG]       "mouse" (258)
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[DEBUG] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: GET_MESSAGE_INTERFACE_VERSION.
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_memcard2 = "disabled"
[libretro INFO] Memcard 2: disabled
[libretro INFO] Starting PCSX-ReARMed c3f78cc (cc 10.3.0 32bit armv7 neon ari64 gpu=neon)
[libretro INFO] build time: Dec 17 2024 23:39:32
[libretro INFO] old fpscr = 63000010
[libretro INFO] 4 cpu core(s) detected
[libretro INFO] psxMap: tried to map @80000000, got 0x86000000
[libretro INFO] psxMap: tried to map @77000000, got 0x86000000
[libretro INFO] psxMap: tried to map @1f800000, got 0x84880000
[libretro INFO] psxMap: tried to map @1fc00000, got 0x84800000
[libretro INFO] Init new dynarec, ndrc size 1000000, pgsize 4096
[libretro INFO] ndrc config: mul=175, ha=0, pex=0
[libretro INFO] (0x812074cc) testing if we can run recompiled code @0x82300000...
[libretro INFO] test passed.
[libretro INFO] RAM is not directly mapped
[libretro INFO] Mapped (RAM/scrp/ROM/LUTs/TC):
[libretro INFO] 0x86000000/0x84880000/0x84800000/0x0/0x82300000
[libretro INFO] psxMap: tried to map @08000000, got 0x84000000
[libretro INFO] compiler thread enabled
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_bios = "auto"
[INFO] [Environ]: SYSTEM_DIRECTORY: "ur0:/vitaroms/system_data/BIOS".
[libretro INFO] found BIOS file: PSXONPSP660.bin
[INFO] [Environ]: GET_CAN_DUPE: true
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: PERFORMANCE_LEVEL: 6.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[DEBUG]    Port 1:
[DEBUG]       "D-Pad Up" => "D-Pad Up"
[DEBUG]       "D-Pad Down" => "D-Pad Down"
[DEBUG]       "D-Pad Left" => "D-Pad Left"
[DEBUG]       "D-Pad Right" => "D-Pad Right"
[DEBUG]       "B Button (Down)" => "Cross"
[DEBUG]       "A Button (Right)" => "Circle"
[DEBUG]       "Y Button (Left)" => "Square"
[DEBUG]       "X Button (Top)" => "Triangle"
[DEBUG]       "Select Button" => "Select"
[DEBUG]       "Start Button" => "Start"
[DEBUG]       "L Button (Shoulder)" => "L1"
[DEBUG]       "R Button (Shoulder)" => "R1"
[DEBUG]       "L2 Button (Trigger)" => "L2"
[DEBUG]       "R2 Button (Trigger)" => "R2"
[DEBUG]       "L3 Button (Thumb)" => "L3"
[DEBUG]       "R3 Button (Thumb)" => "R3"
[DEBUG]    Port 2:
[DEBUG]       "D-Pad Up" => "D-Pad Up"
[DEBUG]       "D-Pad Down" => "D-Pad Down"
[DEBUG]       "D-Pad Left" => "D-Pad Left"
[DEBUG]       "D-Pad Right" => "D-Pad Right"
[DEBUG]       "B Button (Down)" => "Cross"
[DEBUG]       "A Button (Right)" => "Circle"
[DEBUG]       "Y Button (Left)" => "Square"
[DEBUG]       "X Button (Top)" => "Triangle"
[DEBUG]       "Select Button" => "Select"
[DEBUG]       "Start Button" => "Start"
[DEBUG]       "L Button (Shoulder)" => "L1"
[DEBUG]       "R Button (Shoulder)" => "R1"
[DEBUG]       "L2 Button (Trigger)" => "L2"
[DEBUG]       "R2 Button (Trigger)" => "R2"
[DEBUG]       "L3 Button (Thumb)" => "L3"
[DEBUG]       "R3 Button (Thumb)" => "R3"
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] RGB565 supported, using it
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_frameskip_type = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_frameskip_threshold = "33"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_frameskip_interval = "3"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_region = "auto"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_multitap = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_negcon_deadzone = "0"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_negcon_response = "linear"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_analog_axis_modifier = "circle"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_vibration = "enabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_analog_combo = "l1+r1+select"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_dithering = "enabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_neon_interlace_enable_v2 = "auto"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_neon_enhancement_enable = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_neon_enhancement_no_main = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_neon_enhancement_tex_adj_v2 = "enabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_display_fps_v2 = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_cd_turbo = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_cd_readahead = "12"
[libretro INFO] cdrom precache: 12 buffers
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_drc = "enabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_psxclock = "auto"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_drc_thread = "auto"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_nosmccheck = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_gteregsunneeded = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_nogteflags = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_nocompathacks = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_nostalls = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_icache_emulation = "enabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_exception_emulation = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_spu_reverb = "enabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_spu_interpolation = "simple"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_spu_thread = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_noxadecoding = "enabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_nocdaudio = "enabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_gpu_slow_llists = "auto"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_fractional_framerate = "auto"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_screen_centering = "auto"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_screen_centering_x = "0"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_screen_centering_y = "0"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_show_overscan = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_crosshair1 = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_crosshair2 = "disabled"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_konamigunadjustx = "0"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_konamigunadjusty = "0"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_gunconadjustx = "0"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_gunconadjusty = "0"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_gunconadjustratiox = "1.00"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_gunconadjustratioy = "1.00"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_input_sensitivity = "1.00"
[DEBUG] [Environ]: GET_VARIABLE: pcsx_rearmed_show_bios_bootlogo = "disabled"
[libretro INFO] plugin: plugins/builtin_gpu
[libretro INFO] plugin: plugins/builtin_spu
[libretro INFO] plugin: plugins/builtin_pad
[libretro INFO] plugin: plugins/builtin_pad
[libretro INFO] Plugins loaded.
[libretro INFO] chd: TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:94632 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0
[libretro INFO] Loaded CD Image: ux0:/Saban's Power Rangers - Lightspeed Rescue (USA).chd[+chd] (100980083 bytes).
[libretro INFO] Track 01 (DATA) - Start 00:02:00, Length 21:01:57
[libretro INFO] cdrom precache: 12 buffers
[libretro INFO] CD-ROM Label: SLUS_01114                      
[libretro INFO] CD-ROM ID: SLUS01114
[libretro INFO] CD-ROM EXE Name: SLUS_011.14;1
[libretro INFO] using cycle_multiplier_override: 310
[libretro INFO] ndrc config: mul=310, ha=0, pex=0
[libretro INFO] BIOS: 19951204, 'CEX-3000/1001/1002 by K.S.', 'J'


crash team racing
![2024-12-17-220127](https://github.com/user-attachments/assets/a2cba400-2aa9-4029-a67f-4b843ae9c201)

power rangers lightspeed rescue
![2024-12-17-220337](https://github.com/user-attachments/assets/ed958471-9fe4-4b7e-9fe2-150d5b6dd83a)

**Comment by notaz** [comment]
It got further now but the thread could not write to dynarec memory. I've added `sceKernelOpenVMDomain()` call to the thread, if that doesn't help I'll need to disable the whole thread thing. Please retest.

**Comment by zoltanvb** [comment]
It is getting further along, unfortunately still crashes.
[crashlogs2.zip](https://github.com/user-attachments/files/18189330/crashlogs2.zip)

**Comment by notaz** [comment]
It's mostly the same as before and `sceKernelOpenVMDomain` returned 80010058 (ENOSYS?) so it probably can't be done from a thread. I've now disabled all the thread stuff, I suspect things should start working now.

**Comment by zoltanvb** [comment]
It does work now. Thank you for fixing this!

**Comment by DerinQyu** [comment]
Hello, games now boot on latest nightly. Thank you so much. Here is the log file:  
[retroarch.log](https://github.com/user-attachments/files/18193078/retroarch.log)


It is a shame the vita can't handle the dynarec thread I just wonder how big the performance gain would be (I have read it helped a lot on the 3ds).

**Comment by gwlegion** [comment]
hi ... where i can find the nightly built core ?

**Comment by notaz** [comment]
https://buildbot.libretro.com/nightly/playstation/vita/

You can sometimes also use the core updater in RetroArch, but I don't know if it works on Vita.
