### ISSUE TITLE
Return Fire (USA) -  Freezes at the selection screen.

### ISSUE THREAD

**Issue by ghost** [libretro/pcsx_rearmed#857]
### PCSX-ReARMed Version

r24l commit: 67881ef

### Your device

Raspberry Pi3B+

### Operating System of your device

Linux (or Linux-based like RetroPie etc.)

### CPU architecture

ARM 32bit

### Issue description

Hi, I am trying to play Return Fire (CUE/BIN), but the game is freezing at the vehicle selection screen. 
I've tested both the PAL and USA versions, and the issue occurs with both. 

Thanks!

### Step-by-step reproduction and logs

Log file: [runcommand.log](https://github.com/user-attachments/files/18156037/runcommand.log)

**Comment by notaz** [comment]
Should be fixed. Pretty cool game BTW.
