### ISSUE TITLE
Freezing screen on PS1 philosoma using retroarch PCSX

### ISSUE THREAD

**Issue by geysonazevedo27** [libretro/pcsx_rearmed#860]
### PCSX-ReARMed Version

r24I c387c01

### Your device

PC

### Operating System of your device

Windows

### CPU architecture

x86-64 (64bit Intel, AMD, etc.)

### Issue description

When I play Philosoma on PS1 using PCSX from Retroarch, the game freezes and I can't get it out.

### Step-by-step reproduction and logs

The game has a frozen screen in the part that says phase 1 as you can see in the photo, could you fix this problem please?

![Sem título3](https://github.com/user-attachments/assets/ac92777b-ece1-45af-afc7-866b8118ee4e)

**Comment by geysonazevedo27** [comment]
![Sem título3](https://github.com/user-attachments/assets/88e1fe61-f49e-4de3-9c9e-f4ac85363e26)

**Comment by notaz** [comment]
Should be fixed now.
