### ISSUE TITLE
confilcting types for 'uncompress2'

### ISSUE THREAD

**Issue by alucryd** [libretro/pcsx_rearmed#87]
Hi guys,

I've been getting the following error lately trying to build on Arch Linux:

https://paste.xinu.at/gQuiK/

**Comment by orbea** [comment]
I am getting it in Slackware64-current too. I suspect it was because zlib was updated in slackware. In the future you shouldn't use temporary pastebin sites for bug reports.
```
Thu Jan 12 01:15:52 UTC 2017
l/zlib-1.2.10-x86_64-1.txz: Upgraded.
```
```
cc  -DGIT_VERSION=\"" b580cc4"\" -fPIC -Wall -Iinclude -ffast-math -O2 -DNDEBUG -DFRONTEND_SUPPORTS_RGB565 -DHAVE_LIBRETRO -DNO_FRONTEND   -c -o libpcsxcore/decode_xa.o libpcsxcore/decode_xa.c
cc  -DGIT_VERSION=\"" b580cc4"\" -fPIC -Wall -Iinclude -ffast-math -O2 -DNDEBUG -DFRONTEND_SUPPORTS_RGB565 -DHAVE_LIBRETRO -DNO_FRONTEND   -c -o libpcsxcore/disr3000a.o libpcsxcore/disr3000a.c
libpcsxcore/cdriso.c:1096:12: error: conflicting types for ‘uncompress2’
 static int uncompress2(void *out, unsigned long *out_size, void *in, unsigned lon
            ^
In file included from libpcsxcore/cdriso.c:40:0:
/usr/include/zlib.h:1282:21: note: previous declaration of ‘uncompress2’ was here
 ZEXTERN int ZEXPORT uncompress2 OF((Bytef *dest,   uLongf *destLen,
                     ^
make: *** [<builtin>: libpcsxcore/cdriso.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by loganmc10** [comment]
I can't reproduce this in Fedora 25, but perhaps just renaming the uncompress2 function inside cdriso.c will do the trick?

You'd also need to rename this line:
https://github.com/libretro/pcsx_rearmed/blob/master/libpcsxcore/cdriso.c#L1176

**Comment by orbea** [comment]
You can see the referenced PR for one idea....I'm not sure its the best.

**Comment by orbea** [comment]
Your idea worked too, which would you think is better?

**Comment by loganmc10** [comment]
I would rename the function, I think that has the least potential for issues to crop up. But how surprised are you that I picked my own idea lol?
