### ISSUE TITLE
"Analog" controller isn't recognized

### ISSUE THREAD

**Issue by bmn001** [libretro/pcsx_rearmed#88]
Player 1's controller is not recognized as an "analog/dual shock" controller even though "analog" is selected for Pad 1 within the RetroArch options menu.

I'm running lr-pcsx-rearmed on the latest version of RetroPie (4.1.8 as of this posting.) I'm seeing this behavior both on the pcsx binary provided with RetroPie, as well as when I compile the latest from github.

The only way to get the system to recognize the controller as analog is to set **all 8 pads** to analog in the RA options menu.

**Comment by bmn001** [comment]
A little more info: Setting all 8 pads to "analog" will work, but **only** for the first player. Any other controllers will still be seen as standard, non-analog.

This is possibly related to this commit: https://github.com/libretro/pcsx_rearmed/commit/8342a30082638cc032c53e073f893e82f149fcb7
It's a bit beyond my technical knowledge to compile things with old versions of files when the Retropie menu isn't doing the work for me, so I can't say for certain :)

**Comment by andrewlxer** [comment]
The multitap stuff has broken a lot of stuff.  I'm not part of the retroarch project or anything, but I started some cleanup then gave up since I think it'd require a full rewrite at this point, which I don't have time to do.

Perhaps the multitap changes should be reverted?  They seem to be causing lots of issues and are a significant deviation from upstream.

**Comment by loganmc10** [comment]
@alexis-puska can you have a look at this?

**Comment by bmn001** [comment]
Over the weekend I had RetroPie rebuild lr-pcsx-rearmed from source.  It seems to be fixed now.  Enabling analog for player 1 (and only player 1) now works as expected.

**Comment by alexis-puska** [comment]
I have fix this bug some weeks ago, an other poeple made some code style but now it's works. kekun refactore my code in september and introduce a little bug, this bug, some poeple ask to fix it by the retropie forum. The version 4.1 of retropie have the bugged version, juste update and compile from source :)
