### ISSUE TITLE
questions about 3DS port

### ISSUE THREAD

**Issue by Jimmy-Z** [libretro/pcsx_rearmed#89]
* It's missing from nightly for a while, I actually doesn't have a build on my hand, does anyone have a working build?
* retroarch on 3DS show the core name as PCSX, not PCSX-ReARMed, is it just cosmetic or actually a different core? I haven't found a PCSX repo on https://github.com/libretro/, only this.
* I'm guessing the speed difference between 3DS and Vita is NEON support, despite on a much higher frequency, 3DS CPU doesn't support NEON, and PCSX-ReARMed probably used the NEON GPU in Vita builds, is that right?
* I want to help improve PCSX on 3DS, I'm a programmer, have some C experience but I know pretty much nothing about emulation, where should I look into?

I prefer PSX on 3DS over Vita, despite the inferior screen, the resolution is just enough for PSX, and the pixelating gives a *genuine* nostalgic feeling. and it has ZL/ZR for L2/R2!

**Comment by fr500** [comment]
The speed difference is most likefly because neon yeah

**Comment by gingerbeardman** [comment]
Latest available 3DS build is 1.3.6

**Comment by Saphiresurf** [comment]
As of now I've noticed that PCSX Rearmed builds are back on the 3DS nightlies. I've been having issues running them as they've crashed everytime that I've tried, but I may just be doing something incorrectly here (testing with Crash Bandicoot which ran on 1.3.6). Do the builds on the latest nightlies actually run at the moment or are they non functional for now?

**Comment by negativeExponent** [comment]
this should be working in latest commits

@twinaphex @hunterk @hizzlesomething
