### ISSUE TITLE
[Vita] pcsx_rearmed will stop working after Sleep-Mode

### ISSUE THREAD

**Issue by paulo-lima-dev** [libretro/pcsx_rearmed#91]
So the pcsx_rearmed core will freeze and sometimes loose audio and lagg after the vita enters sleep mode.

This behavior does not happen on Snes2005 or Gpsp.
So I think is core related.
Tested on 1.40

**Comment by notaz** [comment]
The core can't do anything about the sleep modes, I'd say it's a frontend problem.
